### ISSUE TITLE
Realistic Biome support for BOP

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Team-RTG/Realistic-Terrain-Generation#1003]
Some BOP terrain looks very unrealistic,so I hope to be able to generate more realistic biome in the RTG world.

**Comment by srs-bsns** [comment]
Can you be more specific?

What biome(s) are you talking about?
How is the terrain unrealistic?
Are you really using the RTG WorldType?

**Comment by mgdgfbhevdyeh** [comment]
Boreal Forest,Flower Field,Orchard,Seasonal Forest(the terrain and the tree look very untrue.)

**Comment by mgdgfbhevdyeh** [comment]
I'm sure I'm using RTG WorldType

**Comment by whichonespink44** [comment]
@mgdgfbhevdyeh All of those biomes are using a 'plains' template, so we could maybe try to add some rolling hills in a future version of RTG. The trees that you're seeing are from BOP, but we could maybe add some of RTG's trees in there to add some variety.

I'm closing this issue, but we'll take your feedback into consideration the next time we re-design the BOP biomes.

**Comment by mgdgfbhevdyeh** [comment]
ok i know
