### ISSUE TITLE
Add a config setting to set tree density during biome decoration

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1004]
Apparently some people feel that tree density is too thick in some biomes and would like to be able to reduce the amount of trees generated so forest are more sparse.

**Comment by whichonespink44** [comment]
This should be configurable on a per-biome basis, so I'm thinking a tree density 'multiplier' for each biome should do the trick for now. Something like:

`S:"Tree Density Multiplier"=1.0`

and then in DecoTree we can multiply the local 'loops' variable by that value.

**Comment by srs-bsns** [comment]
Yeah, I was thinking something along those lines. We'll need to set reasonable hard-coded upper limits though to prevent extreme values being set, because I can totally see people that don't know how the process works setting ridiculously high values and making the magic smoke leak out of their CPUs.

**Comment by whichonespink44** [comment]
This is almost finished - just want to test a few more scenarios & then I'll submit a PR for review.

**Comment by whichonespink44** [comment]
Added in 6dd8ade
