### ISSUE TITLE
net.minecraftforge.fml.common.MissingModsException: Mod RTG (Realistic Terrain Generation) requires [betteragriculture@[1.0,)]

### ISSUE THREAD

**Issue by seanimusprime** [Team-RTG/Realistic-Terrain-Generation#1008]
I'm getting this error when launching my server after updating to the newest version of RTG.
##### Affected Mod Versions:
- Forge version: 12.18.2.2107
- RTG version: 1.10.2-4.1.1.3
- Better Agriculture version: (MC-1.10)-0.16
##### Issue Description:

I get the error

> net.minecraftforge.fml.common.MissingModsException: Mod RTG (Realistic Terrain Generation) requires [betteragriculture@[1.0,)]
> Missing Mods:
> betteragriculture : [1.0,)
##### Steps to reproduce the issue:
1. Launch server.
2. Read the log.

**Comment by srs-bsns** [comment]
Fixed in f38b4be976eeaabc5ad1cb7dab35a74ebea969fb
