### ISSUE TITLE
Crash with Snow layers

### ISSUE THREAD

**Issue by MCEventHorizon** [Team-RTG/Realistic-Terrain-Generation#1018]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: 12.18.2.2114
- RTG version: 4.1.1.4
##### Extra Information:
- Crashlog: http://pastebin.com/8bZgXZXp

**Comment by srs-bsns** [comment]
Dupe of #1012. Already fixed in 616a7cf

**Comment by MCEventHorizon** [comment]
Do you have this version out cause I can't login to my world without crashing?

**Comment by whichonespink44** [comment]
It will be released tonight (GMT).
