### ISSUE TITLE
No tree generation

### ISSUE THREAD

**Issue by Rozzers** [Team-RTG/Realistic-Terrain-Generation#1023]
I was flying around checking out the generation when i stumbled upon no tree gen. It would generate flowers and structures but no trees.

http://imgur.com/a/KVN0w

This would happen all over the place after reaching a certain point (not sure what that point is). Every biome had no trees.

Edit: typos

**Comment by whichonespink44** [comment]
@Rozzers Please post your fml-client-latest.log file and we'll take a look.

**Comment by Rozzers** [comment]
here it is. I explored a little more before shutting down and saving.

[fml-server-latest.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/562823/fml-server-latest.txt)

**Comment by whichonespink44** [comment]
Did you install RTG on an existing world? I noticed quite a few `Fixed minecraft:blocks id mismatch` messages in the logs which is usually suggests that the world has gotten corrupted somewhere along the way through the adding and removing of mods.

To determine if this is an issue with RTG, try creating a new world using the same seed as your current world and flying to the coords in the screenshot you posted. If it's still treeless and barren after creating a new world, then it might be an issue with RTG.

Also, I noticed that you have Biomes O' Plenty installed, but not Climate Control or Biometweaker, one of which you will also need if you want BOP biomes to generate in RTG worlds. Try creating a new world using your existing setup first, and then if everything's alright, download and install either Climate Control or BiomeTweaker if you want to continue to use BOP.

Let us know how it goes.

**Comment by Rozzers** [comment]
Ok. Looks like thats it. Is there no way to reset something like this?

**Comment by whichonespink44** [comment]
Unfortunately not, unless you made a backup of your world before you installed RTG?

When you install RTG for the first time, you should always create a new world, and then you should never remove it from that world. It's usually safe to update RTG from one version to the next, unless the release notes for a particular version say not to, but it should always be a new world when it's first installed.

I'm going to close this issue, but if you need help getting your world setup, feel free to keep commenting in this thread, or you could always hop onto our Discord server (chat room) where there's usually someone around who's willing to help out with stuff like this:

https://discord.gg/0wIG7mz3g6TpkBsB
