### ISSUE TITLE
Concurrent Modification Exception, caused by Chococraft's Gysahls

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1028]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:

1.7.10-1614

- RTG version:

A copy I built against this pull in an attempt to solve an issue with Ridiculous World: https://github.com/Team-RTG/Realistic-Terrain-Generation/pull/990
Otherwise though, the build is basically 1.1.1

- Other mod(s):

Chococraft

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

Trying to generate a world sometimes causes this crash.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Try to generate a world
2. Might appear randomly

##### Extra Information:

http://pastebin.com/vZPd5h3h
http://pastebin.com/kPN9Hh76
Despite having the config option on to stop this from happening, I'm still having the error.

**Comment by whichonespink44** [comment]
8403660 needs to be backported in order to fix this.

**Comment by whichonespink44** [comment]
Also see #996

**Comment by Sunconure11** [comment]
I see. I guess if this continues, I'll have to wait for a port and build against it and hope the issue stops or something.

**Comment by whichonespink44** [comment]
@Sunconure11 are you able to log back in after the crash? if not, 8403660 might not be the right fix for this.

We're going to try and release an update for 1.7.10 tonight.

**Comment by Sunconure11** [comment]
I did not test that far, as it happened during generation and effectively halted attempts at pregeneration.

**Comment by Sunconure11** [comment]
However, whatever caused this happened fairly far out. If it were to be crashing when logging in though, what would need to be done?

**Comment by whichonespink44** [comment]
Just logging back in to see if it crashes again... if it's the bug I think it is, then you should be able to log back in without crashing. If it still crashes, then we'll need to dig a bit deeper into what's causing it.

**Comment by Sunconure11** [comment]
Server crashes if it tries to generate the chunk possibly causing the issue, but runs fine otherwise.

**Comment by whichonespink44** [comment]
Cool, I'll be in 1.7.10 tonight so will put in a fix for this.

**Comment by whichonespink44** [comment]
Fixed in 3fe6f96
