### ISSUE TITLE
Trees not replacing tallgrass blocks

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1031]
Either trees aren't replacing tallgrass blocks, or the tallgrass is replacing log blocks. 99.99% certain it's the former but need to investigate to be certain.

It'll most likely be one of these methods:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/world/gen/feature/tree/rtg/TreeRTG.java#L185-L211

**Comment by whichonespink44** [comment]
@srs-bsns said:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/world/gen/feature/tree/rtg/TreeRTG.java#L201-L210
that needs to include Material.GRASS

**Comment by srs-bsns** [comment]
But then I eventually said...

``` java
    @Override
    protected boolean canGrowInto(Block blockType)
    {
        Material material = blockType.getDefaultState().getMaterial();

        return material == Material.AIR
            || material == Material.LEAVES
            || material == Material.PLANTS
            || material == Material.GRASS
            || material == Material.GROUND
            || material == Material.WOOD
            || material == Material.VINE
            || material == Material.SNOW;
    }
```
