### ISSUE TITLE
No Class Def Found Error (calling client classes on server, util/Logger)

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1034]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:

1.7.10-1614

- RTG version:

1.1.2

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Generate a world
2. ???
3. http://pastebin.com/UjKKjeEJ

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

http://pastebin.com/UjKKjeEJ

By setting it to crash when a faulty structure tries to generate, I get this error instead:

http://pastebin.com/CzQYtiDQ

**Comment by whichonespink44** [comment]
Pretty sure this isn't RTG's fault, but we've added a workaround in 3421f23 - it will be in the next release.

**Comment by Sunconure11** [comment]
Still receiving the noclassdef error, even after I decided to compile a dev build and put it towards the server to see if this would solve anything.

Here is the source code of the mod I am using to pregenerate the world:

https://github.com/gecgooden/chunkgen

It appears there are some known issues with ChunkGen and RTG.

https://github.com/gecgooden/chunkgen/issues/35

**Comment by srs-bsns** [comment]
The crash being reported in from RTG's logger trying to call client classes on the server.

This does not fix the underlying issue. Minecraft was already in the process of crashing and there was a call to Logger#fatal which, itself, threw an exception. So this is a case of exception-ception.. get it?
