### ISSUE TITLE
BOP biome re-decoration

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1037]
- [ ] Coniferous Forest
- [ ] Fen
- [ ] Rainforest
- [ ] Snowy Coniferous Forest
- [ ] Temperate Rainforest
- [ ] Tropical Rainforest
- [ ] Woodland

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3826

**Comment by ghost** [comment]
Side note: I don't know wether you took this into account already, but you shouldn't mess with the [Origin Island](http://biomesoplenty.wikia.com/wiki/Origin_Island) biome at all, as this biome reproduces an old Minecraft version. Any fancy stuff there would look out of place.

**Comment by Quizer9O8** [comment]
Could you also re-decorate the Rainforest?

**Comment by whichonespink44** [comment]
> Could you also re-decorate the Rainforest?

Added it to the list.

**Comment by lightningo7** [comment]
It seems that BOP is triggering it's own tree decoration whenever the tree decoration event is posted, making it difficult to redecorate many of the biomes. Will be holding off on this issue until that gets fixed on BOP's side or we get a workaround on our side.

**Comment by whichonespink44** [comment]
Just been speaking with the BOP devs, and they've confirmed that BOP is doing decoration when the various Forge decorate events fire, but they seem pretty confident that only one type of decoration should be triggering for each event. For example, when the TREE event is fired, it's intended behaviour for BOP to generate its trees.. But what we're seeing on our side is that when the TREE event is fired, BOP is decorating the entire biome, not just trees.

So... here's what we need to do:

First, we need to figure out if there are any 'stray' Forge events being called. We can probably do this with some basic logging in the DecorateBiomeEvent: https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/event/EventManagerRTG.java#L349

If there aren't any stray Forge events being fired, then it'll most likely be a BOP issue.

Either way, there might be a workaround that we can try:

If we add the RTG worldtype to BOPBiomes.excludedDecoratedWorldTypes, which is available via the BOP API, it might just start working like it used to (best case) or we might need to call BOP generators individually (worst case).

**Comment by lightningo7** [comment]
I was mistaken about the decorating the whole biome, it's just the trees that are decorating.

**Comment by Quizer9O8** [comment]
I've noticed that there are a lot of small ponds in the Mountain Peaks biome.
Can you reduce that amount please?

**Comment by srs-bsns** [comment]
@Quizer9O8 Mountain Peaks is a BoP biome, and BoP is responsible for decorating it with ponds, not RTG.

**Comment by whichonespink44** [comment]
> Either way, there might be a workaround that we can try:
If we add the RTG worldtype to BOPBiomes.excludedDecoratedWorldTypes, which is available via the BOP API, it might just start working like it used to (best case) or we might need to call BOP generators individually (worst case).

So... adding the RTG world type to `BOPBiomes.excludedDecoratedWorldTypes` prevents *all* BOP decorations from generating in RTG worlds. This includes everything from the Jacaranda trees in Extreme Hills to the decorations that generate in the BOP biomes themselves. So this approach is a dead end.

**Comment by srs-bsns** [comment]
For BoP biomes, overrides can be used. In the case of ponds in the Mountain Peaks biome you can create a file called `mountain_peaks.json` and put it in `config/biomesoplenty/biomes`. The file should contain:
```json
{
    "generators":
    {
        "lakes":
        {
            "amountPerChunk": <float value>
        }
    }
}
```
For `<float value>` any value lower than `1.8` will reduce the amount of ponds. (`1.8` is the default) Higher values will increase the amount.

@whichonespink44 The generators can be removed from each biome singly in code. Each BoP biome has it's own instance of a [GenerationManager](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.11.x-6.0.x/src/main/java/biomesoplenty/common/world/GenerationManager.java), and you just need to make a call to the biome's `removeGenerator()` method to remove a specific generator. A generator could be removed and readded with different parameters to change it.

**Comment by srs-bsns** [comment]
Moved to the 1.11.2 TODO list: #1116
