### ISSUE TITLE
Crash during block generation while travelling world.

### ISSUE THREAD

**Issue by Zarepheth** [Team-RTG/Realistic-Terrain-Generation#1054]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.10.2-12.18.2.2147
- RTG version: 1.10.2-4.1.1.7
- Pam's Harvest Craft version: 1.9.4-1.10.2h

##### Issue Description:

The seed for my world, with Forge, BOP, RTG, and numerous other mods installed, generated what appears to be a water world with small islands vastly separated (at lest in the directions I've thus far traveled (North from original spawn point)). Going west from the spawn point, I saw an island south of me via peripheral vision. After getting on the island (Island was an Ice Plains biome, surrounded by cold beach) and heading southwest, by foot, I made it over the first hill and partway down before the game crashed.

Further up the call stack, are a few stack frames from Pam's Harvest Craft. I'm not sure if it's related - but could be an incompatibility between the two mods (I was looking at a Maple tree from that mod shortly before the crash).

##### Extra Information:
~~- crashlog and other files:~~
~~[https://gist.github.com/Zarepheth/8750e5839af1396f473703e7245a09ef.js]()~~
srsEdit: [Crash Log](https://gist.githubusercontent.com/Zarepheth/8750e5839af1396f473703e7245a09ef/raw/2a6887c3d70077a4ffb6a93d93181b88ce3c5dfa/Crash.Log)

I've included the main RTG config file and the RTG config files for BOP, Mithwood Forest, (since I have those mods installed), as well as Vanilla (since it may have been modified from the default). From the date-time stamps, if appears that BOP and Vanilla were modified after initial creation, but the other RTG config files are still unchanged.

**Comment by ghost** [comment]
I doubt Pam's is related. Her mod has lots of items to load, so it tends to show up in crash reports whether it's related or not (and, from my personal experience with crash reports with Pam's, it's almost certainly not). But you'd need a response from a dev or contributor who's actually familiar with the code (I am not). As for the spaced out landmasses, I've had that before. It's a feature of some mod (but I'll be darned if I can remember which), but I remember that you can change it in the configs.

**Comment by srs-bsns** [comment]
This is most certainly not RTG.

This exception is being thrown on a method (`updateGlassLayers`) that does not exist in the vanilla class `net.minecraft.block.state.pattern.BlockMaterialMatcher`, which likely means that the class is being patched at runtime.

There are two candidates that I saw at quick glance that could be at fault here. 1. Optifine, or 2. Whatever is in DynamicLights-1.10.2.zip

Steps you can take:
- Create a new world with the same seed, and the same mods and config settings. Travel to the same location in the world and see if the crash occurs again.
  - If the crash does not occur again, then it is likely a rare occurance.
    - Forget it happened.
  - If the crash does occur again, then you can be certain that it's reproducible.
    - Try creating a new world again with the same seed, and the same mods and config settings, but with Optifine removed. If the crash still occurs, try removing DynamicLights-1.10.2.zip. If the crashing stops, congratulations, you've won the game. If it continues to crash, then it is the Apocalypse.

**Comment by Zarepheth** [comment]
The crash recurred while traveling in the same vicinity with a new world off the same seed. I'll experiment with removing Optifine and DynamicLights tomorrow. _(for some reason, I thought I had previously removed Dynamic Lights as Optifine already provides that capability...)_

**Comment by Zarepheth** [comment]
I removed Optifine from my list of mods. In a new world, generated from the same seed, with the same parameters, I encountered a crash in the same vicinity. Optifine is not the cause.

### So far, the Original crash, last nights crash while testing in a new world, and the current crash with Optifine removed show RTG as the first mod on the stack trace.

Upon closer examination, I see identical stack traces between the original crash and the current crash, but the details prior to the stack trace are a little bit different.

### Original Location:

`net/minecraft/block/state/pattern/BlockMaterialMatcher.updateGlassLayers(III)V @111: invokeinterface`

### Current Location:

`net/minecraft/block/state/pattern/BlockMaterialMatcher.updateLevels(III)V @290: invokevirtual`

### Original Reason:

`Type 'net/minecraft/world/gen/ChunkProviderDebug' (current frame, stack[1]) is not assignable to 'net/minecraft/world/gen/MapGenCaves'`

### Current Reason:

`Type 'net/minecraft/stats/StatCrafting' (current frame, stack[1]) is not assignable to 'net/minecraft/stats/StatList'`

**Comment by Zarepheth** [comment]
Okay, I've repeated the situation 3 times after the original crash and continue to crash in the same vicinity each time. This time, both Optifine and Dynamic Lights were removed; so neither of them is the cause.

The stack trace is the same as all previous crashes and the Location and Reason are the same as the most recent crash.

If some mod is actually adding methods to a built-in class, at run time, it is neither Optifine nor Dynamic Lights. I'll remove "CraftingTableIV" and restore Optifine, then try again in yet another new world from the same seed and settings.

**Comment by whichonespink44** [comment]
@Zarepheth To save some time, maybe try removing mods in 'batches' - so like, 5 or 6 at a time, and then seeing if you can reproduce the crash. Please keep us posted if you find anything - maybe there's something we'll be able to do on our end as a quick fix.

**Comment by Zarepheth** [comment]
@whichonespink44 - that's a good idea.

Anyway, I've tested by removing Crafting Table IV, but still get the crash.

Looking at the stack trace, it seems to be related to generating a Pumpkin as new chunks are created. Since that is a vanilla item, I find it rather odd to cause a crash. I think my next test will be to remove Pam's HarvestCraft. Then start in on batches at a time.

**Comment by whichonespink44** [comment]
From what I've been hearing, you might not have to go any further than removing HarvestCraft... but only one way to find out. :)

**Comment by Zarepheth** [comment]
Well, that's annoying - same crash, without Pam's Harvest Craft.
And the Location and Reason details are back to the original crash, even though the stack trace no longer has Pam's Harvest Craft in it. Removing Pam's Harvest Craft shortened the stack trace by 11 lines. I'm no Java expert, nor have I seen much source code for Minecraft, but is world gen done via recursive function calls?

Looks like it's time to pull multiple mods at a time and retest...

**Comment by Zarepheth** [comment]
Pulled out half my mods. Had to make multiple attempts as some were dependencies of others. Anyway, the 1st half of the alphabet (minus the dependencies and biome adding mods, plus enough additional to equal half) seems to have the problem as no crash occurred. I did notice one difference - the villages generated with different layouts, although in similar locations.

Next up: Put back half of the mods I removed and try again.

**Comment by Zarepheth** [comment]
Restored 18 of the 36 removed mods. No crash and the villages resumed their former layout.

I'm not sure which mod changes the village layout, but it's within these 18:
- BaseMetals
- EndMetals
- Excore
- fastleavedecay
- hopperducts
- improving minecraft
- inventory tweaks
- iron chest
- jei
- labyrinth
- lightning craft
- llibrary
- mcmultipart
- modernmetals
- moreshears
- multihotbar
- natures compass
- nether core

The crash is probably caused by one of these 18 mods:
- Apple Skin
- Aquaculture
- Bagginses
- Baubles
- BetterFps
- BirdsNests
- BlockDrops
- Bookshelf
- Botania
- coroutil
- CraftingTableIV
- CraftingTWeaks
- crystallogy
- CyanosLootableBodies
- DAngerSEnse
- ElecCore
- EnchantingPlus
- exnihiloomnia

I'll restore 9 of the remaining 18 and see what happens.

**Comment by whichonespink44** [comment]
Cool, nearly there! The only one that looks possibly suspicious is BetterFPS since it changes things at quite a low level... but that's the thing with these things... you just never know - could be any of those.

**Comment by Zarepheth** [comment]
The crash is occurring while I'm at sea, coordinates approximately -650, 5xx. I'm pretty sure it occurs when a new chunk is created while I'm exploring.

Also, it is causing by one of these 9 mods:
- Apple Skin
- Aquaculture
- Bagginses
- Baubles
- BetterFps
- BirdsNests
- BlockDrops
- Bookshelf
- Botania

Better FPS is supposed to be improving some Trig functions by using a faster, simpler (and a bit less accurate) algorithm. I wouldn't expect it to impact world generation, but visual rendering. Anyway, need to pick 4-5 of the above mods to remove and retest.

**Comment by whichonespink44** [comment]
if it's happening at sea, maybe Aquaculture?

**Comment by Zarepheth** [comment]
Well, I removed 5 of the previously restored 9 mods. As I went around the Ice Plains island, I noticed a lone pumpkin, covered with snow, next to the beach.

Pumpkin coordinates X=-803, Z=539, Y=66, Vertical Chunk = 4.

The crashes typically occurred when the large hill came into view, but before I row far enough to see the other side.

Suspect mods:
- Apple Skin
- Aquaculture
- Bagginses
- BetterFps
- BirdsNests

**Comment by srs-bsns** [comment]
1. ~~BetterFPS isn't even in your original crashlog, so why is it even being loaded now?~~ n/m, I forgot it doesn't load as a mod.
2. https://github.com/Guichaguri/BetterFps/blob/590a04ce6b516d8316bd920c7c79d90ce94cda5f/src/main/java/guichaguri/betterfps/clones/tileentity/BeaconLogic.java#L102

**Comment by srs-bsns** [comment]
Well, here's your problem right here: [19:24:30] [main/DEBUG] [FML/]: Examining for coremod candidacy BetterFps-1.3.3.jar

BetterFPS v1.3.3 is for Minecraft 1.11, not 1.10.2. Downgrade back to BetterFPS v1.3.2.

**Comment by Zarepheth** [comment]
@srs-bsns You are probably right. I've narrowed down the crash to either "BetterFps" or "BirdsNests".
As for BetterFps not even being in the original crash, I'm pretty sure I didn't change my loaded mods for 1.10.2 until after I started testing and trouble-shooting. Anyway, I've had BetterFps (of some version) installed for quite a while... (Note: I reviewed the original crash log and I don't see it listed, so I don't know what's going on.)

I'll restore "BirdsNests" and see if the crash recurs, with BetterFps being the only mod removed.

**Comment by Zarepheth** [comment]
With only BetterFps removed, no crash occurs.
It's possible I added it without double-checking its MineCraft version because it was recently updated. I think I noticed that 1.11 mods were out after I'd already downloaded a couple updated mods.

Later this evening, I'll verify that BetterFps 1.3.3 crashes the game when running a 1.10.2 profile, then see what happens with BetterFps 1.3.2.

**Comment by Zarepheth** [comment]
BetterFps 1.3.2 works with no crashing (at least at the point all the other crashes occurred).
BetterFps 1.3.3 causes a crash.

**Comment by Zarepheth** [comment]
I've posted the issue on Guichaguri's BetterFps project: [https://github.com/Guichaguri/BetterFps/issues/15](https://github.com/Guichaguri/BetterFps/issues/15).

**Comment by Guichaguri** [comment]
BetterFps 1.3.3 is for Minecraft 1.11 indeed. The beacon improvement was added in 1.3.3 and I'm still testing it. Any other crash logs, please, report them directly to me ;)

It might be fun to implement a transformer tracking feature to OpenEye for logging which tweaker/coremod might have caused the crash...
