### ISSUE TITLE
Forestry trees not generating?

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1057]
We've had reports that Forestry trees aren't generating in RTG worlds.

**Comment by srs-bsns** [comment]
I'm pretty sure that Forestry trees don't naturally generate in the world. They can only be grown from Forestry saplings for which there are mechanics to acquire them (eg: bee pollination), though I could be wrong. However, from a quick glance at the source, I did not see a tree generator.

Perhaps, @mezz can enlighten us.

**Comment by mezz** [comment]
That's correct, Forestry trees don't naturally generate in the world.

**Comment by whichonespink44** [comment]
Thanks for the insight @mezz - much appreciated.
