### ISSUE TITLE
Port the 1.10.2 Logger to prevent NoClassDefFoundError

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1058]
http://hastebin.com/xucohuzeyo.sql

**Comment by srs-bsns** [comment]
already fixed in:
1.7.10: f93ecbdf3906a1c0f47400c24052996619c09fe2
1.8.9: a4e01a5a7a912a5f82552d12a6728dab7ad369a8
