### ISSUE TITLE
(Feature Request) Fractal Terrain option.

### ISSUE THREAD

**Issue by Quizer9O8** [Team-RTG/Realistic-Terrain-Generation#1062]
Is it possible for RTG to have a kind of config for fractal terrain feature? It would make some amazing continents and island from the shores all the way up to the snowy peaks.
ATG did something similar with the biome placement which was decided by the altitude, climate, geology, and rainfall.
To visualize it better here's an image to show you how it would look like.
![image](https://cloud.githubusercontent.com/assets/19509275/20651769/6201ab36-b4eb-11e6-9989-6cc853189cd7.png)
![image](https://cloud.githubusercontent.com/assets/19509275/20651800/29520316-b4ec-11e6-91dd-4bea021919e2.png)
 This request might end up becoming a totally different mod.

**Comment by whichonespink44** [comment]
It's a cool idea, but this would be better suited for something like Climate Control or another biome layout manager mod.
