### ISSUE TITLE
Possible conflict with world generation manager

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#1063]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 12.18.2.2151
- RTG version: 4.1.1.8

##### Issue Description:
When I have world generation manager installed, something is stopping its ASM transformer from working. I'm unsure if the issue is related to RTG, but it's my best guess at the moment. 

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Install world generation manager, including CreativeCore
2. Install RTG, version above
3. Add in biometweaker and biomes o plenty if needed

##### Extra Information:

fml-client-latest.log file

https://drive.google.com/file/d/0B3ZoX-8LP704bmk2UlliZkU1a00/view

**Comment by srs-bsns** [comment]
RTG doesn't utilise ASM at all.

**Comment by whichonespink44** [comment]
@chaNcharge The reason that mods use ASM is to modify Java code in other mods that they otherwise wouldn't be able to modify, so if another mod is having trouble modifying some code, it's up to that mod to fix it.

**Comment by chaNcharge** [comment]
Ok, thank you for the response
