### ISSUE TITLE
Populate biome configs with defaults for filler/mix/top blocks

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1065]
When the biome configs are created they should be populated with default values for:
```
S:"RTG Surface: Filler Block"
S:"RTG Surface: Mix Block"
S:"RTG Surface: Top Block"
```
This way people that want to change the blocks that are used in a biome will see what blocks are being used and will know which one to change. If someone that wants to change the blocks sees empty config fields, they're likely to become confused.

**Comment by whichonespink44** [comment]
The problem with adding default values is... if we ever modify a biome's surface blocks and update the default config values, the user will still have the old values in his configs, which means we'd need to either tell folks to delete configs before updating or implement some sort of config update management system, so not sure adding pre-populated defaults is the way to go.

However, I definitely agree that seeing empty values without any comments describing what the config does, or what format the values should be in, is extremely confusing. But I think all of the confusion can be eliminated if we just add some helpful comments, which is something I've been wanting to do for a while, but kept getting sidetracked.

Happy to discuss the pre-populating approach further though if we think it's worth exploring further.

**Comment by srs-bsns** [comment]
If not populate the config values, then atleast populate the comments with the default values?

**Comment by whichonespink44** [comment]
Added for 1.8.9 in 354f24e

**Comment by whichonespink44** [comment]
Added for 1.7.10 in d5e86bc
