### ISSUE TITLE
Outback biomes appear to be vacant in some spots

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1066]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:

1614

- RTG version:

1.1.1.3

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

It appears outback biomes are not always 100% decorated. Not sure if this is intentional or not. It happens with a few other similar biomes too.

https://www.dropbox.com/s/sxoztc7kjkj1vpo/Screenshot%202016-12-01%2017.17.50.png?dl=0

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Generate a world with BoP
2. Find an outback
3. https://www.dropbox.com/s/sxoztc7kjkj1vpo/Screenshot%202016-12-01%2017.17.50.png?dl=0

##### Extra Information:
N/A

**Comment by whichonespink44** [comment]
Fixed in 0effd67

**Comment by srs-bsns** [comment]
Does this need to be fixed post-1.7.10? I never checked.

**Comment by whichonespink44** [comment]
Not sure, but I'll definitely check it out. It probably does.

**Comment by whichonespink44** [comment]
Fixed for 1.10.2 in a13a7e2

**Comment by Sunconure11** [comment]
I found similar generation in Mesa Plateau M biomes on 1.7.10.

https://www.dropbox.com/s/iv38m5wvh303zlj/Screenshot%202016-12-07%2019.53.40.png?dl=0

I've also been seeing this issue again: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/817

But it always seem to trigger in savannas or similar biomes as of late.

I still have Magia Naturalis, but I'm likely going to pull it soon to see if it solves the issue for me, or if other stuff keeps causing it.

**Comment by srs-bsns** [comment]
@Sunconure11 
Magia Naturalis has a known serious issue with blocking biome decorations. It's not related to this issue at all, nor does it have anything to do with RTG.
See your other issue: #870

**Comment by Sunconure11** [comment]
Yeah I pulled it for now. I don't think it caused the missing generation in Mesa Plateau M biomes though. I'm pretty sure the shoreline between it and a river is not meant to be grass.

**Comment by Sunconure11** [comment]
I can confirm that some of the mesa biomes might be having the same issue as the outback. This is unrelated to the weird generation bug that I gave up trying to resolve as I wait for Thaumcraft to come onto 1.0.2.

https://www.dropbox.com/s/kr0g08aufus4gtb/Screenshot%202017-01-16%2019.11.32.png?dl=0

Mesa Plateau M

Check the code of similar biomes, to see if they could hypothetically be having the same issue.

This image is from the same seed as in the previous image of the same biome, but the map had been reset.

**Comment by Ezoteric** [comment]
It also spawns desert temples, it was near a river and beach but the biome said outback, just my 2 cents :P

**Comment by whichonespink44** [comment]
Fixed for 1.8.9 in 7101cae
