### ISSUE TITLE
Replace FATAL with FMLLog.bigWarning

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1068]

**Comment by whichonespink44** [comment]
Fixed for 1.10.2 in e41f0f8

**Comment by Sunconure11** [comment]
Is this CME related to this issue, by any chance? While it happened on a thermos server, I don't think thermos is to blame. I was using a mod to generate chunks when this happened, after finally pulling Magia Naturalis.

http://pastebin.com/fWEgy6gw

**Comment by srs-bsns** [comment]
This issue is only about changing how our logger handles `Level.FATAL` logging events. It has nothing to do with CMEs.

**Comment by Sunconure11** [comment]
I see. I guess I'll open up a new issue about this, though I'm pretty sure I did.
