### ISSUE TITLE
Enable 'cliff blocks' to be changed on a per biome basis.

### ISSUE THREAD

**Issue by TitusArmillius** [Team-RTG/Realistic-Terrain-Generation#1072]
The terrain shadowing option which changes the blocks used for the surfacing of steep surfaces in desert/mountainous biomes only applied universally.

In order to add increased biome customization, the blocks used for cliff surfacing should be configurable for each biome, akin to the other options currently available.

**Comment by whichonespink44** [comment]
Added to 1.10.2 in 0c4f542

**Comment by srs-bsns** [comment]
This doesn't seem like it would be that difficult to backport to 1.7.10, but would it really be that useful?

People that are still playing 1.7.10 have worlds that are many months old and probably aren't going to create a new world where this would be used.

**Comment by whichonespink44** [comment]
Added for 1.8.9 in e3a10d8

**Comment by whichonespink44** [comment]
Added for 1.7.10 in 2bbbc74
