### ISSUE TITLE
Some trees will be still generated after changing a biome on a map manually

### ISSUE THREAD

**Issue by ErikSteiner** [Team-RTG/Realistic-Terrain-Generation#1081]
##### Affected Mod Versions:

- Forge version: 1.8.9 - 11.15.1.1902
- RTG version: RTG-1.8.9-1.0.0-snapshot-3

##### Issue Description:
It seems like the vegetation would not follow the guideline of the biome settings, if I repopulate my map.
Repopulation means, that I can use [MCEdit](http://www.mcedit.net/) to highlight a specific chunk and tell Minecraft to respawn all vegetation and ores, related to the biome that is in this chunk. If I chop all trees in a chunk of a forest biome and I use MCEdit to repopulate this chunk, next time visiting this chunk, Minecraft will respawn all trees, vegetation and ores.

I came across this issue by using [World Painter](http://www.worldpainter.net/) to create a map with just the terrain (no trees, no ores, no vegetation). There are two options for populating a map that is exported from World Painter. The first option is to check the checkbox in the export menu of World Painter (Allow Minecraft to populate the entire terrain), all chunks will then be set to repopulate when visiting those biomes ingame. The other option is to use MCEdit and highlight the chunks by hand.

For both options I need to open MCEdit afterwards, load the map and to use the NBT Explorer to change the generatorName from vanilla to RTG and the generatorVersion from 1 to 0. So Minecraft is going to use the RTG mod for populating the terrain. The next picture will show the terrain, exported from World Painter, but before I set the map to repopulate. For now, you will not find any ores, trees, or vegetation. Using the F3 key will just inform you about the biome that you are currently in.

![vanilla](https://cloud.githubusercontent.com/assets/2684018/21094645/3d38c82a-c058-11e6-8f7a-7855d4354233.jpg)

The next picture will show the terrain after the population with RTG. In my opinion it is very strange to see a birch forest in forest/ forest hills biome, but maybe this is normal?

![2016-12-12_10 55 30](https://cloud.githubusercontent.com/assets/2684018/21094978/c19b382c-c059-11e6-9245-16c2957509d7.jpg)

Now comes the strange part. By exploring the map, I have several places at which the biome will not match the vegetation. For instance, I have several forests on Plain biomes (circled 1) and forests in forest biomes that will look like a different kind of forest biome (circled 2). The forest biome (circle 2) looks like a roof forest biome, but it should be a normal forest instead..
It seems to me that trees for forest biomes will not follow the biome guideline. I have several spots at my map that are Plain-Biomes and they still contain trees like in the forest biome. Moreover the output of the existing trees in forest biomes will be different. At different spots at the map, trees of forest biomes will look different..

![2016-12-12_08 52 29](https://cloud.githubusercontent.com/assets/2684018/21091947/b46bc514-c049-11e6-9fa5-b5c8df8d123f.jpg)

I just did another test. I started Minecraft and created a new world in Singleplayer using RTG under "More World Options". I traveled a bit around and closed Minecraft. I then opened MCEdit highlighted the whole map and used the replace tool, to  replace all vegetation- and treeblock with air. It cost me some minutes. When the map was empty, I highlighted all chunks and set them to repopulate. I saved the map and loaded it in singleplayer. The map was populated again and the result looked similar to the state it was before..

**EDIT:** To be clear, RTG is working correctly if I generate a map via singleplayer -> create world. My issue will only occur if I try to populate a terrain, exported from World Painter.

I hope someone can help me with this.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Create a map in World Painter
2. Export the map and highlight "Allow Minecraft to populate the entire terrain", you don't need to check the resource generator
3. Open the exported map in MCEdit and click the NBT Editor and change generatorName from vanilla to RTG and the generatorVersion from 1 to 0
4. Save the map and load it in single player

##### Extra Information:
- Feel free to ask for any information I could provide.

**Comment by ErikSteiner** [comment]
Strange thing is that if I add biomes of Biomes O' Plenty to the map and populate it, those biomes will work and they will obey the config. All vanilla biomes  that are affected will not. Using Bop with Biome Tweaker and the configuration provided in the Rtg thread.

**Comment by whichonespink44** [comment]
@ErikSteiner i have absolutely zero experience with WorldPainter, and I don't think anyone else on Team RTG does either... maybe @MobiusPeverell ? ... so I'm not sure how much help we're gonna be.

From reading your initial post, a couple of things jumped out at me... first, it's normal for RTG to generate decorations from one biome in another biome as the biomes transition into each other (we call it 'decoration bleeding') so that might explain some of the stuff you were seeing... then again, maybe not.

Also, something else to keep in mind... is that RTG uses what we call a 'delayed decoration system' which might be interfering with what you're trying to do. Delayed decorations basically mean that RTG sometimes doesn't actually decorate the biome until its neighbouring chunks have also been decorated... this is to avoid what we call 'rabbit holing' whereby Minecraft gets stuck in an infinite(ish) decoration loop when it tries to decorate one biome, whose decorations bleed into another biome, causing it to decorate, whose decorations bleed into another biome, causing it to decorate, etc etc. Again, not sure if that's actually interfering with what you're doing, but just something to keep in mind.

It's very strange indeed that BOP works and vanilla does not... do other biomes from other biome-adding mods also work? Or is it strictly a BOP thing?

**Comment by ErikSteiner** [comment]
@whichonespink44: 
> From reading your initial post, a couple of things jumped out at me... first, it's normal for RTG to generate decorations from one biome in another biome as the biomes transition into each other (we call it 'decoration bleeding') so that might explain some of the stuff you were seeing... then again, maybe not.
> 
> Also, something else to keep in mind... is that RTG uses what we call a 'delayed decoration system' which might be interfering with what you're trying to do. [...] Again, not sure if that's actually interfering with what you're doing, but just something to keep in mind.
I didn't notice  anything that could just be related to biome bleeding. I mean the decoration/vegetation of biomes is just wrong. Speaking from the perspective of my exported map from World Painter.

> It's very strange indeed that BOP works and vanilla does not... do other biomes from other biome-adding mods also work? Or is it strictly a BOP thing? 
I only use RTG, BoP and Biome Tweaker (because it is required). Should I try out a specific mod to clarify the issue? Maybe you have an idea what to try out..


## **Scientific investigation of the biomeology**
_It isn't actually a scientific investigation, but man it became a lot of text.._

I have a theory why it does not work as it should. To anticipate it, my theory seems to be right. So I created a map in world painter with vanilla biomes and a few BoP biomes. My core problem is, that all vanilla biomes don't contain the vegetation of a corresponding biome, but of a random one. This issue will occur if I only use the mod RTG, or RTG together with Biome Tweaker and BoP. Therefore the issue can not be related to BoP, or Biome Tweaker. The only strange thing is, that only the BoP biomes on my map will contain the correct vegetation (decoration, trees, etc.).

My theory is, that if you create a map in singleplayer with RTG, Minecraft will pick a random seed and will create the map. The output of the biomes is related to the seed: What biome to put where. Normally, the decoration and vegetation of a biome should be spawned in conjunction with the biome. So Minecraft, or in this case RTG looks at the map, thinks "Hey this is a plain biome, I am going to put some shrubs here" and continues with the next chunk/biome.

Now to me it looks like RTG is not going to spawn the decoration and vegetation related to the actual biome, but to the seed. Finally it won't make any difference if the vegetation and decoration is being placed related to the seed, or if the biome is being placed related to the seed and RTG just adds vegetation and decoration (related to the biome) afterwards.

In my case, however, the above facts make a clear difference to the output of my map. Down below you can see some tests that I did..

## **Case One**
**My used Mods:** RTG-1.8.9-1.0.0-snapshot-3, BiomeTweaker-1.8.9-2.1.211, BiomesOPlenty-1.8.9-3.0.0.2004-universal
**Config:** I used the configuration for Biome Tweaker 1.8.9 provided by the RTG Thread.

1. I started Minecraft, clicked Singleplayer, Create New World, More World Options, World Type: Realistic and allowed cheats. I clicked Create New World and found a very nice looking island with Taiga Hills Biome. I waited some time, so Minecraft can load all chunks in the surroundings. I took a screenshot and exited to the main menu.
![2016-12-13_08 24 57](https://cloud.githubusercontent.com/assets/2684018/21134864/f465c51c-c11f-11e6-8355-def7671135d8.jpg)


2. I opened the map in MCEdit afterwards, selected a small amount of chunks that were in front of the screenshot above and set them to "Repopulate". Next time visiting the map, Minecraft will redecorate them. In the next step I deleted everything in the selected chunks that was a block of vegetation or of a tree. I used the "Replace Tool" for that, by turning Wood 17:0 into Air for instance. When I was done, I only had a nice looking field of grass, I mean just the terrain. This is important, because when the map is going to repopulate, Minecraft will spawn new trees, ferns, vegetation and decoration, so it has enough space to do all that magic. After it I wanted to change the biome of the empty space from Taiga Hills Biome to something different. I used the [SetBiome](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1265434-1-9-sethblings-setbiome-mcedit-filter-updated-for) filter to replace the biome of these chunks from Taiga Hills Biome to Plain. In theory, if I load the map in singleplayer, the decoration and vegetation should be spawned, related to the Plain Biome.
When I was done, I created a backup of the map, so it was easier for me to do some testing without removing all that vegetation stuff all over again..
So here is the output of the map, loaded in Minecraft:
_As you can see, the color of the grass changed, related to the different color set of the Plain Biome. The trees however are still the same like they were in the Taiga Hills Biome._
![2016-12-13_08 29 49](https://cloud.githubusercontent.com/assets/2684018/21135482/59547200-c122-11e6-99aa-e1230bad9787.jpg)


3. The result was pretty disappointing, but I thought to myself that the result of the output was because of some "biome bleeding". I mean that the neighbor biome (Taiga Hills Biome) tinted the Plain biome. I took the backup of the map from the first test (1.), opened the map in MCEdit and selected a larger amount of chunks. I removed the vegetation and decoration of those chunks and set the biome to Plain again. This time it should be more visible that we now are having a Plain Chunk..
_As you can see, the grass color changed a bit more, having a larger space of the Plain biome. The trees are still looking the same like in a Taiga Hills biome_
![2016-12-13_08 42 22](https://cloud.githubusercontent.com/assets/2684018/21135848/7bc4a85e-c123-11e6-89d9-6ff253bfb6b9.jpg)


4. After the third test, I thought that the problematic output could be caused by the terrain. I mean I wanted to change a hill biome to a plain biome. Maybe the decoration don't likes hilly terrain? Therefore I took the backup of the map and replaced the same amount of chunks like in test three (3.) with the Birch Forest Hills biome. In theory one should see a lot of birch trees then.. Finally.. No..
![2016-12-13_09 32 52](https://cloud.githubusercontent.com/assets/2684018/21136083/78d4f9ea-c124-11e6-96e0-e35e1bedc1b2.jpg)


**Résumé of Case One**
I was not able to exert influence on the vegetation and decoration output by changing the biome. 
RTG always used the vegetation and decoration of the biome that was previously there, in this case Taiga Hills Biome. The map seed was always the same, because I always altered the same map, so the only difference was the biome that was changed. 



## **Case Two**
**My used Mods:** RTG-1.8.9-1.0.0-snapshot-3, BiomeTweaker-1.8.9-2.1.211, BiomesOPlenty-1.8.9-3.0.0.2004-universal
**Config:** I used the configuration for Biome Tweaker 1.8.9 provided by the RTG Thread.

From my investigations of Case One, I came to the conclusion, that my exported World Painter map must have the same problem with biomes, than the map of Case One.

So I created the following test environment:
- Create a Map in Singleplayer that has the same map seed than the map in World Painter. Even if isn't important what that seed in World Painter is, but I am cautious. The seed ID is **2823673442459948865**
- Open the created Singleplayer map and travel to a specific place that is also represented on the map of World Painter.
- Create a copy of the Singleplayer map (RTG Test - WP)
- Open World Painter and use the Merge option to export the map to "RTG Test - WP"
- Having two maps now, one that is the natural output of the seed (lets call it RTG Test) and a merged version that reflects the map of World Painter "RTG Test - WP" (with terrain and biomes). I have to add that if the map is being exported (in this case merged), the vegetation and decoration will be placed at the point of loading the map and visiting a specific chunk. Until then the map is naked.

_Merging means, that World Painter will replace the whole terrain and the biome-information with the information of the map that I have painted in World Painter. By merging the map, all vegetation and decoration of the original map will be removed and all chunks will be set to repopulate._

1. I started Minecraft, clicked Singleplayer, Create New World, More World Options, World Type: Realistic and allowed cheats. I entered the seed from above and clicked Create New World.

2. While the world was loading, I switched to World Painter and chose a location for investigation. I chose my favorite location, noted the coordinates and had a look at the biomes of that area. The next few screenshots will show the circled location, the camera will be a bit higher (northern), facing to the south.
![wp](https://cloud.githubusercontent.com/assets/2684018/21136933/fa61ebfa-c127-11e6-8984-027b23e348de.png)


3. I then switched to Minecraft and entered /tp 718 125 431, facing south. The following picture represent the map that was created with the seed from above (RTG Test). You can test it on your own:
_There are little trees that represent the forest biome and larger trees in the distance that represent forest hills biome. You can see a little swamp biome in the distance_
![2016-12-13_10 07 58](https://cloud.githubusercontent.com/assets/2684018/21137136/d543cb6c-c128-11e6-9a3b-283f3d37a3e2.jpg)


4. I exited Minecraft to the main menu to save the map. After that I switched to World Painter and clicked "Merge with Minecraft map" and chose the map from the test above "RTG Test - WP". When the export process was done, I switched to Minecraft, still in the main menu and opened the altered map "RTG Test - WP". The good thing is, that I was still at the same position than before. So you have the same position of the camera, with the same angle than in the screenshot above. This makes it easier to notice some interesting things:
_These little trees in front of the camera and the larger trees in the background are still there. There is still the same vegetation and decoration than before. Did you notice the swamp trees from the picture above? They are still there, even if they are now a bit higher. More than that even if the biomes were changed in test two, the vegetation and decoration is still the same like in test one (3.). The only difference seems to be the river, that divides the biome in front. As a side note, the biomes changed in test two. F3 will give me the information that I am now in Roofed Forest, even if the vegetation still looks like the vegetation of a forest biome_
![2016-12-13_10 06 45](https://cloud.githubusercontent.com/assets/2684018/21137550/410b9e0a-c12a-11e6-8da6-f297f162ecd9.jpg)


**Résumé of Case Two**
As in test one, my theory was also confirmed in this test. So no matter what I do in World Painter and to what I change the biomes there, if I export the map, the biome information will be exported, but the output of the decoration and vegetation is still related to the seed and not to the biome. However, I am able to see the changes to the biomes via F3 ingame.


**I hope I was able to provide as much information as I could in order to investigate this problem and hopefully find a solution. On the one hand the output of my World Painter map looks pretty awesome, but on the other hand it is very strange that all decoration and vegetation of vanilla biomes that are affected by RTG will not follow the guideline of the biome, but of the seed. Furthermore I do not fully understand why the decoration and vegetation of BoP biomes will follow the guideline of the biome and not of the seed. Feel free to ask for savegames or log files.**

Edited at CET 22:32:51 12/13/2016: Changed and optimized the text a bit..

**Comment by ghost** [comment]
Hm. Certainly seems reasonable. Just wondering though, why did you want a pre-made map (terrain at least) loaded through RTG? For the trees? Because you can paint those in yourself using a custom layer with Custom Tree Repository trees. Great looking map, by the way.

**Comment by ErikSteiner** [comment]
> Just wondering though, why did you want a pre-made map (terrain at least) loaded through RTG? For the trees? Because you can paint those in yourself using a custom layer with Custom Tree Repository trees.

Long time ago, I started to use Terrain Control to alter the biome settings and to create a landscape of my dreams. It is a very powerful tool, but I am not one of those who are good at programing beauty. After a while I changed my strategy and used Terrain Control just only for the vegetation, so I removed the vanilla trees from specific biomes and added Custom Tree Repository, added decoration.. It was very time consuming. To that time, I already used World Painter to create my naked terrain and I just painted the biomes on top of that. I then set the specific chunks to repopulate and everything was fine. **Back ingame in Minecraft I was able to enjoy my work.** -> I am currently failing at this sentence here with RTG.. So Terrain Control was cool, but I am tired of doing all on my own. RTG looks very unique and awesome, so why shouldn't use this mod for my map that contains mostly vanilla biomes?

> Great looking map, by the way.

Thank you. The oldest part of the map is from 2011. At that time Minecraft got out of Beta. While the core of the map grew and a lot of buildings were build, I revamped the surrounding area a few times. I always wanted to have a large island with smaller island, so one can travel by boat between them. Total surface area: 8,667 km². Land area: 1,707 km².
This edit should be the last one :)

**Comment by ghost** [comment]
Yeah, I just do all my vegetation and everything in Worldpainter using custom object layers with Repository trees.
And a cool tip I saw a little while back: try doing cliffs with wavy veins of prismarine in the stone using custom terrain. It looks awesome.

**Comment by ErikSteiner** [comment]
@whichonespink44 Hi there.

Today I want to show the influence of BoP and Thaumcraft biomes on the output of the map. I am going to create a map in singleplayer with RTG, Biome Tweaker, BoP and Thaumcraft, with the seed **2823673442459948865**. Then I am going change the biomes of this map. Normally I could do that with MCEdit like in my last investigation, but World Painter can do that, too. A lot faster. I am going to change the biomes in a specific location to biomes of BoP and Thaumcraft only, because in my last investigation, I came to the conclusion that vanilla biomes of RTG will not be decorated in relation to the biome, but to the map seed. So what will happen, if I am using BoP and TC biomes only?

## **Decoration output of a vanilla map in Minecraft**
Before I begin my investigation, I want to show Minecraft's vanilla behavior. For that I am going to use no Mods. I am going to create a map in singleplayer with the vanilla terrain generator (seems logical if I am not using any mods), take a screenshot and change the biome to something else. Then I set the chunks to repopulate and take another screenshot of the result.

I left the field for the seed blank, so here we are in a jungle biome:
![2016-12-13_21 33 00](https://cloud.githubusercontent.com/assets/2684018/21216800/16d7a2d4-c2a9-11e6-9a3c-4f20a3dd1dd0.jpg)

Then I open the map in MCEdit, highlight some chunks and remove all vegetation, set the biome in these chunks to birch forest and set the chunks to repopulate. As you can see, I only left the terrain:
![mcedit](https://cloud.githubusercontent.com/assets/2684018/21216912/b067a2e6-c2a9-11e6-9491-612a084ab62e.jpg)

I load the map again and take a screenshot. As you can see, the decoration changed to a typical birch forest biome. F3 will give me the information, that I am in a birch forest:
![2016-12-13_21 32 20](https://cloud.githubusercontent.com/assets/2684018/21216945/dd44bbfa-c2a9-11e6-9bd6-777329b20604.jpg)

So the map seed has no influence on the output of the decoration of a biome. If I change a biome to something else, remove all the vegetation and set the chunk to repopulate, Minecraft is going to repopulate the chunk in relation to the biome and not to the seed.


## **Decoration output of a RTG map in Minecraft**
Now I am using the mods down below and create a map in singleplayer. The generator will be set to realistic and I will use this seed here: 2823673442459948865

**My Mods:** RTG-1.8.9-1.0.0-snapshot-3, BiomeTweaker-1.8.9-2.1.211, BiomesOPlenty-1.8.9-3.0.0.2004-universal
**Config:** I used the configuration for Biome Tweaker 1.8.9 provided by the RTG Thread. I downloaded the config for Biomes O' Plenty and added the lines of the TC-config. Just rename the RTG.txt to RTG.cfg:
[RTG.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/654146/RTG.txt)

The output of the map has changed a bit, I guess that this is because I added Thaumcraft as another mod. When Minecraft is ready, I am going to explore the map and save it by going back to the main menu. Then I create a copy of the map folder and load that copy into World Painter. I am going to change all biomes of that map to only one biome and set the whole terrain to grass. After the map export, the map will be empty and I have to set the map to repopulate. Then I can easily compare both maps and I can investigate the influence of the vanilla biomes on BoP- and TC-biomes.

1. The folder name of the generated (not edited) world is **RTG BOP TC** and the edited world's name is **RTG BOP TC - BoP - WP**. I changed the biomes of **RTG BOP TC - BoP - WP** to Cherry Blossom Grove only, so everything on this map should be a pretty Cherry Blossom Grove. Now I am going to show you some examples where the vegetation don't fit to the biome and where I get the impression that the vegetation of the former biome will cut through the current biome-decoration.

- The first screenshot shows the edited world. As you can see, there are a lot of Cherry Blossom trees, but there are also some trees that look like a pine. F3 will give me information that I am in a Cherry Blossom Grove biome.
![2016-12-16_07 56 39](https://cloud.githubusercontent.com/assets/2684018/21254427/a9251c54-c365-11e6-94a7-d346e35b8d16.jpg)
- So let's take a look at the, let's call it vanilla world and maybe we can find the reason for those pines from the picture above. The grass with the mint green color represents a Grassland biome of Biomes O' Plenty. In front of use, we have a ForestHills biome. The biome to the right, covered with snow is a Extreme Hills biome. If we compare both screenshots, it seems obvious that those pines from the ForestHills biome of the picture above, are going to cut through the Cherry Blossom Grove biome  (edited world), but their position changed slightly. Smaller trees seem to have no impact on the edited world (don't cut through).
![2016-12-16_07 57 15](https://cloud.githubusercontent.com/assets/2684018/21254520/2d4b6c86-c366-11e6-9066-0750c524b23b.jpg)
My first conclusion is, that if a BoP biome will be changed to a BoP biome, everything is fine. If a ForestHills biome will be changed to a BoP biome, larger trees of the ForestHills biome are still visible, even if their position moved slightly.
- The next screenshot shows three biomes of the vanilla map. Down below colored in mint green, we have the Grassland biome of BoP, in front of us we have a Forest biome and in the background we have a ForestHills biome. I draw some lines to show the borders of the biomes. I guess that the trees at the buttom of the screenshot come from "biome-bleeding", so they blent into the Grassland biome.
![2016-12-16_08 20 29](https://cloud.githubusercontent.com/assets/2684018/21254885/c74ce704-c368-11e6-8bd2-5866d82fb575.jpg)
- The fourth screenshot shows how it looks like in the edited world. We are still having Cherry Blossom Grove biomes everywhere, but there are trees that don't fit into this biome.. Moreover you can see some shrub of the Forest biome between the cherry trees and to me it seems like the density of the cherry trees were increased. So my conclusion is, that the smaller trees of the Forest biome just have been converted to cherry trees.
![2016-12-16_08 27 15](https://cloud.githubusercontent.com/assets/2684018/21255078/f73e7468-c369-11e6-8e77-f42ed88f35dd.jpg)

- Because of that, I decide to create a new copy of the vanilla world and to convert the biomes of the copy to Grassland. The copy of the vanilla world is called **RTG BOP TC - BoP - Grassland**. The Grassland biome looks like this and it will make it easier for me to analyse the impact of vanilla biomes that have been changed to a BoP biome:
![2016-12-16_08 58 06](https://cloud.githubusercontent.com/assets/2684018/21255754/1e04eb82-c36e-11e6-8528-68c335665c7e.jpg)

- After I changed everything to Grassland biome, I visited the location again. As you can see, the vegetation of the Forest and of the ForestHills biome is present. It seems that I was right with my theory that smaller trees of the Forest biome were just converted to cherry trees in my last test. This could explain the increased density of those cherry tress from the test before.
Did you notice the group of sheeps? Before I loaded the map with the Grassland biome, I added two lines at the end of the RTG.cfg:
grassland.removeSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE")
grassland.addSpawn("net.minecraft.entity.passive.EntitySheep", "CREATURE", 1000, 20, 40)
I wonder if somehow only the biome name will be changed, but everything else would be left the same. I mean, if I change a Forest biome to Grassland, will just the name (F3) change to Grassland, or will the biome behave like a Grassland biome? It turned out that I found large groups of sheeps everywhere on the map, no matter what a biome was before, now being changed to Grassland, I found them in Forest, ForestHills, etc.
![2016-12-16_10 47 29](https://cloud.githubusercontent.com/assets/2684018/21258667/582fd866-c37e-11e6-870a-8ef807aa5a5a.jpg)

2. For my last test I want to know the behavior of a Thaumcraft biome on the output of a map. So I created a copy of **RTG BOP TC**, changed all biomes to Tainted Land and replaced the terrain with Grass. I renamed the folder to **RTG BOP TC - TC - Tainted Land** and set the chunks to regenerate.

- Now back in place, everything changed to Tainted Land biome of the Thaumcraft mod. While looking at the screenshot down below, I noticed that mushrooms will also cut through the changed biome. If you have a look at the vanilla map, you will get the information that a Magical Forest (Thaumcraft) biome can be seen in the background of the screenshot (to the right side, on the hill). This will mean that if I change a Thaumcraft biome, that spawned at my vanilla map naturally, to another Thaumcraft biome, the biome will change, but the vegetation will not. So it would be very interesting to know if the same thing will happen with a BoP biome, that contains trees and that will be changed to Grassland for instance.
Screenshot of the altered map:
![2016-12-16_11 21 56](https://cloud.githubusercontent.com/assets/2684018/21259546/383748d8-c382-11e6-927a-d035a60f57c3.jpg)
Screenshot of the vanilla map:
![2016-12-16_11 22 10](https://cloud.githubusercontent.com/assets/2684018/21259788/4f039354-c383-11e6-8d5b-7a68480f2fa1.jpg)

3. OK, it was not my last test. Now I am looking at a BoP biome: Dead Swamp
What will happen if I change the whole map to Grassland, so Dead Swamp will turn into Grassland?
Screenshot from the vanilla world:
![2016-12-16_11 59 46](https://cloud.githubusercontent.com/assets/2684018/21260753/c81b7bfe-c387-11e6-847e-1edae1c7abb4.jpg)
Screenshot of the altered world:
It is very interesting, that it seems like the terrain were decreased in height. Pretty strange, but I can not see any trees of the Dead Swamp on the other hand. So except the weird output of the Grassland, I will not have any trees that cut through the biome.
![2016-12-16_12 01 43](https://cloud.githubusercontent.com/assets/2684018/21260761/d400abce-c387-11e6-960a-dda18a96d47a.jpg)

Still on the same map, I am going to visit a (Steppe) BoP biome, that was changed to Grassland. Steppe is very interesting, because it contains a few of trees. So what will happen if I change the biome to Grassland. This is how it looks like in the vanilla map:
![2016-12-16_12 14 11](https://cloud.githubusercontent.com/assets/2684018/21313706/a413e4a8-c5f3-11e6-8b3e-20281708969f.jpg)

Like in the biome before, you can see that the terrain was changed slightly in height. There are also trees of the Steppe-biome, even if the biome changed to Grassland:
![2016-12-16_12 15 52](https://cloud.githubusercontent.com/assets/2684018/21313720/b16ff7b8-c5f3-11e6-9ab7-f1aace42eaea.png)


## **Résumé**
When I started to investigate the issues of wrong vegetation and trees in biomes that were changed, I thought that the issues would only occur in vanilla biomes that were altered by RTG. I was wrong I guess. If I changed a vanilla biome to a BoP, or a TC biome, there were always the same types of trees that cut through the terrain: this tree that looks like a pine, smaller trees that look like in the vanilla game and mushrooms. The same happened to me if I changed a BoP, or a TC biome to a biome of the same mod, or to a biome of a different mod. Moreover I think that I have to rename my issue, there is no problem with the vegetation that will not be placed correctly, but with the trees. There is only an issue with trees and to me it looks like the trees are going to be placed by the seed ID while the other things will be generated by the biome. I don't have any idea of the different pipelines of RTG, but normally the process should look like this:

- The seed id will be the foundation of the biome placement and everything that is related to decoration and trees will be placed by the output of the biome:
![prasentation1](https://cloud.githubusercontent.com/assets/2684018/21314444/74007084-c5f7-11e6-8b99-088542644778.png)

- The following picture shows my point of view of RTG. It seems like some trees were cut out of the generator process and they will be generated directly out of the seed. Strange thing is that as you saw at the example of the Cherry Blossom Grove, smaller trees can be converted to fit into the new biome:
![prasentation2](https://cloud.githubusercontent.com/assets/2684018/21314536/f0936d4a-c5f7-11e6-98d8-a61c60a9146b.png)

I hope that there is a chance to fix the issue, because the output of a map, that were made in World Painter, or even if you only change a biome of your map, is totally tied to the former biome. It would be very disappointing for me to have no influence on the output of a map.

Here is the link to my save files, so you can have a look on your own: [LINK](https://mega.nz/#!DcBnGK6a!VQv3HrEz2xwr04boacybXYWLZfiISOxcsSEiJ-3fjAM)

**Comment by ErikSteiner** [comment]
There is really something strange going on. It seems like I am right with my theory of how RTG works, even if I am not aware of the process in detail. If I set the world to repopulate, RTG seems to start from scratch by looking at the seed ID and places the trees (all type of trees and Mushrooms, too) related to the ID. There is also something going on with the terrain generator, because I saw a change in height if I changed a biome to Grassland. On the other hand, I don't know why the complete generation of the terrain will no kick in, so deleting the current terrain and doing the terrain again by the seed. It seems to me like it is mixed.

On my recent exploration on my world painted map, I had an interesting discovery. I was in a Quagmire biome of BoP and the former biome of the original map was a MushroomIsland. The MushroomIsland contained some Glowshrooms that emitted light. Being on my world painted map, it seems to me that those lights were generated, because of the seed ID, while there were no Glowshrooms, but the light sources.

Quagmire. This is how the world looks like, after I exported my map from World Painter.
![2016-12-21_08 02 20](https://cloud.githubusercontent.com/assets/2684018/21380472/ca926c40-c755-11e6-986c-f488a8ef746f.jpg)

MushroomIsland. This is how the world looks like, if the world is generated by the seed ID from before.
![2016-12-21_08 04 13](https://cloud.githubusercontent.com/assets/2684018/21380495/ec52f89a-c755-11e6-8400-24b608fdbe5a.jpg)

**Comment by whichonespink44** [comment]
@ErikSteiner We were discussing this issue on our Discord server the other day, and Zeno had this to say about it:

> IMO it's the painter mod's issue. The painter mod would need to replace the Genlayer stack with something that produces the painted biome where it has been painted. It would be expensive disk-access-wise and a pain programmatically for us to check the stored biomes as well as the Genlayers.

With that said, I'm not sure what the best way forward is from here... I'm thinking it would probably be best if the author of World Painter got involved, as it sounds like there isn't much we can do from our side.

@Captain-Chaos Any ideas on how this issue can be resolved? If there's anything we can do on our side, we'd be more than happy to explore those options. Also, feel free to hop on Discord server if you want: https://discord.gg/0wIG7mz3g6TpkBsB

**Comment by Captain-Chaos** [comment]
Could someone give me a summary of the issue? Is "the painter mod" WorldPainter, and to what does "the Genlayer stack" refer? It doesn't sound like something that WP would have control over. Remember that WorldPainter is not a mod, it's a stand alone program which generates Minecraft maps on disk. It has no influence on a Minecraft client or server's runtime behaviour other than what can be communicated through the chunks or the level.dat file. Much of Minecraft's API (things like block names for instance) doesn't apply to WorldPainter because it isn't used on disk.

Regarding biomes, all WP can do is set the biome IDs stored in the chunks (to vanilla Minecraft IDs or custom IDs), and reset the "TerrainPopulated" flags on the chunks. There is no way that I'm aware of to communicate anything else to the runtime system about what should happen when a chunk is populated.

**Comment by whichonespink44** [comment]
@Captain-Chaos Sorry for not replying sooner - I have absolutely no idea how I missed your reply!

Given that WP works primarily with the level.dat file, I don't think there's anything that can be done to resolve these issues. And even if there was, we don't have the resources to dedicate to fixing it as all of our time has already been allocated to other projects.

Having said that, we're making a number of fundamental changes to RTG in the 1.11.2 version, so maybe we can look into this again at a later date, if those issue haven't already resolved themselves, as these sorts of things sometimes have a way of doing.
