### ISSUE TITLE
Remove biome patching from RTG saplings

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1082]
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-master/src/main/java/rtg/event/EventManagerRTG.java#L223-L228

RTG should just log a warning here instead of patching the biome and handover the sapling growth to the vanilla logic.

This will prevent situations like #1080 from happening in rare edge cases.

**Comment by whichonespink44** [comment]
Fixed for 1.10.2 in 72a502a

**Comment by srs-bsns** [comment]
This should be an easy port to 1.7.10

**Comment by whichonespink44** [comment]
Fixed for 1.8.9 in 55b66dd
