### ISSUE TITLE
Add support for Growlith's fork of Ars Magica 2 on 1.10.2

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1083]
https://github.com/Growlith1223/ArsMagica2

**Comment by srs-bsns** [comment]
@whichonespink44 It's likely still the one biome. We just need to port from 1.7.10: https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.7.10-master/src/main/java/rtg/world/biome/realistic/arsmagica

**Comment by whichonespink44** [comment]
The Witchwood Forest isn't currently being registered in 1.5.0-11: https://github.com/Growlith1223/ArsMagica2/issues/30

Gonna have to wait until that gets fixed before we can add biome support.

**Comment by srs-bsns** [comment]
fixed in https://github.com/Growlith1223/ArsMagica2/pull/107/commits/afac12cbbb31e6e85c32c49cb3184e9e76b6496d

**Comment by srs-bsns** [comment]
@whichonespink44 
There is a new release with the working biome that can be used for testing: https://github.com/Growlith1223/ArsMagica2/releases/tag/v1.5.0-12

**Comment by whichonespink44** [comment]
Added in 0a37d66
