### ISSUE TITLE
Village frequency issue

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1088]
On the MMD Dev Server, village generation seems to be boosted somehow. The RTG configs are using vanilla frequency settings (min distance = 8, max distance = 32), but there seems to be way more villages than there should be.

I've not noticed this in any testing I've done in SSP with those same settings, so I can only assume it's a mod interaction bug. I'll try to investigate this in SSP with the MMD Dev modpack and see if I can find the source.

![1088-villages](https://cloud.githubusercontent.com/assets/8453133/21373312/f7eb34ac-c6eb-11e6-8062-60bf376cce07.png)

**Comment by whichonespink44** [comment]
Villages tend to generate more frequently in RTG worlds, I'm assuming because there are more suitable spawn locations, given a greater amount of flat terrain, but I haven't confirmed that's the reason. That's why the default RTG configs are set to be lower than vanilla, so that they effectively end up generating at about the same frequency as vanilla.

**Comment by srs-bsns** [comment]
Due to how villages seem to generate on the sides of mountains and over rivers, I can't see there being much checking going on for a suitable site that would have them generating less in a vanilla world. Though I always wondered why you had more relaxed settings in the config.

I don't really recall seeing much of an issue like this during testing when I used the vanilla values, though. Or, maybe I'm just being senile.

The first time you changed them from defaults was here: https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/3f9ad31413b0a3f40ef4ae16a58d4d04b6e25746
from the changelog for [v0.3.0](https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v0.3.0): `Made villages & scattered features twice as rare - but they're still generating more frequently by default than they do in vanilla.`

and then to the current settings: https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/26432933c4f5dbbef75afadf0abc25056e0568b3
from the changelog for [v0.5.0-RC-1](https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v0.5.0-RC-1): `Increased default frequency of villages & scattered features.`

/shrug... guess we should just stick with the RTG defaults then.

I'll still do some testing with the MMD dev modpack to be sure though.

If there is an issue, it could be with the delayed decoration system, and it will likely be somewhere in here: https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/world/gen/ChunkProviderRTG.java#L510-L767

**Comment by whichonespink44** [comment]
Actually, now that I think about it, it's probably more to do with the fact that villages can generate in most biomes in RTG, whereas only a couple biomes in vanilla have villages enabled. I bet the frequencies would be the same if only the vanilla village-biomes had villages allowed in RTG worlds.
