### ISSUE TITLE
Vines on Volcanoes

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1091]
They're everywhere... need to copy across the fix from 1.7.10 as I think it got lost somewhere along the way.

**Comment by srs-bsns** [comment]
I've never seen this. (not callin you a liar though as none of the volcanos I've seen recently were in Jungle.) #BlameRTG

**Comment by whichonespink44** [comment]
Fixed in 1597c0e

(Vines weren't appearing on volcanoes in Mega Taiga, but they were on volcanoes that spawned in jungles.)
