### ISSUE TITLE
Server cant generate chunks caused to run out of memory [1.7.10]

### ISSUE THREAD

**Issue by Happiys** [Team-RTG/Realistic-Terrain-Generation#1092]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.7.10 - 10.13.4.1614
- RTG version: 1.7.10-1.1.1.3

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
Forge seems to confused it self with what mod It wants to use to generate a world so it run out of memory in 10 seconds *16 gbs of ram*

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Used the mod with Highlands and Biomes O' Plenty on newest version on the server
2. Use mod by it self on the server
3.

##### Extra Information:
Pastebin when used with a private modpack
http://pastebin.com/Winx9rmu

**Comment by srs-bsns** [comment]
1. The stacktrace in that crash report doesn't show any RTG classes at all, and it alludes to it occuring with Mystcrafts chunk provider, which means this is in a Mystcraft dimension. RTG only works in Dim 0 and will not do anything in a Mystcraft dimension at all.

2. RTG has never done anything on it's own that would lead to a server running out of memory. Either your server doesn't have enough memory allocated to the JVM, you are using bad GC settings in the JVM, or another mod is causing a memory leak.

3. You are using RTG with mods that add biomes (BoP, Highlands, EBXL) and you aren't using either ClimateControl or BiomeTweaker, so your Overworld (Dim 0) isn't going to have any of the mod-added biomes.

**Comment by Happiys** [comment]
Yeah kinda found out after removing it
