### ISSUE TITLE
Wrong kinds of wood generating in tropical biomes

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1096]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:

2185

- RTG version:

4.1.2.1

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

When Biomes O' Plenty is installed, if one goes in a tropical biome, fallen hellbark will dot the landscape as opposed to fallen palm wood.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Generate a world with a tropical island biome on 1.10.2
2. ???
3. Fallen hellbark instead of fallen palm wood

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by srs-bsns** [comment]
![2017-01-01_17 58 09](https://cloud.githubusercontent.com/assets/8453133/21583374/f05d23bc-d04b-11e6-9c30-4773cd5c2e9a.png)

**Comment by whichonespink44** [comment]
Bleh, thought we fixed that one already... I'll get this sorted for the next release this weekend.

**Comment by whichonespink44** [comment]
Fixed in 6d7f75d
