### ISSUE TITLE
[feature request] biome size settings by biome

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#1098]
I would like to be able to set biome sizes per biome rather than by world.  So for example, have plains size 7 and swamps size 2.  This would be especially good with other mods that add special or magical biomes, as we like large biomes, but having those biomes large makes them kind of not-special.  Now that you have a config file for each biome, this ought to be possible and not too difficult to add ?  To my knowledge there's never been a mod that's enabled you to do this, so it would be a first as well :)

**Comment by srs-bsns** [comment]
RTG only generates the terrain, it does not handle biome layouts.

As of the time of this posting, I don't believe there is any mod that can do what you are asking.
