### ISSUE TITLE
Igloo generation seems broken

### ISSUE THREAD

**Issue by NitroxydeX** [Team-RTG/Realistic-Terrain-Generation#1099]
##### Affected Mod Versions:
- Forge version: 1.10.2-12.18.3.2185
- RTG version: 1.10.2-4.1.1.8
- Biomes O Plenty: 1.10.2-5.0.0.2109

##### Issue Description:
![minecraftcoldbiomes](https://cloud.githubusercontent.com/assets/9305576/21591067/2198bc38-d101-11e6-8ca2-7987d7ccc2e2.PNG)

I've searched through a kinda big cold area for Igloos. You find some special items from "Tough as Nails" inside the Igloo chests but I couldn't locate a single one there. 
I've saw a comment in the forum that mentioned Igloos should be fixed since some of the 1.9-updates.

**Comment by srs-bsns** [comment]
Igloos are very rare, even in vanilla. The only biomes they generate in are Ice Plains, and Cold Taiga, and even in those biomes they are very rare. Regardless, I've verified that they are generating in RTG worlds.

If Tough As Nails generates loot in igloos, then it's either designed to be very rare loot, or the mod is imbalanced by relying on that loot being found only in igloos. Try opening up an issue in the [TaN repo](https://github.com/Glitchfiend/ToughAsNails/issues) and see what they say.
