### ISSUE TITLE
Add biome signature to volcanoes

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1100]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=4135

@Zeno410 Not sure how possible/desirable this would be, but maybe we could add a config option similar to the ones we have for the scenic lakes? So by default, the volcanoes would inherit the biome signature of the biome they generate in, but if the user enters the biome ID of BOP's Volcanic Island, for example, then the volcano would use that for its biome signature.

**Comment by srs-bsns** [comment]
This would only be possible by adding a custom biome, and there's no way to do that without a client-side component.

Perhaps, in the future, volcanos can be moved to an add-on where adding a biome for them is more appropriate (and most desireable).
