### ISSUE TITLE
Crash while exploring ice plains

### ISSUE THREAD

**Issue by CcytherR** [Team-RTG/Realistic-Terrain-Generation#1101]
http://pastebin.com/LUcQMzfh

**Comment by whichonespink44** [comment]
I noticed the ChunkGen mod in your crash report... did this crash happen in-game or whilst you were pre-genning the world?

Either way, there's not that much RTG can do about ConcurrentModificationException crashes. Are you able to log back in and continue playing? Or does it crash every time you try to log back in?

**Comment by whichonespink44** [comment]
Also... just out of curiosity... what biome are you using for your Lonely Biome? :)

**Comment by CcytherR** [comment]
ice plains :) its in the title lol sorry i didnt think of checking back till now, i just got the same error again for a different biome so its not biome exclusive this time it was caves biome as lonely biome from enviromine mod, just playing around testing lonely biome with every biome, after this crash it lets me log back in after  it seems similar to another crash that occurs when theres a fault with the way a structure is generated but after the initial crash its playable as normal after that but i forgot the name for it, its one that fires a lot when pregenerating large amounts of terrain

**Comment by srs-bsns** [comment]
Apart from adding 3fe6f962e37baacce831bc63a0cac578c5b05d8e in the previous release, there isn't much more we can do to prevent CMEs like this in 1.7.10 as it is a crash with how Minecraft works. CMEs like this don't appear to happen in new versions of Minecraft.
