### ISSUE TITLE
New Kind of Mega Lag

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#1102]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: forge-1.10.2-12.18.3.2185
- RTG version: RTG-1.10.2-4.1.2.1

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
I'm building a new 1.10.2 server game for our small group of games, and I thought I'd encountered every type of lag or game slowdown there was, but when I upgraded RTG to version 4.1.2.1, I found an entirely new one, so congratulations on that :)

The lag is kind of like the entire CPU is being used up, and nothing can happen.  But the CPU is fine, the fps is fine, the memory usage is fine.  Now, this does not happen with just RTG installed, but as soon as I add Biome o Plenty (version BiomesOPlenty-1.10.2-5.0.0.2109-universal) and Biome Tweaker (version BiomeTweaker-1.10.2-2.1.230) the "lag" happens.  When I replace RTG with version 4.1.2.0, the "lag" is no longer there.

This would not be a problem usually, as I would just use 4.1.2.0 instead, but we were hoping to also use Ars Magica 2 in this build.

[fml-client-latest.zip](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/687016/fml-client-latest.zip)

Let me know if you need any further info.

Easy test:  make new world, fly to where the world is not loading, fly up to a tree, spawn a skeleton from a spawn egg - it won't fall for a LONG time.

**Comment by srs-bsns** [comment]
We are aware of this and are currently investigating the issue.

**Comment by Zygus42** [comment]
NM - turns out that when you follow instructions and delete the RTG folder first, it fixes this issue pretty much completely.  Is still maybe a tad slower, but not much.

**Comment by srs-bsns** [comment]
No, there is an issue, but it is itermittant. This will likely be resolved for our next release.

**Comment by Zygus42** [comment]
Don't know if this helps at all, but it doesn't happen if you delete the config folder and start up a new world, but if you then run it again with the new config folder (no changes), it happens again when you start up a new world.

**Comment by srs-bsns** [comment]
@Zygus42 Deleting the config won't have any effect. When RTG starts it uses the default config values, and if the config files don't exist, then it creates them with the same dafault values.

You aren't seeing the issue all the time because it is itermittant, and since it only happens when generating new chunks, you won't see it immediately in a new world until you leave the spawn area, and even then it will only happen in limited circumstances depending on what biomes are present in the area.

**Comment by Zygus42** [comment]
Wish I could show you on my computer, because i'm a computer programmer and so I know what you're saying, but I'm adhering to a pretty strict testing regime for this build and my results are NOT intermittent, they're consistent and re-creatable.  I'm re-creating the same world over and over again each time, and when I start it without a folder, and move away from the spawn spot (always moving in the same direction), I get to the edge of the starting area and it's black and un-generated, but then it generates, slowly but surely.  When I do exactly the same thing after a restart with the config folder in place, I get to the edge of blackness and nothing happens - the blackness just sits there and stares back at me - after a few minutes it generates some of it, but then when I move to the new blackness, same thing.  Now, to my mind that would indicate that when the config folder exists, the mod is doing something to the folder that then means it no longer works, but hey, it's your code :)  Let me know if you need any info and good luck with bug busting.

**Comment by whichonespink44** [comment]
@Zygus42 Can you try this snapshot and see if you still experience the same issue? https://drive.google.com/open?id=0B7tFzVqlzYLPZFVjYWd1eUNwX00

I loaded up the seed from your log file, using that version of RTG + BOP and spawned in a Jungle biome. Tried flying around waiting for the blackness to appear, but everything seemed alright, so hopefully our latest changes will have fixed it.

Let us know if not.

**Comment by Zygus42** [comment]
Lovely.  Works like a charm !  Well done !

**Comment by Zygus42** [comment]
_Sorry to add to this, with a semi-related issue.  The version above (v4.1.2.2-snapshot-1) works, but the version you put on CurseForge (v4.1.2.2) no longer works with the Stream mod.  Getting the following:
[Uploading crash-2017-01-11_12.43.50-client.txt…]()

Not sure if you want me to report this to the Streams dev instead......_

NM NM NM - turned out to be a completely unrelated issue where i was using a 1.11 file in my 1.10 build :(  Sorry, and ignore this entirely !

**Comment by srs-bsns** [comment]
@Zygus42 The link you provided doesn't link to anything (so by default GitHub linked it to this issue instead of the file).
Please open up another issue for this though.

**Comment by whichonespink44** [comment]
Fixed in c1f2b6f
