### ISSUE TITLE
Something else than RTG 2 [Name Suggestion]

### ISSUE THREAD

**Issue by Quizer9O8** [Team-RTG/Realistic-Terrain-Generation#1107]
Since RTG 2 is in the making it might be a good idea to rethink the name choice.
The name RTG 2 sounds so simple and dull since the number 2 gets used often by rewrites or sequels which make number 2 less special IMO (in my opinion). It wouldn't be a bad idea to call RTG 2 something else other than only a 2 added.
text inside in parentheses: (hello world) won't be included.
Here are some name suggestions I came up with.

-RTG (Realistic Terrain Generation) Reimagined
-RTG Volume 2
-RTG Global Shift
-RTG Revolution
-RTG Evolution
-RTG (No name change at all)
-RTG 2 (not so special but can do)

If you have any suggestions of your own feel free to comment down below.

**Comment by srs-bsns** [comment]
A rewrite of RTG is currently *not* in the making.

If you are refering to the RTG2-* branches in this repo, they haven't been touched in months. The name of those branches is just a working name to differentiate them.

It's not likely that the name will change, and if it does, it will likely be shortened, not lengthened.

**Comment by Ezoteric** [comment]
RTG FH where FH stands for Fuck Hope as mc code will be garbage for ever....
