### ISSUE TITLE
RTG generation on world AFTER creation?

### ISSUE THREAD

**Issue by hagfelsh** [Team-RTG/Realistic-Terrain-Generation#1113]
Not a bug--just a design operation question: 

Will RTG generate chunks as needed in a world that was initially created without the mod?  I didn't find this wonderful thing until after we had been building for several weeks.  There's no way they'll allow a wipe and restart at this point.

I set level-type to RTG and teleported to random places to see if I could notice a difference, but nothing appears to be generating any differently.  It's worth noting that I'm suing biomes oplenty and I've added ClimateControl, too.  That seems to be called GeographicCraft, now, according to the file name of the download that's linked in RTG's readme.

**Comment by whichonespink44** [comment]
~~If you set level-type=RTG, then it should be generating realistic terrain in new chunks.~~ See message below.

The places that you teleported to... are you *sure* they were new chunks?

**Comment by srs-bsns** [comment]
>If you set level-type=RTG, then it should be generating realistic terrain in new chunks.

Negative. The `level.dat` file in the world save directory will need to be NBT-edited to change the name of the generator to `RTG`.
If you do this in an existing world, you are going to have chunk walls between existing chunks and new chunks.

@hagfelsh In the future, please try to limit questions to our [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes), or our [Discord server](https://discord.gg/0wIG7mz3g6Qynq4E). This issue tracker is for bugs.

**Comment by hagfelsh** [comment]
@srs-bsns Sorry about the abuse!  I should have looked again for the forum; you're so active here that I didn't pause to think about it!  Thanks for answering my question, too :)
