### ISSUE TITLE
BoP biomes not recognized in 1.11

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#1115]
RTG-1.11, BoP 2128, and GC 0.8.5

RTG is not recognizing the BoP biomes. They are there: GC finds them and BoP generates its own worldtype just fine, but RTG puts this in the log files:

[14:25:37] [Client thread/WARN] [FML/rtg]: [RTG-WARN] WARNING! RTG could not find a realistic version of Alps (41) from biomesoplenty.common.biome.overworld.BiomeGenAlps. (If Alps is a non-Overworld biome, then this is not an error.)

##### Steps to reproduce the issue: (If it's easily reproducible.)

Run BoP, GC, and RTG together under 1.11 with patch biome set to -1.

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/e5b80427b32400853f7728e318a3c06405bae9be/src/main/java/rtg/world/biome/realistic/biomesoplenty/RealisticBiomeBOPBase.java#L93

I win again.

**Comment by whichonespink44** [comment]
Forgot to lowercase BOP's mod ID in RBBOPBase.addBiomes() ... this will get fixed in #1114

**Comment by whichonespink44** [comment]
> I win again.

I *knew* you wouldn't be able to resist the temptation ;)
