### ISSUE TITLE
Biome Support for Rockhounding: Surface Mod 1.10.2

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1121]
##### Affected Mod Versions:
Forge 1.10.2
[Rockhounding: Surface v1.07](https://minecraft.curseforge.com/projects/rockhounding-mod-surface/files/2373420)

##### Issue Description:
This mod recently added the White Sands Beach.

**Comment by whichonespink44** [comment]
Added in 93e07d2

**Comment by WenXin20** [comment]
The mod had a update recently, version 1.08, where the White Sands Beach was disabled by default in the config and the White Sands Biome was added instead.
