### ISSUE TITLE
Crash w/ Simple Dimensions & Terrain Control

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1123]
##### Affected Mod Versions:

- Forge version: 1.10.2-v2221
- RTG version: v4.1.2.2
- [ Simple Dimensions v1.3](https://minecraft.curseforge.com/projects/simple-dimensions)
- Terrain Control using the [Biome Bundle v4.1](https://minecraft.curseforge.com/projects/biome-bundle) Configurations _(Installation instructions are on the website)_

##### Issue Description:
I get a crash when I create a dimension using the simple dimensions mod and choosing Realistic Terrain Gen while in a Terrain Control World.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Download the mods, and unzip the biome bundle folder.
2. Create a world named **world** and use the terrain control world gen option.
3. Use **/simpledimensions create** once the world loads.
4. Choose the realistic terrain gen option with the dimension creator screen, and click create
5. And finally, teleport to the dimension using **/tpd 30000**, or whatever it says the dimension id is.
6. The game then crashes once it loads.

##### Extra Information:
- [Crash Log](http://pastebin.com/yDAJm9Q5)
- [Client Log](https://gist.github.com/WenXin20/8bdc5baacad6f1332b3dcf3c892a1255)

**Comment by srs-bsns** [comment]
Please see our [Minecraft Forum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes) for mod compatibility lists.

```
Unfortunately, however, RTG is not compatible with the following mods:
 - Wildycraft - crashes on startup
 - TerraFirmaCraft - deviates too far from standard biome generation
 - Terrain Control / Biome Bundle - Incompatible terrain generators
```

RTG will also not work outside of Dimension 0.

**Comment by WenXin20** [comment]
Ok, thanks
