### ISSUE TITLE
[Request] Allow RTG creation for custom dimensions

### ISSUE THREAD

**Issue by AlexiyOrlov** [Team-RTG/Realistic-Terrain-Generation#1128]
- Forge version: 1.10.2-12.18.3.2185
- RTG version: 4.1.2.2

##### Issue Description:
I have a dimension creation system in my mod, and when I tried to create a dimension with RTG world type, it crashed. So I looked at your code and saw that you are allowing RTG to work only in dimension 0, otherwise it throws exceptions.

##### Steps to reproduce the issue:

1. Make a dimension with id other than 0.
2. Attempt to create it with RTG world type.

I would be grateful if you allowed RTG worlds to be created in other dimensions.

**Comment by srs-bsns** [comment]
@AlexiyOrlov This is already on our [TODO list](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1116) for 1.11, but due to the possible complexity of removing the dimension restriction, and of it possibly being a breaking change, it's something that may not get backported to 1.10.

**Comment by whichonespink44** [comment]
Added for 1.10.2 in ee80ee5

**Comment by srs-bsns** [comment]
fixed in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/bb9f7737687b5f6bc455ad67dcfe9fa72f1cf604
