### ISSUE TITLE
River frequency multiplier description states river width instead

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1132]
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.11.2-dev/src/main/java/rtg/api/config/RTGConfig.java#L895

**Comment by whichonespink44** [comment]
Fixed for 1.7.10 in 5bba123

**Comment by whichonespink44** [comment]
Fixed for 1.8.9 in 4197527
Fixed for 1.10.2 in fa69977

**Comment by srs-bsns** [comment]
This will be irrelevant with the generator options.
