### ISSUE TITLE
Ocean monuments not generating in BiomeTweak'd RTG worlds

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1133]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=4199

**Comment by srs-bsns** [comment]
RTG + BiomeTweaker
Seed: -6114793308047248760
BT Script:
```
keep = forBiomes(0, 24)
keep.addToGeneration("ICY", 1)
keep.addToGeneration("COOL", 1)
keep.addToGeneration("WARM", 1)
keep.addToGeneration("DESERT", 1)
keep.set("genWeight", 100)
keep.set("isSpawnBiome", true)
remove = forAllBiomesExcept(keep)
remove.remove()
Tweaker.setAverageBiomeSize(4)
```

![2017-02-04_05 42 01](https://cloud.githubusercontent.com/assets/8453133/22617858/cb9ecb6e-ea9c-11e6-8098-0de2d7fb1389.png)

**Comment by whichonespink44** [comment]
Confirmed ocean monuments generating in all MC versions with BiomeTweaker + BOP.
