### ISSUE TITLE
[1.10.2] Spruce Trees Spawn w/ Oak Stumps

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1135]
##### Affected Mod Versions:

- Forge version: 1.10.2-2221
- RTG version: 4.1.2.2

##### Issue Description:
Some Spruce trees are generating with oak log stumps.
![2017-02-09_14 46 22](https://cloud.githubusercontent.com/assets/12000593/22802588/f1e9fdc8-eed6-11e6-86ff-5950d952b4d0.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Create a world.
2. Find spruce trees that also comes with side stumps

**Comment by srs-bsns** [comment]
>252 mods loaded :frowning_face: 

@WenXin20 Can you reproduce this with only RTG loaded, please? This has never been observed anywhere.

**Comment by WenXin20** [comment]
No, it looks like another mod is involved.
I started a different custom pack that has about 90 mods and got that glitch again. I'll try to figure out which mod(s) is involved.

**Comment by WenXin20** [comment]
Nevermind, it was just a visual glitch with the resource pack I was using, for some reason it had the bark logs all set as oak. So no bug with any mods. :)
