### ISSUE TITLE
Railcraft Mines not spawning in RTG worlds

### ISSUE THREAD

**Issue by TitusArmillius** [Team-RTG/Realistic-Terrain-Generation#1137]
I have disabled all ore gen, both in the RTG and with other mods (WTF's expedition, etc.). Railcraft ores like sulfur and basalt do spawn, but not the mines.

Railcraft blog example pic: [http://www.railcraft.info/wp-content/uploads/2016/10/skygen_screenshot.png](url)

Game log:[https://gist.githubusercontent.com/TitusArmillius/b455ee64dfdcea7af426aeea89de69bd/raw/09fd1c597332cb3140e0518c1999976ff5c8b991/log](log)

In-game screenshot: http://i.imgur.com/TGLtRBL.jpg

**Comment by srs-bsns** [comment]
https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/worldgen/GeneratorMine.java#L41

Sky generation of mines seems to currently be in a permanently disabled state.
