### ISSUE TITLE
Hard Dependency on Rockhounding-Surface Mod

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1139]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 2221
- RTG version: 4.1.2.3
- Rockhounding-Surface version: 1.07

##### Issue Description:
The newest version of RTG requires Rockhounding-Surface v1.07 when it shouldn't. I also have Rockhounding installed, but it isn't being detected.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Install Rockhounding-Surface w/ RTG v4.1.2.3
2. Luanch game
3. Get missing mods screen that says the rockhounding mod is missing.

**Comment by srs-bsns** [comment]
Another mod that is using a very non-standard version string. \*sigh*

The fix should be released once @whichonespink44 is around.

**Comment by WenXin20** [comment]
Thanks
