### ISSUE TITLE
Sunflowers generate in mossy cobblestone

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1141]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:

1.10.2 - 12.18.3.2234

- RTG version:

4.1.2.4

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

https://www.dropbox.com/s/zhla08vswdwh9fe/Screenshot%202017-02-22%2008.32.28.png?dl=0

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Find the right biome
2. ???
3. https://www.dropbox.com/s/zhla08vswdwh9fe/Screenshot%202017-02-22%2008.32.28.png?dl=0

**Comment by whichonespink44** [comment]
Fixed in e213120
