### ISSUE TITLE
Adventures of A'ishah on wiki incomplete

### ISSUE THREAD

**Issue by zubzubby** [Team-RTG/Realistic-Terrain-Generation#1142]
Hi,

I think the Adventures of A'ishah tutorial on your wiki is incomplete. I went through the steps carefully and with the exact same mod versions and the worlds generated were completely different to the screnshots provided. Also, to get to the link that is described in "Part 2 - General Config Changes" you need to go back to a previous revision where the link is still on the page.

It's a shame as I would love to see how this turned out. Perhaps complete it or take it off until it is so other people don't go through all the steps like myself

**Comment by TitusArmillius** [comment]
I've pm'd you zub, we'll talk there.
