### ISSUE TITLE
1.10.2-Floricraft Biome Compatibility

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1143]
The recent update for **[Floricraft](https://minecraft.curseforge.com/projects/floricraft/files/2385058)** in 1.10.2 adds the Flower Lands Biome, that has lots of flowers and generates path blocks.

**Comment by whichonespink44** [comment]
Added in 1a152c0

@Shadows-of-Fire Plants integration? ;)

**Comment by Shadows-of-Fire** [comment]
Sounds like it'll get the same treatment the flower forest does... this'll be fun.
