### ISSUE TITLE
Biome config for rivers

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1144]
Currently, rivers are hardcoded to be disallowed in some biomes, so this would just be converting that into a biome config. (We would use the current hardcoded values for the defaults.)

**Comment by whichonespink44** [comment]
Added for 1.10.2 in 9a8886a

**Comment by srs-bsns** [comment]
Issue no longer relevant. Moved to generator settings in 1.12.
