### ISSUE TITLE
Crashing When Generating World

### ISSUE THREAD

**Issue by CrazyGamerT** [Team-RTG/Realistic-Terrain-Generation#1145]
##### Affected Mod Versions:

- Forge version: 10.13.4.1558
- RTG version: 1.1.1.4
- Using Java 8 Update 111 (64-bit)

##### Issue Description:

After the world finished generating and it started to load my player in, it immediately went to the Shutting Down Server Screen.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Install Forge 10.13.4.1558
2. Install RTG version 1.1.1.4
3. Generate a Minecraft world in Realistic World type

##### Extra Information:
http://pastebin.com/Aqpcnnta

**Comment by srs-bsns** [comment]
This has nothing to do with RTG, it is with client-side rendering.

Also, you are not using Java `1.8.0_111`, you are using `1.8.0_25` that ships with Minecraft.
