### ISSUE TITLE
Not sure if this is RTG's fault or AM2's fault so I'll post it here

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1146]
https://www.dropbox.com/s/z309ccbgczm3d63/Screenshot%202017-02-27%2014.46.52.png?dl=0

This occurs when you enter a witchwood forest. I am on RTG-1.10.2-4.1.2.4, and forge version 2234.

**Comment by srs-bsns** [comment]
This should have already been fixed in AM2. Be sure that you are using the latest version of it.

If you are still having issues, report it to @Growlith1223: https://github.com/Growlith1223/ArsMagica2/issues

**Comment by Growlith1223** [comment]
yea this was fixed
