### ISSUE TITLE
pfaa geologica boulders from rtg

### ISSUE THREAD

**Issue by 31trainman** [Team-RTG/Realistic-Terrain-Generation#1147]
Could rtg generate boulders from the various pfaa mod rock types?

**Comment by Zeno410** [comment]
We would need some sort of API function from pfaa which would return a cobblestone type from a BlockPos. Also OK if we can get a stone type we can get a cobblestone version from.

**Comment by whichonespink44** [comment]
Without an API or an IMC implementation, this isn't going to be possible.

I'm closing this for now, but if @lawremi ever adds an API for this sort of thing, we'll be happy to re-open and add support for Geologica boulders.

**Comment by lawremi** [comment]
Maybe you could just look in the ore dictionary for blocks registered under "stone" or "cobblestone" and pick one to generate a boulder? That would work across many mods. May want a configurable blacklist for the weird cases.
