### ISSUE TITLE
Question or feature request . . . Adding mix blocks to biomes that don't normally have them

### ISSUE THREAD

**Issue by Winddbourne** [Team-RTG/Realistic-Terrain-Generation#1148]
I'm working on an experimental 1.10.2 mod pack using RTG file "rtg-1.10.2-4.1.2.4" and I'm looking at a lot of work altering biomes. 

Going through the files I find that not every biome file has the same options listed. Particularly I'd like to add mix blocks to more biomes both for more variety, and to give the world a specific feel/flavor. I'd like to know if it is possible to copy the section of code from somewhere like "birchforesthills" to a file like "desert" that doesn't have a mix block listing and have it work? 

If not could this be added as an option? If so perhaps this could be listed in the wiki under "configuration" so people will know exactly how to do it properly. 

Thanks for reading this. :)

**Comment by whichonespink44** [comment]
@Winddbourne Unfortunately you can't copy & paste biome config options from one biome to another. If the biome hasn't been configured to have mix blocks, then it won't generate a mixed-block surface.

I was contemplating adding mix blocks to all biomes, but after looking at it in more detail, it's a lot more work than I thought it would be, so this isn't going to be a thing after all.

If there are any specific biomes that you want us to add mix blocks for, we might be able to add them, so just let us know.
