### ISSUE TITLE
[suggest] Procedurally generated paths

### ISSUE THREAD

**Issue by leagris** [Team-RTG/Realistic-Terrain-Generation#1149]
##### Issue Description:
Add natural paths generation by RTG

##### Steps to produce paths

1. Use Perlin Noise Terrain Elevation and, or, Biome Distribution data for path frequency and width to determine if `x,z` has a path run at `y=surface`
2. Perform path rendering from [blocks substitution rules](#path-blocks-substitution-rules).

##### Path blocks substitution Rules

<table width="100%">
  <thead>
    <tr valign="bottom">
     <th>Condition</th>
     <th>Surface Replacement Rule</th>
    </tr>
  </thead>
  <tbody>
    <tr valign="top">
      <td><pre lang="java">block(y+1)=="air" && (
  block(y)=="grass" ||
  block(y)=="potzol" ||
  block(y)=="mycellium" )</pre></td>
      <td><pre lang="java">block(y)="grass path";
block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">block(y+1)=="air" &&
block(y-2)!="water" &&
block(y-2)!="flowing water" && (
  block(y)=="water" || block(y)=="flowing water" )</pre></td>
      <td><i>Draw a ford across shallow water</i> <pre lang="java">for( px=x-1; px==x+1; px+=1 ) {
  for( pz=z-1; pz==z+1; pz+=1 ) {
    if( block(px,y,pz)=="water") {
      block(px,y,pz)="flowing water";
    }
  }
}
block(y-1)="cobblestone";
if( Random.nextFloat()<.25f ) {
  block(y)="mossy cobblestone";
  block(y+1)="air";
}</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="stone" )</pre></td>
      <td><pre lang="java">block(y)="cobblestone";
      block(y+1)="air";</pre></td>
    </tr>
    <tr>
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="cobblestone" )</pre></td>
      <td><pre lang="java">block(y)="gravel";
      block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="gravel" )</pre></td>
      <td><pre lang="java">block(y)="dirt";
      block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="dirt" )</pre></td>
      <td><pre lang="java">block(y)="dry dirt";
      block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="sand" )</pre></td>
      <td><pre lang="java">block(y)="sandstone";
      block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="sandstone" )</pre></td>
      <td><pre lang="java">block(y)="hardened clay";
      block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="snow block" )</pre></td>
      <td><pre lang="java">block(y)="ice";
      block(y+1)="air";</pre></td>
    </tr>
    <tr valign="top">
      <td><pre lang="java">( block(y+1)=="air" || block(y+1)=="snow" ) && (
  block(y)=="snow block" )</pre></td>
      <td><pre lang="java">block(y)="ice";
      block(y+1)="air";</pre></td>
    </tr>
    <tr><td align="middle" colspan="2">…</td></tr>
  </tbody>
</table>

**Comment by whichonespink44** [comment]
I think this is probably a little outside RTG's scope.
