### ISSUE TITLE
[Feature Request]Realistic mountain chains

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Team-RTG/Realistic-Terrain-Generation#1150]
In the RTG world the mountain seems to be produced separately.
If you RTG generate a real mountain chains, I think it will be more realistic.

**Comment by mgdgfbhevdyeh** [comment]
![lxwi14x](https://cloud.githubusercontent.com/assets/20567492/24450005/c3b82196-14ab-11e7-9a03-05d0b8d81e02.jpg)
![4vidmqv](https://cloud.githubusercontent.com/assets/20567492/24450004/c3a4def6-14ab-11e7-87d9-b473317a3c45.jpg)
Best looks like this
I think RWG mountain chains is better than RTG mountain

**Comment by srs-bsns** [comment]
I don't see how this is possible from RTG.

In order to have mountain chains, it would require that the world have a very large mountainous biome, or multiple mountainous biomes grouped together. This would require biome manipulation, which RTG does not do.

This is why @Zeno410 does this sort of thing in GeographiCraft, since it handles biome layouts.

**Comment by mgdgfbhevdyeh** [comment]
OK I know.

**Comment by mgdgfbhevdyeh** [comment]
well,but i think:
RTG should have the mountain chains, because it is the Realistic-Terrain-Generation
In Realistic Terrain, there are mountain chains in many places(And has a great impact on the climate in many areas)
Such as South America and Asia-Europe continental line


If you need Mod to generate mountains, I think it should be called Beautiful Terrain generation
Do not need Mod to generate mountain chains, this should be Realistic Terrain Gen

**Comment by srs-bsns** [comment]
I understand what you are saying, but as I stated, such land features in Minecraft are specific to certain biomes, and therefore in can only be done if RTG handled biome layouts, which is does not. Although biome managment is something we may add to RTG in the future, it's not a priority, and would require a considerable amount of new code.

**Comment by mgdgfbhevdyeh** [comment]
OK I know
