### ISSUE TITLE
flowing liquids config option not working

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#1151]
##### Affected Mod Versions:
- Forge version: 1.10.2-12.18.3.2254
- RTG version: RTG-1.10.2-4.1.2.4
no other mods

##### Issue Description:
I thought that this wasn't happening very often, so I set the lava and water generation chances to 1 from their usual 200, and in extensive testing with no other mods installed, I encountered 1 lava flow, and that included 3 extreme hills biomes.

##### Steps to reproduce the issue: (If it's easily reproducible.)
1. set chances to 1
2. make world
3. fly around

**Comment by whichonespink44** [comment]
I set the water & lava chances to 1, and after flying around for 3 minutes in the first Extreme Hills biome I found, I saw these:

![2017-05-19_11 56 21](https://cloud.githubusercontent.com/assets/10927161/26245152/be4bc184-3c8a-11e7-81d2-5ca49c25d819.png)
![2017-05-19_11 58 12](https://cloud.githubusercontent.com/assets/10927161/26245157/c274c396-3c8a-11e7-80f5-0b3f6bdd1e48.png)
![2017-05-19_11 58 42](https://cloud.githubusercontent.com/assets/10927161/26245162/c727d252-3c8a-11e7-9cf5-90280525b850.png)
![2017-05-19_11 59 35](https://cloud.githubusercontent.com/assets/10927161/26245171/cd0614ea-3c8a-11e7-9e33-ec1c1c11c06c.png)
![2017-05-19_11 59 50](https://cloud.githubusercontent.com/assets/10927161/26245176/d1ac4ae6-3c8a-11e7-80f4-10444a80a391.png)

If it was broken before, it's fixed now :)
