### ISSUE TITLE
Imcompatible with Advent of Ascension dimensions

### ISSUE THREAD

**Issue by jahtim** [Team-RTG/Realistic-Terrain-Generation#1155]
forge 1614 , mc 1.7.10

mods : AoA , RTG, CC, BOP, Galacticraft

I entered a lot of Advent of Ascension dimensions and find that the biome in those dimensions are equal to overworld. No AOA biomes generated in those dimensions, expect for a few dimension where generating is quite normal.
I set CCDimension white list to 0, and this still happen.
Any idea what's going on ?

**Comment by jahtim** [comment]
Reference ClimateControl #13

**Comment by srs-bsns** [comment]
RTG doesn't work outside of the Overworld (Dim 0).
