### ISSUE TITLE
Consider relicensing under LGPL

### ISSUE THREAD

**Issue by XDjackieXD** [Team-RTG/Realistic-Terrain-Generation#1156]
Using a mod licensed under GPL requires violating its terms as it requires every linked code to be licensed under a GPL compatible license as well. FML links mods into Minecraft when loading them, thus violating the terms of the GPL license.
Please consider relicensing under the LGPL or another non-viral license.

**Comment by srs-bsns** [comment]
There is no licencing issue with using GPL.
