### ISSUE TITLE
Wider calderas for volcanoes and moar lava!!!

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1157]
Maybe even a lava tube that runs to deep into the ground?

**Comment by Cronosus** [comment]
to bedrock....

**Comment by whichonespink44** [comment]
> to bedrock....

Could maybe even add a config option for the depth of the tube.

**Comment by Cronosus** [comment]
yes yes.. good option.. 
but for me it will be alwas bedrock, i using vulcanoes for building deep structures :)

**Comment by srs-bsns** [comment]
It would probably be better to add this to the 1.11.2 TODO list instead, and backport later if necessary..

**Comment by Cronosus** [comment]
hmm.. i still using 1.7.10

**Comment by srs-bsns** [comment]
We are only developing for 1.10/1.11 now. 1.7.10 is retired and no new features will be backported before 1.10.

**Comment by whichonespink44** [comment]
Added for 1.10.2 in 33a56e9 and 02c113a

**Comment by ghost** [comment]
mc-1.11.2 label? you are working on 1.11.2? we're waiting for it eagerly :)
