### ISSUE TITLE
Wiki Link Broken

### ISSUE THREAD

**Issue by pdewilde** [Team-RTG/Realistic-Terrain-Generation#1160]
##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
The [link to rtg.cfg](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/etc/config/RTG/rtg.cfg) is broken : [on this page](https://github.com/Team-RTG/Realistic-Terrain-Generation/wiki/RTG-configuration)

**Comment by srs-bsns** [comment]
There are a lot of broken links in the Wiki as a lot of it hasn't been updated in quite a while. Fixing it is on the TODO list.

The links you are refering to are now fixed.
