### ISSUE TITLE
Add support for 10paks Mods

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1161]
http://10paksmods.net/

A few new biomes are added, would it be possible to add support for them?

**Comment by srs-bsns** [comment]
There's no point in doing this now as Real World is only released for 1.11.2 and we don't have a release of RTG for 1.11.2 yet.

**Comment by StoneLegion** [comment]
That is a negative thinking! Make it 1.11.2 then you don't have to think that way ;)

**Comment by whichonespink44** [comment]
Added in https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.12.2-real-world-support

Will merge branch when generator settings are finished.

**Comment by srs-bsns** [comment]
None of these changes touch generator settings. Just merge it now.

**Comment by whichonespink44** [comment]
Added in 83a54ba
