### ISSUE TITLE
compatibility issues with Advent of Ascension 

### ISSUE THREAD

**Issue by Ebola131** [Team-RTG/Realistic-Terrain-Generation#1162]
##### Affected Mod Versions:
- BiomesOPlenty-1.7.10-2.1.0.1595-universal
- ClimateControl-0.8.2
- AoA-Snapshot 2 (2.5) 

- Forge version: 1.7.10-10.13.4.1614-1.7
- RTG version: RTG-1.7.10-1.1.1.4

##### Issue Description:
I have set up my world with the mod configuration as mentioned above and what is troubling me is the compatibility between RTG, ClimateControl and AoA. Advent of Ascension adds several extra dimensions and when i travel to one of those, they don't always generate the way they should. Some of them generate correctly, but the game sees the default overworld biomes and I end up with wrong mobs spawning, other dimensions get completely messed up, with overworld biomes generating and some work perfectly. I am aware that RTG only makes changes to the overworld, but when I run the game without RTG and ClimateChange everything works fine. The BiomeIDs and DimensionIDs seem to be alright. In ClimateControl and RTG config folders I don't see any AoA config files generated. I am also aware that RTG does not support AoA, but as I have read usually there is no such problem. I was thinking about swapping ClimateControl for BIomeTweaker, but I don't really feel like spending too much time configuring to make the mods work together. That's why i downloaded CC.

Not sure if this will be of any help, but in case you still might think there is something wrong with the IDs: [biome.xlsx](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/948314/biome.xlsx)

**Comment by srs-bsns** [comment]
RTG doesn't do anything with dimensions or biome layouts. Anything happening outside of the Overworld (Dim 0) can never be attributed to RTG.

Furthermore, RTG is no longer being developed for 1.7.10.

Try opening an issue [here](https://github.com/Zeno410/Geographicraft/issues) to bring this to @Zeno410's attention so he can look into it.
