### ISSUE TITLE
[Request] Config options for BoP

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#1167]
Is it possible to set, by menu or file, the decoration options for BoP? When using the BoP generator, I kill off poison lakes, quicksand, and poison ivy.

**Comment by srs-bsns** [comment]
In the future, please direct questions to our [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes) or on our [Discord channel](https://discord.gg/0wIG7mz3g6TpkBsB). This issue tracker is for issues only.

To answer your question, it's BoP that is in control of it's own biome decorations. There is no way to control them through RTG.
