### ISSUE TITLE
Possible issue with ender eyes and maybe this particular map generation on the latest version

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1175]
I'm sorry if I'm vague, but this is only because I know issues can emerge like this with alternate map generation.

Users on my server are complaining that ender eyes do not work. Granted, I generated the original world on a private server on my machine, but it is bound by the RTG world type, thus, this issue could be connected.

I'll go ahead and test the server myself, to see if I can replicate what these players are finding. If it is also related, the server is using Sponge.

Edit: Confirmed the issue happens, as these players have been rather vague about issues in the past. This is really the only mod that I think could maybe cause this issue. Since modlister is a thing, I will dump the list of mods I have installed, just in case I missed something: http://www.modlister.com/user/Sunconure11

**Comment by whichonespink44** [comment]
I haven't been able to reproduce this.

Eyes of Ender are pointing to strongholds when thrown, and I've successfully followed them to confirm.

The Ender Compass mod is also working correctly, so I think we can rule out RTG here.

Looking at your mod list, nothing's really sounding any alarm bells, so maybe it is related to Sponge somehow?

**Comment by whichonespink44** [comment]
@Sunconure11 If this does end up involving RTG in any way, please let us know.

**Comment by Sunconure11** [comment]
I'll look into it over the next few days, I need to get my sleep back on track a bit.

**Comment by Sunconure11** [comment]
It's indeed a sponge issue.

https://github.com/SpongePowered/SpongeForge/issues/1535

https://github.com/SpongePowered/SpongeForge/issues/937
