### ISSUE TITLE
Undecorated chunks when used with SpongeForge

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1177]
CC: @gabizou

I'm not sure the issue here, but since RTG doesn't exhibit this behavior in any other (known) configuration with other mods, and since in my latest test world there aren't any other loaded mods, I'm inclined to believe that this issue lies with SpongeForge. Regardless, I'm opening the issue here for discussion of a possible solution that may require code modification on both sides.

- Forge version: 1.10.2-12.18.3.2281
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2322
- RTG version: 1.10.2-4.1.2.4

![2017-05-24_15 46 22](https://cloud.githubusercontent.com/assets/8453133/26424543/934454ec-409f-11e7-9ad1-f6ded944739a.png)
![2017-05-24_15 53 56](https://cloud.githubusercontent.com/assets/8453133/26424546/95ff2914-409f-11e7-96b5-fb453ed9a9c2.png)

**Comment by whichonespink44** [comment]
I can confirm this is happening with RTG-1.10.2-4.1.2.4 using the same Sponge/Forge versions in the OP.

Seems to only be happening in Plains and Savanna biomes, which seems a bit odd:

![2017-05-24_21 57 00](https://cloud.githubusercontent.com/assets/10927161/26425433/a4c2e936-40cc-11e7-9e37-8ea5cbd6d69a.png)

![2017-05-24_21 59 29](https://cloud.githubusercontent.com/assets/10927161/26425437/a8a0b614-40cc-11e7-923b-3bd1e7fcf79b.png)

**Comment by ghost** [comment]
Reproduced with Forge 1.10.2-12.18.3.2185 and RTG 1.10.2-4.2.0.0-snapshot-1, *without* SpongeForge.

I've also noticed that it never occurs in spawn chunks, if that helps at all.

[Image](https://i.imgur.com/An8YjU6.png)

**Comment by srs-bsns** [comment]
@Quintinius, This issue is about a known problem in SpongeForge that happens with any version of RTG. The Sponge team is aware of it and it will be addressed.

The issue you are refering to is a known issue in RTG (https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1174) that was introduced recently and only affects snapshot-1. It has likely been fix in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/dad07333b398154b7ed2139272a5a9e33d69a8b8

**Comment by whichonespink44** [comment]
Just confirmed this is still an issue with 1.10.2-2281-5.2.0-BETA-2401 when using RTG 4.1.2.4 and 4.2.0.0-snapshot-2.

Really noticeable in any Plains or Savanna biome, and occasionally noticeable in Forest and Taiga biomes.

**Comment by ghost** [comment]
same problem is with 1.11.2 version of RTG and SpongeForge

**Comment by srs-bsns** [comment]
@hunter688 
There is no 1.11.2 version of RTG. We had been porting it in-dev for a short while, but then stopped to work on a new release for 1.10.2. Any build of RTG you may have for 1.11.2 is a custom build and cannot be supported. It also won't have any of the changes we've made for the next 1.10.2 release making it pointless.

Furthermore, it's irrelevant the version of RTG as this is a SpongeForge issue.

**Comment by srs-bsns** [comment]
I'm closing this now since the issue is open on the SpongeForge tracker.

**Comment by ghost** [comment]
Im compiled 1.11.2 fork... ok
