### ISSUE TITLE
[request]Re-decoration BOP Flowering Tree

### ISSUE THREAD

**Issue by 963548217** [Team-RTG/Realistic-Terrain-Generation#1178]
It seems very uncoordinated in the RTG forest.
![2017-05-26_13 12 32](https://cloud.githubusercontent.com/assets/24326794/26481755/d36ae1f4-4215-11e7-83a5-36f9dd8a892d.png)

**Comment by srs-bsns** [comment]
BoP trees are handled by the BoP generators (even in vanilla biomes). If you want to disable them you can do it through biome overrides that go in `/config/biomesoplenty/biomes/`. You will have to get help from the BoP devs on how to structure the override files.
