### ISSUE TITLE
Config option for fallen log frequency

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1179]
I've noted that on maps with smaller biomes, the amount of fallen logs a nearby forest can generate and place into say, a desert, can become way too much. Would it be possible to add a configuration option to deal with the amount of fallen logs that can be generated?

**Comment by whichonespink44** [comment]
Added for 1.10.2 in 8623564

**Comment by srs-bsns** [comment]
Not sure why this is still open as the code added in 1.10 still exists and should still work in 1.12.
