### ISSUE TITLE
RTG not generating decorations, barren chunks

### ISSUE THREAD

**Issue by jordanasch** [Team-RTG/Realistic-Terrain-Generation#1194]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.10.2.12.18.3.2281
- RTG version: 1.10.2.4.1.2.4

I do have a lot of mods and I have no idea which one could be causing the problem so I will just post them all. (I am also open to any suggestions anyone has but maybe PM me so that this thread is kept relevant to RTG)

 AutoRegLib-1.0-2
  BabyMobs-1.10.2-1.5.4
  BetterPvP_1.11.4_Forge_1.10.2
  BetterQuesting-2.3.217
  Bullseye-1.9.4-1.0.3
  CraftTweaker-1.10.2-3.0.20
  CustomNPCs_1.10.2(17mar17)
  CustomStuff3-1.10.2-0.11.7 
  Decocraft-2.3.6.1_1.10.2
  Excore-1.6.2-1.10.2
  ForeverEnoughItems-1.0.17.2-1.10.2
  FTBLib-1.10.2-3.5.3
  FTBUtilities-1.10.2-3.5.1
  gemcraft-1.10.2-1.2.5
  GraveStone Mod 1.5.12
  jei_1.10.2-3.14.7.417
  justenoughdimensions-1.10.2-1.3.6
  LevelUp!-0.12.9-1.10.2
  Light-Level-Overlay-Reloaded-Mod-1.10.2
  mdecore-1.10.2-1.5.1
  MineTweakerRecipeMaker-1.10.2-1.2.1.20
  morematerials-1.10.2-1.9.20160723.0
  Neat 1.3-10
  netherportalfix-mc1.9.4-4.0.1
  NPCIntegration-2.3.19
  OptiFine_1.10.2_HD_U_D7
  Progression-1.10.2-0.6.9
  Quark-r1.1-70
  RecallStones-1.10.2-0.6.3
  RFExpansion-2.3.24
  roughMobs1.0.9-1.10.2
  RTG-1.10.2-4.1.2.4
  ServerPropertiesLAN-2.4
  SpartanShields-1.10.2-1.1b
  StandardExpansion-2.3.124
  Surge-1.10.2-1.1.0.70
  tellme-1.10.2-0.5.3
  The Beneath-1.10.2-1.2.0
  ToughAsNails-1.9.4-1.1.1
  TreeChopper-1.10.2-1.1.1a
  worldedit-forge-mc1.10.2-6.1.4-dist
  worldutils-1.10.2-0.2.2
  WTF-Expedition_1.10.2_v1.5Beta1

##### Issue Description:
(Please provide screenshots if necessary/possible. Images can be dragged & dropped into this window.)

My problem is that when I enter my world it is not generating decorations properly. (I don't know what mod actually is causing the problem but I figured I would post it here as the issue's main side effect is only visible through your mod)

On the left side of this image you can see the effects of my issue on the right side you can see how it should normally look
http://i.imgur.com/6EDiGGE.png

I've had this problem for some time now, but I have a work around that works for my client on LAN but the reason I need to fix this now is because we have recently purchased a server and the work around no longer works.

In a single player environment, when I first open my world(This only happens with the first boot up of the world) it doesn't generate decorations properly. But if I save & quit and then without closing minecraft launch my world a second time (Or more times) it no longer has the issue of generating decorations properly.

I can't recreate this on a server, restarting the server has no effect to the issue.

Side Note.. Each time I restart my game the RAM load becomes more taxing on my computer, this may only happen if the game I just closed was Open to LAN. I don't have much information on why that happens.

Here is a log that tracks 2 world launches, one with the broken decorations, and one without. As stated before the first launch is broken and the second is working.
https://paste.ee/p/utT8W

Thanks for any help in advance!
Aschy

(Sorry if I didn't post this in the right area!)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Start Minecraft
2. Load World
3. Visit chunks that have not been generated yet

### Steps to fix

4. Save and Quit world
5. Return to world
6. Visit ungenerated chunks (As this does not fix already generated chunks)

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by whichonespink44** [comment]
Can you try to reproduce this without Optifine installed? I suspect one of its settings might be causing this issue.

**Comment by jordanasch** [comment]
Hey guys, sorry I actually had the mod developer of Just Enough Dimensions, Masa, helped me with this one as his mod was causing the problem, updating to his new version of the mod fix my problem.

**Comment by srs-bsns** [comment]
Fixed in: https://github.com/maruohon/justenoughdimensions/commit/92d06aa0195352a193054ffdaae52660e7760f52
