### ISSUE TITLE
Wheat no longer generates in plains 

### ISSUE THREAD

**Issue by PsychoLynx** [Team-RTG/Realistic-Terrain-Generation#1196]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: forge-1.10.2-12.18.3.2185-universal
- RTG version: 4.2.0.0-snapshot-2 (17.6.2017 commit)

##### Issue Description:
Can't get wheat to spawn on the plains biome any more.

##### Steps to reproduce the issue: (If it's easily reproducible.)

In plains.cfg ->

decorations {
    # If FALSE, no RTG decorations will generate in this biome. Instead, only vanilla decorations will generate.
    # RTG decorations include custom trees, shrubs, boulders, etc.
    #  [default: true]
    B:"Use RTG Decorations"=true

    wheat {
        #  [default: true]
        B:"Allow Wheat"=true

        #  [range: 0 ~ 2147483647, default: 50]
        I:"Wheat (Chance)"=200000000

        #  [range: 0 ~ 2147483647, default: 255]
        I:"Wheat (Max Y)"=255

        #  [range: 0 ~ 2147483647, default: 63]
        I:"Wheat (Min Y)"=63
    }

No wheat generates when spawning on a plains biome.

**Comment by whichonespink44** [comment]
```
I:"Wheat (Chance)"=200000000
```
The higher the chance, the MORE RARE wheat will be. Try setting it to `1` and see if it generates.

**Comment by PsychoLynx** [comment]
Mea culpa - I forgot it was the other way around :S

**Comment by whichonespink44** [comment]
To be fair, there should really be a comment that explains the difference between higher and lower values like it does elsewhere... I'll add better comments for the next release.
