### ISSUE TITLE
Recurrent Complex runs in compatibility mode

### ISSUE THREAD

**Issue by niftybottle** [Team-RTG/Realistic-Terrain-Generation#1201]
##### Affected Mod Versions:

- Forge version: 12.18.3.2316
- RTG version: 4.2.0.0 Snapshot 1, 4.2.0.0 Snapshot 2
- Recurrent Complex: 1.3.2, 1.4.1

##### Issue Description:

Recurrent Complex runs in compatibility mode when using RTG worldgen, stating: "Chunk finished generating without Forge population being triggered (dimension 0). This is a bug with the dimension - please report this to the dimension's author. Recurrent Complex will proceed to generate in compatibility mode". This limits the number and variety of structures that Recurrent Complex generates.

It's a subtle effect and kind of hard to take a picture of, but here are  a couple of structures that generate in vanilla worlds that I've never seen in RTG worlds:
![2017-06-26_00 38 05](https://user-images.githubusercontent.com/6424737/27561841-6d3929bc-5a8f-11e7-92b4-d37aa08da0ec.png)
![2017-06-26_00 41 07](https://user-images.githubusercontent.com/6424737/27561866-825d31a8-5a8f-11e7-9325-1d13e20454a6.png)

##### Steps to reproduce the issue:

1. Install most recent Realistic Terrain Gen, Recurrent Complex
2. Create a new world using Realistic world type

##### Extra Information:

[Here is the fml log](https://gist.githubusercontent.com/niftybottle/bd5dd9eaecdd491ab1de8f59ff2ee0d4/raw/87ba0056fb918e654721ba89ca4f756085a767bc/fml-server-latest-RecComplex-RTG.log)

**Comment by niftybottle** [comment]
[Here is a cleaner FML log](https://gist.githubusercontent.com/niftybottle/efe64d8d50d07acc3a8e8637de1467b8/raw/e4481263086a364f1e5da98aebf3c7f1ebdda685/fml-client-latest-cleaner.log). Sorry about that.

**Comment by whichonespink44** [comment]
@Ivorforce Could you give a little insight into what triggers this log message:

> Chunk finished generating without Forge population being triggered (dimension 0). This is a bug with the dimension - please report this to the dimension's author. Recurrent Complex will proceed to generate in compatibility mode

There are some RC structures that aren't generating in the Overworld using RTG for some reason, so just want to see if there's anything RTG can do to get them generating.

**Comment by Ivorforce** [comment]
It's rather unrelated to the spawning - If structures don't spawn it's usually that their biome dictionary entries don't match up. You can test that by editing the structure, looking at its biome spawn expressions and using /#biome to verify what biomes correspond to what types.

As for the error message - please refer to https://github.com/Ivorforce/RecurrentComplex/blob/5d980ee4cab886f97c638595fe6173affbec7ed5/src/main/java/ivorius/reccomplex/world/gen/feature/GenerationSanityChecker.java 
If anything is unclear from that don't hesitate to ask and I will modify the comments there. :)
