### ISSUE TITLE
Latest version not working in 1.11.2

### ISSUE THREAD

**Issue by arthur-hi** [Team-RTG/Realistic-Terrain-Generation#1202]
- Forge version:13.20.0.2228
- RTG version: 1.10.2-4.1.2.4

Not showing up in world types

1. make new world
2.look at world types
3.where it at do

**Comment by whichonespink44** [comment]
RTG version **1.10.2**-4.1.2.4 is for MC version **1.10.2**

There is no 1.11 version of RTG, sorry.
