### ISSUE TITLE
Infinite loading screen in modpack caused by cofhcore maybe ?

### ISSUE THREAD

**Issue by Eldwen** [Team-RTG/Realistic-Terrain-Generation#1205]
##### Affected Mod Versions:
MODLIST : 
[MODLIST.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/1118124/MODLIST.txt)

- Forge version:12.18.3.2316
- RTG version: 4.1.2.4 +older versions & all 4.2.0.0 snapshots (4rth too)
-Last versions of all the mods which appears in the  bug text file bellow (I'm on the 07/02)

##### Issue Description:
Basically, I'm playing on a modded minecraft, I'm using all the mods from te modlist above, obvioulsy i used biome tweaker withyour example Biome o plenty script.
And when i select realistic rtg gen as generation while create the map and when i click create world it work until "building terrain" appears and then it start an infinite loading. I checked in my task manager : my processor stop calculating for minecraft (0% is used by it) and the ram usage of minecraft slowly decrease. So i used the task manager to force close minecraft and I took those logs : 
[BUG.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/1118128/BUG.txt)

so the last core can be the issue ore mekanism or fast leaf decay or quark or tinker's alloying addon as they appears in this error.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.Use the modlist above with all the mods up to date or direclty use this "modpack" on twitch (ex curse app) by clicking in minecraft tab "create a profil" and "import" and selecting the following archive
[MODLIST-1.0.zip](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/1118131/MODLIST-1.0.zip)

2.Just launch the game and create a new map with rtg terrain generation and then u'll have the infinite loading screen

##### Extra Information:
GITHUB VERSION OF THE LOGS : 
https://gist.github.com/1ChaVnere/119812876783927c813fa061bfe5f227

GITHUB VERSION OF THE MODLIST : 
https://gist.github.com/1ChaVnere/5b4f075554e912220b2f9ed488bf68a5

**Comment by whichonespink44** [comment]
Any chance you could provide your fml-client-latest.log file (or fml-server-latest.log if you're on a server)?

**Comment by Eldwen** [comment]
I will just let me reproduce it

**Comment by Eldwen** [comment]
https://gist.github.com/1ChaVnere/1746045b4ea62a5622ff4522c761334b

**Comment by whichonespink44** [comment]
It's hard to tell what's going on from the crash report and log file, but it doesn't look like it's got anything to do with RTG, even though it's in the stack trace.

Unfortunately, there are too many mods for us to reproduce/diagnose this locally, so the only thing I can suggest is to try removing mods until the crash goes away. And then when you've identified the mod that's causing the crash, try reproducing it with only that mod and RTG installed.

**Comment by Eldwen** [comment]
yea i understandbut i don't have that much timer sorry i gave youthe way to install the exact same pack using the archive above with wurse app (aka twitch). I feel a bit disapointed cuz your mod is really cool but i'l  simply remove it, that's the easier way to me :/ Thank you for your help ! :)

**Comment by whichonespink44** [comment]
We suspect it might be Mekanism's salt gen that's causing the issue. Maybe try removing that mod first to see if the problem persists.

I'll close this issue for now, but feel free to let us know how you get on.
