### ISSUE TITLE
Game Crashing when generating terrain with COFH present and loaded

### ISSUE THREAD

**Issue by samiscool51** [Team-RTG/Realistic-Terrain-Generation#1207]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 12.18.3.2316
- RTG version: 1.10.2-4.2.0.0-snapshot-4
- COFH version: 1.10.2-4.1.9.13

##### Issue Description:
Whenever i load or create a chunk within a RTG enabled world with cofh enabled the game crashes
@KingLemming has been notified about this issue and i said to him that i would get your opinion about the crash log to see if something is wrong with RTG or COFH, 

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. download COFH 1.10.2-4.1.9.13
2. load up a new world (or an old one) and generate or load chunks
3. wait for the game to crash, i have noticed it sometimes doesn't crash when generating or loading new chunks making it annoying to recreate

##### Extra Information:
Crash log - https://pastebin.com/j32Xbeea
mod list - https://pastebin.com/ctXvDbDg

**Comment by ElvenChaos** [comment]
I've narrowed down the offending mods to the combination of CoFHCore 4.1.9.13, RTG (either snapshot or 4.1.2.4 -- I tested with 4.1.2.4), and Pam's HarvestCraft 1.10.2j. All three mods must be present for the crash to occur.

[Crash Log](https://pastebin.com/Y0XPccx1)

Issue has been reported to the other two repositories:
https://github.com/CoFH/Feedback/issues/340
https://github.com/MatrexsVigil/harvestcraft/issues/310

**Comment by ACGaming** [comment]
Can confirm this.

- CoFHCore 1.10.2 4.1.9.13
- RTG 1.10.2 4.1.2.4

[Crash report](https://paste.ubuntu.com/25016509)

**Comment by KingLemming** [comment]
Feel free to close this out. I've put defensive code in CoFHCore which will mitigate the underlying crash. For reference, it seems that there are certain conditions where the Post event manages to resolve before the Pre event.

So this may even be some bug with Forge and the event bus. In any case, there's no actual harm with me just putting in a null check. I apologize for my grumpiness in my own thread and for making assumptions about RTG's code.

**Comment by whichonespink44** [comment]
It's all good, glad we got to the bottom of it.

Gonna see if there's anything RTG can do to optimize its terrain generation, since you mentioned in the other issue that it seemed to happen when large mountains were generating. Maybe @Zeno410 has some thoughts on how that might be possible?

**Comment by whichonespink44** [comment]
@samiscool51 @ElvenChaos @ACGaming 

I believe this version of CoFH Core resolves this issue: https://minecraft.curseforge.com/projects/cofhcore/files/2446771

Can you guys confirm?

**Comment by afannnn** [comment]
Yes I can confirm.

**Comment by samiscool51** [comment]
yep, confirmed
