### ISSUE TITLE
[Question] Can I install this mod in Sponge?

### ISSUE THREAD

**Issue by 5igm** [Team-RTG/Realistic-Terrain-Generation#1210]
Hi! Just a question. Can I install this mod in Sponge server? And when will the version for MC1.11.2 release? I am so excited for that.

**Comment by srs-bsns** [comment]
This issue tracker is for issues only. In the future, please direct questions to our [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes) or our [Discord channel](https://discord.gg/0wIG7mz3g6TpkBsB).

Currently there is an unresolved issue (https://github.com/SpongePowered/SpongeForge/issues/1596) when using RTG with SpongeForge that causes some chunks to remain undecorated.

It is highly unlikely that we will be releasing RTG for 1.11.2; We will mostly likely be porting directly to 1.12.
