### ISSUE TITLE
Surface Lava Pools do not generate

### ISSUE THREAD

**Issue by WesCook** [Team-RTG/Realistic-Terrain-Generation#1213]
##### Affected Mod Versions:

- Forge version: 12.18.3.2316
- RTG version: 4.1.2.4

##### Issue Description:

Surface lava pools do not appear to generate regardless of their setting in the config file.

I'd read that this was a bug and they generate under the surface, but I'm not sure if this is accurate.

##### Steps to reproduce the issue:

1. In rtg.cfg, set surface lava pools to 1 (most frequent).
2. Set underground lakes to disabled to avoid confusing them.
3. Fly around.  At maximum generation rate, you would expect them to be common.  Underground pools generate *everywhere* when maxed out.

**Comment by srs-bsns** [comment]
Surface lava lakes are currently disabled (hard-coded). They may be re-enabled in the future when their generation can be improved.

**Comment by WesCook** [comment]
Sorry, I didn't see that anywhere.

**Comment by StoneLegion** [comment]
Frack! 1.7.10 user crying here. I would of accepted the current system as i need it.
