### ISSUE TITLE
Sponge in ocean caves

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1214]
![](https://cdn.discordapp.com/attachments/168326116761665536/335578191726903299/2017-07-14_15.57.50.png)

**Comment by touhouzun** [comment]
Please use potion of night vision for a better view,it's so dark for mod authors to see,however I have a different problem.
...You're using biomes o' plenty,right?

**Comment by srs-bsns** [comment]
What mod authors are you refering to?

This issue was opened by @whichonespink44, as a reminder to himself, to fix an problem with code that he wrote himself.

Biomes O' Plenty is not in use; This is RTG by itself in a dev environment.

**Comment by touhouzun** [comment]
Ah I'm sorry for that.I have a brighter screenshot but I always fail to upload it.

**Comment by srs-bsns** [comment]
There's no point in adding additional screenshots, we know where the issue is.

**Comment by srs-bsns** [comment]
In addition to this, sponges are currently too common in 1.12 and need to be scaled back substantially.

![2018-04-10_02 09 32](https://user-images.githubusercontent.com/8453133/38547717-d02c2878-3c7d-11e8-9862-b928b4d83fdb.png)

**Comment by whichonespink44** [comment]
Fixed in bf6cf8d
