### ISSUE TITLE
WorldGen Problem With Futurepack

### ISSUE THREAD

**Issue by wisabel** [Team-RTG/Realistic-Terrain-Generation#1216]
- Forge version:10.13.4.1614
- RTG version:1.7.10-1.1.1.6

##### Issue Description:
 Maybe there is no love between RTG and Futurepack

##### Steps to reproduce the issue: (If it's easily reproducible.)
Generate new terrain

##### Extra Information:
crash-report here
https://pastebin.com/K2ackhugm/

**Comment by whichonespink44** [comment]
Can you post the crash report again? The link above isn't working.

**Comment by wisabel** [comment]
sorry
https://pastebin.com/fUNHzdXa

**Comment by whichonespink44** [comment]
Thanks.

So it looks like Futurepack is calling the `loadChunk` method, which RTG's chunk generator has implemented:

```
    public Chunk loadChunk(int par1, int par2)
    {
        if (1>0) throw new RuntimeException();
        return provideChunk(par1, par2);
    }
```

But it looks like some debug code forgot to be removed... I'll have a chat with the rest of the team and see what we can do.

Thanks for bringing this to our attention.

**Comment by srs-bsns** [comment]
Fixed in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/34ca1bee1a9bf8a88091041280dde901c7106cda
