### ISSUE TITLE
1.11.2 Crash at startup on server side

### ISSUE THREAD

**Issue by Aang23** [Team-RTG/Realistic-Terrain-Generation#1219]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: latest 1.11.2
- RTG version: 1.11.2-dev

##### Issue Description:
I compiled the alpha RTG version for my server, from the 1.11.2-dev branch. Working on client side, but not on server side...

##### Steps to reproduce the issue: 

1. Install a server
2. Set the world type to RTG
3. Start it !

##### Extra Information:
https://pastebin.com/ajFhjLv3

**Comment by srs-bsns** [comment]
The 1.11.2 branches we never fully updated and should be considered non-working, which is why we haven't even released an alpha yet.
We had initially started to update to 1.11.2 but then stopped to put out one last 1.10.2 release that is still being worked on.

**Comment by Aang23** [comment]
So 1.11.2 will be out when this last 1.10.2 release is done.
