### ISSUE TITLE
Weird beach borders with e.g. crescent shapes

### ISSUE THREAD

**Issue by salmjak** [Team-RTG/Realistic-Terrain-Generation#1221]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 12.18.3.2316
- RTG version: 4.2.0.0-snapshot5
- Geographicraft: 0.8.7

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
![image](https://user-images.githubusercontent.com/18286743/29749391-62f5cfac-8b2a-11e7-869d-990212c6a2b9.png)
![image](https://user-images.githubusercontent.com/18286743/29749393-73925cea-8b2a-11e7-803d-e8412cd1cb5b.png)
![image](https://user-images.githubusercontent.com/18286743/29749396-848ff1ce-8b2a-11e7-9c4f-dec4b0155b36.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Generate a new world

Thought it was a bug with bleeding beaches but set bleed distance to 0 and still get these.

**Comment by salmjak** [comment]
Hmm... I'm pretty sure now that the snapshot does not seem to work with

**Comment by salmjak** [comment]
![image](https://user-images.githubusercontent.com/18286743/29790221-57e26b42-8c39-11e7-8fbe-3859a80ece35.png)
![image](https://user-images.githubusercontent.com/18286743/29790244-6f9cd75e-8c39-11e7-87f8-3ab29545b5ab.png)
![image](https://user-images.githubusercontent.com/18286743/29790261-7e3d7048-8c39-11e7-85b0-6691b482b6d8.png)

**Comment by whichonespink44** [comment]
I've seen this in my testing as well... not sure what's causing it, though I suspect it's related to the new river system. I'll need to speak to @Zeno410 to confirm.

1 2 3 NOT IT!

**Comment by srs-bsns** [comment]
I can't see this ever being fixed. This was introduced by changes Zeno made (in BiomeAnalyser, I believe) and I don't think anyone is going to go digging into that spiderweb method calls and strange iterations.

1 2 3 NOT IT!
