### ISSUE TITLE
Witchery worldgen crash (RTG-1.7.10-1.1.1.6)

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Team-RTG/Realistic-Terrain-Generation#1223]
Forge 1.7.10 1614

When I launch a MultiMC pack including RTG, Witchery, ClimateControl, Thaumcraft, Advanced Rocketry, Gregtech, Biomes O'Plenty, Fastcraft, and others, when I generate a world the first time, it works fine, but if I restart Minecraft and try to generate the same seed again, I get the following crash. The strange thing is that deleting the configs causes it to work one more time, but even if you don't change them at all you still have to delete them again to get the world to generate once more.

Crash Report : https://pastebin.com/pcDkv1rZ

**Comment by srs-bsns** [comment]
This is an exception thrown on a vanilla Minecraft class (that can't be found), which should _never_ happen, unless some mod is doing something it shouldn't. My guess is it's Optifine.
There's no way this is RTG. All we are doing in this case is providing a vanilla chunk generator (Which means this is happening in a non-Overworld dimension).

Next time please use pastebin for your crash report.

**Comment by bHXDgiuMa5yLHyC8** [comment]
For the benefit of anyone else who is having this problem: disabling Optifine and Fastcraft doesn't appear to do anything.

**Comment by Robijnvogel** [comment]
@bHXDgiuMa5yLHyC8 Since Optifine is explicitly mentioned in the stacktrace, I doubt that.
at WorldServer**OF**.(WorldServer**OF**.java:69)
at WorldServerMulti**OF**.(WorldServerMulti**OF**.java:23)
If you remove Optifine, those lines in the crash report should change in the very least.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Apparently removing Thaumic Horizons prevents this issue.

**Comment by Robijnvogel** [comment]
Try [this](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2361575-thaumic-horizons-v1-1-9-thaumcraft-4-addon?comment=2102). :)

**Comment by Robijnvogel** [comment]
There is a link in the spoiler to a version that may solve your crash.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Thanks a lot. That version didn't help, but this issue doesn't seem to have anything to do with RTG.
