### ISSUE TITLE
Only large islands generate

### ISSUE THREAD

**Issue by iAerosoft** [Team-RTG/Realistic-Terrain-Generation#1224]
##### Affected Mod Versions: 
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.7.10
- RTG version: 1.7.10
- Biomes o Plenty: 1.7.10
- Climate Control: 1.7.10
- Alternate Terrain Generator: 1.7.10

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
I'm running a server with the mods listed above for terrain generation, I have RTG enabled in my sever properties and it works pretty well. The only "issue" I have is that my server only generates large islands, it doesn't ever create large landmasses where I can travel for days. It's just a large island I can walk around and clear in about 5-15 mins. Is this how it's supposed to be? I'm surrounded by ocean and it never looks like there's more land around. It's always just 1 big island

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.
2.
3.

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by srs-bsns** [comment]
RTG doesn't handle biome layouts. The world you are seeing is the result of ClimateControl.

In the `climatecontrol.cfg` set `B:SeparateLandmasses` to `false`.
