### ISSUE TITLE
Doesn't spawn BOP nether biome in nether.

### ISSUE THREAD

**Issue by ComfyFluffy** [Team-RTG/Realistic-Terrain-Generation#1232]
Hi. When I use RTG with BOP and Climate Control mod  on MC 1.10.2 , it doesn't spawn BOP nether biome in nether.

Mods version:
RTG-1.10.2-4.2.0.0-snapshot-5
GeographiCraft-1.9.4-0.7.6
BiomesOPlenty-1.10.2-5.0.0.2290

**Comment by srs-bsns** [comment]
RTG doesn't touch The Nether, has never touched The Nether, and never will touch The Nether. If you are having a problem with BoP's Nether biomes, then it is something else doing it.

Also, you are using a snapshot release, which is alpha level code, which means you shouldn't be using it at all unless you were testing for us. Use our current stable release for 1.10.2 which is `RTG-1.10.2-4.1.2.4`.
