### ISSUE TITLE
[1.12.2/update] Cannot select world type

### ISSUE THREAD

**Issue by arutr** [Team-RTG/Realistic-Terrain-Generation#1234]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 14.23.2.2634
- RTG version: RTG-1.12.2-6.1.0.0-alpha.1

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

The 'Realistic' world type option does not appear in 'More settings' tab when creating a new world.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Create a new world
2. Go to More Settings

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by srs-bsns** [comment]
The RTG world type has been disabled. The 1.12 branch is currently unstable and not ready for use, which is why there isn't a release as of yet.
