### ISSUE TITLE
Savanna Plateau needs to possibly be reverted to the previous terrain

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1239]
The changes made to the Savanna Plateau terrain post RTG 4.1.\*.\*, which is currently in use in 1.12 dev, has plateaus that are too high, too steep, and too closely resemble the Mesa Plateaus, which aren't very realistic for Savanna. They also lack proper checks for the surrounding area which can lead to strange artifacting from incomplete plateaus.

The old terrain was much better than this, so the terrain changes should be reverted.

![savannap1](https://user-images.githubusercontent.com/8453133/41148910-2451e450-6ad8-11e8-9f9d-db58db249a48.png)
![savannap2](https://user-images.githubusercontent.com/8453133/41148915-27347b60-6ad8-11e8-95a9-11a3b38b4a79.png)

**Comment by Ezoteric** [comment]
Yeah its what i said a few times :P 

Sometimes its even worse and you get like 8 huge plateaus that fills the whole biome haha

**Comment by srs-bsns** [comment]
We should maybe reduce the height of, or remove, the second tier for 1.12 to make it look more natural.

Here's an example of the old Savannah Plateau terrain currently in 1.10:
![2018-07-23_21 57 47](https://user-images.githubusercontent.com/8453133/43156132-4df39004-8f47-11e8-89c0-7ffcd15e3caf.png)

**Comment by Ezoteric** [comment]
can you like, having it have  % of chance to get a 2nd layer ? that would be nice  :)

**Comment by mgdgfbhevdyeh** [comment]
So what about Mesa biome?
#1116 is now close, it marked change on the mesa and it complete, but seems like nothing happeneds

**Comment by whichonespink44** [comment]
Fixed in 0bfa6f8
