### ISSUE TITLE
Beach repair

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1240]
An attempt should be made to fix, or atleast improve, the beach repair system. Currently, in some situations in some biomes, the repair is running in areas that it shouldn't which leads to strange and isolated beaches. There is also an issue with artifacting that was introduced since RTG 1.10 stable that needs to be fixed.

![beach2](https://user-images.githubusercontent.com/8453133/41149597-f997f8ec-6ad9-11e8-911f-77fb5c71880a.png)
![beach3](https://user-images.githubusercontent.com/8453133/41149577-ea728224-6ad9-11e8-8889-34a2f18a0e92.png)

**Comment by Ezoteric** [comment]
2nd pic is quite nice tbh :D

**Comment by Robijnvogel** [comment]
Is the fact that that beach in the second picture stretches far land inwards considered problematic as well? Because I think that would actually be realistically possible.

**Comment by srs-bsns** [comment]
The problem is that there is a limit on it, and when it reaches the limit it leaves a very noticeable straight line where it stopped, like in the first image. The reason it went so far inland is because the land is still very low there.
I might investigate using jitter to create a minor dithering effect where the beach meets the inland biome. You can see the effect in both of those images where the beach meets a stone beach, at the top in the first image and the right in the second.

The artifacting issue is that streak of grass that's cutting through the sand in the second image. That shouldn't be there.

**Comment by srs-bsns** [comment]
This is not going to happen. This takes place in `BiomeAnalyser` which is far too embedded and grotesque to touch.
