### ISSUE TITLE
Deeper Lakes

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1241]
Currently, when lakes are generated, the whole lake goes no deeper than a river, on average. They should be made to go much deeper than that.

![lakes1](https://user-images.githubusercontent.com/8453133/41149893-b9eaafcc-6ada-11e8-975f-523a0256670b.png)

**Comment by whichonespink44** [comment]
At least deep enough to hide more of the visible terrain at the bottom of the lake.

**Comment by whichonespink44** [comment]
This can wait until after we release for 1.12

**Comment by srs-bsns** [comment]
See my comment in the river issue: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/923#issuecomment-513525985

**Comment by whichonespink44** [comment]
See my comment in the river issue: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/923#issuecomment-513541638

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/923#issuecomment-1119701401
