### ISSUE TITLE
Too many mobs spawning

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1242]
Just as in 1.10, too many mobs appear to be spawning. This may be due to how chunks are being loaded with the delayed decorator, so this is low priority as all that code is being stripped, so it might just fix itself.

**Comment by whichonespink44** [comment]
I suspect this does have something to do with the DD system, but I also suspect that mobs might be spawning more frequently because RTG's open, often flat, terrain gives them more opportunities to spawn (something to do with more air blocks, etc), similar to how villages would generate more frequently because RTG tends to more frequently create the conditions under which villages *can* generate.

**Comment by srs-bsns** [comment]
>but I also suspect that mobs might be spawning more frequently because RTG's open, often flat, terrain gives them more opportunities to spawn

There seems to be a disparity of mob spawning in similar terrain with vanilla, which is why I suspect that mob spawning routines are being called multiple times, just as ore gen is. It's all going to get sorted out in the end.


> similar to how villages would generate more frequently because RTG tends to more frequently create the conditions under which villages can generate.

Villages simply generate more in RTG worlds because we allow them in a lot more biomes than vanilla does.

**Comment by whichonespink44** [comment]
> Villages simply generate more in RTG worlds because we allow them in a lot more biomes than vanilla does.

That's true, but I seem to recall more villages spawning when only allowing them in the same biomes that vanilla does. Could be wrong though as it was some time ago when I tested it... like early RTG beta days.

**Comment by whichonespink44** [comment]
The Beta Testers are currently keeping an eye out for excessive mob spawns... so far, no one's noticed anything out of the ordinary, so this probably got resolved (or at least was improved) when we removed the delayed decoration system.

**Comment by whichonespink44** [comment]
I'm closing this for now as no one's reported seeing anything unusual, and I also haven't noticed anything excessive in my testing, at least nothing more excessive than what happens in default worlds.
