### ISSUE TITLE
Pinky has gone missing

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#1244]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1337
- RTG version: 401

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
I cant find pinky

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. install discord
2. go to team rtg
3. go look for him

##### Extra Information:
Robijn vogel is a n00b

**Comment by Robijnvogel** [comment]
I've been trying hard to hide it, but I must face the truth... You got me. :(

**Comment by srs-bsns** [comment]
Can you not add spam issues to our tracker, please.
