### ISSUE TITLE
Crashed while loading game (missing polar_chasm) 1.12.2

### ISSUE THREAD

**Issue by Sagez** [Team-RTG/Realistic-Terrain-Generation#1245]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
mod list is already in crashlog.txt
- Forge version:
forge-1.12.2-14.23.4.2709-universal.jar
- RTG version:
RTG-1.12.2-6.1.0.0-alpha.1.jar (built by June 22, 2018 via 1.12.2-update github version)
##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
Error show "java.lang.NoSuchFieldError: polar_chasm" while loading minecraft.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Start the game.
2. waiting for the game appear to main menu (but it didn't happen)

##### Extra Information:
[crash-2018-06-22_17.47.43-client.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/2129374/crash-2018-06-22_17.47.43-client.txt)
[fml-client-latest.log](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/2129376/fml-client-latest.log)

**Comment by srs-bsns** [comment]
There is no 1.12 release. There is no working branch for 1.12. Please stop building from source and opening issues, 1.12 is not ready yet.
