### ISSUE TITLE
Request: Dynamic Trees compatibility

### ISSUE THREAD

**Issue by nepphhh** [Team-RTG/Realistic-Terrain-Generation#1247]
That's all. See BoP/DT compatibility mods for an idea of what I'm looking for, I guess.

**Comment by srs-bsns** [comment]
I am almost certain that adding support for Dynamic Trees would require a client-side component, in which case this will not be added to RTG as it is server-side only.

Regardless, this sort of compatibility would be best added by a separate mod, such as it is done for other mods like BoP, Traverse, Thaumcraft, and Heat and Climate.

**Comment by Ezoteric** [comment]
tbh i think when RTG comes out the mod maker will prolly make the mod himself right :)
