### ISSUE TITLE
Can't find RTG-Realistic world gen option

### ISSUE THREAD

**Issue by nepphhh** [Team-RTG/Realistic-Terrain-Generation#1248]
##### Affected Mod Versions:
- Forge version: 14.23.4.2705
- RTG version: 1.12/update branch (commit 92db872b72b7a0d4f456c107df3fde95690e1ff3)
- BoP version: 7.0.1.2355 (Any later versions than this cause loading crashes because of the removal of a Nether biome. Some really rare cold one.)
- CC version: 0.8.7

##### Issue Description:
No RTG-Realistic option appears in the world type button.
BoP, Geographicraft/CC are installed. Quark is installed. Its realistic mode is disabled.

**Comment by whichonespink44** [comment]
There is no 1.12 release. There is no working branch for 1.12. Please stop building from source and opening issues, 1.12 is not ready yet.

**Comment by nepphhh** [comment]
Understood. Thought bug reports could help with branch development.

**Comment by srs-bsns** [comment]
Duplicate of #1245

**Comment by srs-bsns** [comment]
Duplicate of #1245
Duplicate of #1234
