### ISSUE TITLE
Remove village generation from most biomes

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1249]
For 1.12, we should disable village generation in most biomes in which it is currently enabled. Perhaps only allow villages in the same biomes as vanilla.
Currently villages are enabled in biomes that they never should have been, like Extreme Hills, so we get crap like this:
![2018-07-23_18 20 38](https://user-images.githubusercontent.com/8453133/43156485-44daf4de-8f48-11e8-8057-90ae705cdf31.png)

**Comment by whichonespink44** [comment]
We'll still keep the biome config option to enable/disable villages, but we'll only enable them by default in the biomes that vanilla allows them to generate in.

**Comment by whichonespink44** [comment]
Fixed in a296c6e
