### ISSUE TITLE
[1.12] Fix server compatibility

### ISSUE THREAD

**Issue by Aang23** [Team-RTG/Realistic-Terrain-Generation#1251]
I tried the current source to see the progress (Not to use it as it is not a release), and I noticed that it does not start on server, and tough it may be good to inform you, and have it noted down here, as I saw you did this for others issues.
Just ./gradlew runserver to see the issue.

**Comment by MoeBoy76** [comment]
<insert angry comment about people not reading that 1.12 is not for use at all>
