### ISSUE TITLE
problem with Nature Compass mod

### ISSUE THREAD

**Issue by matheusvingadouro** [Team-RTG/Realistic-Terrain-Generation#1254]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.12.2-forge1.12.2-14.23.4.2705
- RTG version: RTG-1.12.2-6.1.0.0-beta.1
other mod to be listed: NaturesCompass-1.12.2-1.5.1

##### Issue Description:
I've found a bug with a mod named "Natures Compass" it is used to find biomes easier.... I tried to find a Mesa in my rtg test world, when I selected "mesa" a problem happened and I was kicked from my own test world
I tried a second time and I got a crash

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.get in a world with rtg set
2.right click with nature compass item in your hand and select a biome
3.after that you get kicked from your own world or you get a crash

##### Extra Information:
https://pastebin.com/JESRyKWV -> crash I got
(I can't put the log here because it is too big to be in pastebin)

**Comment by whichonespink44** [comment]
I can confirm this is happening as well.

**Comment by srs-bsns** [comment]
I'm not sure why this was so quickly flagged as a bug (in RTG). The stacktrace clearly shows that this exception is thrown client-side.

**Comment by srs-bsns** [comment]
@matheusvingadouro Use https://gist.github.com/ for large log files.

**Comment by matheusvingadouro** [comment]
here is the log
https://gist.github.com/matheusvingadouro/96f9698a1f3340947cf1fd1a852f892a

**Comment by srs-bsns** [comment]
This is an issue with GeographiCraft and it's use of custom GenLayers.
