### ISSUE TITLE
RealisticBiomeBase -> Biome#getBiomeName is now client-side only

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1256]
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.12.2-dev/src/main/java/rtg/world/biome/realistic/RealisticBiomeBase.java#L376

This needs to be updated to get the biomes ResourceLocation instead.

**Comment by whichonespink44** [comment]
Fixed in 488e462
