### ISSUE TITLE
Feature Request of configurable tall/small tree size ratios

### ISSUE THREAD

**Issue by Willynator** [Team-RTG/Realistic-Terrain-Generation#1266]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: forge-14.23.4.2749
- RTG version: RTG-1.12.2-6.1.0.0-beta.2

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

The trees in RTG are beautiful with only one complaint. It seems a large majority of generated trees are several dozen blocks high, but occasionally you may see what seems like a tree of a more manageable size but that still fits the stylings of other RTG trees.

My suggestion is to possibly add a config option to set the ratio of the size of trees which seems most problematic in forest biomes.

Smaller Tree Example
https://gyazo.com/b4734276f7fecb529d968d3d956f63c0

Large Tree Example with the previously mentioned trees still in shot
https://gyazo.com/8009ece66e1f8e033295a0782125113e

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/923#issuecomment-1119701401
