### ISSUE TITLE
Server crash from calling client-side method: Biome#getBiomeName

### ISSUE THREAD

**Issue by andrboot** [Team-RTG/Realistic-Terrain-Generation#1268]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

Streams-1.12-0.4.4.jar
- RTG version: RTG-1.12.2-6.1.0.0-beta.2.jar
GeographiCraft-1.12-0.8.9b.jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
##### Issue Description:
Server crashes on boot
(No world created yet)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Start Server 
2. Watch crash

##### Extra Information:
https://pastebin.com/raw/mbq78dRe

**Comment by Aang23** [comment]
Another crash log : Obtained with ./gradlew runserver from the github commit a08280a2f40b849310cf98329c17568e551f2cd7
level-type set to RTG
No other mod used.

Logs : https://pastebin.com/XGmu4uQ4
Crash : https://pastebin.com/fQU79V7U
