### ISSUE TITLE
Savannah M terrain is overly extreme, requires adjustment

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1276]
![2018-08-14_04 25 35](https://user-images.githubusercontent.com/8453133/44085032-5a0fdc40-9f86-11e8-92cb-ae7755d194ef.png)

**Comment by whichonespink44** [comment]
Anybody got any suggestions for this biome? The vanilla version is quite chaotic with massive cliffs and overhangs.

Maybe a variation of one of the X Hills variants?

**Comment by Ezoteric** [comment]
maybe use the rtg mountain biome from bop, that seems okish

**Comment by whichonespink44** [comment]
Fixed in 373dc66
