### ISSUE TITLE
Igloos don't like RTG Ice Plains

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1278]
![](https://cdn.discordapp.com/attachments/477934928902881292/479010625083670548/2018-08-14_20.36.09.png)

**Comment by ThelianTech** [comment]
I have been flying around 5 worlds and found three igloos that are generating normally, im not sure if this was just a freak structure placement or a bug. One possibility is maybe that the structures bounding box is colliding with the snow layers thinking that it is blocks it needs to place on top of. but i cant confirm that possibility yet.
-Signed off by EmberFlash <thelianinteractive@gmail.com>

**Comment by whichonespink44** [comment]
![2019-07-20_08 06 30](https://user-images.githubusercontent.com/10927161/61575604-746b9e80-aac5-11e9-9bce-2880919e1248.png)

Every igloo I've seen in testing (a grand total of 3) has looked ok to me. Closing this for now and hoping for the best!!!
