### ISSUE TITLE
Add Support for Project: Vibrant Journeys

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#1288]
##### Issue Description:
This mod includes several biomes in it. Could support be added for this?

##### Extra Information:
[Project: Vibrant Journeys](https://minecraft.curseforge.com/projects/project-vibrant-journeys): v1.12.2-1.1.4
[Project: Vibrant Journeys Wiki](https://github.com/mc-jt9/ProjectVibrantJourneys/wiki)

**Comment by whichonespink44** [comment]
Support added in 411d9a2
