### ISSUE TITLE
Add biome weighting for RTG biomes

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#129]

**Comment by whichonespink44** [comment]
RTG's custom biomes will eventually be removed, but as long as they're present, it would be great to have config options to enable/disable them to make testing easier.

**Comment by Ezoteric** [comment]
I gonna look into this today cause most maps i generate does not have a ocean within 40000 chunks (map gen 100) I hope I can fix this 😊

**Comment by whichonespink44** [comment]
Yeah, it can be a pain trying to find the biome you're working on without hardcoding it.

Just to clarify, are you adding weighting to the 'base' biomes (rtg_xxxx) or the vanilla ones?

Either way, be sure to sync with master before you start as I've completely removed 'coasts' from the codebase: 6496501

**Comment by Ezoteric** [comment]
Yesterday I deleted all RWG biomes from chunk generator and gave 3 vanilla biomes a hot cold and snow addition. This way there are no more RWG biomes also.
I duno if we need to keep using those as that's the way RWG chose biomes to create.

And yes I am putting weight on vanilla biomes. I have RWG on pause for now 😛

**Comment by whichonespink44** [comment]
Yeah, all those RWG base biomes were doing is creating an empty biome & setting the temp/rain so that the realistic sub-biomes could have someplace to live, so... since we're using vanilla biomes, we could probably do it the same way but not sure how we'd organise it. Need to think about it.

**Comment by Ezoteric** [comment]
Well vanilla has its temperatures so that's easy to fix I'll. Test some things

**Comment by whichonespink44** [comment]
Added in 399ef13

**Comment by Ezoteric** [comment]
Did you also tested this? :p

**Comment by whichonespink44** [comment]
Yep. It's not ideal, but it seems to be working well enough to close this for now. If you generate any maps, let me know what you think. (Setting the weight to 0 should stop it fron generating.)

**Comment by Ezoteric** [comment]
Yeah I can test it if you like haha

I gonna integrate your Simplex changes and dump the layers in it and everything else so ppl can fix that version. Cause I think that's the best to do.
