### ISSUE TITLE
RTG and Biomes`o Plenty Integration

### ISSUE THREAD

**Issue by SSKirillSS** [Team-RTG/Realistic-Terrain-Generation#1293]
Hello. I tried to create a world in a singleplayer game - the world was created and all biomes of Biomes o' Plenty worked correctly. But when I installed all mods to the server, the result was negative: only RTG biomes are generated with some features of Biomes o' Plenty generation (Mud, some types of trees and plants), but there were no Biomes o' Plenty biomes at all.
P.S. I'm using the default GeographiCraft and RTG settings(Tested on singleplayer and server).

Tested versions:
Forge:
1.12.2-forge1.12.2-14.23.4.2705(Client & Server);
1.12.2-forge1.12.2-14.23.4.2749(Client);
1.12.2-forge1.12.2-14.23.4.2750(Client & Server);
SpongeForge:
spongeforge-1.12.2-2705-7.1.0-BETA-3361(Server);
Nucleus:
Nucleus-1.4.3-S7.0-MC1.12.2(Server);
Nucleus-1.5.3-S7.0-MC1.12.2(Server);
Biomes o'Plenty:
BiomesOPlenty-1.12.2-7.0.1.2399(Client & Server);
//2398 does not work.
RTG:
RTG-1.12.2-6.1.0.0-beta.5(Client & Server);
GeographiCraft:
GeographiCraft-1.12-0.8.9b(Client & Server);

Some sreenshots:
Singleplayer: http://prntscr.com/kla60j
Multiplayer:
http://prntscr.com/kladd7 - overworld;
http://prntscr.com/klaf0e - nucleus created world (/world create -g rtg:r_t_g RTG);

**Comment by srs-bsns** [comment]
First of all, RTG is currently in a closed beta, and I do not recognise you as one of our beta testers. Please stop building from source and opening issues. Once RTG has reached sufficient stability there will be a public release for everyone else to test with.

Secondly, RTG, (including the current private betas,) has never handled adding biomes to the world. GeographiCraft or BiomeTweaker is used to do this and is only required to add BoP biomes to a world as they are not added by default like they are for pretty much every other mod that adds biomes. If there is an issue with biomes not being added to the world, then it is an issue with one of those mods, not RTG.

Thirdly, I have personally tested the combination of RTG, BoP, and GeographiCraft on a dedicated server, and I know that they work together, so I am not sure what issue you are having, but it is not related to RTG, BoP, or GeographiCraft.

Pic for proof: (Forge 14.23.4.2705, RTG 6.1.0.0-beta.5, BiomesOPlenty 7.0.1.2399, GeographiCraft 0.8.9b)
![2018-08-21_12 47 07](https://user-images.githubusercontent.com/8453133/44417004-768a4d80-a542-11e8-97f0-01b71f5731c1.png)
