### ISSUE TITLE
BOP's Redwood Forest Not "As Dense" as it should be.

### ISSUE THREAD

**Issue by ThelianTech** [Team-RTG/Realistic-Terrain-Generation#1297]
![2018-10-30_15 01 26](https://user-images.githubusercontent.com/29005715/47760320-444f4780-dc79-11e8-85b0-2f1e4a96a415.png)

BOP's Redwood Forest is normally very dense. Probably A Bug.

-Originally Reported by Robijnvogel, Posted here by EmberFlash

**Comment by whichonespink44** [comment]
Fixed in 2549650
