### ISSUE TITLE
Mushroom biome everywhere

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#1298]
##### Affected Mod Versions:

- Forge version: release 1.7.10-Forge10.13.4.1566-1.7.10
- RTG version: RTG-1.7.10-1.1.1.6

##### Issue Description:
Every time i generate a world with this mod, it's endless mushroom biome and chunk errors everywhere.
It's actually everywhere. I can't continue playing because theres too much mushroom biome and none of the biomes i need. I don't know why this is happening. This only happens if i select the "realistic" world type on the world creation menu.
![unknown](https://user-images.githubusercontent.com/36605997/47952661-1e74bc00-df73-11e8-935e-b0a2066531bc.png)
![unknown](https://user-images.githubusercontent.com/36605997/47952666-2d5b6e80-df73-11e8-978c-2d6fa290e612.png)
(these two screenshots are from two different worlds, right next to / in spawn area.)

**Comment by srs-bsns** [comment]
This is a 3 year old issue that has nothing to do with RTG. Furthermore, this is in 1.7.10 which is no longer supported.
