### ISSUE TITLE
Compatibility With Pam's Harvestcraft

### ISSUE THREAD

**Issue by NialMontana** [Team-RTG/Realistic-Terrain-Generation#1299]
Affected Mod Versions:
Pam's Harvestcraft 1.7.10Lb

- Forge version:
10.13.4.1614 - 1.7.10

- RTG version:
1.1.1.7

Issue Description:
When attempting to create a world in the RTG generator with pam's harvestcraft installed the game crashes upon attempting to load the world.

Steps to reproduce the issue:

1. Create or load a world with both mods installed
2. Game crashes

Extra Information:
Crash report: https://pastebin.com/wjQbBXqr

**Comment by srs-bsns** [comment]
1. This is a HarvestCraft issue.
2. 1.7.10 is no longer supported.
