### ISSUE TITLE
Remove CustomizeBlockEvent

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#1302]
The `CustomizeBlockEvent` isn't really useful as the blocks can just be set via configs and should remain world persistent.
It is highly unlikely that any mod would utilise this event (which would require a dependency on the RTG API) and it creates an environment in which another mod could corrupt the world by arbitrarily changing which blocks are used during chunk generation.

**Comment by whichonespink44** [comment]
IIRC, this event was added to allow UBC to 'do its thang' with RTG's boulders, so if UBC isn't using this event, then I don't see any harm in removing it. But either way, I don't think this needs to be sorted before we release for 1.12

**Comment by Aang23** [comment]
No UBC doesn't use that event anymore in 1.12.2.

**Comment by whichonespink44** [comment]
Then we burn it to the ground!!! 🔥🔥🔥

**Comment by srs-bsns** [comment]
Closed in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/d6b7a9323a5aeb93ef4834ddc46ec3c47bc3f7fa
