### ISSUE TITLE
compile error , maybe typo in January 2 2019 commit

### ISSUE THREAD

**Issue by Tsoccerguy3** [Team-RTG/Realistic-Terrain-Generation#1304]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:
- RTG version: 1.12.2-dev

##### Issue Description:
Probable typo in last commit 

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Compile 1.12.2-dev
2.
3.

Task :compileJava
RTG\build\sources\main\java\rtg\world\WorldTypeRTG.java:107: error: package rtg.client.gui does not exist
        mc.displayGuiScreen(new rtg.client.gui.GuiCustomizeWorldScreenRTG(guiCreateWorld, guiCreateWorld.chunkProviderSettingsJson));
                                              ^

**Comment by srs-bsns** [comment]
Meh. Not sure how IDEA missed migrating that qualified name when I refactored.
