### ISSUE TITLE
Chunk Walls after opening to LAN RTG + BOP /w supplied BT configs 

### ISSUE THREAD

**Issue by Retrobearr** [Team-RTG/Realistic-Terrain-Generation#1305]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version:7.10.99.99
- RTG version:1.1.1.7

##### Issue Description:
(Please provide screenshots if necessary/possible. Images can be dragged & dropped into this window.)
I know this an older version that isn't being worked on anymore but I'm hoping y'all will at least give me an idea of what's messing up and where I could fix it.  I'm running the latest version of FTB infinity and added RTG and biome tweaker to it using the configs you have for RTG and BOP on here.    Anyways after someones joins me once I open to LAN the whole biome gen freaks out and start generating a whole other seed we think.   Once I save the world restart FTB open to LAN and have my friend join me new chunks just become chunk walls and whole different biomes 

https://i.imgur.com/sraKGNL.png

Same world seed without my friend joining

https://i.imgur.com/LndPmEL.png

When I play alone restart multiple times nothing ever happens.  It only acts up after my friend joins on on LAN 

I know this is horribly out of date but all help would be appreciated 

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.
2.
3.

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by srs-bsns** [comment]
1.7.10 is no longer supported.
