### ISSUE TITLE
Suggestions for a few biome-adding mods

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1310]
1. Auxiliary Biomes
2. Redwoods

**Comment by srs-bsns** [comment]
Auxiliary Biomes:
RTG does not call this method on biomes and would have no way of reliably creating similar terrain for it without a bunch of special casing.
https://github.com/coderbot16/AuxiliaryBiomes/blob/master/src/main/java/net/coderbot/auxbiomes/biomes/BiomeMarsh.java#L70-L94

**Comment by whichonespink44** [comment]
Support for Redwoods added in b96e26c
Support for Auxiliary Biomes added in bb11aed
