### ISSUE TITLE
Disable lava lakes on the surface by default

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1312]
Not sure about the best way to go about this, but those surface lava lakes have to go as they just mutilate the landscape.

Maybe a config option, but definitely disabled by default.

**Comment by whichonespink44** [comment]
Fixed in 04c7602

**Comment by srs-bsns** [comment]
1. The API shouldn't be referencing stuff outside of it like that. (This should have been done in `RealisticBiomeBase`)
2. This is also a bad way to do it as there are implementers that override that method which will completely ignore the config setting.
3. If you are going to make it configurable via a config setting, then that method becomes pointless.

**Comment by whichonespink44** [comment]
> 1. The API shouldn't be referencing stuff outside of it like that. (This should have been done in RealisticBiomeBase)

Where is the API referencing something outside of it?
