### ISSUE TITLE
Snow not generating properly in Extreme Hills

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#1317]
![2019-08-02_14 32 23](https://user-images.githubusercontent.com/10927161/62374498-03e86700-b534-11e9-898d-cee18b3792a9.png)

![2019-08-02_14 35 32](https://user-images.githubusercontent.com/10927161/62374505-08148480-b534-11e9-9d34-69d901bcb604.png)

![2019-08-02_14 35 54](https://user-images.githubusercontent.com/10927161/62374514-0ba80b80-b534-11e9-8e58-59f2ae817bad.png)

**Comment by srs-bsns** [comment]
I was already looking into a solution for this myself. It has to do with the recalculation of the snow height for Extreme Hills biomes. My Bug, My issue.

**Comment by 74HC14** [comment]
Is the snow also supposed to be generating in smooth tile-based layers on the mountains?

**Comment by srs-bsns** [comment]
Your question doesn't have any relevance to this issue, so I don't know why you are asking this here.

If what you are refering to is happening in biomes that generate those layers (ice plains), then yes. Sometimes flatter biomes have poor transitions into mountainous ones and ride up into mountains.

Nothing can be done about this without completely rewring the terrain gen system in RTG.
