### ISSUE TITLE
[Suggestion] Geographicraft compatibility or native north/south biome temperatures

### ISSUE THREAD

**Issue by 74HC14** [Team-RTG/Realistic-Terrain-Generation#1318]
Geographicraft adds an option to generate terrain with colder biomes the further north or south you travel of 0,0, specifically an option named "Frozen Icecaps". This is a suggestion to either allow geographicraft to do its thing to RTG-generated worlds (which I think involves a bit of its own terrain manipulation) or to implement this feature in RTG itself.

**Comment by srs-bsns** [comment]
`B:"Frozen Icecaps"` only changes Ocean biomes in cold climates into Minecraft's unimplemented Cold Ocean biome.
What you are refering to is the banded climate, which is completely handled by Geographicraft and has to do with how the biomes are layed out in the world, not with terrain gen. RTG does not interfere with this.
