### ISSUE TITLE
Mobs Not Spawning

### ISSUE THREAD

**Issue by roland3564** [Team-RTG/Realistic-Terrain-Generation#1319]
##### Affected Mod Versions:
- Forge version: 1.7.10 - 10.13.4.1614
- RTG version: 1.1.1.7
##### Issue Description: 
when loading realistic worlds mobs are not spawning
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. create world
2. join the world
3. mobs are not spawning
FIXED
i used the realistic world gen not the realistic terrain gen

**Comment by ThelianTech** [comment]
Even if it was an issue with our mod. This still would have been closed due to No Legacy support. Please update to 1.10.2 or newer.
