### ISSUE TITLE
Mesa (Bryce) generating a rocky desert

### ISSUE THREAD

**Issue by GeneralDexter** [Team-RTG/Realistic-Terrain-Generation#1321]
##### Affected Mod Versions:

I use FTB Relevation, but i have replaced BiomesOPlenty to version -1.12.2-7.0.1.2399-universal

- Forge version: 14.23.5.2836
- RTG version: RTG-1.12.2-6.1.0.0-beta.11
- GeographiCraft-1.12-0.8.9b

##### Issue Description:

Mesa (Bryce) ID=165 (Eroded Badlands) generating a strange terrain. It looks like a rocky desert.

![2019-09-07_01 03 16](https://user-images.githubusercontent.com/33551042/64465210-9e2b6400-d10b-11e9-9aec-da36cfdc4794.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Just generating a new world.

##### Extra Information:

So the worldgen of this 1.12.2 beta rtg seems fine at all. I'm very happy with this beta.

**Comment by srs-bsns** [comment]
The Bryce mesa variant has looked like this in RTG since 1.7.10.

It's modeled after the real Bryce Canyon:
![Bryce Canyon, Utah](https://upload.wikimedia.org/wikipedia/commons/4/4d/USA_10654_Bryce_Canyon_Luca_Galuzzi_2007.jpg)

**Comment by GeneralDexter** [comment]
Ok yes i agree with you, but compared to the vanilla generation... it seems it's a bit unstructured. I just wanted to let you know. Here a screenshot from vanilla generation:
![1080px-Minecraft_1 8 3_bryce_seed_with_mesa_biome_and_forest_plateau_rivers_lake_clay](https://user-images.githubusercontent.com/33551042/64536854-1b2c2880-d31a-11e9-903d-c364bba93035.jpg)
