### ISSUE TITLE
Option to disable shadow blocks

### ISSUE THREAD

**Issue by IronPiston** [Team-RTG/Realistic-Terrain-Generation#1322]
##### Affected Mod Versions:

- Forge version: 14.23.5.2838
- RTG version: 6.1.00-snapshot.1

##### Issue Description:
I tried disabling the shadow blocks (out of personal preference), and found they still generated when configured to not have a designated block. Either a toggle to disable shadow blocks, or having no block set automatically disable them, would be appreciated.

![2019-09-10_18 09 24](https://user-images.githubusercontent.com/11603684/64656804-41bf9180-d3f6-11e9-989c-f59e7dcb20c6.png)
![2019-09-10_18 09 36](https://user-images.githubusercontent.com/11603684/64656807-4421eb80-d3f6-11e9-890f-f4cbc6008a66.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Remove all blocks for shadow blocks
2. Restart client
3. Generate new world and locate a mountain

**Comment by whichonespink44** [comment]
This might be doable... If it's not too involved, we'll try to get it into the next snapshot.
