### ISSUE TITLE
Crashes when i disable some of the bop biomes

### ISSUE THREAD

**Issue by Wolfram96** [Team-RTG/Realistic-Terrain-Generation#1323]
##### Affected Mod Versions: RTG-1.12.2-6.1.0.0 
GeographiCraft-1.12-0.8.9b; BiomesOPlenty-1.12.2-7.0.1.2441-universal; DynamicTrees-1.12.2-0.9.5; DynamicTreesBOP-1.12.2-1.4.1e;
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: forge1.12.2-14.23.5.2846
- RTG version: RTG-1.12.2-6.1.0.0 

##### Issue Description: Well were to start, i think a more broad description of what i´m trying to to do will be easier for you to answer or help me with. I am creating my personal modpack for personal use only and had basically everything ready when i noticed that you updated your mod 3 days ago with this alpha version and since the only thing i never could stand about bop were the shit vanilla terrain generation and the bad colour palette and feel of some bop-biomes i was incredibly pleased that you despite no-one seeming to care decided to update your mod which was one of my favourites in 1.7.10, i had honestly nearly given up on finding a mod like yours that allowed for bop.

Anyway it didn't work. But i felt i had to try with clean config files and add one mod after the other to see were the problems lie. I managed to add bop as well as dynamic trees and its add-on before i was confident enough to get rid of the awful biomes that sadly come with the bop- mod, for example "alps" which is just ugly and a terrible joke since i live just an hour away from the original alps and they are gorgeous mountains not at all like the bare rocks in bop. Anyway the only way i know of disabling them is to set their biome-ids to "-1" in the bop configs but it seems that was the, or at least one of the main problems that had the game crash on loading a new world. I still have to do some more testing but if i have to play with all the ugly unrealistic biomes i might as well not use bop at all. After all when striving for realism that just breaks the whole experience (though i have to say most other terrain mods make the exact same mistake, aka. otg biome bundle, etc).

Now my question would be is there any way to make it work, am i missing something or does your mod not allow for that kind of modularity. I will probably use your mod without bop in the meantime. Thx for coming back by the way, i think minecraft looks awesome with your mod. If only climate control could mach the biomes up nicer. Basing it just on such few temerature-zones is a little emersion breaking, asking for logic would probably too much but a slightly better colour-machup wouldnt hurt. 
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
![rtg error](https://user-images.githubusercontent.com/38047736/64906192-92c7d200-d6e3-11e9-97f7-36e158c71b8d.PNG)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1.install mods
2.change bop config to disable some biomes
3.enjoy

##### Extra Information: 
not sure how to do that, i think its easy enough to reproduce to not need it

- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by Ezoteric** [comment]
crashlog, please provide it

**Comment by whichonespink44** [comment]
@Wolfram96 I've never had any problem disabling biomes using the -1 method, so a crash log would definitelty shed some light on what's going on behind the scenes.

Alternatively, you could try setting the 'instances' of the BOP biomes to 0 in `minecraft/config/GeographiCraft/biomesoplentyInCC.cfg` though I can't remember if that completely removes the biomes or not.

**Comment by Ezoteric** [comment]
yes i set biomes i dont want to to 0 incidence and they dont spawn

**Comment by srs-bsns** [comment]
Closing due to:
1. lack of response for request of crash report.
2. Not reproducible.
3. If any bug *does* exist to cause this, it will likely be wiped out with the coming custom gen layers.
