### ISSUE TITLE
No BOP Biomes Spawning

### ISSUE THREAD

**Issue by Liam-McCormack-Github** [Team-RTG/Realistic-Terrain-Generation#1324]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.12.2-forge1.12.2-14.23.5.2838
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1
BiomesOPlenty-1.12.2-7.0.1.2441-universal
Traverse-1.12.2-1.6.0-69
I also have Dynamic Trees installed which works great.
##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
No BOP Biomes when using RTG World Type but no RTG when using BOP World Type

I saw on 1.7.10 Post that you had to use BiomeTweaker and I have installed that but still nothing. I feel like I am being stupid or you haven't intergrated this feature yet or something.

I have reinstalled both Biomes O plenty and RTG but still no clue what I am missing.
##### Steps to reproduce the issue: (If it's easily reproducible.)

1.Install RTG, BOP and Traverse
2.Create RTG World
3.No BOP Biomes

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by whichonespink44** [comment]
Have you created 'tweaks' for BiomeTweaker? If not, you'll need to add those before BOP biomes will generate in RTG worlds.

Here are some example tweaks that should get you up and running: https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.12.2-dev/etc/biometweaker/BiomesOPlenty/RTG.cfg

Let us know if they're still not spawning for you.

**Comment by Liam-McCormack-Github** [comment]
Sorry for taking so long to get back. It works, thanks for the help.

Is there a way to change biome sizes?

**Comment by srs-bsns** [comment]
> Is there a way to change biome sizes?

In RTG, currently no, but there will be a setting before final release.

If you are already using BiomeTweaker, there is a setting, but you must have missed it in the example config:
https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.12.2-dev/etc/biometweaker/BiomesOPlenty/RTG.cfg#L370
```
Tweaker.setAverageBiomeSize("RTG", 4)
```
`4` is the default biome size in the vanilla default world type. `6` is the biome size in the vanilla Large Biomes world type.
I can't remember if this value gets clamped to min/max anywhere, but you probably don't want to go lower than `3` or higher than `6`.

**Comment by TheNaberiusCz** [comment]
Hello, could you help me with the tweaker part? I dont understand what that means, i have the same issue as [Liam-McCormack-Github]

I have downloaded the RTG.cfg, but what do i do with it? Please?
