### ISSUE TITLE
Snow layers on ice in Biomes You'll Go glaciers biome creates anomalies and crash risk

### ISSUE THREAD

**Issue by Syampuuh** [Team-RTG/Realistic-Terrain-Generation#1328]
##### Affected Mod Versions:

- Forge version: 14.23.5.2847
- RTG version: 6.1.0.0-snapshot.1
- BYG version: 1.6.8b2

##### Issue Description:

Because RTG seems to replace all snow blocks with snow layers, the glaciers biome from BYG has some strange issues. Most obviously, because snow layers cannot be placed on ice, removing any blocks through any memes makes every other connected block "realize" it can't be there and they vanish in large strips. This looks really strange, but it's mostly harmless on its own.

https://streamable.com/yj718

The real issue arises on a server when lava is flowing onto the snow layers. I guess the mass scale of interaction between fluid and the blocks is really screwing things up because the server will instantly crash when around this. I have been unable to recreate the issue locally, but here is an unabridged crash log from the server:

https://hastebin.com/raw/epuriwuten

With a structure mod on my server that adds some boulders with lava, this made a section of the map simply crash the server if a player approached it. I could only resolve this and properly diagnose the issue by copying the world and removing the lava locally.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Run BYG and RTG on a server
2. Find a glaciers biome
3. Interact with snow layers

##### Extra Information:

Hopefully this could be as simple as blacklisting the biome (and maybe any others that fit this bill, or ice blocks themselves from getting snow layers), but if it's not impossible a fix that could be retroactively applied to existing worlds would be enormously appreciated. I can't really be easily certain that the issue my players encountered was an isolated (but persistent) fluke or if there could be another crash just around the corner if they find another lava source in the biome

**Comment by srs-bsns** [comment]
The fix will be in the next release. Not sure when that will be though.
