### ISSUE TITLE
[Suggestion] JEID compat

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#1329]
If this isn’t already possible, I would advise adding support for it.

**Comment by MoeBoy76** [comment]
This isn’t possible and won’t be possible until 1.14+ as the biome max is hardcoded at 256

**Comment by Sunconure11** [comment]
JEID alters the map gen system itself to try and make it closer to newer builds of MC.

**Comment by srs-bsns** [comment]
No changes will be made in RTG to accomodate mods that alter the limitations of registries or that completely break the region/save format.

Issues are not the place for discussion, so locking.
