### ISSUE TITLE
Add config option 'Use Only Natural Blocks for Vanilla Biomes'

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#133]
If set to TRUE, realistic vanilla biomes can only generate with blocks that can be found 'naturally' in non-realistic vanilla biomes. Ice Mountains (realistic), for example, uses Packed Ice for parts of the cliffs of the mountainside, but if 'Use Only Natural Blocks for Vanilla Biomes' is set to TRUE, then Packed Ice would be replaced with stone.

**Comment by Massanutten** [comment]
Would this config option also effect the cyan stained clay currently used in mountain generation?

**Comment by UndeadZeratul** [comment]
Not to mention vanilla biomes use packed ice as a naturally forming block, in the ice plains spikes biome.  What qualifies as a natural block?

**Comment by whichonespink44** [comment]
_"Would this config option also effect the cyan stained clay currently used in mountain generation?"_
Yes.

_"What qualifies as a natural block?"_
'Natural' in this case means blocks that can only be found in the biome in question. For example, the RTG Swampland in 0.0.16 generates willow trees made of jungle wood. If `"Use Only Natural Blocks for Vanilla Biomes"=true` then either the willow trees would use Oak wood (because Oak wood can be found in Swamps in vanilla MC, whereas Jungle wood cannot) or the willow trees would be removed from the biome.

The idea behind this config option is to give vanilla 'purists' the ability to keep everything truly vanilla, whilst still being able to enjoy RTG's realistic terrain gen.

It might be overkill, but I just thought I'd post it here anyway to see if there's any interest.

**Comment by UndeadZeratul** [comment]
Oh, ok...  so the trees would be come more of a custom shaped vanilla tree, rather than what it is currently.  Just wanted to confirm, thanks.

**Comment by whichonespink44** [comment]
Added in 0.5 via Biome configs. Surface blocks not yet implemented, but closing this issue as it's currently in development.
