### ISSUE TITLE
Feature request: Realistic Ore Generation

### ISSUE THREAD

**Issue by ZeltigDemon** [Team-RTG/Realistic-Terrain-Generation#1330]
I love the mod for the wold it generats. For me the make it even better to add a Realistic ore Veins which can be turned on and off via config

**Comment by srs-bsns** [comment]
RTG is currently feature-locked so there will be no more added features to it.
Such a feature is also outside of the scope of RTG. There are other mods that can handle custom ore gen that will work fine along side of RTG. I suggest you use one of them.
