### ISSUE TITLE
Having more than 256 biome IDs crashes (with JEIDs)

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#1331]
##### Affected Mod Versions:
BiomesOPlenty-1.12.2-7.0.1.2441-universal
CoralReef-2.5-1.12.2
Traverse-1.12.2-1.6.0-69
ProjectVibrantJourneys-1.12.2-1.6.4
NetherEx-1.12.2-2.0.15
twilightforest-1.12.2-3.10.1013-universal
BiomesYouGo1.7.0
AuxiliaryBiomes-1.12-1.0.0
environs-1.12.2-1.0.1
Explorercraft-2.2.9

(Presumably works with any combination of biome adding mods that result in more than 256 IDs)
JEIDs Version: JustEnoughIDs-1.0.3-48.jar

- Forge version: forge-14.23.5.2847
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1.jar

##### Issue Description:
Upon trying to test a large number of biome adding mods listed as support in the RTG 1.12.2 snapshot it turns out that through the use of JustEnoughIDs to surpass the 256 biome ID limit, RTG will crash when trying to load a RTG world or create a new one.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. In combination with JustEnoughIDs surpass 256 biome ids and then load the game
2. Attempt to load a RTG world or create a new one
3. After some time the game will crash

##### Extra Information:
- Crash log: https://paste.dimdev.org/obeyajubir.mccrash

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1329#issuecomment-542038247
