### ISSUE TITLE
Is the rarity of caves in current RTG 1.12.2 source intentional or simply part of the work-in-progress?

### ISSUE THREAD

**Issue by keenerb** [Team-RTG/Realistic-Terrain-Generation#1332]
##### Affected Mod Versions:
No other biome or cave affecting mods.  Ancient Warfare, Roguelike Dungeons, and CustomNPCs are only other mods installed.

##### Issue Description:
Compiled 1.12.2 dev branch commit 821aad0c867b3915af0a4a6562195ca6040230f6

There is an extremely low number of caves generated with this build.  I'm unsure if this is intentional as part of your overall design philosophy or simply an artifact of the general in-progress nature of the 1.12.2 update.

**Comment by srs-bsns** [comment]
This is an intentional default setting that WhichOnesPink made, however, I will likely be setting this back to vanilla defaults before final release.
The low amount of caves has negative effects on normal gameplay as players highly depend on them for early resource gathering.
Also, many mods depend on them to generate specialized materials. For example, Thaumcraft crystals, which only generate in caves.

**Comment by keenerb** [comment]
Thanks for the prompt response.  Is it the cavechance and cavedensity lines in RTGChunkGenSettings.java that determines this?  I tried tinkering with those values and didn't see any difference in generation; what would "vanilla defaults" be for those, if you know offhand?

**Comment by keenerb** [comment]
I think I see the reason for the change.  I was making a silly mistake when changing the values in the source and compiling, it's working now.

![2019-11-16_02 11 41](https://user-images.githubusercontent.com/1183671/68989549-91677280-0816-11ea-8514-8b9885891149.png)

I changed the values to what is referred to as the "default values" (7 and 15) elsewhere in the code and it was rather ugly.

**Comment by keenerb** [comment]
OK, so changing the values in RTGChunkGenSettings.java for cave chance and density don't appear to change anything.  I've tried values between 1/1 and 20/30 for chance and density and no caves were generating.

If I hard-coded values into MapGenCavesRTG.java like:

        // Vanilla chance = 7. HIGHER values = FEWER caves.
        int chance = (7 < 1) ? 1 : 7;

        // Vanilla density = 15. HIGHER values = BIGGER caves.
        int density = this.rand.nextInt(this.rand.nextInt(this.rand.nextInt(15) + 1) + 1);

then I get a healthy number of caves, although it does somewhat affect the look of the plains biomes.
