### ISSUE TITLE
Configure height snow spawning

### ISSUE THREAD

**Issue by qinlit** [Team-RTG/Realistic-Terrain-Generation#1333]
RTG version: RTG-1.7.10-1.1.1.7
How would I change the height/level at which snow starts spawning? I'm looking to disable the snow that spawns in the extreme hills biomes. I'm using biometweaker as well but I haven't found a way to configure it in any of their documentation or github issues section.

**Comment by srs-bsns** [comment]
This can not be changed in 1.7.10 and 1.7.10 is no longer supported.

**Comment by qinlit** [comment]
Thank you
