### ISSUE TITLE
Tfc Support

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#1339]
Don't really know where to put this, so if its in the wrong place sorry
##### Affected Mod Versions:
Tfc

- Forge version: Latest

Just asking if there can/will be any support for Tfc

**Comment by srs-bsns** [comment]
RTG and TFC both use a custom chunk generator and there can only be one. This is an impossibility.

**Comment by MagmaSlime123** [comment]
> RTG and TFC both use a custom chunk generator and there can only be one. This is an impossibility.

Override the TFC generation with RTG's. If this isn't active then why have it.

**Comment by srs-bsns** [comment]
You obviously have no understanding of how chunk generation works in Minecraft. An impossibility is an impossibility.

And please don't necropost in old issues because the issue you opened was closed.
