### ISSUE TITLE
Add support for the Lost Cities mod

### ISSUE THREAD

**Issue by MCUmbrella** [Team-RTG/Realistic-Terrain-Generation#1340]
**Issue Description:**
  This is also a terrain generator mod that randomly generates cities in the world.
  It has APIs compatible with other terrain generators, but I think it may be difficult for one terrain generator to be compatible with another terrain generator.

**Extra Information:**
  The Lost Cities' source code: https://github.com/McJtyMods/LostCities

**Comment by srs-bsns** [comment]
The only way to make this work on the RTG side is very hacky and undesireable and so we won't be supporting Lost Cities in RTG worlds. Lost Cities should still work properly in other dimensions, provided that the dimension isn't set to use the RTG chunk generator.
