### ISSUE TITLE
1.12.2 - Village in Deep Ocean

### ISSUE THREAD

**Issue by thisischrys** [Team-RTG/Realistic-Terrain-Generation#1343]
I saw #934 and that it was to blame on an old Java Version: I am using Java 1.8.0_231

##### Affected Mod Versions:

- Forge version: 14.23.5.2847
- RTG version: 6.1.0.0-snapshot.1

I am also using the following mods that interact with RTG:

- AbyssalCraft 1.12.2-1.9.15
- Auxiliary Biomes 1.0.0
- Better Agriculture 1.2.3
- Biomes O' Plenty 7.0.1
- BuildCraft 7.99.24.4
- Plants 1.12.2-2.10.7
- Redwoods 1.2.2
- Thaumcraft 6.1.BETA26
- Traverse 1.12.2-1.6.0-69 (Traverse: Legacy Continued)

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Seed: ChriSandraCraft
2. Village Location: x: 1222 z:912
3. Screenshot: https://i.imgur.com/FVDNBcP.jpg

**Comment by irongrid** [comment]
I am also having this issue. 
Affected Mod Versions:
* Forge: 14.23.5.2847
* RTG: 6.1.0.0-snapshot.1

I'm using mods that interact with RTG too. 

Biomes O' Plenty 7.0.1
BuildCraft 7.99.24.4
Plants 1.12.2-2.10.7
Streams 1.12-0.4.7
Geographicraft 1.12.2-0.8.9.4

Seed:
1: Seed: -153256623
2: Village location: In the screenshot
3: Screenshot: https://media.discordapp.net/attachments/648622127003467816/664941985785970708/unknown.png

**Comment by ghost** [comment]
Fix the Issue in Geographicraft.cfg Line 571

<img width="228" alt="Annotation 2020-01-09 144231" src="https://user-images.githubusercontent.com/59351590/72110958-4cc7f700-32ee-11ea-87d3-ad5f7cdab046.png">

**Comment by irongrid** [comment]
> Fix the Issue in Geographicraft.cfg Line 571
> 
> <img alt="Annotation 2020-01-09 144231" width="228" src="https://user-images.githubusercontent.com/59351590/72110958-4cc7f700-32ee-11ea-87d3-ad5f7cdab046.png">

But it's already on false and keeps generating? 
![image](https://user-images.githubusercontent.com/50276754/72142167-61f76100-3394-11ea-8103-b84714bf6fed.png)

**Comment by lex1975** [comment]
> 
> 
> Fix the Issue in Geographicraft.cfg Line 571
> 
> <img alt="Annotation 2020-01-09 144231" width="228" src="https://user-images.githubusercontent.com/59351590/72110958-4cc7f700-32ee-11ea-87d3-ad5f7cdab046.png">

I confirm this is disabled (false) by default.

**Comment by srs-bsns** [comment]
RTG uses the vanilla village generator which does not generate villages on oceans. The only outstanding issue with villages in RTG involves rivers, because the generator doesn't know where RTG rivers are.

This can only be caused by another mod that changes how villages are generated.
