### ISSUE TITLE
Magic Kingdoms and Far from home support

### ISSUE THREAD

**Issue by Matthysse** [Team-RTG/Realistic-Terrain-Generation#1346]
- Forge version: 1.12.2 - 14.23.5.2847
- RTG version: 6.1.0 (mc1.12.2)

 Issue Description:
Could you add a Magic Kindoms support (a mod that adds a lot of stuff, including new biomes) and a support for the mod Far from home which adds beautiful biomes.

**Comment by srs-bsns** [comment]
**Far From Home** does not actually add biomes, nor is it a terrain generator even though it claims to be. It is a collection of scripts for OpenTerrainGenerator which makes it absolutely incompatible with RTG.

Support for **Magic Kindoms** may happen in the future, but there are other things that need to be done first.

**Comment by Otep123** [comment]
Hopefully the mod support may happen soon, i love both RTG and MK lol

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/pull/1370#issuecomment-1119683669
