### ISSUE TITLE
fix en_US.lang RTG-1.12.2-6.1.0.0-snapshot.1

### ISSUE THREAD

**Issue by lex1975** [Team-RTG/Realistic-Terrain-Generation#1347]
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1.jar

##### Issue Description:
some lines are not localized in en_US.lang :

gui.createWorld.customize.setting.seaLevel=Sea Level
gui.createWorld.customize.setting.riverSizeMult=Size Multiplier

I tested my edits in the game.

**Comment by srs-bsns** [comment]
Options with unlocalized strings are being removed.
