### ISSUE TITLE
Bug start-up crash

### ISSUE THREAD

**Issue by OmicronGuy** [Team-RTG/Realistic-Terrain-Generation#1350]
##### Affected Mod Versions:

- Forge version: forge-1.12.2-14.23.5.2838.jar (universal installer for server
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1.jar

Other mods:
- BetterDiving-1.12.2-1.4.14
- Chisel-MC1.12.2-0.2.1.35
- CoralReef-2.5-1.12.2
- CTM-MC1.12.2-1.0.1.30
- CustomMobSpawner-3.11.5
- DrZharks MoCreatures Mod-12.0.5
- Ecnanos'+More+Armor++Tools+Mod+[1.12.2]+{1.3.2}
- levelup2-1.2.4
- Mantle-1.12-1.3.3.55
- MineTraps-1.12.2-(v.1.0.4)
- Rex's-Additional-Structures-1.12.x-(v.2.3.1)
- TConstruct-1.12.2-2.10.1.87
- TinkerToolLeveling-1.12.2-1.1.0
- Trapcraft-1.12-v2.4.3a-universal
- u_team_core-1.12.2-2.2.5.147
- useful_backpacks-1.12.2-1.5.3.59

##### Issue Description:

https://pastebin.com/FMKMtzTp

##### Steps to reproduce the issue: (If it's easily reproducible.)

Not sure if it's easy to reproduce, It's happend when launching my modded server

##### Extra Information:
https://pastebin.com/BzvLbHp9

**Comment by srs-bsns** [comment]
[20:23:58] [Server thread/WARN] [FML]: Zip file RTG-1.12.2-6.1.0.0-snapshot.1.jar failed to read properly, it will be ignored

You probably have a corrupt jar. Redownload the mod from: https://www.curseforge.com/minecraft/mc-mods/realistic-terrain-generation/download/2782568
