### ISSUE TITLE
Memory Leak RTG

### ISSUE THREAD

**Issue by enterprise12nx** [Team-RTG/Realistic-Terrain-Generation#1351]
##### Affected Mod Versions: The modpack is Industrial Age The Turning by enterprise12 on twitch for the modlist
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 14.23.5.2838
- RTG version: RTG-1.12.2-6.1.0.0-snapshot.1

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

In a large modpack i created me and many users reported a memory leak, ram usage continues to climb slowly no matter how much or little is provided until minecraft freezes often

Removing rtg even in a default world type solved this issue, im aware it is an alpha snapshot version.
Looking through the latest.log i have not seen anything related to RTG in the logs, is there anything i can provide to assist with this issue?

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Use RTG?
2.
3.

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by srs-bsns** [comment]
There is no memory leak in RTG, there is only poor memory management in 1.12 without proper JVM settings, and those are highly dynamic based on loaded mods and available server resources.
It is widely known that large mods packs require a server to be restarted on a regular basis to be able to free up memory that a running JVM is unable to.

**Comment by enterprise12nx** [comment]
this happens even in singleplayer, i have a massive player base doing testing as this was a fairly large modpack in 1.7 i maintained for several years and am bringing back for 1.12.2

While you can only believe me by word, whenever i get crashes or errors, i usually solve them myself by looking through the latest.log
I went through removing tons of mods to try to isolate this problem, removing rtg was the only mod that fixed our "memory leak" problem, using F3 to watch the ram usage, with this mod ram continues to climb in usage, even while standing still, whether its and rtg or non rtg world, in single player or multiplayer.
the memory leak only happens client side, not server side.  Removing this mod fixes the issue on the client.

We are using Surge, Vanillafix, Sledgehammer, foamfix, betterfps all together, to improve performance, which helps ram usage as well

**Comment by Robijnvogel** [comment]
Since RTG is completely server-sided and does not even need to be installed on the client when playing on a standalone server, I doubt that it would ever have a direct impact on client-sided RAM usage, expecially when the world type is not even being used.

However I could see how rendering the higher trees that were generated by RTG's server-sided processes could take a little extra RAM.

Have you tried running VanillaFix' profiler to see what takes up all of this RAM exactly?

**Comment by enterprise12nx** [comment]
no how do you run the vanillafix profiler?

**Comment by enterprise12nx** [comment]
> Since RTG is completely server-sided and does not even need to be installed on the client when playing on a standalone server, I doubt that it would ever have a direct impact on client-sided RAM usage, expecially when the world type is not even being used.
> 
> However I could see how rendering the higher trees that were generated by RTG's server-sided processes could take a little extra RAM.
> 
> Have you tried running VanillaFix' profiler to see what takes up all of this RAM exactly?

no how do you run the vanillafix profiler?

**Comment by srs-bsns** [comment]
This issue tracker is for actual issues with RTG, not for tech support, or tracking issues that are unsubstantiated. Please take this discussion elsewhere, such as Discord.

**Comment by Robijnvogel** [comment]
> no how do you run the vanillafix profiler?

Shift + F3 as it says on the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/vanillafix) .

For further questions I would indeed like to refer you to the [Discord server/channel](https://discordapp.com/invite/Z2EsuxJ) at least until you find out more about RTG's (non-)involvement in these performance issues. ;)
