### ISSUE TITLE
Support for NetherEx 

### ISSUE THREAD

**Issue by SemperX** [Team-RTG/Realistic-Terrain-Generation#1352]
- Forge version: forge - Minecraft Forge - 14.23.5.2847
- RTG version: rtg - Realistic Terrain Generation - 6.1.0.0-snapshot.1

##### Issue Description:
Please provide support for NetherEx. 
https://www.curseforge.com/minecraft/mc-mods/netherex

I do not have other terrain mods installed nor do I have BOP installed.
[RTG]: ||  ID | Biome Class                    | Registry Name
[RTG]: ||  73 | BiomeFungiForest          | netherex:fungi_forest 
[RTG]: ||  74 | BiomeTorridWasteland   | netherex:torrid_wasteland
[RTG]: ||  75 | BiomeArcticAbyss          | netherex:arctic_abyss

**Comment by srs-bsns** [comment]
These are Nether biomes. RTG has never supported The Nether or The End, so supporting these biomes is pointless.
