### ISSUE TITLE
Support for Traverse and Ice and Fire

### ISSUE THREAD

**Issue by SemperX** [Team-RTG/Realistic-Terrain-Generation#1353]
- Forge version: forge - Minecraft Forge - 14.23.5.2847
- RTG version: rtg - Realistic Terrain Generation - 6.1.0.0-snapshot.1
- Traverse - 1.6.0
- Ice and Fire - 1.8.4

##### Issue Description:
Please provide support for Traverse and Ice and Fire 
https://www.curseforge.com/minecraft/mc-mods/traverse-legacy-continued
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons

The newer versions of Traverse have 22 biomes included.  The one below is the only one I see in my modpack

I do not have other terrain mods installed nor do I have BOP installed.
[RTG]: ||  ID | Biome Class                      | Registry Name
[RTG]: ||  65 | BiomeCanyon                   | traverse:canyon
[RTG]: ||  66 | BiomeCragCliffs                | traverse:crag_cliffs
[RTG]: ||  71 | BiomeGlacier                    | iceandfire:glacier

**Comment by srs-bsns** [comment]
You are using the wrong release of Traverse. You should be using: https://www.curseforge.com/minecraft/mc-mods/traverse-legacy-continued
Ice and Fire support has already been ported from RTG 1.10 in dev, but isn't in the current snapshot.

**Comment by SemperX** [comment]
Traverse-1.12.2-1.6.0-69 is the version I am using as you can see I linked to the same mod in my original question.

**Comment by SemperX** [comment]
[RTG]: || 65 | BiomeCanyon | traverse:canyon
[RTG]: || 66 | BiomeCragCliffs | traverse:crag_cliffs

are still not supported by current snapshot of RTG
