### ISSUE TITLE
Thaumcraft Crash

### ISSUE THREAD

**Issue by gmnovakrc** [Team-RTG/Realistic-Terrain-Generation#1359]
Yes I'm aware there's a lot of mods.
On a server, player (x) walked into certain area then crash occurred. Other players were able to log back into world after relaunching server. Player (x) joins, then server immediately crashes, location related I'm guessing?

Any help is greatly appreciated.

[crash-2021-01-02_22.55.23-server.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/5761181/crash-2021-01-02_22.55.23-server.txt)

**Comment by srs-bsns** [comment]
1. 1.7.10 hasn't been supported in literally years.
2. This is not an RTG issue.
