### ISSUE TITLE
Mushroom biomes not generating as islands

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#136]
Mushroom Island and Mushroom Island Shore generate 'inland'. This is probably because they're being added via the 'Support' approach.

**Comment by Ezoteric** [comment]
This has been the problem since day one, its the same problem why the volcano's are screwed up :(

**Comment by Ezoteric** [comment]
BTw do you have any vanilla island ?
Cause MC makes then as layer not as biome :O

**Comment by whichonespink44** [comment]
Just looking at this now... the only 'island' code from RWG is the Tropical Island and Tundra Island, so I'm going to see if I can port those across as vanilla biomes somehow.

**Comment by Ezoteric** [comment]
what i want to know is, can we force biomes to only connect to a specific biome so we can "fix" tropical islands :p

Cause tropical islands also makes a beach which can be enormous :O and the fact it can blend in all biomes which screws the volcano :(

If you manage to get vanilla islands to work maybe we can port the volcano on that :P

**Comment by whichonespink44** [comment]
I'm pretty sure that's what 'rivers' are supposed to do (baseRiverWet, BaseRiverCold, etc), which is to serve as links between biomes, but I'm not sure what logic is being used. I need to do some proper testing to find out.

If that IS what rivers are used for, then what I'd like to try to do is... add multiple rivers per vanilla biome. If Forests, for example, could be associated with both baseRiverWet & baseRiverTemperate, then when choosing a biome to transition to, the game would have to connect it to a biome that has at least one of those two rivers also associated with it. That would prevent what's currently happening in some cases, where it transitions from a hot desert into a cold taiga.

**Comment by Ezoteric** [comment]
If that was the how it works its not working because that way you shouldnt have multiple biomes in 1 chunk inland (as in not at a river)

The logic i see is perfect, desert -> river -> plains for example which creates a perfect biome transition right :)

But thats just what i think

**Comment by whichonespink44** [comment]
Yep, those are exactly the kinds of transitions I'd like to see too.

I've just been testing a few things, and I think the latest commit (6e886e1) might have 'fixed' Mushroom Islands.

I only found one Mushroom Island so far, but it was in the middle of an ocean!! :) Not sure if I just got lucky though, so I'm still flying around to make sure.

In the meantime, if you want to help test, just grab the latest version and let me know if you find any that are still spawning inland.

**Comment by Ezoteric** [comment]
yeah sure, i can generate maps from 100 big while playing LoL :D

**Comment by Ezoteric** [comment]
so far no luck in finding one, also i dont see any temples anymore :O even tho nothing changed...

**Comment by whichonespink44** [comment]
I just found another one, but it was inland in the middle of a jungle biome  :(

I wish I knew how the biomes were being chosen behind the scenes... like, how does the mod tell the game which biome it should generate next? Or, how does the game know which biome to generate?I've looked though the ChunkGenerator and ChunkManager and backtraced just about everything, but I'm struggling to see how the next biome actually gets chosen. Maybe I need to look deeper into the Minecraft code to find it?

**Comment by Ezoteric** [comment]
lol i had mushroom switched off in config i found out as that isnt realistic to me :P hahaha

Anyway you said something about you cant turn off RWG biomes ?
in chunkmanager, just put // infront of all cold hot snow biomes at start and leave the rest on :P
I now didnt saw rwg biomes :P but my jungle was HUGE lol and also stone beach is missing from config that biome is also very lame.

**Comment by Ezoteric** [comment]
About how it generated i dunno exactly but it should be in those 2 files.
I think at the part when all the hot cold snow wetlength is. but hey i dont know shit about java :P

**Comment by whichonespink44** [comment]
@Ezoteric I think I've managed to force Mushroom Islands to generate as islands. If you get some spare time, would you mind generating a couple maps to see if it works all the time?

Just grab the `issue/136/mushroom-islands` branch and do your thang (i.e. tell me that it doesn't work :D haha ). Oh, and you'll need to disable the Mushroom Island Shore biome in the configs when doing your testing, but try to leave most of the other ones enabled so we can get a true test.

**Comment by whichonespink44** [comment]
Fixed in 0.5
