### ISSUE TITLE
JEI and RTG

### ISSUE THREAD

**Issue by dazadazu** [Team-RTG/Realistic-Terrain-Generation#1360]
How do I use RTG but also keep the mods like abyssalcraft and what not? When I have the mod JustEnoughIds It says RTG is the problem and when I remove JEI it says abbysalcraft is the problem which I assumed is biome ID.

**Comment by MoeBoy76** [comment]
JEIDs is the problem, Minecraft doesn't support more that 256 biomes in 1.12.2 and RTG expects this behaviour as well
