### ISSUE TITLE
Gaps in generation

### ISSUE THREAD

**Issue by Keaft** [Team-RTG/Realistic-Terrain-Generation#1365]
##### Affected Mod Versions:
- Forge version: 14.23.5.2855
- RTG version: 1.12.2-6.1.0.0-snapshot.1
- Climate Control/Geographicraft 1.12-0.8.9b
- Worley's Caves 1.12.2-1.5.2

##### Issue Description:
There are 1 block high air gaps in the terrain in many places. It seems most prevalent where there is biome blending and connecting to the caves generated by Worley's Caves. I'm unclear if it's the combination of the mods contained in the profile below. My guess would be Worley's Caves, RTG, and Biomes O' Plenty.

Edit: I can confirm that using RTG, Geographicraft, Biomes O' Plenty, and Worley's Caves causes the air gap.
Edit 2: RTG, Geographicraft, and Worley's Caves are all that's necessary to cause this issue.
Edit 3: Changing Worley's Caves to generate under y63 does in fact keep the air gaps, but that means no surface caves exist.

![image](https://user-images.githubusercontent.com/68153/124366526-b2f4b800-dc0d-11eb-863f-6adb1420bd1d.png)

![image](https://user-images.githubusercontent.com/68153/124366541-cc95ff80-dc0d-11eb-9900-5779bed0f392.png)

##### Steps to reproduce the issue:

1. Install mods listed above.
2. Generate a world and explore.

**Comment by juraj-hrivnak** [comment]
This is not an issue with RTG.
This is how some Worley Caves entrances can look like.
