### ISSUE TITLE
Compat for Ice and Fire

### ISSUE THREAD

**Issue by doarlock** [Team-RTG/Realistic-Terrain-Generation#1366]
##### Affected Mod Versions:
Ice and Fire, last version

- Forge version: Last Version for 1.12.2
- RTG version: Last Version for 1.12.2

##### Issue Description:
Can add support for the Gorgon temple from the Ice and Fire mod?

**Comment by MagmaSlime123** [comment]
The Temples gen. just fine, but they gen. slightly weirdly.
Mod's been dead anyway.
