### ISSUE TITLE
support Sakura and ChinjufuMod

### ISSUE THREAD

**Issue by joe-vettek** [Team-RTG/Realistic-Terrain-Generation#1367]
I really like the terrain in your module, especially rivers and plains. Can you add support for these two classic Japanese-style modules?If you did it, I think many players will thank you, and I have seen a lot of regrets about it on some related websites.

**Comment by KisaragiEffective** [comment]
+1

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/pull/1370#issuecomment-1119683669
