### ISSUE TITLE
Mod does not work on server, but works fine on client.

### ISSUE THREAD

**Issue by JunePrimavera** [Team-RTG/Realistic-Terrain-Generation#1369]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.12.2 (14.23.5.2855)
- RTG version: 1.12.2 (6.1.0.0 Snapshot)

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

When using it on a server, it does not do anything, even if the version is correct.

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Download the forge mod
2. Put it into your server mods folder
3. Add server-type=RTG into the server.properties file
4. Load server

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

The mod works fine, but only on client, not on server.

**Comment by srs-bsns** [comment]
It's not `server-type=RTG` it's `level-type=RTG`.
Be sure you delete any world save directory that may exist from previous server starts so that the world will start fresh.
