### ISSUE TITLE
[1.12.2] feature request: re-adding flat-bedrock generation

### ISSUE THREAD

**Issue by KisaragiEffective** [Team-RTG/Realistic-Terrain-Generation#1371]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

- Forge version: 1.12.2-forge-14.23.5.2859
- RTG version: 1.12.2-6.1.0.0-snapshot.1
- Biomes O' Plenty version: 1.12.2-7.0.1.2445
- GeographiCraft version: 1.12-0.8.9b

##### Issue Description:
I would like to make bedrock layer flat. I use both RTG and BOP, so GeographiCraft is also installed.
I know there was support for #245, but it seems that was removed in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/646f3aa493c4b1a1634a34a14a48738dfdc80e71.
I hope you support that again.

##### Steps to reproduce the issue: (If it's easily reproducible.)
N/A

##### Extra Information:
- crash log: N/A
- client log: N/A

**Comment by srs-bsns** [comment]
For a client, on the first page of the `Customize World Screen` you can set the level of `Bedrock Layers`.
For a server you can add `bedrockLayers:#` where `#` is a number between `1-10`.
There is no longer a way to do this from the config as the bedrock layer setting is world-specific.

**Comment by KisaragiEffective** [comment]
Thank you for quick answer. I'd like to configure it on a server, so where can I do it?

**Comment by srs-bsns** [comment]
In the `server.properties` file: `generator-settings={bedrockLayers:1}`

**Comment by KisaragiEffective** [comment]
Thank you very much for your help, much appreciated :)
