### ISSUE TITLE
How about let it run in 1.16.5 Fabric?

### ISSUE THREAD

**Issue by 982074664** [Team-RTG/Realistic-Terrain-Generation#1372]
How about let it run in 1.16.5 Fabric?
High version minecraft need it!

**Comment by srs-bsns** [comment]
No. 
Fabric... never.

From our pinned Discord message addressing this qurestion:
> srs_bsns — 28/07/2018
With Minecraft 1.13 having now been released, I thought I would elucidate a bit on the state of RTG before we get too many questions about updating RTG to 1.13.
The short answer is, a port of the current mod is unlikely to happen, and there are several reasons for this:
> 1. Chunk generation has been completely reworked in Minecraft in 1.13, which will require a complete rewrite of RTG's chunk generation system.
> 2. Forge is being rewritten for 1.13, and therefore every way in which RTG interfaces with Forge will have to be rewritten.
> 3. RTG's current codebase is mostly based on RTG for 1.7, as in there is still a lot of code that has existed since the first 1.7.10 releases and that code is highly antiquated and needs to be rewritten, and
> 4. A lot of the current code still has bugs in it, or does things in improper ways, and although we hope to get most of it sorted out for 1.12, we will, more-or-less, be using stop-gap measures in some places due to the complexity of the code. (Fixing some parts of the chunk generation process would pretty much require rewriting the whole thing, because fixing one thing breaks 3 others, and that's not something we want to do for 1.12.)
> 5. The complexities of RTG's chunk generation has pretty much no documentation, so porting that code is totally futile compared to just rewriting it from scratch.
