### ISSUE TITLE
Aspects of terrain generate more blocky at high distances due to float usage

### ISSUE THREAD

**Issue by muzikbike** [Team-RTG/Realistic-Terrain-Generation#1373]
##### Affected Mod Versions:

- Forge version: 14.23.5.2859
- RTG version: 6.1.0.0-snapshot.1

##### Issue Description:
32-bit floats appear to be used for controlling some aspects of world generation. This results in blocky artifacts that can be seen in these features if we travel sufficiently high distances from the origin of the world.

In the following two screenshots, the area to the left is before 16,777,216 blocks, and the area to the right is after it:
![2023-04-13_19 43 43](https://user-images.githubusercontent.com/52297970/231854560-9ee59f52-0b0b-4b67-9984-8d45844c256d.png)
![2023-04-13_19 43 48](https://user-images.githubusercontent.com/52297970/231854565-fd5e9c8f-8779-491b-817c-6d0cd8a4567f.png)

Here's a typical ocean floor after 16,777,216 blocks - note the weird horizontal stripes:
![2023-04-13_19 44 23](https://user-images.githubusercontent.com/52297970/231854716-d3846a11-274f-4088-8066-9bafd99314dd.png)

Surface terrain and the blocks which are chosen to be used for the surface are affected to the same extent:
![2023-04-13_19 40 15](https://user-images.githubusercontent.com/52297970/231854878-9ecdd3b0-a7be-4130-8cd6-3f7e697160e2.png)

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. Create a world, preferably in Creative
2. Teleport 16,777,216 blocks or more from the origin
3. Closely inspect the terrain

**Comment by muzikbike** [comment]
We can take this to the extreme by using FarLandsMod and teleporting out farther than the usual vanilla limit of 30 million to really see these effects in action. Here's the ocean floor after about 2 billion blocks:
![2023-04-13_19 39 16](https://user-images.githubusercontent.com/52297970/231855341-7ba733cd-4f3b-429e-b67b-e36337a9c887.png)

**Comment by srs-bsns** [comment]
This game engine wasn't really designed for reaching the extremities of Java primitive values. Just stay within acceptable bounds. :)
