### ISSUE TITLE
Is there a way to disable RTG handling a particular biome?

### ISSUE THREAD

**Issue by darchitectlp** [Team-RTG/Realistic-Terrain-Generation#1374]
Forge: forge-14.23.5.2859
RTG: RTG-1.12.2-6.1.0.0-snapshot.1

Is there a way to turn RTG's handling of a biome off? Like if I want BOP's Crag biome to generate in the normal BOP way, is there a setting that allows that? Or the Marsh biome from Auxiliary Biomes?

**Comment by srs-bsns** [comment]
Terrain is generated globally from a single chunk generator, not per biome, so unfortunately it is impossible to have selected biomes generate in a vanilla sense.
