### ISSUE TITLE
Crash when creating a world.

### ISSUE THREAD

**Issue by KempeR0744** [Team-RTG/Realistic-Terrain-Generation#1377]
##### Affected Mod Versions:
(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

List of mods that can affect world generation: Biomes o plenty, RTG, galactic craft, extra planets, nether lucius.
- Forge version: last, for minecraft 1.7.10 - 10.13.4.1614
- RTG version: RTG-1.7.10-1.1.1.7

##### Issue Description:
(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
no, i have log file: 
[crash-2024-06-11_15.43.21-server.txt](https://github.com/user-attachments/files/15788170/crash-2024-06-11_15.43.21-server.txt)

##### Steps to reproduce the issue: (If it's easily reproducible.)
I'll start by saying that after I enable the RTG mod, in the Tlauncher settings, I start minecraft, create a world with the generation type: “Realistic” and click create world. After the generation of the world starts, after a few seconds, Minecraft “crashes”.
p.s I'll tell you right away that mods and my worlds don't conflict after changing id biomes. i edited them all.

##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by srs-bsns** [comment]
1.7.10 hasn't been supported in like 8 years.
No support will be given for the use of any launcher other than the vanilla launcher.

**Comment by KempeR0744** [comment]
> 1.7.10 hasn't been supported in like 8 years.
No support will be given for the use of any launcher other than the vanilla launcher.

but that doesn't change the fact that the mod conflicts when i create a world using the “realistic” type.

**Comment by srs-bsns** [comment]
We don't support 1.7.10 anymore. At all.
