### ISSUE TITLE
very poor chunk generation performance

### ISSUE THREAD

**Issue by CrazyAmphibian** [Team-RTG/Realistic-Terrain-Generation#1378]
##### Affected Mod Versions:
- Forge version: 10.13.4.1614
- RTG version: 1.1.1.7
- Minecraft version: 1.7.10

##### Issue Description:
unplayably bad stuttering when generating new chunks
![2024-07-30_03 19 35_2](https://github.com/user-attachments/assets/169ce741-f6e0-465e-82df-8eebee0263e7)

```
03:19:38.198
net.minecraft.client.multiplayer.ChunkProviderClient
Client thread
Warning: Clientside chunk ticking took 459 ms
03:19:38.771
net.minecraft.client.multiplayer.ChunkProviderClient
Client thread
Warning: Clientside chunk ticking took 569 ms
03:19:39.325
net.minecraft.client.multiplayer.ChunkProviderClient
Client thread
Warning: Clientside chunk ticking took 552 ms
03:19:39.747
net.minecraft.client.multiplayer.ChunkProviderClient
Client thread
Warning: Clientside chunk ticking took 419 ms
03:19:43.158
net.minecraft.client.multiplayer.ChunkProviderClient
Client thread
Warning: Clientside chunk ticking took 496 ms
```

##### Steps to reproduce the issue: (If it's easily reproducible.)

1. install the mod
2. make a world with the new generation
3. load in the world and start moving around

##### Extra Information:
tested on 3 newly generated worlds. the issue occurs on all 3. some biomes seem to be far worse than others (extreme hills seems to be the biggest offender, alongside forests.)
this is the only installed.
JVM args: `-Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

**Comment by srs-bsns** [comment]
The 1.7.10 version of this mod has been retired for years.
