### ISSUE TITLE
add a notice of deprication for old versions

### ISSUE THREAD

**Issue by CrazyAmphibian** [Team-RTG/Realistic-Terrain-Generation#1379]
##### Issue Description:
the older versions of the mod are not being maintained, however there is no information which suggests this, both on the readme (which suggests the opposite), and on the curseforge page.

**Comment by srs-bsns** [comment]
It is essentially infered by the fact that there hasn't been a commit or release for 1.7.10 in about 7 years.
No SANE person is working on such old versions of Minecraft anymore.
Please stop opening issues about this.

https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v1.7.10-1.1.1.6
> This is the FINAL FINAL FINAL release of RTG for Minecraft 1.7.10.

(Note: there was one release after this, but it was a special request by the developer of GregTech to fix a critical bug, but the above statement still applies.)
