### ISSUE TITLE
Add min temp for cactus decorations to generate

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#148]

**Comment by Ezoteric** [comment]
You doing this? if not i can see if it helps when i use your snow layer fix code :P 

Prolly the same right

**Comment by whichonespink44** [comment]
Looking into the crash at the moment - feel free to use the snow layer fix here to see if it works. If we need to push 0.0.6 back until tomorrow, that's fine. Or we could release 0.0.6 and then release some bug fixes afterwards. Hopefully I can get this crash thing resolved before 0,0,6 though.

**Comment by whichonespink44** [comment]
Cacti decorations are done manually, so this isn't necessary.
