### ISSUE TITLE
A few changes...

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#159]
Isnt this what we all wanted to see ?

![lolz](https://cloud.githubusercontent.com/assets/14137626/9983216/5ff22268-5ff5-11e5-8729-358dca44c6ee.png)

**Comment by Dream-Master** [comment]
Nice

**Comment by Ezoteric** [comment]
I just posted this as a reminder that this is where it should end with.

This map is made by hand but funny is that the desert is almost the same but the hills are lower in the map and that is what I still need to do. The other stuff can be done as well if you have noise knowledge. 

But trust me, this IS possible.

**Comment by whichonespink44** [comment]
That looks great! As long as we can find a vanilla biome for the volcanoes to live, that's fine by me. I think the Ocean & Deep Ocean biomes would be the best candidate for those. Sure, it might look weird in F3 if it says Ocean as the biome, but you're actually walking on a tropical island, but I think it would be fine.

What do you guys think?

**Comment by Ezoteric** [comment]
That's why I would want to name it but islands are layers not biomes so we need to check into that. 
Even tho I would say make a biome as it's better I think

**Comment by Ezoteric** [comment]
Btw in your F3 code, i will fix that also, cause with hotbiome for example it doesnt show the subbiome and with jimmies it did :P

**Comment by Ezoteric** [comment]
Hmmz I think you made the F3 code differently ? 
Cause all I had to do with jimmies was add string name in realistic biome Base and in all the biome files

**Comment by Razorskills** [comment]
Do you think it would be possible in the future if this is implemented to be able to use project red basalt for volcanos if it is available? Then you could disable the PR ones and use realistic ones. Or perhaps the "valcano" rock blocks could be changable depending on what mod someone hsd that adds volcanos. Or they could have 2 different types of volcanos.. An ugly one and a nice one. But then you wouldn't be able to find basalt. Which is why im suggesting the base volcane block could be a bit modular.

**Comment by Ezoteric** [comment]
Yes, that was something i wanted to do for villages as well with chisel 2 :P 

I think its possible but i was thinking of using black stained clay with a rare mix of coal blocks up in there. seems nice and its still vanilla (shame we cant use bedrock for that haha)

**Comment by Razorskills** [comment]
Perhaps a config allowing you to change the black stained clay to a different block would make anyone wanting to do this with any mod happy?

**Comment by Razorskills** [comment]
That is, if you are willing to do that.  (github mobile.. Why can't i edit my previous posts?)

**Comment by Ezoteric** [comment]
set it on desktop mode and you can.

Anyway i think we already gonna make a option for stuff like that, well see ;)

**Comment by whichonespink44** [comment]
_"Anyway i think we already gonna make a option for stuff like that, well see ;)"_

Yeah, if we can get these tropical island/volcanoes added into an existing biome (e.g. Ocean/Deep Ocean), then it should be easy enough to add a config option to choose which blocks are used for the volcano, including support for blocks added by other mods.

**Comment by Ezoteric** [comment]
Yes about the volcano island. I think  a easy way is add a mushroomisland file and edit that to our volcano island. Then we can have both and a option for 1 of the 2 and what blocks used for the volcano. But I think the coolest will be blackstained clay with a few Coalblocks. Bedrock is just silly and obsidian too much of a cheat haha
