### ISSUE TITLE
Ore generation in mountains

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#160]
See http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-5?comment=62

**Comment by Ezoteric** [comment]
Hmmz didn't know they were empty... must be at a specific altitude but that's logic cause most ore doesn't generate higher then 90 orso.

Need to lookup the ore stats first cause I think copper and coal is the only 60+ ore (vanilla ore)

**Comment by whichonespink44** [comment]
Yes, if we're going to implement this one, we need to do it for vanilla ores only, and we should stick to whatever the vanilla rules are for ore gen at certain heights as the default, and then maybe let users customize it to whatever they want. So maybe something like...

[default: 1]
oreIronMinHeight=1
[default: 63]
oreIronMaxHeight=63

What you reckon?

**Comment by Ezoteric** [comment]
Yes something like that and yes keep it locked but I would say coal can be to 255 for all I care

**Comment by whichonespink44** [comment]
More feedback: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-8?comment=127

**Comment by whichonespink44** [comment]
Another requested feature... _"Ore X can only generate in these biomes: "_

**Comment by Ezoteric** [comment]
Btw if you want to support all ore giving mods that's gonna be a Shit load hahaha

**Comment by Ezoteric** [comment]
I think I already changed this for vanilla :p

**Comment by scalda** [comment]
there would need to be a way to disable this option as it could interfere with world gen of cofhcore if you are using cofhcore to handle your ore gen.

**Comment by Ezoteric** [comment]
it will not interfere it will just make it that coal and iron are seen at higher altitudes

**Comment by whichonespink44** [comment]
It should be easy enough to add a disable/enable flag as well, just in case.

**Comment by whichonespink44** [comment]
I've decided not to implement this feature as it falls outside the scope of what RTG is trying to do. If users want this functionality, they will need to find another mod to use alongside RTG (e.g. [Custom Ore Generation](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291128-custom-ore-generation-first-revival)).
