### ISSUE TITLE
End goal

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#161]
To make super realistic landscapes I've checked some hand made maps.
To be able to get this generated we need the following. 

Biome weights option
Biome size option
Noise knowledge or person
Some tweaks in the used blocks

This besides your new code.

**Comment by whichonespink44** [comment]
I think I can biome weights for both vanilla and modded, and I'm pretty sure I can do biome size and block tweaks. As for the noise... I could probably get my head around it, but I'd have to watch a few tutorials and read a few articles, but that could take a lot of time.

It would be great if we could find someone who knows a lot about noise to help out, but... how do we go about doing that? Should we post something in the RTG thread? Or maybe in the 'Mod Development' thread?

**Comment by Ezoteric** [comment]
I found a site where some ppl do some sick Shit with noise for a minecraft look a like game/program I gonna ask some questions there for help
