### ISSUE TITLE
"Continental" maps, with a connected ocean

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#162]
Reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-6?comment=67

Not sure we should worry about this one, but... if it's easy enough to do, we could always add a config option.

**Comment by Ezoteric** [comment]
Yes it's not that hard I guess terrain control has that option also I think

**Comment by whichonespink44** [comment]
Great idea here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic?comment=763

**Comment by whichonespink44** [comment]
Outside the scope of RTG. Please use [Climate Control](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294659-climate-control-change-climate-zones-sizes-ocean) to achieve this functionality.
