### ISSUE TITLE
F3 code

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#164]
Think i gonna add the subbiome names in your F3 code (if this is almost the same as jimmies)

This is only needed for RWG basebiomes tho

So you dont have to dump it in master if you gonna delete those base biomes...

**Comment by whichonespink44** [comment]
Yep, base biomes are gone so no need to add them to the F3 code... but feel free to add anything else in there that you think will be helpful.
