### ISSUE TITLE
Plebs are needed !!!

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#169]
haha this is how you need to look for people ;)

I am generating a map with your version :P

**Comment by whichonespink44** [comment]
What's a pleb? Heh, maybe I'm older than I thought. Let me know how the map turns out!

**Comment by Ezoteric** [comment]
map turned out boring ;) haha

nah its the same, a lack of oceans and i forgot to turn off the river biome :P

Plebs are needed is from ceasar games :P hahaha means workers i think :P

**Comment by whichonespink44** [comment]
If you turn off rivers in the config... do they still generate?

Btw, I'm back on the scene... let me know if you want me to show you around GitHub Desktop and we can do a screenshare.

**Comment by Ezoteric** [comment]
ow i went out to buy some stuff haha, we could do tomorro orso it has no real haste anyway :)

i didnt check, tbh i think my gen layer works cause i got normals deserts also :O totally weird...

I also made a pull request for the stuff i did
