### ISSUE TITLE
Add support for TerraFirmaCraft

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#180]
Reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-6?comment=84

Not sure if this is possible since TFC uses its own world type, but maybe we can figure something out.

**Comment by Ezoteric** [comment]
So does bop and ebxl  haha but I know what you mean. Btw read on mcf that your recode is going better as planned? Good to hear :) can't wait to see it

**Comment by whichonespink44** [comment]
More info:

_"When trying to get Terrafirmacraft to work with this, the game crashes since TFC hates all biomes, basically. So I tried disabling in the RTG config all biomes that TFC doesn't have, this works to an extent, but then RTG crashes with this: http://pastebin.com/hcb6jwCb"_

Reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-10?comment=207

**Comment by whichonespink44** [comment]
More info: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-10?comment=209

**Comment by whichonespink44** [comment]
After looking into this further and consulting with the TFC devs, unfortunately it is not possible to support TFC. See this post for more info: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-15?comment=437
