### ISSUE TITLE
Help Needed?

### ISSUE THREAD

**Issue by afanofjapan** [Team-RTG/Realistic-Terrain-Generation#184]
I have basic Java code knowledge. Is there anyway I can help with this mod?

**Comment by Ezoteric** [comment]
Yes help is welcome but I think Mr pinku needs to make a to do list so we know what has to be done. Haha

**Comment by Ezoteric** [comment]
Btw a fan of Japan 
Do you understand tree making in java ?
This mod has own trees if you understand how that works you could check into the issue "more trees"  cause we want some real looking trees like on the screen shots haha like those real pine  trees aka Christmas tree haha

**Comment by whichonespink44** [comment]
@afanofjapan Yeah, help is definitely welcome. We've got a lot of open issues in the Issue tracker... is there anything in there that you'd be interested in helping out with? If you want to ease your way into things, maybe the Mod Support milestones would be a good place to start? We already have BOP and ExtraBiomesXL pretty much finished, but there's still Enhanced Biomes and Highlands to add in.

**Comment by Ezoteric** [comment]
Btw pink biomegenbase  is pretty much our realistic Base ? So in other words we replace biomegenbase and the biomes? Cause it makes changing to genlayerrtg easier :)

**Comment by whichonespink44** [comment]
@Ezoteric - replied here: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/165#issuecomment-143300791  :wink:

**Comment by afanofjapan** [comment]
I think I am most interested in the biome mod support. I will look at realistic tree options. Is there any specific kind of realistic trees you guys want made? Also I saw you guys were in a Hangouts group? May I join it or no?

**Comment by Ezoteric** [comment]
I have no idea if that was hangouts but we had a chat about showing some stuff about github and eclipse haha

About the trees I'll send you a link to a page on planet MC there is a world save with 90+ trees all marked with a number I'll check and will update that issue with numbers and the link to the world save.

**Comment by Ezoteric** [comment]
Ok i updated topic more trees:
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/157

**Comment by whichonespink44** [comment]
@afanofjapan Feel free to help out with either of those areas (mod support and/or trees). As for the hangout group, we don't have anything setup at the moment, but it's something I'll look into for the future.

**Comment by PaddyDwyer** [comment]
Hi, I'd also like to help out. I'm not sure if it's something you're interested in but I spent the weekend porting RTG to use minecraft 1.8. It's loading but I think there's bugs in the biome generation. 

Anyways with that done, I could do with learning more about any of the systems. I'd love to work on anything you need help with.

**Comment by whichonespink44** [comment]
@PaddyDwyer Wow, well done for porting RTG to 1.8... I hope it wasn't as painful as I imagine it was!

If you're still keen to help out with the 1.7.10 version, the area we're struggling the most with at the moment is incorporating GenLayers into the current biome generation system. Currently, RTG bypasses the whole GenLayer system that MC uses to generate the world, which means that it isn't capable of generating islands in the middle of the ocean (Mushroom Islands, for example, currently generate inland, often surrounded by other land biomes). So if you think you can help out in that regard, that would be fantastic. BOP uses GenLayers... Enhanced Biomes uses GenLayers... but we've so far been able to get them integrated into RTG.

If you feel GenLayers would be biting off more than you can chew, perhaps a good place to jump in would be Mod Support. We currently have support for all BOP, EBXL and TC biomes, but we still need to add support for Highlands and Enhanced Biomes. If you can get your head around the support section, you'll get a good idea for how the biomes are being generated behind the scenes, which might spark some interest in other areas.

There's also a nasty Railcraft crash (#195) I can't seem to figure out if that's more your cup of tea.

Happy for any help at all really at this stage, so just let me know what you're keen on.

**Comment by PaddyDwyer** [comment]
It was a bit painful :) It definitely is buggy at the moment. It's generating cold biomes right beside hot biomes so you have a taiga in the desert. I'm going to fix that first. 

I was having a look at the Mod Support earlier and it looks fairly straight forward. Once I have that noise issue fixed I'll take a look at adding support for the highlands mod.

**Comment by whichonespink44** [comment]
_"Once I have that noise issue fixed I'll take a look at adding support for the highlands mod."_

:+1:
