### ISSUE TITLE
Streams mod: Working but generating some weird bridge things

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#187]
![image](https://cloud.githubusercontent.com/assets/10927161/10115541/2f06aed2-6403-11e5-8daa-00a771cdf3fb.png)

**Comment by whichonespink44** [comment]
_"I'm sure that the 'bridges' are an issue with 'Streams' - I seem to remember something about them being mentioned in that thread."_ - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-6?comment=102

**Comment by whichonespink44** [comment]
The author of Streams (delvr) indeed confirmed that the bridges will be fixed in the next major release: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2346379-streams-real-flowing-rivers?comment=251

**Comment by Ezoteric** [comment]
Ok then all there is left is fix cutting down mountains. Cause that is still poop ;)

**Comment by whichonespink44** [comment]
Apparently that's going to get fixed too, in addition he's also adding underground rivers and lava rivers... let's hope RTG plays nicely with the new version! :)

**Comment by Ezoteric** [comment]
Yeah or just integrate streams ;)
