### ISSUE TITLE
Weird water rectangles caused by plants generating in water

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#188]
![image](https://cloud.githubusercontent.com/assets/10927161/10115586/a824be2a-6404-11e5-83d8-307e4a692372.png)

**Comment by whichonespink44** [comment]
What mod is that plant from? It looks like something from Plant Mega Pack but not sure. Need to find out what mod it's from so we can investigate this issue further.

**Comment by Razorskills** [comment]
that kind of looks like it might be from Better Foliage.. just from a quick glance.. I will have to load it up and check, it just renders client side visuals and no actual plants etc.

http://minecraft.curseforge.com/mc-mods/228529-better-foliage

**Comment by Ezoteric** [comment]
I can confirm it's not better foliage cause I use that and don't have the problem .

Also better foliage doesn't add blocks. It's just a skin added on the blocks. You can also not cut the stuff from foliage it doesn't even show up in wialla

**Comment by whichonespink44** [comment]
I'm thinking either Plant Mega Pack or Biomes O' Plenty... probably the latter actually.

**Comment by Ezoteric** [comment]
Maybe just ask the guy in question?  Or like I said wait for the core :p

**Comment by whichonespink44** [comment]
I'm pretty sure this occurs even when BOP is the only mod installed (without RTG).
