### ISSUE TITLE
Floating trees

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#189]
![image](https://cloud.githubusercontent.com/assets/10927161/10115589/de3157bc-6404-11e5-898d-9b4a6bd9d397.png)

**Comment by whichonespink44** [comment]
_"I get the BOP 'floating trees' as well - usually at the edge of ponds, lakes and rivers - but I have them without RWG/RTG so I think that may be more to do with the way BOP draws the ground."_ - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-6?comment=102

**Comment by whichonespink44** [comment]
I wonder if there's anything RTG can do to help alleviate this problem... we'd probably need to listen for BOP's tree gen event (if it has one), check the blocks underneath the tree, and then if Block == Blocks.air, then fill it with Blocks.dirt (or something similar). Not sure if this is possible though.

Might be worth creating a branch off `master` and playing around.

**Comment by Ezoteric** [comment]
Tbh I think we need to focus on our core from now on and then focus on fixes. I mean we are gonna use a total different generation approach now so it might be fixed using layers or if you fix it it won't work on the new system. But that's my 2 cents ;)

**Comment by Ezoteric** [comment]
This counts for all problems that's related to our generation. I mean fixes like the spruce woods is something else :p

**Comment by whichonespink44** [comment]
_"Tbh I think we need to focus on our core from now on and then focus on fixes."_

Agreed. The new GenLayer stuff will likely resolve most of the crashes/issues that have been reported recently.

**Comment by Ezoteric** [comment]
That I don't know but i think it will yes ;)

**Comment by whichonespink44** [comment]
This is a BOP bug, confirmed with only BOP installed.
