### ISSUE TITLE
Iceberg rows: Weird stripey pattern of random ice

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#190]
![image](https://cloud.githubusercontent.com/assets/10927161/10115596/04a77bce-6405-11e5-96e5-640bf42bde9f.png)

**Comment by Ezoteric** [comment]
is this with or without genlayer ?

**Comment by whichonespink44** [comment]
Without

**Comment by Ezoteric** [comment]
Yeah those things are weird and ugly haha dunno why they are the same and in rows all the time

**Comment by Ezoteric** [comment]
Btw your land also got cut off by a river ?

**Comment by whichonespink44** [comment]
Looks like it... this wasn't from my testing though... someone in the forums posted it, so I just copied here. :)

**Comment by Ezoteric** [comment]
I turned off those ice rows with your temp fix for the snow layers haha
