### ISSUE TITLE
Village modifications

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#192]
This is exactly what i was looking for.
A way to change the village !!!

![2015-09-26_15 47 04](https://cloud.githubusercontent.com/assets/14137626/10117847/fba27e78-6465-11e5-801d-2b0b6555a532.png)

Changed torch and the well :P

**Comment by whichonespink44** [comment]
Sweet! How much work is involved? Do you have to manually place each block?

**Comment by Ezoteric** [comment]
0 cause that well is from eb as well haha I don't know how to convert it I'll show you the 2 files

**Comment by Ezoteric** [comment]
If I can understand how to change it I can replace the whole village and make specific types for biomes that was my plan anyway haha

**Comment by Ezoteric** [comment]
look this is the normal code for the well:
https://gist.github.com/Ezoteric/4ec990ba1ea880e9025d

And this from a schematic
https://gist.github.com/Ezoteric/526a0f999b69a684d4e7

now i thinnk we only need to use the blocks part and not need the rest but its still a bit different. I know its fixable but i need to know what numbers need to go where.. get it?

**Comment by whichonespink44** [comment]
I think I get it. As for which numbers go where, I think you'd have to look at setBlock() definition and placeBlockAtCurrentPosition() definition to see which parameters match up (x, y, z, etc)

**Comment by Ezoteric** [comment]
Yeah actually  what I tried worked I'll show a screenshot cause some placements are wrong haha

**Comment by Ezoteric** [comment]
stairs are wrong and button placements also :P

![2015-09-26_19 52 30](https://cloud.githubusercontent.com/assets/14137626/10118965/2539fca8-6488-11e5-80ba-a20c43e4a4ec.png)

**Comment by Ezoteric** [comment]
but for a test its quite good.
now here is what i did:

original:
world.setBlock(x + 1, y + 1, z + 0, Blocks.stone_stairs, 2, 3);
new:
this.placeBlockAtCurrentPosition(p_74875_1_, Blocks.grass, 0, 0, 0, 0, p_74875_3_);
So it misses that 2, 3 :O

**Comment by Ezoteric** [comment]
Btw is it maybe possible to use the original code? cause changing all that is quite some work :P

**Comment by Ezoteric** [comment]
bah need some help with this, doesnt run my file :( haha

**Comment by whichonespink44** [comment]
Not sure village modifications fall within the scope of RTG (although I'm open to hearing ideas), but either way, post your stuff on Gist and I'll take a look. :)

**Comment by Ezoteric** [comment]
Even better I created the addon RTG on my git

**Comment by Ezoteric** [comment]
Also I don't care if you want it as long as I love can dear ;)

**Comment by whichonespink44** [comment]
_"Even better I created the addon RTG on my git"_

Sweet, have you pushed your latest stuff to the fork?

**Comment by Ezoteric** [comment]
yes this is with all my latest shit :P

**Comment by Ezoteric** [comment]
btw its also with genlayers lolz so we need to fix that eventually :P
