### ISSUE TITLE
Railcraft world gen crash

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#195]
_"Getting a crash which looks related to Railcraft worldgen: http://pastebin.com/edYyRRHZ - Was just walking around the map when the server died, seed 246016553525613_"

Reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-8?comment=116

**Comment by Ezoteric** [comment]
lol thats one filled modpack
btw seeds are useless anyway with mods :(

**Comment by whichonespink44** [comment]
Yeah, I managed to repeat the crash, and after doing some debugging I think I've narrowed it down to either a problem with the way Railcraft generates its ores under certain circumstances, or a problem with the way RTG is posting events to the ORE_GEN_BUS... and since no one else has reported any similar crashes in the Railcraft community, I can only assume that it's the latter :(

(Incidentally, I'm almost 99% sure that this is what was causing that other crash.)

**Comment by Ezoteric** [comment]
well, i think we need to rewrite chunk manager and provider anyway
then it will deff work :)

**Comment by whichonespink44** [comment]
Heh, yeah, we definitely need to rewrite ChunkProvider... or at least re-factor it to be more readable. Last time I tried to do it, that's how I found out about the ORE_GEN_BUS issue.

**Comment by Ezoteric** [comment]
haha
yeah lets check EBs files for that, he also has noise shit in it so we just have to skip that part and use ours :)

**Comment by scalda** [comment]
I can 2nd this crash with railcraft, hopefully it can be resolved as i like the genarator but don't want rwg due to the biomes with no way to turn them off

**Comment by scalda** [comment]
This is still happening on the latest release you pushed today.

**Comment by whichonespink44** [comment]
@scalda Thanks for the crash report. This is a major issue for us, so we'll do whatever we can to get RTG working with Railcraft.

**Comment by scalda** [comment]
i have narrowed it down to either the firestone or quarried stone as i have them now disabled them and everything is fine

**Comment by Nephatrine** [comment]
Any progress figuring this out? Quarried stone is my favorite building material so I'd rather not have to disable it.

**Comment by whichonespink44** [comment]
The only progress I've made is that I _think_ I might've figured out a way to prevent the crash from happening... that's the good news. The bad news is that it means tweaking all of the modded biomes that RTG supports ni the same way that I've been tweaking the vanilla biomes (which is basically bypassing the base biome's decoration() method and decorating the biome manually through RTG.

I'll do some testing after 0.0.13 is released and all the vanilla biomes are using the new decoration approach to see if the crash still happens.

**Comment by xeronut** [comment]
Using RTG 0.0.12 and Railcraft 9.8.0.0 I am able to generate Quarried Stone deposits without crashes.  Here is a pic:  http://i.imgur.com/RvXBCD8.png

**Comment by whichonespink44** [comment]
After 30 minutes of flying and TPing around with RailCraft 9.8.0.0 and no crashes so far! Can also confirm that Quarried Stone is generating in the Overworld.

Thanks for the heads-up @xeronut - I'll update the OP shortly to inform users that RTG only supports RC 9.8.0.0.

**Comment by Razorskills** [comment]
hmmm.. I am not sure if this is related.. but: https://www.dropbox.com/s/5yaixbuwlrlz26u/crash-2015-10-24_10.29.25-server.txt?dl=0

I set the world type to Realistic, and immediately after loading it gave me that crash.

I came back and tried making a default world and it worked just fine. I am going to test it some more and update my post here with more info. I want to make sure Its Railcraft + RTG and not any of my other mods.

**Comment by whichonespink44** [comment]
That's strange, I tested a handful of worlds with just RTG (0.0.13) and RailCraft (9.8.0.0) and never had a crash. I'd be interested to know what biome you spawned in and what biomes were in the surrounding area.

Seems to be an issue with setting the world's [tick rate](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/ore/BlockWorldLogic.java#L74) to [6000](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/ore/BlockWorldLogic.java#L121), but why it was cause an infinite loop I'm not sure.

Let me know if you have any other problems with that world.

**Comment by Razorskills** [comment]
here is a zipped up copy of the world before any mods removed etc: https://www.dropbox.com/s/qui8xoj6jl3efsb/Realistic-20151024-104344.zip?dl=0

here is a mod list/modpack that im working on. some of the mods I updated to latest version while testing this so its not exactly the same. but instead of hunting down mod names through the config that might be easier.

**Comment by xeronut** [comment]
I'm at a loss for what might be causing this too.. if it helps at all, I have poor ores and the residual heat blocks disabled.  I can't think of anything else I did differently.  Here's a zip of my railcraft config folder:  http://www.mediafire.com/download/3zxbo304tx74s47/railcraft.zip

**Comment by whichonespink44** [comment]
This has also been reported in the [forums](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-13?comment=327), so re-opening this issue to investigate further.

Thanks for all the feedback guys, keep it coming if you think it's useful.

I'll keep you posted if I make any progress.

**Comment by Haggle1996** [comment]
Probably not helpful, but worldgen crash with Railcraft 9.8.0.0 and RTG 0.0.13

http://pastebin.com/bjF5UTWu

**Comment by whichonespink44** [comment]
I need to take a break from biome decoration, so I'll be looking at this tonight.

Can anyone confirm if the crash still happens when the RC world module is disabled?

**Comment by Haggle1996** [comment]
I'm testing this now using AdminCommandsToolbox to pregenerate 10s of thousands of chunks. I'll keep you posted.

**Comment by Haggle1996** [comment]
Generated 50,000 chunks with Railcraft world module turned off ... no errors or crashes.

**Comment by whichonespink44** [comment]
Ok, so I've been debugging this for a couple hours now, but haven't gotten anywhere worth mentioning. The only thing I have is a workaround, which is to disable the World Logic block in the `config\railcraft\blocks.cfg` file. That's the block from the crash report, but I still have no idea why it's crashing. It seems to be getting tripped up when scheduling the World Logic block to do a tick update with a 6000 delay, so... maybe it's too long of a delay? Not long enough? Either way, I'm not sure what I can do about it.

@Haggle1996 Thanks for helping to test. I'd be really interested to know if you can generate that many chunks with just the World Logic block disabled. I flew around for a couple thousand blocks, but I'm worried there might be other potential crashes we haven't discovered yet.

**Comment by Haggle1996** [comment]
Yes, testing now.

**Comment by Haggle1996** [comment]
With just the world logic block disabled, it works fine. 

I noted that with RailCraft's world module turned off, the pack created a 1.5GB log file spamming RotaryCraft/RTG loop messages (but still generated 50k chunks without a crash). With just the World Logic block turned off, the log file was a more happy 4MB after generating 50k chunks.

**Comment by whichonespink44** [comment]
Awesome, thanks @Haggle1996 - I've updated the OP in the forums with the workaround. It's not ideal, but it'll have to do for now until we get more Forge gurus involved in the project.

**Comment by Razorskills** [comment]
Perhaps @CovertJaguar might be able to help. Maybe we could make an issue here: https://github.com/CovertJaguar/Railcraft/issues

and perhaps if he is willing, could point you guys in the right direction to fixing the bug!

**Comment by CovertJaguar** [comment]
Well I don't know how much help I can be, but I can say that BlockWorldLogic is the Saltpeter Regen Bedrock Block.

**Comment by CovertJaguar** [comment]
The crash seems to be on the following line:
```
 world.scheduleBlockUpdate(x, y, z, this, tickRate(world));
```

And it appears to be BlockStaticLiquid causing the call to updateTick() that starts everything.

**Comment by whichonespink44** [comment]
Thanks for pointing me in the right direction @CovertJaguar.

I think I might've fixed this. I've tested a few different worlds and haven't had the crash yet.

Would anyone be up for testing out this snapshot to see if it's actually fixed?

[RTG-1.7.10-0.0.14-snapshot-1471aeb.jar](https://goo.gl/0o9YD2)

(I used fresh, unmodfied configs for both RTG and RailCraft 9.8.0.0)

**Comment by Razorskills** [comment]
well, I loaded it up and used the zip copy of my world that would not load with RTG + Railcraft and it loaded in just fine. So far.. So good! Il report back if there is any bad news. but atm its looking really good!

**Comment by Haggle1996** [comment]
Ran your snapshot through 50,000 chunks and no errors. Generation was about 50% slower than .13 with WorldLogic turned off, but that may be due to random structure generation. I'm not super-concerned about it.

**Comment by whichonespink44** [comment]
@Haggle1996 Thanks for running it through the grinder. I haven't been able to reproduce the crash in my testing either since making the changes to the chunk generator, so I think I'm going to close this one.

Thanks to everyone who contributed to this one... it was definitely a nasty one, but we got there in the end! :)

**Comment by Haggle1996** [comment]
Just FYI, I've run my pregen a few more times and the slowdown appears to solely be related to Recurrent Complex structure generation, and not RTG. Thanks for fixing!

**Comment by whichonespink44** [comment]
:+1:
