### ISSUE TITLE
Ocean and river

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#198]
Ocean still hardly comes and by turning off rivers it still creates river LAND as in almost a biome size 4 full of sand called river :(

**Comment by whichonespink44** [comment]
Hmm, I see a decent amount of oceans when I fly/TP around the world (although I do tend to TP 1,000 blocks at a time :D

As for rivers, yeah, not sure what to do about that. Need to give it some thought.

**Comment by Ezoteric** [comment]
I generate biiiig maps and trust me it's gay :p
