### ISSUE TITLE
surface Savannaplatue file

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#199]
I think this is the one causing the desert to be generated :P

It also has desert as base... when i turned it off it became a the exact same land as the vanilla desert

**Comment by whichonespink44** [comment]
Hmm, that's odd... what's even more bizarre is that the new Desert generates perfectly in a single-biome world. Maybe the two are bleeding into each other too much during generation?

**Comment by Ezoteric** [comment]
Because it's always bordering the sannavapletau

**Comment by Ezoteric** [comment]
That's why I think he's the culprit
