### ISSUE TITLE
BiomeManager.java

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#200]
public static void addFrozenBiome(BiomeGenBase biome, int weight) {
		if(weight < 1) return;
		for(int a = 0; a < weight; a++)
			frozenBiomes.add(biome);
		BiomeManager.addBiome(BiomeType.ICY, new BiomeEntry(biome, weight));		
	}

This either needs to add our climate shit OR the support file you deleted had the types so we could set them to these.

How ever, this is 1 way its preventing using layers :p

**Comment by Ezoteric** [comment]
A much better map finally :P

http://imgur.com/aCvq4Ao

**Comment by whichonespink44** [comment]
Working on BiomeManager stuff now... closing this, see #165 for latest discussion
