### ISSUE TITLE
Highlands Support

### ISSUE THREAD

**Issue by PaddyDwyer** [Team-RTG/Realistic-Terrain-Generation#201]
Hi, I'm taking a look at adding Highlands support.

I feel like this is a really stupid problem to have. How do I start minecraft from eclipse with a mod I'm going to depend on.

I thought i could download the highlands jar and throw it into forge/run/mods but I get an error when I hit the run button.

    cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: highlands.block.BlockHighlandsSapling.func_149676_a(FFFFFF)V
    	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)

No problem running highlands from the launcher of course.

Do you have any pointers on what I should be doing?

**Comment by whichonespink44** [comment]
_"Do you have any pointers on what I should be doing?"_

Unfortunately not - the way I test with other mods is by compiling and then running Minecraft outside the dev environment with the other mods installed.

**Comment by Ezoteric** [comment]
Same here. I don't even know how to run it in eclipse haha :p

**Comment by Ezoteric** [comment]
Anyway I'm off to bed I've done too much today and nothing worked haha but also no errors ;)

**Comment by whichonespink44** [comment]
If you create a `libs` folder in the root of your mod, you can put deobfuscated/dev versions of mods in there, then run `gradlew eclipse` and it loads that mod when you run Minecraft from Eclipse. For example, I created the `libs` folder, then downloaded the dev versions of Code Chicken Core and NEI and dropped them in that folder, then ran `gradlew eclipse` ... now every time I run Minecraft from Eclipse to test RTG, I've got NEI as well.

That's the good news. The bad news is that I couldn't find a dev version of Highlands :(

**Comment by Ezoteric** [comment]
Btw didn't mojang say all mods have to be open source ?

**Comment by Ezoteric** [comment]
And what's the difference between running MC in eclipse or normal?

**Comment by whichonespink44** [comment]
_"And what's the difference between running MC in eclipse or normal?"_

In Eclipse, there's a green [Play] button at the top which launches Minecraft with whatever mod you're currently working on. It's just a quick way to test any changes you've made instead of doing a `gradlew build` and dragging the JAR file to your normal Minecraft mods folder.

**Comment by Ezoteric** [comment]
Which means it's crap as you still need to test it with mods and therefore double work ;) I'll wait 30 sec and just run MC thnx tho ;)

**Comment by PaddyDwyer** [comment]
I know where the source for highlands is. I could always download that and make my own dev version.

**Comment by Ezoteric** [comment]
Then you my friend are helped ;)

**Comment by whichonespink44** [comment]
@PaddyDwyer I tried doing the same but ran into gradle issues. I'm sure it's just my inexperience with gradle, so hopefully you'll have better luck than me.

**Comment by whichonespink44** [comment]
@PaddyDwyer How's it going? I'm planning to re-factor the EBXL stuff tonight, which shouldn't take too long as there aren't many biomes, so... I was thinking of starting Highlands as well, but I don't want to start if you're already working on it. If you haven't had time, no worries.

**Comment by PaddyDwyer** [comment]
I haven't had time so go ahead. Once I'm back able to work on stuff (next week maybe) I'll look for something new to do.

**Comment by whichonespink44** [comment]
:+1:

**Comment by whichonespink44** [comment]
Added in df91175
