### ISSUE TITLE
Kelp forest is Kelpless

### ISSUE THREAD

**Issue by Claycorp** [Team-RTG/Realistic-Terrain-Generation#221]
http://i.imgur.com/6EiGSJq.jpg
I think kelp forests got goofed as that should be ocean not hills. 

Even though it is very pretty it should return underwater perhaps?

EDIT: Seems as if other water biomes are being inverted. http://i.imgur.com/3Th7FXp.jpg That should be a coral reef.... Not CORALless ;)

**Comment by Ezoteric** [comment]
Loool pinky hahaha

**Comment by whichonespink44** [comment]
Thanks for the heads up @Claycorp. Anyone from @Team-RTG/readers wanna take a stab at this one?

**Comment by Ezoteric** [comment]
Yeah I'll fix this

**Comment by Ezoteric** [comment]
I may fix this in a hour orso

**Comment by whichonespink44** [comment]
:+1:

**Comment by Ezoteric** [comment]
Haven't checked it cause I'm not home but this was the code I used for my previous RWG versions

**Comment by Ezoteric** [comment]
So it's an underwater canon but it's cool for kelp forest haha and a lazy fix for coral reef

**Comment by Ezoteric** [comment]
I pushed the fixes pink

**Comment by whichonespink44** [comment]
Fixed in 0e77cbb

https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v0.0.12
