### ISSUE TITLE
Wheres the fields/meadows/flat things?

### ISSUE THREAD

**Issue by Claycorp** [Team-RTG/Realistic-Terrain-Generation#222]
Great mod. Like amazing at generating some really awesome stuff like this canyon http://i.imgur.com/inVk362.jpg

Though i've noticed there is a distinct lack of flat/ish areas. Mountains and hills everywhere but no relatively flat areas!
The most i would ever come across was small areas at the foot of a hill/mountain. Even those aren't really that flat with tons of little pits.
http://i.imgur.com/RyDzCnC.jpg This was the flatest spot i could find (exluding water/swamp like areas)

**Comment by Ezoteric** [comment]
Most terrains are wip :p

**Comment by Claycorp** [comment]
Understandable :p 
I still can't get over how awesome dem canyons are. Looking forward to seeing more flat space through!

**Comment by Ezoteric** [comment]
Yeah me 2 haha and yes canyons are almost perfect but there will be more flats 😉

**Comment by whichonespink44** [comment]
Yeah, as mentioned, RTG is heavily biased towards hilly/mountainous terrain at the moment, but this is something we'll be spending a lot of time on during Beta.

Gonna close this one, but feel free to hop on the forums to discuss further.
