### ISSUE TITLE
BOP - Exception ticking world - Already decorating

### ISSUE THREAD

**Issue by scalda** [Team-RTG/Realistic-Terrain-Generation#228]
Hey guys our server just crashed while exploring please see attached pastebin.

http://pastebin.com/xL0jKD4s

Regards

Scalda

**Comment by whichonespink44** [comment]
Thanks for reporting this. Would you be able to turn on the "Enable Debugging" option in ConfigRTG.cfg, try to repeat the crash, then Dropbox me the zipped fml-client-latest.log? (And don't forget to disable debugging afterwards.)

Also, I noticed that your pack has RailCraft... just in case you weren't aware, RTG is currently incompatible with RailCraft. See #195 for more info.

**Comment by scalda** [comment]
yes i can do that for you and see if i get it again.

and i'm aware that railcraft is incompatible as i was the one who posted abot it being the quarry stone or firestone

**Comment by whichonespink44** [comment]
I haven't tested for this crash, but I'm 99% certain that the work I'm doing on RTG's chunk provider will resolve this. If it doesn't, then manually decorating the BOP biomes should do the trick.

**Comment by whichonespink44** [comment]
Been doing some extensive testing with BOP and 0.0.14 today and haven't had any crashes, so I'm going to close this for now, as I'm pretty sure the latest version has resolved most of these random crashes. Feel free to create a new issue if it's still happening for you.
