### ISSUE TITLE
Desert Temples spawning underground

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#231]
Hey pink, can you code that when it spawns a desert piramid it gives the coordinates ?

Cause i suspect it makes the temples under the mountains. Ive seen a desert temple once spawned into the ground and only 2 blocks of the top stuck out.
So it seems it does the decoration after temples, and if that is true what more ? :P
Plus when that is the case then its a bad thing and may cause more errors related to deco

**Comment by whichonespink44** [comment]
From the Minecraft wiki:

_"Desert temples always spawn with their floor at y=64. This may cause the desert temple to be partially buried."_

This explains the desert temples generating underground, which I was aware of and didn't really think it was a bug, more of an 'extra challenge' to find a desert temple.

However... now that you've mentioned it, I'm also starting to wonder if it has the potential to cause crashes. I'm fairly certain that it doesn't affect RTG's decoration, but it may be causing conflict with other mods' decoration. Maybe it's not an issue that it generates them underground, but maybe there's an issue **when** it generates them. Like, maybe RTG should be doing it earlier or later?

**Comment by Ezoteric** [comment]
Hmmz, i can see if i can set the max height of the flat parts of the desert to 65 :P and see whats gonna happen
