### ISSUE TITLE
Enhancement Please add support for 3 Japaneses mods that add biomes . 

### ISSUE THREAD

**Issue by crunkazcanbe** [Team-RTG/Realistic-Terrain-Generation#234]
I have not tested yet but will soon but there are three mods one called MapleTrees mod here http://forum.minecraftuser.jp/viewtopic.php?t=6984 the other Apple&Milk&tea 2 Here http://minecraft.curseforge.com/projects/applemilktea2 and other SextiarySector 2 here http://forum.minecraftuser.jp/viewtopic.php?t=22369 . Just use Google translate to translate the page ,but I love these mods and even though a lot of westerns don't know much about them there good and fun and I always play with them and there just as good as American / UK made mods . Me and my wife love them . I would love a little support for them . BTW Sextiary Sector has a dependencys that can be found here http://forum.minecraftuser.jp/viewtopic.php?t=17110 . Thank you -Crunk Please Please add support for me and the wife . Thanks again guys .

**Comment by whichonespink44** [comment]
I'm not familiar with any of these mods, but if they add biomes, then I'll see what I can do.

Is there anything else from any of these mods that you would like RTG to support?

**Comment by crunkazcanbe** [comment]
Well the maple trees mod adds just maple trees and other fall looking trees into
the world that spawn in other biomes . I don't know if rtg needs to support that
or not but if you don't mind looking into it that would be cool . All three add
biomes though if my mind serves me right .



Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.4.10&pv=5.1.1&source=email_footer_2] on the Galaxy Note 5 On Wed, Oct 21, 2015 at 1:06 PM, WhichOnesPink < notifications@github.com [notifications@github.com] > wrote:
I'm not familiar with any of these mods, but if they add biomes, then I'll see
what I can do.

Is there anything else from any of these mods that you would like RTG to
support?

—
Reply to this email directly or view it on GitHub
[https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/234#issuecomment-149964496] .[https://github.com/notifications/beacon/AFZoAEPrpG9RKk_m_rHejUvj0Zkt7NLPks5o972ugaJpZM4GTHX-.gif]

**Comment by xeronut** [comment]
Plants from AMT2 and its tree addon have spawned properly in RTG as far back as 0.0.15, if memory serves me right.  I don't use the Maple Tree addon, but I'm going to assume it'd require no more compatibility adjustment than, say, Natura trees (none).  Sextiary Sector 2 will probably need support for its Magical Desert biome.  Here's a link to their wiki, processed through Google Translate (info about biome config is at the bottom of the page, default ID 120) - https://translate.google.com/translate?hl=ja&sl=ja&tl=en&u=http%3A%2F%2Fwww26.atwiki.jp%2Fminecraft%2Fpages%2F1337.html

**Comment by whichonespink44** [comment]
That's incredibly helpful @xeronut - thank you very much! :+1:

**Comment by crunkazcanbe** [comment]
So what is the deal with this so far man ? Do you support SS2 yet ?

**Comment by whichonespink44** [comment]
Not yet - I'm currently working out a better system for mod support, which will hopefully be ready shortly after the 0.5.0 release. But support for SS2 will be one of the first (if not __the__ first) mod that RTG supports using the new system. (Might do Ridiculous Biomes first as it's been on here the longest :smile: )

**Comment by whichonespink44** [comment]
Sextiary Sector 2 no longer adds a Magical Desert biome.
