### ISSUE TITLE
Crash on a New World While Generating New Chunks Flying around .

### ISSUE THREAD

**Issue by crunkazcanbe** [Team-RTG/Realistic-Terrain-Generation#239]
I was Just flying around in a new world in amazement with this mod and EnhancedBiomes together's World Gen . Looks wonderful ,but All of a sudden the chunks stopped Generating ,and I pressed F3+A and it did nothing as it usually starts chunks back generating so I tried F3+S Then and still nothing ,but then MC stopped responding and crashed with this crash log here http://pastebin.com/XmZedaXV

**Comment by whichonespink44** [comment]
Hi Crunk. Thanks for reporting the crash. It looks like you had the EB Fen biome enabled, and unfortunately, that's one of the biomes that isn't currently supported yet by RTG. Take a look at this issue for more details: #218
