### ISSUE TITLE
Will not load without Buildcraft installed

### ISSUE THREAD

**Issue by m0rgs** [Team-RTG/Realistic-Terrain-Generation#244]
Upgraded from 0.12 to 0.13;

> BuildCraft|Core : minimum version required is 7.1.9

Mod causes Minecraft to refuses to load without Buildcraft installed.

I realise the changelog says:

> Updated mod dependencies.
> If you don't have the minimum required version of supported mods, Minecraft will prompt you to update.

...but surely this mod isn't intended to be dependent on BC to load at all?
I don't want BC ;)

I have no configs, I deleted server/config/RTG folder when I upgraded the version.

Downgrading to 0.12 fixes issue.

**Comment by Razorskills** [comment]
weird, i dont have buildcraft and it launched just fine on 0.13 yesterday. What other mods do you have? perhaps one of those is the culprit? or a really weird bug..

**Comment by m0rgs** [comment]
Possibly an interaction between multiple mods, but I have no idea which.

Runs fine with 0.12
Install 0.13, claims to require BC, minecraft will not start
Downgrade to 0.12 runs fine again
No other changes made

Here is a list of mods

> AdvancedMachinesAS-1.7.10.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar
AncientTrees-1.7.10-1.6.2.jar
AOBD-2.7.1.jar
AOBDBB-1.0.4.jar
AppleCore-mc1.7.10-1.1.0.jar
appliedenergistics2-rv2-stable-10.jar
AsieLib-1.7.10-0.4.0.jar
AuraCascade-526.jar
Baubles-1.7.10-1.0.1.10.jar
bdlib-1.8.2.92-mc1.7.10.jar
BetterVillages-0.4(1.7.10).jar
BigReactors-0.4.3A.jar
BluePower-1.7.10-0.2.945-universal.jar
Botania r1.7-204.jar
BrandonsCore-1.0.0.7.jar
buildcraft-6.4.16.jar
buildcraft-compat-6.4.2.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel2-2.4.1.40.jar
CodeChickenCore-1.7.10-1.0.6.43-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
compactmachines-1.7.10-1.19b.jar
ComputerCraft1.73.jar
DeadlyWorld-1.7.10-1.0.2.jar
DifficultLife-1.2.1710.3.jar
Dimensional-anchor-59.0.2.jar
Draconic-Evolution-1.7.10-1.0.2-Snapshot_3.jar
DummyCore1.12.jar
EasyCrafting-1.7.10-2.0.1.16.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
EnderCore-1.7.10-0.1.0.24_beta.jar
EnderIO-1.7.10-2.3.0.415_beta.jar
EnderStorage-1.7.10-1.4.7.36-universal.jar
EnhancedPortals_1.7.10-universal-3.0.10.jar
EssentialCraftv4.6.1710.35.jar
extrabiomesxl_1.7.10-3.16.3.jar
ExtraCells-1.7.10-2.2.71b121.jar
extrautilities-1.2.8.jar
Farseek-1.0.8.jar
fastcraft-1.21.jar
FloodLights-1.7.10-0.4.3-62.jar
Framez-1.7.10-0.2-32-universal.jar
GekosLasers-1.7.10-0.8.jar
generators-0.9.14.79-mc1.7.10.jar
GraviSuite-1.7.10-2.0.3.jar
GravityGun-4.0.0-beta.jar
Guide-API-1.7.10-1.0.1-20.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar
Headcrumbs-1.3.1.jar
Highlands-1.7.2-v-2.2.3.jard
HungerOverhaul-1.7.10-1.0.0.jar
ibench-1.7.10-1.0.12.jar
iChunUtil-4.2.2.jar
IGW-Mod-1.7.10-1.1.3-18-universal.jar
ImmersiveEngineering-0.4.4.jar
immersiveintegration-0.4.1.jar
immibis-core-59.0.8.jar
industrialcraft-2-2.2.780-experimental.jar
InfernalMobs-1.7.10.jar
InfiniBows-1.7.10-universal-coremod-1.3.0.20.jar
INpureCore-[1.7.10]1.0.0B9-54.jar
InventoryTweaks-1.59-dev-152.jar
Iron Backpacks-1.7.10-1.0.4-universal.jar
ironchest-1.7.10-6.0.60.741-universal.jar
IvToolkit-1.2.jar
JourneyMapServer1.0.5_MC1.7.10.jar
KoreSample-1.7.10-1.3.2.jar
LatBlocks-1.7.10-1.6.9.2.jar
LatCoreMC-1.7.10-1.6.9.4.jar
LavaMonsters-1.7.10-2.2.1.jar
LomLib-1.7.10-3.2.0-universal.jar
MagTools-1.7.10-0.1.6.jar
malisiscore-1.7.10-0.11.4.jar
malisisdoors-1.7.10-1.6.jar
Mantle-1.7.10-0.3.2.jar
MatterOverdrive-1.7.10-0.4.0-RC4.jar
Mekanism-1.7.10-8.1.3.231.jar
MekanismTools-1.7.10-8.1.3.231.jar
Minechem-1.7.10-5.0.5.398.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
MobiusCore-1.2.5_1.7.10.jar
MoreChisels-1.7.10-1.0-20.jar
MoreEnchantments-1.7.10-1.3.2.1.jar
MSM-SNAP-3.0.0e-For-MC-1.7.10.jar
neiaddons-1.12.8.30-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.0.9.jar
NotEnoughItems-1.7.10-1.0.4.107-universal.jar
NotEnoughResources-1.7.10-0.1.0.95.jar
NuclearCraft-0.0.1.5--1.7.10.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.4.3.jar
OpenModsLib-1.7.10-0.7.3.jar
OpenModularTurrets-1.7.10-1.3.8-35.jar
OpenPeripheralAddons-1.7.10-0.3.1.jar
OpenPeripheralCore-1.7.10-1.1.1.jar
OpenPeripheralIntegration-1.7.10-0.2.2.jar
Opis-1.2.5_1.7.10.jar
Pam's HarvestCraft 1.7.10i.jar
ParticlePhysics-1.7.10-1.0.44.jar
PlayerAPI-1.7.10-1.4.jar
PortalGun-4.0.0-beta-4.jar
PowerConverters-1.7.10_3.3.0-jenkins.76.jar
ProjectE-1.7.10-PE1.9.2.jar;d
ProjectE-1.7.10-PE1.9.3h.jar
QmunityLib-1.7.10-0.1.114-universal.jar
QuantumFlux-1.7.10-1.2.3.jar
QuarryPlus-1.7.10-2.1.0.jar
RandomThings-2.2.4.jar
RecurrentComplex-0.9.6.3.jar
rftools-3.10.jar
rfwindmill-1.7.10-0.7a.jar
RouterReborn-1.7.10-1.2.0.31-universal.jar
RTG-1.7.10-0.0.12.jar
Ruins-1.7.10.jar
runicdungeons-1.1.5c.jar
SimplyJetpacks-MC1.7.10-1.5.1.jar
SoulShards-TOW-1.7.10-0.1-RC9-7.jar
SpiceOfLife-mc1.7.10-1.2.3.jar
StorageDrawers-1.7.10-1.5.12.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.0.3B1-218.jar
ThermalFoundation-[1.7.10]1.2.0-102.jar
Treasure-1.7.10-1.2.jar
twilightforest-1.7.10-2.3.5.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
Wawla-1.2.1_1.7.10.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
