### ISSUE TITLE
[Suggestion] Add support Magneticraft oil

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#253]
Please. Add support Magneticraft Oil.

**Comment by whichonespink44** [comment]
Does Magneticraft add biomes? If not, what exactly do you want RTG to support? (Sorry, I've never used Magneticraft)

**Comment by Ezoteric** [comment]
As topic says oil, I think it doesn't spawn oil. ;)

**Comment by Tsyklop** [comment]
@whichonespink44 this is not the biome. It is a source of oil.

**Comment by whichonespink44** [comment]
RTG already supports all Magneticraft world gen.
