### ISSUE TITLE
Forced Village Generation

### ISSUE THREAD

**Issue by Massanutten** [Team-RTG/Realistic-Terrain-Generation#255]
This mod appears to force village generation even when generated structures is set to off when the world is created - confirmed by removing all other mods, starting a new world, making absolutely sure I disabled generated structures, and then spawning directly in a village XD.  I had the same issue with Ted's RWG, so I suspect that whatever is causing it might be somewhere in whatever you brought over from his code.

**Comment by whichonespink44** [comment]
Thanks for reporting this - it's been fixed in #243 and will be in version 0.0.14 which should be released tomorrow afternoon.
