### ISSUE TITLE
Make ocean look like this...

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#258]
![ocean](https://cloud.githubusercontent.com/assets/10927161/10866356/ecec68de-8022-11e5-826d-68b1875a00a3.png)

**Comment by whichonespink44** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-13?comment=379

**Comment by Ezoteric** [comment]
Btw that ocean looks a lot like my canyon ocean :p

**Comment by xeronut** [comment]
This was an ocean pic I found posted in the ATG forum thread.  It's actually what the Abyssal Ocean from BoP looks like when using that mod.  I mostly like the scalloped sides that generate in the Ocean/Deep Ocean transitions, and never felt like the vanilla Deep Oceans were actually "deep" - just a few blocks lower.  Also, one of my dreams is to build Zeal Palace on a Deep Ocean floor, and I felt a dome would look much better when surrounded by this. :D  Thanks for looking into implementing it!

**Comment by whichonespink44** [comment]
Closing this, but it's been labelled for easy reference.
