### ISSUE TITLE
Make savanna plateau look like this...

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#259]
![savanna-plateau](https://cloud.githubusercontent.com/assets/10927161/10866365/1bfcda14-8023-11e5-84db-60dff4e34e90.jpg)

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-13?comment=379

**Comment by Ezoteric** [comment]
Lol gl with that haha :p

**Comment by retep998** [comment]
Perhaps RTG can adjust the chance of a tree spawning based on the slope of the ground where a slope above a certain threshold wouldn't spawn trees at all (smaller bushes can have a higher threshold). That would make those nice looking height transitions. Also spawning surface cover like grass/dirt/snow depending upon the slope (for snow it should be a combination of altitude and slope).

**Comment by Ezoteric** [comment]
I think RWGcanyon forest is quite like this only need to get rid of the 2 extra pleatues.

**Comment by whichonespink44** [comment]
Closing this, but it's been labelled for easy reference.

**Comment by topisani** [comment]
i thought that was  a real picture...

**Comment by whichonespink44** [comment]
Yeah, me too when I first saw it :)
