### ISSUE TITLE
Water Lakes might generate at y != 64?

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#261]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-14?comment=388

**Comment by crunkazcanbe** [comment]
I am all for this feature man !!! :)

**Comment by whichonespink44** [comment]
Added in 2ee6a76
