### ISSUE TITLE
Emeralds are still generated in the world.

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#268]
Emeralds are still generated in the world.

The config file generation is off.

RTG 0.0.15

**Comment by whichonespink44** [comment]
Thanks for reporting this.

I think I know why it's still happening - should be fixed in the next release.

**Comment by whichonespink44** [comment]
This should be fixed in 94ee4a8.

Here's a snapshot if you want to test it out: https://goo.gl/GikRGk

**Comment by Tsyklop** [comment]
I put snapshot. Now we have to find the biome which generated emeralds.

**Comment by Tsyklop** [comment]
I don't notice emeralds in those biomes in which they are generated in 0.0.15

**Comment by whichonespink44** [comment]
Emeralds only generate in the vanilla Extreme Hills biome, and only if `"Generate Emerald Ore"=true`

**Comment by Tsyklop** [comment]
i find emerals in `Alps` biome. And i turn off this option in config file.

**Comment by whichonespink44** [comment]
Thanks for testing it out.

It looks like BOP [generates emeralds](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenAlps.java#L48) when it decorates its biomes... currently I'm only listening for when emeralds are generated during [chunk population](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/event/EventManagerRTG.java#L55-L57).

In order to prevent emeralds from generating in modded biomes, I will either need to listen for biome decoration events (which would cause additional lag if emeralds were disabled), or I would need to manually decorate every modded biome (which I'm actually planning to do eventually).

Not sure when this one will get fixed for modded biomes, but I'll leave this issue open and update it when progress has been made.

**Comment by whichonespink44** [comment]
For reference, here are all the modded biomes that generate emeralds...

**BOP**
* [Alps](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenAlps.java)
* [Crag](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenCrag.java)
* [Highland](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenHighland.java)
* [Jade Cliffs](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenJadeCliffs.java)
* [Alps Forest](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/biome/overworld/sub/BiomeGenAlpsForest.java)
* [Mountain](https://github.com/Glitchfiend/BiomesOPlenty/blob/4588b048e4807f517d2b22874b0e79f15f2bc444/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenMountain.java)

**EB**
* [Alpine Tundra](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/grass/BiomeGenAlpineTundra.java)
* [Plateau](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/grass/BiomeGenPlateau.java)
* [Snowy Plateau](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/snow/BiomeGenSnowyPlateau.java)
* [Mountains Archipelago](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/archipelago/BiomeGenMountainsArchipelago.java)
* [Mountains](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/grass/BiomeGenMountains.java)
* [Volcano](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/wasteland/rock/BiomeGenVolcano.java)
* [Sandstone Ranges](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/wasteland/sandstone/BiomeGenSandStoneRanges.java)
* [Scree](https://github.com/SMEZ1234/EnhancedBiomes/blob/d8dbb1f0029559764c8a88c9dbdb6186aca93f35/java/enhancedbiomes/world/biome/wasteland/sandstone/BiomeGenScree.java)

**EBXL**
* [Mountain Ridge](https://github.com/ExtrabiomesXL/ExtrabiomesXL/blob/cf951e606ee71f4eedc84c390261043acddff536/src/main/java/extrabiomes/module/summa/worldgen/MountainRidgeGenerator.java)

**Comment by Tsyklop** [comment]
@whichonespink44 thanks

**Comment by whichonespink44** [comment]
@Tsyklop Sorry, I posted that mainly for my own reference... I'm working on this issue now, and it should be resolved in the next release.

**Comment by Tsyklop** [comment]
@whichonespink44 Okay. I wait.

**Comment by whichonespink44** [comment]
This has been fixed in the 0.1.0 branch.

@Tsyklop Thanks for all your help with testing this - much appreciated.
