### ISSUE TITLE
Support for ChromaticCraft

### ISSUE THREAD

**Issue by Thiana** [Team-RTG/Realistic-Terrain-Generation#273]
Could you please consider adding support for the biomes in Reika's ChromaticCraft (Ender Forest, Rainbow Forest)? Thank you.

Reika's Biome code is available here (https://github.com/ReikaKalseki/ChromatiCraft/tree/master/World)

**Comment by whichonespink44** [comment]
If it's doable, I'll do it, maybe even in time for tomorrow's 0.0.17 release.

**Comment by whichonespink44** [comment]
Added in 18a97af

There wasn't much I could do in terms of decorating them, but they're now supported. All structures/features seemed to be generating properly as well.

**Comment by Thiana** [comment]
Thank you :)
