### ISSUE TITLE
Add support for AbyssalCraft

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#281]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-17?comment=525

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287002-1-7-10-forge-ssp-lan-smp-abyssalcraft-v-1-9-0

**Comment by CliveBarker** [comment]
Thanks, sorry for the duplicate, looking forward to this,

**Comment by whichonespink44** [comment]
Added in 37582ef

**Comment by CliveBarker** [comment]
THAAAAAAANKS!!!!!!!!
