### ISSUE TITLE
AM Witchwood Forest not generating witchwood trees

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#284]
The Witchwood Forest (Ars Magica 2) has the right colouring and does generate, but is populated with oaktrees instead of witchwood trees (I'm quite sure it isn't a biome id conflict as I don't even have BoP, ExBXL or EB installed currently).

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-17?comment=539

**Comment by Adaptivity** [comment]
Ars Magica 2 issue: https://github.com/Mithion/ArsMagica2/issues/1284

**Comment by whichonespink44** [comment]
Thanks for letting me know @Adaptivity - much appreciated.
