### ISSUE TITLE
BOP Alps

### ISSUE THREAD

**Issue by Massanutten** [Team-RTG/Realistic-Terrain-Generation#289]
The BOP Alps biome generates as a pretty much flat plain (3-4 block height variations) at sea level.  Is this intentional?

I'm using 0.0.17.

**Comment by whichonespink44** [comment]
You might just be in a flat area of the BOP Alps... there should be really tall, snow-covered mountain ranges that look like this:

![2015-11-23_06 56 46](https://cloud.githubusercontent.com/assets/10927161/11331218/b34d081a-91af-11e5-9d91-9d41b16e5fe8.png)

Try exploring a radius around the flat area and you should see some mountains.

Let me know if not.
