### ISSUE TITLE
Wildycraft crashes on startup

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#291]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-18?comment=546

**Comment by whichonespink44** [comment]
After looking into this in more detail (including looking at Wildycraft's deobfuscated source code), I think this issue needs to be resolved from Wildycraft's side. It is trying to override the use of RTG's custom chunk manager in the Overworld, something that RTG should have exclusive control over because the 'Realistic' world type was chosen on startup.

I'm not sure exactly what the mod author needs to do, but I would imagine it would involve doing some sort of check to make sure that it's only using Wildycraft's chunk manager when in the Wildycraft dimension.

For reference, this issue was also posted in the ATG thread earlier in the year, details below:

Issue reported by Matt_Rosa on ATG thread: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291067-atg-alternate-terrain-generation?comment=1607

TTFTCUTS's reply: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291067-atg-alternate-terrain-generation?comment=1608

This also backs up what I have discovered in my investigations.

**Comment by jredfox** [comment]
Well it's a good thing I don't need this for the ultimate rpg modpack I made. I only need it for a realism modpack
