### ISSUE TITLE
Galacticraft Planets crashes when trying to generate a village

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#292]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2524489-wip-realistic-terrain-generation-0-0-18?comment=596

Similar to #290 and #291

**Comment by Ezoteric** [comment]
I gonna check my mod pack when I get home and see if I get any crashes. I also have gc with planets. And also more planets I think. I'll let you know.

**Comment by whichonespink44** [comment]
:+1:

**Comment by Ezoteric** [comment]
WorldChunkManagerRTG cmr = (WorldChunkManagerRTG) worldObj.getWorldChunkManager();

is the problem.

 micdoodle8.mods.galacticraft.planets.asteroids.world.gen.WorldChunkManagerAsteroids cannot be cast to rtg.world.biome.WorldChunkManagerRTG

**Comment by whichonespink44** [comment]
Added a temporary fix for this is [RTG 0.0.19](https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v0.0.19)
