### ISSUE TITLE
Reduce transitional biome patches in water

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#306]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-0-1-0-realistic?comment=640

**Comment by Claycorp** [comment]
Hm... Could you possibly only do this to certain biomes as it looks amazing with ice. (even if it dosn't totally make sense in some cases)
Example: http://i.imgur.com/F2fwneE.jpg

I hope that it dosn't disappear!

**Comment by Ezoteric** [comment]
That's the reason it should stay everywhere 😝

**Comment by Claycorp** [comment]
I could understand in some places it would make sense to not be used. Mountains and this dosn't always mix well as they are so steep and you just end up with odd patches way up at the top.

**Comment by whichonespink44** [comment]
Yeah, to be honest, the mountain patches are a much bigger issue for me. I don't mind the water patches so much because I actually think it looks cool! But the mountain patches that expose dirt & stone & gravel in an otherwise nicely decorated incline.... yeah, that looks awful.

Hopefully I can figure out a way to remove them only as necessary, but... I'll probably end up implementing it as a config option because I think it's going to have to be an 'all or nothing' thing... either there are transitional biome patches, or there aren't.

**Comment by whichonespink44** [comment]
Fixed in 0.5

**Comment by Ezoteric** [comment]
i still prefer this would be a option, cause i miss my tentacles :( :( :(
