### ISSUE TITLE
Load configs during world load

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#308]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-0-1-0-realistic?comment=642

**Comment by whichonespink44** [comment]
This would definitely save a lot of time when testing. Worth looking into further.

**Comment by Zeno410** [comment]
CC and UB have world-specific configs, and I have utility routines that can manage them. They need some refactoring, though.

**Comment by whichonespink44** [comment]
@srs-bsns Any progress on this? Or is the stuff you've been working on only for the 1.9 version?

**Comment by whichonespink44** [comment]
Closing as it's a duplicate of #589
