### ISSUE TITLE
Biome sizes

### ISSUE THREAD

**Issue by aurumvorax** [Team-RTG/Realistic-Terrain-Generation#313]
Not sure what category this falls under, but I have been noticing that certain biomes are massive compared to all the other biomes.  I suspect this has to do with the temperature/humidity maps, and available variety within each climate area.  For example, I just generated 6 worlds on biome size 1, and each of them had a savannah or desert that was well over 200 chunks is size.  I have also had this happen with ice plains.  I have two suggestions, although I'm not sure how effective/possible they will be:
1 - add config changes to nature of the temp/humidity mapping, specifically, the weighting of different climate groups.
2 - dynamically change weighting of climate groups based on how many biomes are registered within each group

**Comment by whichonespink44** [comment]
@aurumvorax Sorry for the late reply - I thought I'd already commented on this, but looks like I never pressed the submit button!

Right, so... where to start.... I guess the first thing to keep in mind is that the size of biomes is guided (not determined) by the `Size of biomes` setting in _rtg.cfg_ and the individual biome weight settings. However, these settings are only guides - the actual size of the biomes is still largely dependent on the various noise algorithms that RTG uses behind the scenes. For example, even if you set the vanilla Ocean and Deep Ocean weights to 20 and set the `Size of Biomes` setting to 5, it's not absolutely guaranteed that oceans will be bigger and more frequent (even though that's what those settings are supposed to do), but... they're be more likely to be, when they have an opportunity to be (if that makes sense).

Believe me, this system is far from ideal (and it even confuses me sometimes!) - but it's the only system that I've been able to implement without totally re-writing RTG from scratch. If I can think of a better way to do it (perhaps in the way that you described), then I'll definitely do it, as it's probably the most discussed aspect of RTG and something that needs to be properly sorted out.

As for your other suggestions... funnily enough, that's probably the only way that it *can* be done using the current system, although the temp/humidity mappings and climate groups wouldn't be as robust as they could be.

I'm closing this issue, but feel free to continue the discussion if you want.

**Comment by aurumvorax** [comment]
Fair enough, thanks for the reply.  Other than this issue, this is the absolute best worldgen mod I've come across, so thanks for all the hard work.  I will have to dive into the repository over the holidays and see if I have any ideas.
