### ISSUE TITLE
Re-decorate BOP biomes to use RTG's signature style

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#329]
I want to re-decorate as many of the BOP biome as possible for the next update, using RTG's signature style.

This includes flattening biomes that are meant to be flat, using the new 'rolling hills' template for hilly biomes, adding fallen trees, custom foliage, etc, all whilst retaining the 'spirit' of the original biome.

@Team-RTG/readers I could use some help with this, so if anyone wants to help out, just let me know and we'll coordinate something.

For reference, here are some links that will come in handy:
* Google Spreadsheet (working document) - https://goo.gl/Q9jNjX
* List of biomes on BOP Wiki - http://biomesoplenty.wikia.com/wiki/Biomes_Index
* Screenshots - http://imgur.com/a/jDVGa

Also, to make it easier to test, you'll probably want to download the 'Deobf' version of BOP 2.1.0.1465 from [here](http://files.minecraftforge.net/BiomesOPlenty/) and drop it in your [libs](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/master/libs) folder. This will allow you to launch Minecraft within Eclipse rather than building a new version of RTG every time you make a change. (Make sure you run `gradlew eclipse` after you drop it in your libs folder.)

**Comment by whichonespink44** [comment]
For reference, the `[bop-biomes](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/bop-biomes)` branch is where all of the magic is going to happen.

**Comment by Ezoteric** [comment]
Yeah yesterday I had to go but let's talk tonight?

**Comment by whichonespink44** [comment]
Can't do tonight, but I can do tomorrow night if that works?

**Comment by Ezoteric** [comment]
As long as it's before 22:00 your time then yes

**Comment by whichonespink44** [comment]
Yep, that works for me - I can do anytime after 18:00

**Comment by Ezoteric** [comment]
dude where can i find the bop ID list ?

**Comment by Ezoteric** [comment]
cant do shit before you reply cause i cant get nei to work in eclipse :(

**Comment by whichonespink44** [comment]
first link in the OP

**Comment by Ezoteric** [comment]
and how do i set it ?
when i edit ConfigRTG.java public static int generateOnlyThisBiomeId = 98; it does not work

**Comment by Ezoteric** [comment]
ok got it working, so i will only change the surface file and terrain cause all the other shit you did i dont know shit about ;P

**Comment by Ezoteric** [comment]
euh.... i sitll get river biome and tbh i only get river biome after i changed the shit :(

**Comment by whichonespink44** [comment]
Yeah, you still get river biomes when testing single-biome worlds, so 
that's normal.



On 11/12/2015 13:20, Jason wrote:
>
> euh.... i sitll get river biome and tbh i only get river biome after i 
> changed the shit :(
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/329#issuecomment-163934933>.
>

-- 

Jeremy Hoke
Head of Digital

M: +44 (0)7908 845 742
E: jeremy.hoke@d4online.com <mailto:jeremy.hoke@d4online.com>

	
D4
Electric Works
Sheffield Digital Campus
Sheffield, S1 2BJ

Google Plus <https://plus.google.com/111542294372896795241> Facebook 
<http://www.facebook.com/d4online> Twitter 
<https://twitter.com/#%21/d4online> LinkedIn 
<http://www.linkedin.com/company/d4-online-limited>

	
T: +44 (0)114 286 6353
W: d4online.com <http://www.d4online.com/>

This email and any files transmitted with it are confidential and 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this email in error please notify the 
system manager. This message contains confidential information and is 
intended only for the individual named. If you are not the named 
addressee you should not disseminate, distribute or copy this e-mail. 
Please notify the sender immediately by e-mail if you have received this 
e-mail by mistake and delete this e-mail from your system. If you are 
not the intended recipient you are notified that disclosing, copying, 
distributing or taking any action in reliance on the contents of this 
information is strictly prohibited.

**Comment by Ezoteric** [comment]
yeah i just did a new world and got the land thats why i deleted it.

also for example:
I will leave some notes if i need to like xeric needs some rarely seen small hills but besides that its almost the same as savanna so i used that and changed the first grass to sand and it was perfect besides the few hills :P

**Comment by whichonespink44** [comment]
Yeah, that's cool. Whatever works!! :)

**Comment by Ezoteric** [comment]
yeah cause there might be things like, mushrooms needed and i might not know if what i do works or not :P

so when im done you can just read the notes and know what still can/needs to be done :P

**Comment by Ezoteric** [comment]
BTW there is no way i can make journeymap work without scr versions in eclipse ? 
Also NEI didnt show up even tho i did add the scr one (no error it just didnt work)

**Comment by whichonespink44** [comment]
Yeah, I struggled to get NEI working in Eclipse, but really... it's not that big a deal. You don't need to generate a map after decorating each biome. I just walk/fly around for a bit and see how it looks/feels, then tweak if necessary until I'm happy with it.

**Comment by Ezoteric** [comment]
but waila would be usefull so i know what tree is vanilla and what bop is :P

**Comment by whichonespink44** [comment]
True... I've just been middle-clicking on the block if I need to know what it is... and also... if you've dropped BOP into your libs folder, you should be able to go to that biomes class file and see what blocks it's using. (Or view the source on GitHub, whichever's easier.)

**Comment by Ezoteric** [comment]
thnx middle clicking is perfect :) now were even ;) (windows button) :P

**Comment by Ezoteric** [comment]
btw do we have a flat biome with a few small hills here and there ? (like really low hills) ?

**Comment by whichonespink44** [comment]
the new 'Rolling Hills' template has been working a treat for me since I tweaked it. It lets u choose the max height of the hills and the hill strength lets u make it hillier or flatter.

**Comment by Ezoteric** [comment]
ok but im looking for something like our desert, enough flat terrain and here and there a hill
Is that also possible with that rolling hills or can you copy paste tweak it to flattening hills ? :P

**Comment by Ezoteric** [comment]
i mean so far i used savanna  template for xeric, wasteland and now again for tundra as all those biomes are flat and occasionly a hill haha

**Comment by whichonespink44** [comment]
Yeah, that's cool man. It doesn't matter if they're 'samey' to start with - I can always go back and tweak them to make them unique. Most important thing is that they're mostly accurate in terms of the type of terrain (i.e. flat biomes shouldn't have mountains, etc.) As long as we're close.

I'm gonna try to finish work early so I can get back on the scene. Should be able to rock through most of these today/tomorrow.

**Comment by Ezoteric** [comment]
lol, i prolly end up doing most biomes savanna cause most of BOPS biomes are flat....

**Comment by whichonespink44** [comment]
Sounds good!

hey, did you see the BOP Canyon biome? I haven't tried it with other biomes in the world, but I'd love to know what you think about biomes that go below Y=63

**Comment by Ezoteric** [comment]
no i havent i will take a look.
But on the map the mesa looked shitty with all the empty puddles filled with dirt :P 
so if it looks exactly like that, then its crappy :p it should have the same layer and the normal layer ;)

But ill check

**Comment by Ezoteric** [comment]
DUDE WTF 
rolling hills ???? wtf is this shit loooooooooooooooooool

**Comment by Ezoteric** [comment]
![2015-12-11_16 18 17](https://cloud.githubusercontent.com/assets/14137626/11747315/d7120d14-a022-11e5-9158-e25a0a3060af.png)

**Comment by Ezoteric** [comment]
looks more like a earth quake aftermath lolz

**Comment by whichonespink44** [comment]
is that the Canyon?

**Comment by whichonespink44** [comment]
cuz that's not what I was seeing

**Comment by Ezoteric** [comment]
rolling hills terrain, i used it to see what it does for steppe

**Comment by whichonespink44** [comment]
really? than something's not quite right because I've been using it for quite a few and it's lovely!!!

try looking at the Coniferous Forest or Cherry Blossom Hills.

**Comment by Ezoteric** [comment]
yeah i found the problem
i used new TerrainBOPSteppe(), as this was correct

i changed to new TerrainBOPSteppe(63f, 66f, 30f),
and looks quite nice now :P

**Comment by Ezoteric** [comment]
![2015-12-11_16 31 31](https://cloud.githubusercontent.com/assets/14137626/11747632/a72d0840-a024-11e5-878b-66361e6812c2.png)

**Comment by whichonespink44** [comment]
:+1:

**Comment by Ezoteric** [comment]
canyon looks good yes :) no holes on the top floor but i havent seen anything under Y63

**Comment by whichonespink44** [comment]
ah right... i just uploaded the new stuff... give it a look when you get a sec and let me know what you think :)

**Comment by Ezoteric** [comment]
LOOOOOOOOOOOOOOOOOOOOL you got owned within 1 second ingame hahahaha

**Comment by Ezoteric** [comment]
![2015-12-11_17 24 02](https://cloud.githubusercontent.com/assets/14137626/11749085/0e0287aa-a02c-11e5-9d43-47de8b5ae9af.png)

**Comment by Ezoteric** [comment]
thats says more then enough right ? hahahaha

**Comment by Ezoteric** [comment]
after flying arround this was the whole world, no canyon anywhere to be found just flat land filled with mineshafts and temples :P

**Comment by Ezoteric** [comment]
new TerrainBOPCanyon(), doesnt work it needs to have its **f, **f shit

**Comment by Ezoteric** [comment]
so i wont go lower then 45 orso but the temples seem to be at a steady height, i think i gonna look into that and see if we can give it a slightly better random height so that the bottom can be at max 20 till lets say 50 something

**Comment by whichonespink44** [comment]
Are you using the bop-biomes branch to test the Canyon? Or are you using something else?

Hmmm, I'm curious to know how it transitions into other biomes.

**Comment by Ezoteric** [comment]
i was using your bop branche and copy pasted the 3 files you edited. but like i said it cant be () or it does not generate any canyon it will just remain flat ?

**Comment by whichonespink44** [comment]
Cool, cool - well I'm finally on the scene... I'm gonna crack on working my way down the top of the list, and if you wanna keep on working your way up, that's cool, or if you wanna tackle the Canyon biome, that's cool too. Not sure we're gonna be able to get the Canyon to work under all circumstances, but I thought it was at least interesting to know that we could go below sea level if we needed to.

**Comment by Ezoteric** [comment]
well below sea level is not smart as of the obvious reasons :P 
unless you can fix that i would suggest not go below 45 if not lower it at all.

anyway i think im going to bed again cause im still not feeling well. 
at least i did a few ill check in tomorrow for the rest you didnt do.

ill zip my shit and dump it on skype so you have that already

**Comment by whichonespink44** [comment]
:+1:

**Comment by Ezoteric** [comment]
wake up i need some advice

**Comment by whichonespink44** [comment]
Hey, been making good progress - I see you have as well, nice one! :)

What's up?

**Comment by Ezoteric** [comment]
the roof

anyway, i needed some help with some number but i found some of them out, also a bit of a late reaction dont you think :P

**Comment by Ezoteric** [comment]
come on skype so i can send all the files ?

**Comment by whichonespink44** [comment]
sorry, juggling two kids at the moment :stuck_out_tongue_winking_eye:

**Comment by whichonespink44** [comment]
yeah, one sec

**Comment by whichonespink44** [comment]
Added this to `dev` in e8f9b46 - thanks for all your help @Ezoteric :+1:
