### ISSUE TITLE
Add support for the Vampire Forest from Vampirism

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#331]
https://github.com/TeamLapen/Vampirism/blob/master/src/main/java/de/teamlapen/vampirism/biome/BiomeVampireForest.java

**Comment by whichonespink44** [comment]
Oops, Vampirism is for 1.8  :(

**Comment by whichonespink44** [comment]
Updated link to biome: https://github.com/TeamLapen/Vampirism/blob/1.7.10/src/main/java/de/teamlapen/vampirism/biome/BiomeVampireForest.java

**Comment by whichonespink44** [comment]
I've added partial support for Vampirism in the `vampirism-support` branch, but whilst the Vampire Forest is generating, the Vampire Castle is not.

**Comment by whichonespink44** [comment]
I've opened an issue on the Vampirism tracker: https://github.com/TeamLapen/Vampirism/issues/56

**Comment by whichonespink44** [comment]
Added in 3f4a88a.

The minimum required version of Vampirism has been set to 0.7.8.5, which hasn't been released yet.  

@maxanier will be changing the way Vampirism compares biomes in v0.7.8.5, and this change is necessary in order for RTG to be able to generate Vampire Castles.

Also...

@Zeno410 Part of this implementation involved replacing the stub we had for [WorldChunkManagerRTG#findBiomePosition](https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/36c0afb796c6390694f4d39047cc952de73fd850) with the vanilla logic. I've done some basic testing in a few worlds, and it didn't seem to cause any problems, but you might want to have a quick look to see if anything looks like it might give us trouble down the line. If we need to, we can revert back to the stub, as it's not actually required for compatibility - it just allows some debugging commands from Vampirism to work correctly.

**Comment by Zeno410** [comment]
I have no special knowledge on findBiomePosition - I've never had to deal with it in any way. Two *possible* performance issues - if the third integer parameter (the size) is really big, that will induce the GenLayer IntCache to initialize and keep around a large object. Second (probably irrelevant) - after finding a ChunkPosition, I think you should break out of the loop.

**Comment by maxanier** [comment]
Just want to mention:  [WorldChunkManagerRTG#findBiomePosition ](https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/36c0afb796c6390694f4d39047cc952de73fd850) is not compulsory for compatibility, but very recommend, since Vampirism uses it to find possible castle positions on world creation. Otherwise the "blood eye" does not work and Vampirism has to check every newly generated Vampire Forest chunk for a possible position.

**Comment by whichonespink44** [comment]
Ahh, sorry, I thought it was just used for those debugging commands. We'll keep it in for sure, but I'll make that optimisation tweak that Zeno suggested before we release the next version.
