### ISSUE TITLE
0.2.0 some bad generation vs 0.1.0

### ISSUE THREAD

**Issue by Kehaan** [Team-RTG/Realistic-Terrain-Generation#334]
Using 0.1.0 i get https://gyazo.com/ebd3bf2750aff415cd7e9b56ce5a7886
Using 0.2.0 i get https://gyazo.com/520bb33da47156b1d0d636aa200d3dad instead.

Have sent a message to WhichOnesPink on the minecraftforum too. Using 0.1.0 the worldgen looks very pretty again. 

Let me know if you need any logs. And if so which one :P

**Comment by Kehaan** [comment]
You can also get access to my private pack. Where you can easy recreate the issue.

**Comment by Kehaan** [comment]
Dynmap screenshots too:
With 0.1.0:
https://gyazo.com/98fcfe5bf5bf278a50484c5d837d66cd
With 0.2.0:
https://gyazo.com/79933c3f12476b20f5cceb2f20ad9534

**Comment by Ezoteric** [comment]
can you make me a screenshot of your modfolder ?
Cause i used a shitload of mods, generated 200k chunks and never seen shit like that (besides the canyons)

**Comment by Kehaan** [comment]
https://gyazo.com/730fc975d9754a5f715ae4d728273024

**Comment by whichonespink44** [comment]
@Kehaan Thanks for the mod list... a zip file with your entire config folder would also be very helpful.

There's a good chance that this issue has already been resolved in the latest development version as I've improved the biome selection code, so... it might be worth waiting until 0.3.0 is released on Sunday before testing this in any great depth, but it would be nice to see you config folder, just to see if I can spot anything out of the ordinary.

**Comment by Ezoteric** [comment]
yeah upload the mod and config folder plz so i can get gen a bug ass map to check.
saves pinks laptop from exploding :P

**Comment by whichonespink44** [comment]
@Ezoteric My laptop thanks you!!! :smile: 

Also, @Kehaan - just to confirm... this was the same seed on two different worlds, correct? Or did you update to 0.3.0 and then load up your 0.2.0 world?

**Comment by Kehaan** [comment]
Config folder:
https://www.dropbox.com/s/w8gni2ec8tjns4b/config.zip?dl=0

If you want full pack, i would like to send it private. As its going to be a follow up to my Fire In The Pipe 1 pack, and would like to not share it public here :P If so, how can i send it?
I doubt its a config issue. As it gens very good in 0.1.0 but very bad in 0.2.0 with that only change :)
If you want me to test a early copy of 0.3.0 let me know and i will be happy to do that also :)

**Comment by Ezoteric** [comment]
ah yes also provide the seed plz and spawn coordinates and where the bug is.
so i can make sure its reproducing the same world :)

no worries pink.

**Comment by Ezoteric** [comment]
@kehaan add me on skype -> mainflava

**Comment by Kehaan** [comment]
Its the same seed, two different worlds. Will many different ones xD As i tryed to find out what caused the issue lmao

**Comment by Kehaan** [comment]
I also first thought it was because i changed the village maximum range from 32 to 16. But that was not the case. It was just the RTG version.
Have added you Ezoteric If you are the Jason King one :P

**Comment by Ezoteric** [comment]
yes i am but i dont see your shit, whats your skype ?

**Comment by Ezoteric** [comment]
The "bug" was the new savanna plateau you screwed up :p

You can close this after you changed the savanna plateau side blocks back to white stained clay cause the stone makes it look damn ugly :P

**Comment by whichonespink44** [comment]
Heh, I didn't even notice it was a Savanna biome.

Yep, I totally agree about the stone looking ugly, but still not convinced the white stained clay is the best block for the cliff face. Maybe a config option is in order for this one?

**Comment by Ezoteric** [comment]
not convinced ? what more proof do you want :P  or better yet, what replacement did you had in mind, and im all for options but make the clay default ;)

**Comment by Kehaan** [comment]
With how 0.2.0 looks it for sure looked like a bug, and i missed the mountains xD

**Comment by whichonespink44** [comment]
I think I'm going to try and come up with a new terrain template that has a steep incline and then a flat plateau, rather than trying to make the mesa template work. If we did it that way, we wouldn't have to worry about the cliff block, and if we made the plateau high enough, it could look pretty cool. If I can't get it to work, then I'll go back to the mesa template.
