### ISSUE TITLE
Re-decorate EBXL biomes to use RTG's signature style

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#335]
Dude give me the deof file and if you have the id list and i can get started on this

**Comment by whichonespink44** [comment]
Hey man, thanks for volunteering for this! Here's the stuff you'll need:

Deobf - https://goo.gl/kX54mP
IDs - https://goo.gl/5tLqd1

Process is same as before... just drop JAR file in libs folder and run `gradlew eclipse` (might also need to change some biome IDs when testing)

Let me know if you need anything else.

**Comment by Ezoteric** [comment]
Done

**Comment by whichonespink44** [comment]
![Awesome!](http://i.imgur.com/0NgI7nD.gif)

**Comment by Ezoteric** [comment]
took me 3 hours tbh :P its not that much of a hassle but some biomes may look kinda ugly as ebxl only has 28 biomes where 5 orso are flat as shit :p

**Comment by whichonespink44** [comment]
No worries - I'll go through and tweak if necessary.

Nice work man!

Full suite of re-decorated EBXL biomes + full UBC support... that's not a bad update :+1: 

Not gonna get to Highlands this week unfortunately... just been too busy with work, but.. tomorrow's my last day until 2016, so... lots of stuff is gonna get sorted during the holiday break!! :dancers:

**Comment by Ezoteric** [comment]
I do have some requests you can work on :p hahaha 
We need that volcano fixed and I think I might a nice ocean biome for it to make it tropical island which counts as a oceans biome :) that would be perfect haha

**Comment by whichonespink44** [comment]
I'd love to fix volcanoes, but I'm not bothered about them being islands. I just want them to generate completely & only once per biome.

**Comment by Ezoteric** [comment]
You should worry cause if you do it like mentioned before you could also add the no spawn water Shit :p
