### ISSUE TITLE
Re-decorate Highlands biomes to use RTG's signature style

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#339]

**Comment by whichonespink44** [comment]
**Google spreadsheet**

https://goo.gl/FaJJnh

**MCF threads**

1.7.10 - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2104582-forge-highlands-2-2-3-updated-february-19

1.6.4 - http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287147-1-6-4-forge-highlands-1-7-2-pre-release-v2-2-0pre

**Comment by whichonespink44** [comment]
@KdotJPG We're currently working on re-terraforming and re-decorating the biomes from the Highlands mod, which consists of flying mountains and cliff overhangs, and I was just wondering if you might still be up for lending a hand with that? Alternatively, if you could maybe just give us a brief overview of how to implement 3D noise (if a brief overview is even possible with something so complex), it would be greatly appreciated.

**Comment by whichonespink44** [comment]
@Zeno410 - have you done all these? I know there's always more tweaking that can be done, but just wondering if this issue still needs to be open.

**Comment by Zeno410** [comment]
I think they're all acceptable, at least, at this point. We should close this and if specific issues come up with specific biomes we can open new issues.
