### ISSUE TITLE
Villages generate oddly with Better Villages and/or ChocolateQuest

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#340]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic?comment=785

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic?comment=795

**Comment by whichonespink44** [comment]
@walkerjonny is this still happening for you?

I've generated worlds with Better Villages on its own, ChocolateQuest on its own, and BV + CQ but haven't been able to reproduce the issue.

**Comment by whichonespink44** [comment]
@Ezoteric - is this still happening for you on snapshot 5? I seem to recall you saying that you've seen this issue before but that it hasn't happened in a while?

**Comment by Ezoteric** [comment]
Well I dropped chocolate quest and betier village a while ago so I haven't checked it again no. Besides that I didn't had the problem in the first place :) so if you can't he has to try it himself as I couldn't back then.

**Comment by whichonespink44** [comment]
@walkerjonny - I'm going to close this for now, but feel free to re-open if it's still happening for you.
