### ISSUE TITLE
Suggestion: Make mountain area real mountain biomes

### ISSUE THREAD

**Issue by wormzjl** [Team-RTG/Realistic-Terrain-Generation#341]
I.e. when the height exceeds certain values, replace the biome with some mountainous one.
This will allow better control of oregen, both in vanilla (emeralds) and by using other mods like custom ore generation
To prevent breaking existing worlds, probably add a config option?

**Comment by whichonespink44** [comment]
This isn't possible without a total rewrite of the mod... however... I'm probably going to be adding an API soon that COG can use to better control ore gen in mountains, similar to the way it does for ATG.

See this thread for more info: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291128-custom-ore-generation-first-revival?comment=1935

**Comment by Ezoteric** [comment]
Isn't it the ore hardcoded like RTG ?

In our case we can make config option to set height of ore right?  And so should other mods ?

**Comment by whichonespink44** [comment]
Not sure if we can set the max height for ores without overriding WorldGenMineable, which I'd like to avoid.
