### ISSUE TITLE
Crash with GeoStrata

### ISSUE THREAD

**Issue by Haggle1996** [Team-RTG/Realistic-Terrain-Generation#343]
http://pastebin.com/AFuhmX2K

Using 0.3, with GeoStrata in the pack, I receive this error during chunk generation. Without GeoStrata, works fine. Cross posting on both issue trackers.

**Comment by whichonespink44** [comment]
RTG and GeoStrata have always played nicely together. I just generated a 40k-chunk map with both mods installed and everything seemed to be fine.

I suspect this is an issue with Harder Ores and GeoSrata, but I'll leave this open in case it's something on RTG's end.

**Comment by whichonespink44** [comment]
Any luck getting to the bottom of this one @Haggle1996 ?

**Comment by Haggle1996** [comment]
No, I haven't had time to dig back into this, with the holidays and end of year work.

**Comment by whichonespink44** [comment]
No worries mate - I'll close this for now as I'm pretty sure it's not related to RTG, but feel free to re-open or create a new issue if you need to.

**Comment by Haggle1996** [comment]
Just replicated it without RTG, so confirmed it's not RTG. :D It does happen much more frequently with RTG, FWIW.

**Comment by whichonespink44** [comment]
:+1:  Noted.

Hope you get to the bottom of it!
