### ISSUE TITLE
Mountains clipped by height limit

### ISSUE THREAD

**Issue by aurumvorax** [Team-RTG/Realistic-Terrain-Generation#344]
I've found some mountain generation that is a little bit insane, it starts at y=68 and has it's top cut off at y=256.  It also ends up with a strange undercut effect(part of the mountain was cut away by a pair of AE2 meteors)  Obvious main problem is mountain height that can exceed 256, but it'd be nice to avoid cliffs like this that go forever.  Apart from that, the savannah/ice mountain transition actually looks pretty good, like it's got a bunch of frozen rivers slowly grinding down the mountain and melting.

http://imgur.com/a/Zw50y

**Comment by Ezoteric** [comment]
give me some writing rights again m8, i wont screw up things you know that :P

**Comment by whichonespink44** [comment]
Fixed in 76ffe7d
