### ISSUE TITLE
Buildcraft oil generation in Ocean

### ISSUE THREAD

**Issue by walkerjonny** [Team-RTG/Realistic-Terrain-Generation#346]
![2015-12-17_01 49 18](https://cloud.githubusercontent.com/assets/6742581/11858331/f6c754d8-a460-11e5-9f3a-f3f71665b3f4.png)
![2015-12-17_01 46 58](https://cloud.githubusercontent.com/assets/6742581/11858332/f6c774b8-a460-11e5-9001-7ecededb7a2b.png)
The oil reservoirs should generate beyond the water within the remaining layers of stone usually...

**Comment by walkerjonny** [comment]
The bottom of the oil reservoirs seem not to go deeper then y15. You can go deeper, maybe down to y5.
Also you can make the oil reservoirs less high but broader, more like oil fields or more elliptic

**Comment by whichonespink44** [comment]
I think I know why this is happening.

Basically, RTG is calling BC's decorate() method and the oil is generating where it normally would in an unmodified Ocean Oil Field biome.

In order to get the oil to generate more inline with the way it does normally, RTG would need to manually decorate the biome instead of calling BC's decorate() method.

In other words, it's doable (I think) - just need to look into it further.

In the meantime, would you be able to post a screenshot of how it __should__ look underwater?

**Comment by Ezoteric** [comment]
He did gave screenshots in OP you silly goos :P

**Comment by Ezoteric** [comment]
bla :D

**Comment by whichonespink44** [comment]
Oh, I think I might have misunderstood the OP.

This is just a suggestion on how to improve the BC oil generation in general, correct?

**Comment by Ezoteric** [comment]
i think thats my kelpforest canyon ocean :P that goes really deep yes :P 

it should only have that 1 block line visible and the whole ball needs to be underground, realistically this way all the oil would float up right ;)

**Comment by whichonespink44** [comment]
Ok, I think I see a couple things we could try... either we can raise the floor of the Kelp Forest a bit, or manually place the oil wells via the rDecorate() method (depends on whether BC has something in its API that will let RTG generate just the oil wells on their own).

**Comment by Ezoteric** [comment]
i suggest manually rdec so its good in ALL biomes without the hussle :P

**Comment by walkerjonny** [comment]
Usually the oil reservoirs should be completely covered within the ground stone layers beyond the ocean bottom level were the water begins. Only the middle fountain that goes up over ocean surface level should be out of oil - like an oil fountain that is straight shooting up through the ocean to the surface.
I'll see if I can make some screenshots with a default generator bit it is like on the screenshots above. Just fancy yourself that the oil reservoir itself is beyond the ocean bottom level and therefore not visible.
The suggestions were about how you could achieve it without changing too much about the ocean bottom generation itself.

**Comment by whichonespink44** [comment]
Cool cool - no need to do screenshots, I was just a bit confused (thought it was a bug, not a suggestion :smile: )

**Comment by Ezoteric** [comment]
it a bug and not a suggestion :P

**Comment by walkerjonny** [comment]
The small oil reservoir fountain has a thickness of a single block while the larger oil reservoir fountain is a cross with three blocks from north to south and also three blocks from east to west

**Comment by whichonespink44** [comment]
Fixed in b26453c (0.5.0 snapshot 5) - raised ocean floors to prevent this from happening - please re-open if necessary.
