### ISSUE TITLE
Config option to disable terrain shadowing

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#347]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=829

**Comment by aurumvorax** [comment]
Can I also add to this a request to control how steep the slope has to be before it gets stripped of grass/dirt/snow?  I'd really like to see mountains that had grass and trees on the lower slopes.

**Comment by whichonespink44** [comment]
Yep, both of these requests will be implemented in #322. If you want to monitor the progress, just drop a quick comment on that issue.
