### ISSUE TITLE
Mesa biomes have holes everywhere

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#348]
Its broken, there are now more holes then there is land :O

thats mesa plateau F M 

![mesa holes](https://cloud.githubusercontent.com/assets/14137626/11878735/d4a540a8-a4f7-11e5-9960-1f55deb20050.png)

**Comment by whichonespink44** [comment]
Yeah, I think I really messed around with the noise level for that one to try and make it different than the others Mesas.

I think I might've figured out how to get rid of the holes, so I'll definitely take a look at this. If it works, then we can get rid of the holes in the Savanna Plateaus, and any other biome that's using a Mesa-like template (BOP Crag, etc.)

**Comment by Ezoteric** [comment]
I do not have holes in my savanna but that's not the same as yours i think haha:p

**Comment by Ezoteric** [comment]
Hey about biome transitions, it gets sticked as you said, but cant we make it so the the noise from all biomes listins to its start height and follows up from there ? if so that solves your old hot cold fix right ? :P

**Comment by whichonespink44** [comment]
@KdotJPG - any ideas on how we can get rid of those holes?

**Comment by Ezoteric** [comment]
A week ago maybe 2 ago he said he prolly knows how to fix this, and he will when he has some time for it ;)

**Comment by whichonespink44** [comment]
:+1:

**Comment by whichonespink44** [comment]
@KdotJPG If you need a break from the biome layout system, it would be great if we could get the Mesa biome terrain looking good again. I've messed around with a few things, but nothing I change in the terrain noise seems to get rid of the holes. :disappointed:

**Comment by topisani** [comment]
Id say this can be closed, if pink has merged it from 1.8?

**Comment by whichonespink44** [comment]
Yep, it's in dev now.
