### ISSUE TITLE
Cave Control crashes/hangs with RTG

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#350]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=841

**Comment by whichonespink44** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=846

**Comment by whichonespink44** [comment]
Added a config option in dc0c6b7 to prevent RTG from interfering with cave generation.

**Comment by Zeno410** [comment]
This is all we can do, but it probably won't fix the problem - the problem is more likely that Cave Control is trying to modify the vanilla chunk manager and crashing because there actually isn't a vanilla chunk manager. That will have to be fixed at the cave mod's end.

**Comment by whichonespink44** [comment]
I think Reika must've fixed it then... just tested Mohawky's configs from OP with the latest dev build + CaveControl V10b + DragonAPI V10d, and didn't even have to use the new config option. Ah well, at least we have the option now in case another mod does something similar.
