### ISSUE TITLE
Mystcraft compatability

### ISSUE THREAD

**Issue by Leguan12** [Team-RTG/Realistic-Terrain-Generation#363]
Would it be possible to have a RTG specific Page/Symbol to allow Mystcraft to generate worlds using rtgs world-generator? (As far as my knowledge goes the Mystcraft API should allow such additions)

It would be extremely cool to have the option to have any kind of overworld, but still being able to get a RTG based world :)

**Comment by whichonespink44** [comment]
I've had a quick look at Mystcraft's API but couldn't see how I could actually create a page that would generate a world that uses the RTG world generator.

If you can find an open-source example of this being done by another mod, that would be a huge help. If it's possible, I'd be open to adding RTG-generated biomes to Mystcraft.

**Comment by Zeno410** [comment]
My MystcrafttoCC mod generates pages that use and control the CC generator in Mystcraft Ages. However, RTG is dimension-naive and there might have to be a lot of changes for it to work in other dimensions.

**Comment by Ezoteric** [comment]
With other words zeno is on it :p

**Comment by whichonespink44** [comment]
This would be nice to do at some point.

**Comment by Zeno410** [comment]
Indeed. I took a look at it though, and it might be more complex than I thought. RTG has its own chunk generator and we'd have to make sure Mystcraft could play nice with it. Mystcraft does refer to the chunk manager indirectly, so it might work, but there's a potential for some serious additional work. 

This should stay open, I think, but more as a long-term goal.

**Comment by topisani** [comment]
I'm thinking this could be closed, as it is planned for v2, but will probably never happen in 1.7

**Comment by whichonespink44** [comment]
Yeah, I agree. From what I understand about what would be involved in order to get this to work, I don't think it's worth attempting for 1.7.10
