### ISSUE TITLE
Issue with BOP/RTG

### ISSUE THREAD

**Issue by aurumvorax** [Team-RTG/Realistic-Terrain-Generation#364]
When RTG loads all the biomes from BOP, there are several biomes that cannot be disabled in the config, and they can cause biome conflicts and wierd generation - the nether and end biomes.  Adding the ability to disable these in the config should fix the problem.

**Comment by whichonespink44** [comment]
RTG only generates overworld biomes. If there isn't a config option for a particular biome, then it's not possible to generate that biome in an RTG world. None of the Nether or End biomes from BOP have config options in RTG, which means RTG doesn't support those biomes, which means they don't get generated in the overworld. They'll still get generated in the Nether and End, but RTG doesn't generate those - the default world generator does.

If you're experiencing biome ID conflicts, those can only be resolved through BOP's configs, not RTG's.

Hope that helps - feel free to re-open this issue or continue the conversation if necessary.

**Comment by aurumvorax** [comment]
Hmmm, it kept generating Phantasmagoric Inferno, then crashing, but I think I've tracked it down to a BOP ID conflict. It was just odd, because I didn't get any problems when using the same configs and disabling RTG.

**Comment by whichonespink44** [comment]
Glad you managed to sort it in the end. :+1:

**Comment by Zeno410** [comment]
This can happen due to an obnoxious feature of the vanilla sub-biome system if you're using it. It will place biomeID+128 as a "special" biome even if it's not appropriate (like a nether biome). BoP should avoid that in BoP worlds because they have their own sub-biome manager (CC is also immune).

**Comment by Ezoteric** [comment]
Lol zeno promoting his chappy mod ;) hehe don't mind me in drank too much :p
