### ISSUE TITLE
EB crash

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#365]
Here is my crash report :P
This was with CC alpha

[fml-client-latest.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/72821/fml-client-latest.txt)

**Comment by whichonespink44** [comment]
Is this from the latest compiled `master` branch, or something else?

**Comment by Ezoteric** [comment]
It is from the latest compiled unchanged master yes, i only renamed the mod name.

**Comment by Ezoteric** [comment]
anywayz im off to bed, ill see if there is anything i can do tomorrow :)
