### ISSUE TITLE
BOP and EBXL not generating their biomes.

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#366]
No crash just no mod biomes being loaded.
EBXL did gen EelGrass in water tho so it seems its only the biomes it does not gen with EBXL

just making this a issue here for tracking purpose

**Comment by Ezoteric** [comment]
i think ebxl did manage to create biomes :P

**Comment by Zeno410** [comment]
CC or RTG layouts?  CC was having trouble with the duplicate APIs that should be fixed now.

**Comment by Ezoteric** [comment]
Nice to move them but now it cant see highlands api and i cant compile :P

so i cant test

**Comment by Ezoteric** [comment]
ok, bop works its just extremely rare and i found 2 biomes mixing in together like a chess board.
Now this may because of my config settings so i will set everything to default and gen a 2nd map.

Even tho my config settings shouldn't cause those "problems" we need to know if thats the problem or not right guys ;)

**Comment by Ezoteric** [comment]
well did 2 more tests with unmodified rtg and cc configs and get big ass continent maps without any bop biome, not even the coral reef or kelp forest spawned.

for today im done i generated 5 maps thats 5 hours.

**Comment by Ezoteric** [comment]
OK bop works with CC, but crag biome needs a remake cause its a canyon biome and looks fockin gaaaaaaaaaaaaaay

**Comment by whichonespink44** [comment]
@Ezoteric Happy for either you or @Zeno410 to re-design the Crag biome. I don't particularly mind that it's in the style of a canyon/mesa, but what I do mind is that a) it's only minimally keeping in the spirit of the Crag from BOP and b) it doesn't look like a realistic Crag.

If we could shoot for something like maybe the [Temple Crag](https://www.google.co.uk/search?q=temple+crag&biw=1366&bih=681&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjmutrnxILKAhUKvxQKHdgZBpQQ_AUICCgC) in Nevada, USA, that would be awesome, but would love to hear what you guys think.

**Comment by Ezoteric** [comment]
Well i think all canyon biomes will be a problem cause i havent seen a big enough biome that makes it look good, they all to small there for it gets all those choppy plateaus.

here is the current crag
![2015-12-30_11 04 03](https://cloud.githubusercontent.com/assets/14137626/12049387/c785cb9c-aee6-11e5-8418-c0ad7770d875.png)

![2015-12-30_11 04 24](https://cloud.githubusercontent.com/assets/14137626/12049389/ce10cc1e-aee6-11e5-9338-0d4a08d9f440.png)

And look at the minimap :P
![2015-12-30_11 04 40](https://cloud.githubusercontent.com/assets/14137626/12049392/d7f409b2-aee6-11e5-8d23-46707ef1f8b9.png)

**Comment by Ezoteric** [comment]
also you should set back the mesa like it was in 0.0.13 ? if that was a version. 
it the first vid from the guy that made 2 vids

**Comment by Zeno410** [comment]
Something sort of like Temple Crag wouldn't be all that hard. Have a really high base height for the biome and a lot of sharp high-frequency noise. The sides won't be as steep and the points will go out on to the slope up but you'll get a lot of the feel.

I've never liked the BoP Crag - it's just too high. If something really high could be seen far away it would be useful as a landmark but MC doesn't work that way.

**Comment by Ezoteric** [comment]
I turned crag off when I played but with optifine you can also set distance few to extreme and then you will see it from far ;)
