### ISSUE TITLE
Add ability to remove biome IDs from within RTG

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#369]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=963

**Comment by whichonespink44** [comment]
Preliminary support has been added for this in e409f1a thanks to @elix-x - still need to do a bit more work to add full support. (#408)

**Comment by Zeno410** [comment]
We're not going to be doing the request to take out Biome IDs though. ASAIK that can already be done in the biome mods, you just have to work at it, and it's not something we should do (see all the headaches we've had with "no realistic version"). We should probably close this with a mention we'll be working to support extended biome numbers in the future.
