### ISSUE TITLE
WorldGenLakes breaking other world gen

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#378]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1029

I believe this is caused by the order in which we decorate various parts of the biome. I think we need to gen lakes first, which I thought I was doing already, but it needs another look.

**Comment by whichonespink44** [comment]
This definitely needs to be fixed. One for post-0.5

**Comment by Zeno410** [comment]
I'm assuming this is also causing problem ponds in the swamp biomes, and it's particularly gruesome there. I don't think it's an order-of-decoration problem; I don't think it's responding properly to the ground level.

**Comment by whichonespink44** [comment]
Yeah, they look really bad in swamp biomes, especially BOP swamp biomes where they absolutely butcher the terrain & existing decorations. Personally, I'm not a fan of vanilla surface lakes even when they are working and was contemplating disabling them by default in favour of RTG lakes, but... not sure if that's a good move.

**Comment by Zeno410** [comment]
Until and unless they can be fixed they've just GOT to go in the swamps. RTG lakes serve a very different purpose - a large boating lake, while the surface lakes in the swamps (at least the ones I'm thinking about) are just little ponds. But we'd be better off not having them, certainly in swamps. There's plenty of water there anyway.

(I'm not positive its WorldGenLakes - maybe it's some BoP decorator. But whatever it is, terminate with extreme prejudice!)

**Comment by topisani** [comment]
this exists with other things as well. we need to get our orders in order

**Comment by Zeno410** [comment]
Order is not nice though. A may be supposed to follow B - but if decorations A extends into another chunk it may go before B in the *second* chunk. Basically any multi-chunk decorations gets generated in an arbitrary order.

**Comment by whichonespink44** [comment]
I haven't looked in any great detail, but I bet we could fix these issues by writing our own WorldGenLakesRTG and be a bit more strict with the blocks we're allowed to overwrite when generating the lakes.

**Comment by Zeno410** [comment]
The issue isn't usually what it overwrites but a) water level too low and b) not erasing blocks above it.

**Comment by topisani** [comment]
in v2 this could probably be a terrainfeature. That would mean it would be applied to the terrain pre smoothing, and it could look pretty much exactly like the small lakes that ocacionally apear at y=62

**Comment by whichonespink44** [comment]
The only issue I can see with it being a terrain feature is that some mods might depends on the LAKES event, so... just need to keep that in mind if that's the route we go down in v2.

In the meantime, if anyone wants to take this one off me, please feel free. I had a look at the code the other day, and... well... yeah.

**Comment by whichonespink44** [comment]
Fixed in e0c7767
