### ISSUE TITLE
Crash with older BoP version

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#379]
BoP added 5 biomes fairly recently and it would be nice if RTG could run without crashing on older BoPs

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?page=52#c1036

**Comment by whichonespink44** [comment]
Yeah, I've been avoiding that one, trying to encourage people to upgrade their mods, but... it's been happening a lot lately, so probably worth doing.

I reckon all we need to do is check to see if the biome exists before adding it to the pool, or at least doing a version check and handling accordingly.

**Comment by Ezoteric** [comment]
Force version check deny world gen and force em to update bop :p

**Comment by whichonespink44** [comment]
I tried that, but BOP uses the same (incorrect) version number for all of its versions :cry:

**Comment by Ezoteric** [comment]
Then force ppl to read the OP and put up UPDATE BOP !! and not via curise it's outdated haha

**Comment by whichonespink44** [comment]
Fixed in 3ae2420
