### ISSUE TITLE
Weird symmetrical 'dots' appearing in some sandy biomes

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#394]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1118

**Comment by Zeno410** [comment]
Does this happen in vanilla/CC layouts?

**Comment by whichonespink44** [comment]
Not sure... I've only seen it in 0.4.0 and below and only very rarely.

I suspect it might have something to do with the 'Rolling Hills' terrain template I wrote, but that screenshot in the OP looks like it's happening in Ocean as well (unless the rolling hills are bleeding into Deep Ocean somehow, but that seems unlikely).

**Comment by whichonespink44** [comment]
This is still happening, and I still think it has something to do with the 'Rolling Hills' terrain template as it started happening immediately after that update. Though it could just be a coincidence.

**Comment by Ezoteric** [comment]
You made that terrain right ? hmmmz suspicious ;)

**Comment by whichonespink44** [comment]
Haha, suspicious indeed! :stuck_out_tongue_closed_eyes:

**Comment by whichonespink44** [comment]
Has anyone seen this bug recently when generating maps?

I haven't seen it since we raised the height of the plains biomes, so maybe that had something to do with it?

**Comment by topisani** [comment]
i have seen it at some point... and i havent been around for long

**Comment by Zeno410** [comment]
I think I saw it recently. What I saw looked like the jittered biomes were leaking into the surface procedure. I'll take a look when I get a chance.

**Comment by whichonespink44** [comment]
Just so we're all on the same page... the 'dots' in this case are 1x1 air blocks that form a straight line in sandy biomes. I have a screenshot somewhere, so I'll try to find it and post it here, but... essentially, it looks like this...

`S A S A S A S A S A S A S A S A S A S A S`
`S S S S S S S S S S S S S S S S S S S S S`

... where A = Air and S = Sand

**Comment by topisani** [comment]
yep thats what i have seen too

**Comment by Zeno410** [comment]
Ooh, no, that's not what I was talking about. See if you can find a seed for me to look at.

**Comment by whichonespink44** [comment]
I don't have that screenshot anymore since getting my new laptop, and I haven't been able to find another example.

I'll keep looking out for it though and post something here if I see it again.

**Comment by srs-bsns** [comment]
More evidence: [MCF #1937](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1937)

**Comment by whichonespink44** [comment]
Yep, that's exactly what it looks like (the really-close-together ones).

Although... I'm really starting to wonder if this is still an issue because I did quite a lot of flying and TP'ing around before merging the new decoration system into dev, and I didn't see any trace of it.

¯\\\_(ツ)\_/¯

**Comment by whichonespink44** [comment]
+1 for closing this as I haven't seen it in ages (out of sight, out of mind!! :stuck_out_tongue: )

**Comment by srs-bsns** [comment]
I haven't seen it either, except in screenshots that other people have posted, and in those cases it looked like structures that failed to spawn, and not what was appeared originally. I'd say close it, it can always be reopened if it comes back.

**Comment by topisani** [comment]
you can probably remove it from here, but 1.9 is full of it

**Comment by whichonespink44** [comment]
> you can probably remove it from here, but 1.9 is full of it

Probably just need the latest terrain tweaks from 1.7.10, unless it's another issue causing them? Gonna close this one, but can always re-open if necessary.

**Comment by topisani** [comment]
> Probably just need the latest terrain tweaks from 1.7.10
Yup thatss probably it

**Comment by Zeno410** [comment]
This is probably the smoothing process shorting out on terrain that changes too much. I occasionally have bugs that put terrain at 256 and the edges of the walls look like that.

**Comment by whichonespink44** [comment]
That sounds about right... I remember seeing it mainly at the edge of Desert Hills, but like I said, haven't seen it in ages.

Is there anything we can do to prevent it from happening altogether, or is it just a case of dealing with it when it happens? I would imagine it's virtually impossible to reproduce easily.

**Comment by Zeno410** [comment]
Most of the time when I see those artifacts it's the result of a rounding error from noise(x/wavelength) where x is an int. Then there's one which resulted from some hacks I did to river distancing and one still-not-explained larger wall which went away when I changed some wavelengths.

**Comment by whichonespink44** [comment]
#641 

And so the epic battle for weird dot elimination begins once again...
