### ISSUE TITLE
Make RTG gen RC abyssal stone to prevent it from being exposed

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#395]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1134

**Comment by Lathanael** [comment]
Related to #346

**Comment by whichonespink44** [comment]
Fixed in b26453c (0.5.0 snapshot 5) - RTG isn't manually placing the abyssal stone - instead, we've raised the ocean floor to prevent it from being exposed.
