### ISSUE TITLE
[REQUEST] Option to move player spawn to nearest land mass

### ISSUE THREAD

**Issue by Haggle1996** [Team-RTG/Realistic-Terrain-Generation#396]
Please add an option similar to Biomes O' Plenty's 'spawn on beaches':

"spawn settings" {
    B:"Only Spawn On Beaches"=true

    # Must be 256 or higher
    I:"Spawn Location Search Radius"=1024
}

With Climate Control and RTG 0.5.0, the chances of spawning in the middle of an ocean have gone up significantly. Increasing the frequency of seeds helps, but increasing it too much kinda defeats the purpose of Climate Control's oceans.

EDIT: Just FYI, setting the BoP option does not seem to function with RTG/CC, even at ridiculously large radiuses.

**Comment by Ezoteric** [comment]
tbh did it ever work for BOP ?

I mean i used this option in my addon version a while back ago (before 0.5) and it seems it was a 50 50 chance.

**Comment by Haggle1996** [comment]
It works fine in BoP and ATG-type worlds. I don't recall it ever functioning with RTG, but I don't necessarily consider that a bug. I just want a similar feature that keeps the player out of water:

- Move the spawn chunk to a beach
- Move the spawn to ANY land area
- Move land to the spawn zone.

Any of these options is great; maybe WhichOnesPink has a surprise idea.

The worst experience for the player is to spawn in the middle of a deep ocean, with no land in sight. With many mods doing update checks on login, plus others like Galacticraft drawing it's space race screen, it's very likely the player drowns before they can control their character (not to mention my pack has sea monsters that want to eat you).

If this was just a rare occurrence, instead of the majority of map generations, it wouldn't be such an issue. 3 out of the 12 worlds I've pregenerated with snapshot 3/4 start the player in a deep ocean with no land in sight. This is with cranking up the land mass seed frequencies, so I can only imagine it's worse with default configs. Setting the frequencies up really high alleviates the issue to an extent, but you lose the uniqueness of Climate Control worlds.

**Comment by whichonespink44** [comment]
Been discussing this over at Team RTG headquarters, and I think Zeno has come up with the 'surprise idea' - basically, he thinks CC's 'rescue' code (the code that prevents you from spawning in ocean) is getting overriden by other mods... so I think the plan is to make sure it runs last so that you're (almost) always rescued.

**Comment by whichonespink44** [comment]
where the 'almost always' is something like 95%

**Comment by Ezoteric** [comment]
Where the "headquarters" is something like a carton box :p

**Comment by Zeno410** [comment]
Yeah, CC is rescuing *me* out to 9300, -8200. So something is stopping it from running in your setup. Could be another mod or even that setup takes too long (it uses a short timer to prevent it from re-running in existing worlds). I'll try to make it more aggressive.

**Comment by Haggle1996** [comment]
World generation in my pack is expensive, often taking 30 seconds to a minute or more before you're presented with the world (on a slow computer) -- that's due primarily to Custom Ore Generation First Revival, Harder Ores huge veins, and RTG/CC. Switching to pure BoP biomes (no RTG/CC) nets me a good 20-30% improvement in world generation time.

I don't know if any of that information helps, but that's what I'm dealing with. :D

**Comment by whichonespink44** [comment]
Just thought I'd chime in here with my recent experiences with testing the release candidate...

It happens to me a lot.

I can't go into detail now, but I can say that it happened more often than not as I was generating worlds with the various biome mods. Default configs each time.

**Comment by Haggle1996** [comment]
They do appear to be more frequent with snapshot 5 and the latest CC 36. My incidences are set to defaults or higher and it feels like I'm ending up in the ocean even more frequently. This is extremely subjective, but even my alpha players are commenting about it.

**Comment by Ezoteric** [comment]
with CC i only have this a lot when i have the "wrong" settings, when i pump it to a lot of islands i end up 9 out of 10 times on land. 

And i had the exact same problem as you but i found out its the config settings.

**Comment by Ezoteric** [comment]
Btw send me you mod pack again and I'll do some testing. So yes I deleted it for real ;)

**Comment by Haggle1996** [comment]
I think you were testing someone else's pack, but mine's https://www.atlauncher.com/pack/Revolution2

**Comment by Zeno410** [comment]
It has to be some sort of interaction because an ocean start NEVER happens to me. Sometimes I'll do 10 to 20 starts in a row just to get some statistics on how far the rescue takes me (this is to get an idea of how oceanic/continental the world is). This is with Highlands and sometimes BoP. I do sometimes get single-biome island starts if that's what people mean.

**Comment by Zeno410** [comment]
This is with any settings too - sometimes I'll set it to something ridiculous like 10 of one landmass and nothing of anything else for testing purpose. Blam, there's land, every time.

**Comment by Ezoteric** [comment]
Never saw never I can reproduce ocean starts also like in the middle of a huge ocean. It's like I said 1 out of 10 with my current config but I bet I can make it worse. :p

**Comment by Zeno410** [comment]
Send me your configs and a seed.

**Comment by Zeno410** [comment]
Do you ever get a remote start? Try something like medium continent 10 and everything else zero and 9 times out of 10 you'll be thousands of blocks from 0,0. If you don't, something else is preventing the routine from running or overriding it later.

**Comment by Ezoteric** [comment]
I've said this few weeks ago remember. But I'll do some testing and send you everything; ;)

**Comment by Haggle1996** [comment]
FWIW, with ocean landings, my starting coordinates are waaaaaay away from where I would expect to spawn (thousands off from 0,0). JourneyMap will show many randomly-spawned individual chunks between where I would expect to spawn and where I actually end up, in a very random swirly pattern. I believe this is the intended behavior: You didn't spawn on land, so CC is searching for land to put you on. 

I also note that this 'feels' like the most expensive new-world behavior. If I miraculously start on land at the natural spawn point, a new world creates really fast. If it takes a long time to start up, it usually means I've spawned in the middle of the ocean.

Perhaps just increasing the random noise, so that the randomly generated search pattern is a little more spread out? Alternatively, is it possible to inject a forced medium-continent seed or the like at 0,0, regardless of incidences?

**Comment by Zeno410** [comment]
Yes, that's absolutely the CC start search. It's not random, but spiraling out with increasing steps. The steps are large compared to a spiral circuit IIRC so it's kind of random to look at. I don't think the search can fail yielding an ocean start - it just keeps going until it crashes.

Have you looked at the text maps to see if there is land, and maybe Tp'ing to a location? You could also try a start with some simple seed and sending that and the CC config to me. The land structure *should* be essentially the same no matter what other mods and settings you have (also, very similar in default worlds with only some short-distance coast changes).

I'm actually wondering if something else is overriding CC's *generation* at this point. Only a very extreme config would be lots and lots of water like that, and I doubt you have one.

**Comment by Haggle1996** [comment]
I don't know if I've just been lucky with the RNG, or if you actually fixed it with the new config option to force a small continent, but since 0.5.0, I have not encountered a single ocean biome start. I would vote to close the issue.

**Comment by whichonespink44** [comment]
:+1:
