### ISSUE TITLE
Low rate of ocean plant spawns

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#398]
No demo shots, but it's Mohawky's impression, and mine as well. Possibly related to the currently excessive conversion of inland water to River.

**Comment by Haggle1996** [comment]
They do look sparse. I can provide screen shots, if that helps. Also, I'm not seeing any of the special BoP ocean biomes generate like the Coral Reef, though that may be a config issue.

**Comment by whichonespink44** [comment]
In climatecontrol.cfg, make sure you have:

`B:NoBoPSubBiomes=false`

I'm pretty sure I've seen at least one of the BOP ocean biomes in my testing, though I can't remember which one.

**Comment by Ezoteric** [comment]
I have seen both but coral reef is a big one

**Comment by Haggle1996** [comment]
Thank you, @whichonespink44, setting that flag fixed the missing biomes. However, now I'm encountering these more often: ![Underwater Trees](http://imgur.com/yR73Np7). Not sure if it's issue worthy.

**Comment by whichonespink44** [comment]
@Haggle1996 No worries! :smile: 

@Ezoteric Have you ever seen anything like that in BOP's ocean biomes? Looks like maybe the decorations from a neighbouring biome have crept in there somehow.

**Comment by Ezoteric** [comment]
nah coral and kelp were normal as in good not bugged

**Comment by Ezoteric** [comment]
btw i might redo all ocean biomes so they be better and more compat with other mods
i mean deep ocean and coral reef go to layer 20 i think :p

**Comment by whichonespink44** [comment]
hmm, yeah, might be good to boost them up to the other ocean biomes - shame we can't have really deep oceans, but... looks like it causes more trouble than it's worth. I suppose we can always re-visit them after everything's stable.

**Comment by Ezoteric** [comment]
you can always edit it privately :P

**Comment by Ezoteric** [comment]
i mean i dont use all those mods that like railcraft and bc :P so i have 0 problems

**Comment by whichonespink44** [comment]
Getting back to the OP, @Haggle1996 mentioned in #382 that the low rate of ocean plant spawns might be related to #395 (RC's abyssal stone generating on the ocean floor), so it's quite possible that raising the ocean floor will squash two bugs with one fix.

**Comment by Ezoteric** [comment]
what mod does add that so we can look at the code if there is anything saying about height

**Comment by Haggle1996** [comment]
Railcraft adds abyssal stone.

**Comment by Ezoteric** [comment]
im talking about the coral

**Comment by Ezoteric** [comment]
lol @ that picture hahaha well a  forest should have trees right :P

**Comment by whichonespink44** [comment]
@Ezoteric any update on the oceanic biome heights? I can go through and increase the heights if you want - just wanted to make sure you weren't still working on them.

**Comment by Ezoteric** [comment]
I'm doin nothing cause the ocean doesn't read it's terrain file remember

**Comment by whichonespink44** [comment]
Fixed in b26453c (0.5.0 snapshot 5) - please re-open if necessary.
