### ISSUE TITLE
Update OpenSimplex noise 3D with new gradient set from SuperSimplex noise

### ISSUE THREAD

**Issue by KdotJPG** [Team-RTG/Realistic-Terrain-Generation#399]
The 2D OpenSimplex noise is using the new normalized-expanded-vertex-figure gradient set, but the 3D noise is still using the old skewed-expanded-hypercube gradient set. Updating the gradient set should improve isotropy throughout all three dimensions.

I will add this in, and compute the new normalization factor for it.

**Comment by whichonespink44** [comment]
Sounds interesting... I'm assuming this won't have any effect on anything existing because RTG isn't using 3D noise yet. Is that right?

**Comment by KdotJPG** [comment]
RTG is using 3D noise to generate the block arrangement patterns on the surface, so that steep slopes don't "stretch" the patterns.

**Comment by Zeno410** [comment]
So, fewer predictable patterns and direction biases in the surface patterns?

**Comment by whichonespink44** [comment]
Any progress to report @KdotJPG ?

**Comment by KdotJPG** [comment]
Going to include this with the new biome system once that's finally ready.

**Comment by whichonespink44** [comment]
Added in 2db7827
