### ISSUE TITLE
Generate river noise with tanh(x^2) smoothing

### ISSUE THREAD

**Issue by Szperak** [Team-RTG/Realistic-Terrain-Generation#402]
float strength = Math.tanh(Math.pow(noise2d(x/1337, z/1337), 2));

Code above gives good results and does't use veronoi magic.

How it works? Google for y=tanh(x^2)

PS: My second name is 7ERr0r

**Comment by whichonespink44** [comment]
@Szperak looks interesting... in which file did you use that code? Any chance you could post a screenshot?

**Comment by Szperak** [comment]
I used it in my bukkit plugin, here's the old screenshot from developement:
http://screenshot.sh/oBD0xFZKFOIMj

**Comment by Szperak** [comment]
Okay, I see, what's the problem.
http://screenshot.sh/mMbFM4D2PVyCe

**Comment by Ezoteric** [comment]
Lol @ 1337

**Comment by KdotJPG** [comment]
There are definitely a lot of nice properties to this river generation, but one of the main things is that, if you notice, all river intersections are of an even number of paths. There are ways to resolve that (i.e. using three noise instances and doing something that involves a triangle) but then that produces triple and quad intersections that look different from each other.

Definitely think tanh(x^2) is an interesting trick that I'll have to keep in mind though for other parts of the terrain generation.

**Comment by whichonespink44** [comment]
@Szperak I'm closing this, but it sounds like Kdot will keep this in mind for future reference, so thanks for posting this :+1:
