### ISSUE TITLE
Refactor all hardcoded instances of the biome array length

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#408]
From #405:

_"I searched the code base for "256", many of which references are to the biome array and need a similar change:

Found 4,914 match(es) in 352 file(s)

Um, yes, a bit more work! The vast majority are references to the 256 height but somebody's gotta look at a lot of code."_

**Comment by Zeno410** [comment]
No urgency on this one. As long as nothing's trying to use extended biome tables either the old 256 approach or the new "size of biome array" will work just fine. We just have to have EVERYTHING fixed for extended biome tables to work properly.

**Comment by topisani** [comment]
This is in v2. Do we need it here too?

**Comment by whichonespink44** [comment]
Not sure.

@elix-x Are there any mods taking advantage of the AIC's extended biome array length in 1.7.10? If not, I'd be a little reluctant to proceed with this as I don't want to run the risk of introducing any new bugs. In theory, everything should be fine, but... it just feels like we could be opening up a can of worms (bugs) by implementing this now.

**Comment by elix-x** [comment]
Not yet. Meanwhile, i recently finalized API, so i'll be pulling others into this mess.
Considering i pulled you in first, and some time after you moved to climate control based gen, recently i  pulled Zeno in. So, while climate control isn't adapted with AIC, well, RTG cannot be fully used.

So, it's up to you know.

BTW, i still haven't gotten any news from Zeno, so @Zeno410 ???

**Comment by whichonespink44** [comment]
@elix-x Do you have plans to update AIC for 1.9? If so, I think we should try to add support for this in our 1.9 version instead, since we're already in the middle of a [major re-write](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/tree/RTG2) of RTG for 1.9.

**Comment by elix-x** [comment]
I saw that you're working on 1.9, and i have plans on AIC for 1.9, just not yet (i don't thinkg enough biome mods are there for me to move, meanwhile 1.7.10 is getting old). Although, API class will be the same (just different imports related to fml).

**Comment by srs-bsns** [comment]
@elix-x, right now the only mods in 1.9 that add biomes, that I know of, are BoP and AbyssalCraft. As for the other major mods that add a lot of biomes, there might not be many that end up getting ported to 1.9.

1. Highlands, ~40 biomes (Zeno was given permission to take this over, so a future port is expected, eventually)
2. EnhancedBiomesXL, ~30 biomes (devs had plans to update, but stagnant for a long time)
3. Enhanced Biomes, ~90 biomes (Stagnant for a long time and likely won't be ported unless done by a third-party, lack of a licence makes this impossible without @SMEZ1234's direct permission, and he ain't responding)

Any other mods that add biomes only add a few each, and the biomes can be counted with one hand, with the exception being Twilight Forest which added about 20.

I'm not trying to say that you're wasting your time porting AIC to 1.9, but as it stands, it doesn't appear there will be much demand for it, atleast not for a while, so no need to rush it. :smile:

**Comment by elix-x** [comment]
@srs-bsns Yup. And that's why i said, 

> Just not yet

**Comment by topisani** [comment]
right, we can close this then? if no mods currently take advantage of extra IDs, none probably will for 1.7, and new mods are probably not going to aim for 1.7 anyway.

**Comment by whichonespink44** [comment]
Yeah, let's close this for now, but if any mods for 1.7.10 ever take advantage of the extended IDs, I'm more than happy to re-open this.

But I think we should definitely do this for 1.9 as soon as we can, if possible. Might as well get it in early while the codebase is small.

**Comment by elix-x** [comment]
Current situation is weird: forge is in beta, and has already made a few updates that literally broke every mod already updated. So it resulted in making most 1.7.10 modders wait for stabke forge version for 1.9.
And personally, don't know about you, but i still see new mods related to biomes coming out for 1.7.10

**Comment by elix-x** [comment]
@whichonespink44 Agree. Also, as i said, 1.9 API classes are different only with imports, so if you want, you can add it to 1.9 RTG apis folder already and organize imports. It's just that we will be able to test it when i make first 1.9 version.

**Comment by topisani** [comment]
@whichonespink44 this should already be in 1.9 actually.

**Comment by whichonespink44** [comment]
Yeah,1.7.10 will be the standard version for quite some time, despite all the activity in the 1.9 landscape, so it's definitely possible that we end up doing this for 1.7.10. If not, then we'll be ready for 1.9 :)

**Comment by elix-x** [comment]
By the way, Highlands is already for 1.8.9: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2494877-highlands-uncharted-territory-finally-for-1-8-9
