### ISSUE TITLE
Biota not matching biome

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#409]
The biota doesn't seem to end up in the same place as the biome. I think there's a bias moving things in one direction or another. Small sub-biomes sometimes end up entirely devoid of their biota. Then, sometimes, trees can appear far into the "wrong" biome. One valley sub-biome (of Highlands Cliffs) had a strip of tree-free Valley on the south side and  strip of treed Cliffs on the north.

**Comment by Haggle1996** [comment]
Sounds like this would explain the underwater forests and clearly ocean biomes showing a land biome name instead. :)

**Comment by Zeno410** [comment]
Underwater forest, could be. Ocean biomes showing a land biome is a different problem - land near ocean can end up submerged in large tracts because a) some is supposed to be "lake" and b) smoothing. I will be able to "repair" some of that in the future using the same techniques in the upcoming snapshot I use for the beach but right now I'm also having trouble with river conversions and I need to see what's going on in the "water zones" to fix that.

**Comment by whichonespink44** [comment]
Could it have something to do with this:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/d7c9d85d3ee192fea27efd3b99d69d4f1a322760/src/main/java/rtg/world/biome/realistic/RealisticBiomeBase.java#L229

Always wondered what that line was actually doing.

**Comment by Zeno410** [comment]
Yeah, that could explain why the bias goes in different directions (I think). I'm guessing maybe it's to keep us from drowning in decorations? Research project for an upcoming snapshot, I guess

**Comment by whichonespink44** [comment]
Fixed in 9574ab3
