### ISSUE TITLE
BuildCraft treating polar snow deserts as desert

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#412]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1234

**Comment by Ezoteric** [comment]
hwo do you know thats a polar desert ?

**Comment by whichonespink44** [comment]
This was confirmed to be a BOP Arctic biome: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1356

**Comment by whichonespink44** [comment]
[Apparently](https://www.reddit.com/r/feedthebeast/comments/1yd63b/how_can_i_get_buildcraft_oil_to_spawn_in_biomes_o/cfjfskb), BuildCraft oil deposits have a small chance of generating in any chunk, so I guess this isn't a bug.
