### ISSUE TITLE
BOP biomes generate without Climate Control

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#413]
I tried to make landmasses bigger using the settings the mod provides, but, only oceans seem to be effected, and so I'm constantly getting worlds that are just ocean, with tiny islands as opposed to full-fledged landmasses.

Current config settings (tried to turn off and enable a few things in an attempt to fix this):

http://pastebin.com/vsymKf7n

**Comment by Zeno410** [comment]
If you think the oceans are too big you want more landmasses, not bigger ones. Bigger continents tend to have bigger oceans between them. You could post your configs if you want tips.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/kzgbhysvfxaimnj/configs.zip?dl=0

Here are all of my current settings

**Comment by Zeno410** [comment]
The latest snapshot doesn't require CC - if you run it without CC you'll get the vanilla biome layout for that seed, done in RTG terrain. However, those configs only affect the RTG *layout* so what I'd need to see is your CC configs.

**Comment by Sunconure11** [comment]
Try these. I had changed things a bit in an attempt to stop the tiny continent spawn, but, that did not work, so, instead, I just removed CC, as it works fine, and generates all of the BoP biomes without it.

https://www.dropbox.com/s/ois1a1yp7syu11l/ccconfigs.zip?dl=0

**Comment by Zeno410** [comment]
Wait, you can get BoP biomes in a realistic world without CC?

**Comment by Sunconure11** [comment]
Yes.

**Comment by whichonespink44** [comment]
I'm unable to confirm this with 0.5.0-snapshot-5, BOP 2.1.0.1548 and the supplied rtg.cfg. The closest things to BOP that I saw were a vanilla Desert and vanilla Desert Hills that had their skies modified.

@Sunconure11 Are you absolutely certain that you chose the 'Realistic' world type when you created the world? Also, would you be able to post a screenshot with the F3 screen turned on?

**Comment by Sunconure11** [comment]
I am using a realistic world. I'll generate one, just to show you.

**Comment by Sunconure11** [comment]
Not sure what I'm doing right, but, I am finding realistic worlds with BoP biomes.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/2aeqra7p7ijuaes/Screenshot%202016-01-14%2023.30.05.png?dl=0

**Comment by whichonespink44** [comment]
How bizarre! Would you mind posting your *fml-client-latest.log* file as well?

**Comment by Ezoteric** [comment]
This weird cause I made a map and no bop biome anywhere lol

**Comment by Zeno410** [comment]
I'd also tried it too, without success. What version of BoP are you using? One thing I *DON'T* see in the current one is an option to affect default worlds, which I'd swear used to be there.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/403jcomd2a2cqfa/fml-client-latest.log?dl=0

**Comment by Ezoteric** [comment]
BiomesOPlenty-1.7.10-2.1.0.1640-universal.jar with forge 1566 ima trying now :P

**Comment by Ezoteric** [comment]
not gonna happen, i still think you didnt set the world type cause i cant reproduce this

**Comment by Sunconure11** [comment]
Weird, here are the settings of another world I generated, as well as pictures to prove I'm using a realistic world type:

https://www.dropbox.com/s/ahm2qncqyaae6dm/Screenshot%202016-01-15%2012.07.53.png?dl=0

https://www.dropbox.com/s/jmp20spbfkwwmt1/Screenshot%202016-01-15%2012.08.35.png?dl=0

**Comment by Sunconure11** [comment]
Theres also this setting I turned on:

    B:"Allow biomes from this mod to generate"=true

The biomes o' plenty file can be found under the RTG biome folder. I suggest setting that setting to true.

**Comment by Ezoteric** [comment]
Thats true by default and double checked it.
I mean, im a skeptical person, seeing is believing but if this is all true it must be a mod orso interacting with it cause i have used the same rtg + bop + forge + config and that didnt work. 

Can try making a new world and see if that still happens ?

This is soooo weird

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/3cbjhjgvguq7gw4/Screenshot%202016-01-15%2012.20.44.png?dl=0

https://www.dropbox.com/s/zxpf2rxu9axinjy/Screenshot%202016-01-15%2012.20.52.png?dl=0

https://www.dropbox.com/s/flklqflbz9bp3an/Screenshot%202016-01-15%2012.20.56.png?dl=0

https://www.dropbox.com/s/4sviv818usqh7jb/Screenshot%202016-01-15%2012.21.41.png?dl=0

https://www.dropbox.com/s/q9zhkzzxyytkp0s/Screenshot%202016-01-15%2012.21.58.png?dl=0

https://www.dropbox.com/s/wdnmk57jz57j88c/Screenshot%202016-01-15%2012.22.31.png?dl=0

https://www.dropbox.com/s/wwnlp45yoog7qoc/Screenshot%202016-01-15%2012.22.54.png?dl=0

https://www.dropbox.com/s/tjcxfo905dsn06f/Screenshot%202016-01-15%2012.23.00.png?dl=0

https://www.dropbox.com/s/6oh4xfzfssso11w/Screenshot%202016-01-15%2012.23.25.png?dl=0

**Comment by Sunconure11** [comment]
In addition to using BiomeTweaker, I did change the IDs of the biomes from Biomes O' Plenty.

# Configuration file

"biome ids" {
    I:"Alps Forest ID"=253
    I:"Alps ID"=50
    I:"Arctic ID"=51
    I:"Bamboo Forest ID"=52
    I:"Bayou ID"=53
    I:"Bog ID"=54
    I:"Boneyard ID"=207
    I:"Boreal Forest ID"=55
    I:"Brushland ID"=56
    I:"Canyon ID"=57
    I:"Canyon Ravine ID"=252
    I:"Chaparral ID"=58
    I:"Cherry Blossom Grove ID"=59
    I:"Coniferous Forest ID"=60
    I:"Coral Reef ID"=251
    I:"Corrupted Sands ID"=104
    I:"Crag ID"=62
    I:"Dead Forest ID"=63
    I:"Dead Swamp ID"=64
    I:"Deciduous Forest ID"=65
    I:"Dense Forest ID"=66
    I:"Dry River ID"=146
    I:"Eucalyptus Forest ID"=240
    I:"Fen ID"=201
    I:"Flower Field ID"=67
    I:"Frost Forest ID"=68
    I:"Fungi Forest ID"=200
    I:"Garden ID"=70
    I:"Glacier ID"=105
    I:"Grassland ID"=71
    I:"Grove ID"=72
    I:"Heathland ID"=73
    I:"Highland ID"=74
    I:"Jade Cliffs ID"=75
    I:"Kelp Forest ID"=250
    I:"Land of Lakes ID"=232
    I:"Land of Lakes Marsh ID"=233
    I:"Lavender Fields ID"=76
    I:"Lush Desert ID"=77
    I:"Lush River ID"=198
    I:"Lush Swamp ID"=78
    I:"Mangrove ID"=98
    I:"Maple Woods ID"=79
    I:"Marsh ID"=80
    I:"Meadow Forest ID"=106
    I:"Meadow ID"=81
    I:"Moor ID"=246
    I:"Mountain ID"=83
    I:"Mystic Grove ID"=84
    I:"Oasis ID"=103
    I:"Ominous Woods ID"=85
    I:"Orchard ID"=82
    I:"Origin Valley ID"=247
    I:"Outback ID"=86
    I:"Phantasmagoric Inferno ID"=208
    I:"Polar Chasm ID"=217
    I:"Prairie ID"=87
    I:"Quagmire ID"=107
    I:"Rainforest ID"=88
    I:"Redwood Forest ID"=89
    I:"Sacred Springs ID"=90
    I:"Scrubland ID"=108
    I:"Seasonal Forest Clearing ID"=180
    I:"Seasonal Forest ID"=216
    I:"Shield ID"=92
    I:"Shrubland ID"=93
    I:"Silkglades ID"=230
    I:"Sludgepit ID"=94
    I:"Snowy Coniferous Forest ID"=95
    I:"Spectral Garden ID"=218
    I:"Spruce Woods ID"=61
    I:"Steppe ID"=249
    I:"Temperate Rainforest ID"=96
    I:"Thicket ID"=97
    I:"Tropical Rainforest ID"=181
    I:"Tropics ID"=99
    I:"Tundra ID"=248
    I:"Undergarden ID"=210
    I:"Visceral Heap ID"=209
    I:"Volcano ID"=100
    I:"Wasteland ID"=101
    I:"Wetland ID"=102
    I:"Woodland ID"=182
    I:"Xeric Shrubland ID"=183
}


"entity ids" {
    I:"Dart ID"=104
    I:"Mudball ID"=103
    I:"Poison Dart ID"=105
}


"mob ids" {
    I:"Bird ID"=109
    I:"Glob ID"=106
    I:"Jungle Spider ID"=101
    I:"Phantom ID"=107
    I:"Pixie ID"=110
    I:"Rosester ID"=102
    I:"Wasp ID"=108
}


"potion auto assign" {
    # Automatically assign potion ids if false set potion ids manually.
    B:"Potion Auto Assign"=false
}


"potions ids" {
    I:"Paralysis Potion ID"=66
    I:"Possession Potion ID"=67
}

**Comment by whichonespink44** [comment]
It's possible - you could try removing BiomeTweaker and seeing if it still happens... if it does, would you mind posting your BT configs so we can have a look?

The only other thing I can think of is that bug we used to have back in alpha where sometimes BOP biomes would generate even if they were disabled in both RTG's and BOP's configs. I thought that bug was actually caused by a biome ID conflict, but after looking at your BOP IDs, I don't see any that would be conflicting.

Let me know if removing BT has any effect (and thanks for all of your help in trying to resolve this bug!)

**Comment by Sunconure11** [comment]
I will test it.

However, I will send over my BT scripts as well.

https://www.dropbox.com/s/ped84smejbb5glu/scripts.zip?dl=0

**Comment by Sunconure11** [comment]
It happens without BiomeTweaker too. Either my copy is magical, or I'm very lucky.

However, I suggest trying to find a fix for this issue that people are reporting anyways. I don't want to use yet another mod just to make a certain mod's biomes spawn.

**Comment by Zeno410** [comment]
Ezo, have you looked through the BoP configs for some kind of "affect worldtypes" setting?

**Comment by Zeno410** [comment]
Sunconure, do you get the BoP biomes in a default world?

Pink, this *isn't* a bug, it's desired behavior. Now if CC can't overide the BoP settings, there's a problem, but it's a CC-BoP interaction and not actually RTG's problem (but I'm betting CC can).

**Comment by Sunconure11** [comment]
No, I do not get them in default worlds.

**Comment by Sunconure11** [comment]
I did find twilight forest biomes, but, I fixed that issue.

**Comment by Ezoteric** [comment]
bop doesnt havent shit as far as i can see and tell

**Comment by whichonespink44** [comment]
Ok, something weird is going on here... I just tried setting up a new MultiMC instance from scratch, trying to match @Sunconure11's setup as closely as possible. Got everything in, ran Minecraft, copied across supplied configs, loaded up a realistic world... and no BOP biomes.

Then I tried to look at BOP's configs to see if there was any new world type settings... but not only was there no world type settings... there were no BOP configs at all! so either the 'latest' BOP is buggy, or I'm going crazy.

@Sunconure11 - can you try using the 'recommended' version of BOP ([2.1.0.1548](http://files.minecraftforge.net/maven/com/github/glitchfiend/biomesoplenty/BiomesOPlenty/) - confusingly, the one on the right) and trying again?

**Comment by Razorskills** [comment]
Perhaps @Sunconure11 could zip up his whole folder for us to test?

**Comment by Sunconure11** [comment]
It is an instance of the next build of my modpack. I will send it over.

**Comment by Sunconure11** [comment]
As this build of the pack has not been released, it has not been polished fully. However, it contains all of the mods I use, and such.

**Comment by Sunconure11** [comment]
It is being built on a curse instance, and it is kind of messy with unused configs.

**Comment by Sunconure11** [comment]
I can also send over just my configs as well.

**Comment by Sunconure11** [comment]
Configs only: https://www.dropbox.com/s/hpxtzbhxal8qr82/onlyconfigs.rar?dl=0

Everything, no holding back: https://www.dropbox.com/s/xrfczj3nyd8gux9/testbuild.rar?dl=0

**Comment by whichonespink44** [comment]
Has anyone had a chance to test this any further? Is there even a need?

@Zeno410 - you said this is desired behaviour a few posts back and that CC had to handle something?

**Comment by Sunconure11** [comment]
No one has tested further, but, I am still able to find BoP biomes in realistic worlds. I would rather keep that option though, I'd rather CC be an optional dependency.

**Comment by Zeno410** [comment]
We would like BoP to handle biome layout if it's installed and CC/other biome mods aren't, obviously. If both BoP and CC are installed, CC should override BoP but if it doesn't it's not a RTG problem. I'd like to figure out how this works but I don't have the time.

**Comment by Sunconure11** [comment]
It appears BoP biomes stopped appeared in the latest build of this mod.

**Comment by Sunconure11** [comment]
Or at least, are very rare.

**Comment by Zeno410** [comment]
Meaning with BoP installed and no CC, correct? Did you replace your configs?

**Comment by Sunconure11** [comment]
I'll wait until a full release, the snapshots have many issues that I'm not willing to deal with.
