### ISSUE TITLE
Increase default village frequency

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#414]

**Comment by whichonespink44** [comment]
Updated in 2643293

**Comment by Ezoteric** [comment]
Why did you even change the default settings and is it still not the default?

**Comment by Zeno410** [comment]
Is it a config setting? They don't change with code changes unless the user throws out the config files.

**Comment by whichonespink44** [comment]
Yes, it's a config setting. I originally decreased the frequency because after the we flattened a lot of the biomes, villages and structures had a lot more opportunities to spawn, and they were generating way too frequently by default. But I think doubling the rarity was too much, so I've knocked it back down a bit. The new defaults are 1.5 times more rare than vanilla, but with RTG's flat terrain, they should actually generate about the same.
