### ISSUE TITLE
Weird error with this mod and streams

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#431]
http://pastebin.com/w6C7tAf0

**Comment by whichonespink44** [comment]
Can you confirm if this is also happening when using the recommended version of Forge (10.13.4.1558) on a non-Cauldron server?

Also, do you know what biome is using ID 142?

**Comment by Sunconure11** [comment]
It appears to be twilight forest from twilight twilight. I'll see when I can do that.

**Comment by Sunconure11** [comment]
I got a similar crash in SSP, without KCauldron.

Also, my biome dump is out of date. I'll dump my current biomes.

http://pastebin.com/Cg48DXD2

**Comment by Sunconure11** [comment]
This is happening with a clean config, as well.

**Comment by Sunconure11** [comment]
Biome dump: http://pastebin.com/CR71P8sJ

**Comment by Sunconure11** [comment]
It appears to be related to dry rivers.

**Comment by Zeno410** [comment]
Why do you think it's dry rivers? Also, do you see "river strips" of river biome where there are no rivers?

**Comment by Sunconure11** [comment]
Actually, I crashed as soon as I made the world with that error. Did you see the biome dump?

**Comment by Sunconure11** [comment]
I set biome 146 to be dry river.

**Comment by whichonespink44** [comment]
The two rivers from BOP were disabled in a previous version of RTG because they were causing a different crash, which I couldn't get to the bottom of, but maybe it's safe to enable them in the 0.5.0 version.

I'll try enabling them to see what happens.

**Comment by whichonespink44** [comment]
@Sunconure11 I don't think RTG is going to be able to support the two river biomes from BOP. I tried enabling them, but since BOP doesn't seem to be initializing them, RTG can't create realistic versions of them. Can you post your biomesoplentyInCC.cfg when you get a sec?

@Zeno410 If a biome ID is set to -1 in biomesoplentyInCC.cfg, does that mean that CC will essentially ignore that biome? My theory is that @Sunconure11 changed the IDs of the two river biomes to match what's in BOP's configs, but since RTG hasn't added support for them, it's crashing with a 'No realistic version of biome' error.

**Comment by Sunconure11** [comment]
I am not using CC at the moment, I have had too many difficulties trying to set up a satisfactory map. I will look into it later, though.

**Comment by whichonespink44** [comment]
Sorry, I assumed you were using CC.

In that case, just disable the river biomes in BOP's in _biomegen.cfg_

Also, as a general rule of thumb, don't ever change BOP's biome IDs - instead, change the biome IDs of the other mod biomes that you're using to resolve conflicts. Apparently BOP has some issues when its IDs are changed.

**Comment by Sunconure11** [comment]
Hm, I have Erebus and Twilight Forest, and I'm trying to rework the IDs. However, Erebus does not allow biome IDs higher than 127.

**Comment by Zeno410** [comment]
I tried to get CC to be able to run the biome IDs, but I couldn't get it to work. So whatever you set just gets overridden by the biome mod. Currently the config effectively servers as a biome dump so you can go back to an old world and know what the biomes are set to.

**Comment by Sunconure11** [comment]
I'm not using CC just yet.

**Comment by Sunconure11** [comment]
However, I will toy around with it now, to try and create some proper map settings.

**Comment by Zeno410** [comment]
I don't thing the configs are working right with CC so don't try to set anything up yet.

**Comment by Sunconure11** [comment]
I suggest someone reopen this, I was able to change as little biomes o' plenty biomes as possible, and suffered no issues, I was able to give Twilight Forest biomes different IDs

**Comment by Sunconure11** [comment]
Same with Erebus. Dry Rivers might be bugged if you changed their ID.
