### ISSUE TITLE
Desert temples spawning in Outback

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#432]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1353

**Comment by Ezoteric** [comment]
This Prolly cause of being set to sandy

**Comment by whichonespink44** [comment]
Hmmm, I thought it was checking for [HOT + DRY + SANDY](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/structure/MapGenScatteredFeatureRTG.java#L223-L225) - unless it's not making into that bit of code for some reason. Do we know what Outback is registered as?

**Comment by whichonespink44** [comment]
Apparently, it's HOT + DRY + SANDY: https://github.com/Glitchfiend/BiomesOPlenty/blob/0253add36a1fb9ceecea52cbaaeede67ae8cb72a/src/main/java/biomesoplenty/common/init/ModBiomes.java#L447

Hmmmm, maybe we should add another check for 'desert' in the biome name?

**Comment by Ezoteric** [comment]
All sandy will get a temple it's normal

**Comment by Ezoteric** [comment]
And if you get rid of sandy for desert other mods won't get a temple for example Sahara eb

**Comment by Ezoteric** [comment]
Desert = sandy lol

**Comment by Zeno410** [comment]
Outback *is* supposed to be desert. That's what the reference real life biome is.

**Comment by whichonespink44** [comment]
Ok, I'll close this as the biome's been registered with the 3 biome types that are required by RTG to spawn a desert temple. The bug with it being buried is apparently a hardcoded thing in Minecraft (Desert temples always spawn with their floor at y=64)

**Comment by Ezoteric** [comment]
Also not being a bug :p
