### ISSUE TITLE
ExceptionInInitializerError crash (RealisticBiomeHLBase.addBiomes())

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#433]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1366

Something weird going on when trying to addBiomes() in RealisticBiomeHLBase.

**Comment by Zeno410** [comment]
Ultimate cause is this line:
public static Block topBlock = hlBiome.topBlock;

Since it's static, it gets called when the class is initialized, which is an obnoxious early crash.

We need to make that a static routine. Actually in *that* class we can just take it out altogether, but similar code probably gets called in other classes.

I have no idea why it gets called early in Mohawky's setup than in our. Same Highlands, RTG, and CC.

**Comment by Zeno410** [comment]
And naggy Zeno comment: static is evil!

**Comment by whichonespink44** [comment]
I understand what static is, but... I don't understand why it's bad. Looks harmless enough, and like you pointed out, it's working fine for everyone else.

In any case, I'm all for following best practice, even if it means refactoring the entire codebase... would it be better to convert those kinds of static variables into member variables and initialise them during construction?

**Comment by Zeno410** [comment]
The problems with static:
It gets created when the class is initialized. This may be very early and before things the routine needs exist (like here). This can create initialization tangles too when static var A initializing routine B which activates routine C which...
Static vars can't be cleared by the garbage collector, nor can anything they use get cleared, unless the class is unloaded (which tends not to happen)
If you end up needing more than one copy floating around (like for multiple dimensions, or for tests I admit I don't often do) you can't have it.

It's not something to justify rewriting existing code, but it's a good principle to ask "does it really HAVE to be static?". Especially with vars - static methods are less of an issue, at least as long as they're referentially transparent.

**Comment by Zeno410** [comment]
I'll rewrite the Highlands biomes to not use static vars and we'll see if that fixes Mohawky's problem.

**Comment by whichonespink44** [comment]
_"Static vars can't be cleared by the garbage collector, nor can anything they use get cleared, unless the class is unloaded (which tends not to happen)"_

I've just been converted to the "Static is Evil" cult :)

Someone also pointed out in the forums that setting Highlands biomes to -1 in the configs causes a crash... could it be that Mohawky disabled the Bog biome by setting it to -1 and that's what's actually causing the crash?

**Comment by Zeno410** [comment]
ding ding ding, I think
I was just looking at the routine and wondering "how the heck could it possibly be called prematurely"
I'll modify the code to check for that somehow.

**Comment by Zeno410** [comment]
And ... a quick test shows that's the issue

**Comment by whichonespink44** [comment]
:+1:

**Comment by Zeno410** [comment]
PR in, with some other changes I can't easily exclude, but they shouldn't be issues.

**Comment by whichonespink44** [comment]
Fixed in 96e1938
