### ISSUE TITLE
RTG+EB+CC crash on fresh install

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#435]
Got this crash when testing RTG+EB+CC:

https://gist.github.com/whichonespink44/7ba6ef8874e68c6b93a9

This crash only happens with a fresh install of all 3 mods (no configs present for any of the mods)

**Comment by Ezoteric** [comment]
good you say this, cause my play world uses all 3 and does work :P so screw the update i guess :P

**Comment by Zeno410** [comment]
That's a testing crash I put in. It means that when CC went for the EB configs the EB config directory didn't exist.
