### ISSUE TITLE
YO DUDE

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#436]
how can i only make desert spawn or turn off vanilla biomes ????

**Comment by whichonespink44** [comment]
use CC

**Comment by Zeno410** [comment]
Turn off vanilla biomes with VanillaBiomes=false in the CC config. Yeah, very difficult, I know.

All desert? hot climate 1, all other climates 0, 0 out any other Hot biome incidences
