### ISSUE TITLE
Bad generation.

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#438]
http://imgur.com/a/h95TX

http://imgur.com/a/Hm8qs

RTG-1.7.10-0.4.0  BiomesOPlenty-1.7.10-2.1.0.1640-universal

**Comment by whichonespink44** [comment]
Those kinds of biome-surface transitions are an intended feature of version 0.4.0.

However, they will be removed in version 0.5.0 in favour of 'decorative' biome transitions.

**Comment by Tsyklop** [comment]
Thanks
