### ISSUE TITLE
Mowzie's Mobs Ferrous Wroughtnaut crash

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#442]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1405

I forgot to add this to the issue tracker originally.

It's related to the underground chamber that the Ferrous Wroughtnaut generates in.

I reported it in the Mowzie's Mobs thread a while ago but haven't checked to see if there's been any progress.

**Comment by whichonespink44** [comment]
I've posted a follow-up on the Mowzie's Mobs thread:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2361125-mowzies-mobs-fantastical-mobs-for-your-mc-world?comment=3341

**Comment by whichonespink44** [comment]
Mowzie replied with the following:

> Hm... The crash is actually traced back to an incompatibility with LLibrary's structure API. I couldn't tell you the specifics, but a fix would require an edit of LLibrary, not Mowzie's Mobs. Sorry.

I posted an issue on the [LLibrary tracker](https://github.com/iLexiconn/LLibrary/issues/67), so hopefully we're a little closer to getting this resolved.

**Comment by whichonespink44** [comment]
@iLexiconn - would you be able to give us any insight into what might be causing this crash? https://gist.github.com/whichonespink44/129464d524711213d14d

**Comment by iLexiconn** [comment]
LLibrary is trying to load a block from a chunk that isn't loaded yet. I *think* a simple try/catch could fix it.

**Comment by whichonespink44** [comment]
@iLexiconn Thanks for the insight - much appreciated. So is that try/catch something RTG should be doing? Or were you going to add a try/catch to LLibrary?

**Comment by iLexiconn** [comment]
I think I just fixed it, but it's hard to test since MM can't run on the latest version of LLibrary yet.

**Comment by chaNcharge** [comment]
I've tested it with MM 1.2.7, LLibrary 0.3.4, and RTG 0.7.0, it seems to generate just fine for me without crashes.

**Comment by iLexiconn** [comment]
That's weird. We haven't changed anything from the structure API since we added it.

**Comment by chaNcharge** [comment]
![2016-03-23_09 50 19](https://cloud.githubusercontent.com/assets/11594018/13993243/c328a2a8-f0dc-11e5-9072-233150d48363.png)

I just generated a new world with RTG active, and there's the ferrous wroughtnaut chamber. I've had to use Extra Utilities unstable blocks to find them and show them easily.

**Comment by whichonespink44** [comment]
Previously, I'd only tested up to version 1.2.2 of Mowzie's Mobs, but I just did a test with MM 1.2.6 and LL 0.6.2 (the version recommended on the MM OP), and sure enough, Wroughtnaut chambers are working fine!! :)

So somewhere between 1.2.2 and 1.2.6, this apparently got fixed?

**Comment by iLexiconn** [comment]
I see no changes in the structure generation at all. But at least it's fixed, right? ;)

**Comment by whichonespink44** [comment]
Haha - it would be nice to know why, but yeah, to be honest I'm just happy that it's working. :)

I'll see if I can trace it back to the lowest MM version where it was crashing and then add a minimum required version check to RTG to make sure people are using a compatible version.

Thanks for everyone's help with this one... can't wait to add "RTG is now fully compatible with Mowzie's Mobs" on the release notes for RTG 0.8.0 :smile:
