### ISSUE TITLE
java.lang.RuntimeException: No realistic version of biome [Biome_ID]

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#443]
I am getting a **java.lang.RuntimeException: No realistic version of biome 237**.
In this case biome ID 237 is assigned to BoP Spectral Garden. (The only biome that BoP adds for The End dimension.)

This happened while I was doing a kind of biome torture test with the latest versions of RTG (0.5.0-RC2) and CC (beta36,37,38) along with EBXL, Highlands, and BoP, as well as other mods that add biomes (Thaumcraft, Buildcraft, Twilight Forest, etc.) Hence the Spectral Garden biome being assigned to ID 237.

If I reassign that biome to another free ID (eg 141) and try to recreate the map with the same seed, the game won't crash. Thinking that maybe this only altered the biomes near the spawn location, I assumed that if I started to generate more of the world that eventually it would crash again and reference the new ID, but after flying around for a long while I couldn't reproduce this with the new ID assignment.

I tried lowering most biome incendences to 0 to try to increase the chances of the bug showing up, but this didn't work either, so I have no idea the cause and I'm too tired ATM to look into it further.

Full stacktrace: https://gist.github.com/srs-bsns/9bea65e0afc46608c8ed

Just ask for more info if you need it.

Ill try to look into this later on today, unless you find the problem while I'm napping. :)

**Comment by Zeno410** [comment]
What's in biome 109 and are you using the BoPSubBiomes?

**Comment by srs-bsns** [comment]
109 is assigned to Highlands Valley (sub-biome)
currently, B:NoBoPSubBiomes=true

**Comment by Zeno410** [comment]
This is probably a CC problem, not an RTG problem. email me your config folder and a seed and I'll take a look at it. I can't figure out a way this would be happening.

**Comment by srs-bsns** [comment]
You should be able to reproduce this with just these mods (All should be available on curseforge if you don't have them):
```
appliedenergistics2-rv3-beta-5
Baubles-1.7.10-1.0.1.10
BiomesOPlenty-1.7.10-2.1.0.1640-universal
buildcraft-7.1.14
ClimateControl-0.4.beta38
extrabiomesxl_1.7.10-3.16.4
Highlands-1.7.2-v-2.2.3
RTG-1.7.10-0.5.0-RC-2
Thaumcraft-1.7.10-4.2.3.5
twilightforest-1.7.10-2.3.7
```
In [this .zip file](http://www.nihilism.ca/minecraft/RTG-Issue443/RTG-Issue443.zip) are the pertinent config files, just let all other config files generate new.
Also in the zip are the last log files generated and the last crash report from when I tested to make sure this reproduces the crash, and the world save used in the crash which should crash the game if you try to load it.
The mod dir just contains a .txt file that lists the mods required. (I can't be bothered to check all of their licences to know if I can redistribute them, so the mods themselves aren't included. :)

Forge version: 10.13.4.1614
Seed used: 7777777

**Comment by whichonespink44** [comment]
@srs-bsns If you still have that setup available, would you mind testing it against [CC 0.4.beta39](https://www.dropbox.com/s/q0vo7477x4vk7wf/ClimateControl-0.4.beta39.jar?dl=0) and let us know if it's still crashing?

**Comment by srs-bsns** [comment]
I just set this instance up again, same as before, and I verified that the crash was happening.
I then plugged in CC b39 and no crash, so hopefully this issue is put to bed.

I'll close this to remove clutter.

**Comment by whichonespink44** [comment]
Awesome, glad it's working now.
