### ISSUE TITLE
Transitions between biomes are too smooth (RTG + CC + BoP)

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#445]
https://www.dropbox.com/s/b87j4w5y2te778u/Screenshot%202016-01-25%2020.41.13.png?dl=0

I'm trying to set up a suitable set of configuration settings for both large landmasses and yet large oceans, and I came across this.

**Comment by Zeno410** [comment]
Is this near a coast? If so it's a current limitation of the biome repair system. We will be working to improve it, but not in this release.

**Comment by Sunconure11** [comment]
Yeah, it is near a coast.

**Comment by whichonespink44** [comment]
Marking this as a duplicate of #456. Please follow that issue for progress updates.
