### ISSUE TITLE
Growthcraft Bamboo Forest support

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#448]
Growthcraft is being continued, so, would it be possible to add support for its bamboo forest?

https://github.com/GrowthcraftCE/Growthcraft-1.7/

**Comment by whichonespink44** [comment]
Nice, thanks for the suggestion. Should be relatively easy to add support.

**Comment by crunkazcanbe** [comment]
I would also like this . : )

**Comment by whichonespink44** [comment]
Been looking into this one, and I think I'd like Growthcraft to be the first mod to use the API for biome support, assuming the Growthcraft devs are up for it (and assuming it's not going to require a massive re-write of RTG, which I don't think it will). They have a well-documented contribution workflow, and since it's only one biome, it seems like a pretty ideal candidate.

I'll see if I can get this into 0.6, although if it means a massive refactoring, it might have to wait until 0.7

**Comment by Sunconure11** [comment]
I doubt it would require a massive refactoring.

**Comment by whichonespink44** [comment]
You're probably right... from my initial investigations, it will hopefully just involve exposing a few classes to the API and adding a couple Forge events.

**Comment by IceDragon200** [comment]
@whichonespink44 Hello, a (lead) Growthcraft Developer here, if you don't mind, giving me a quick guide on how to add support would appreciated, I'd add it rather promptly

**Comment by whichonespink44** [comment]
@IceDragon200 I'm pleased to hear that you're keen to add support. Sadly, the biome support system hasn't been added to our API yet - it's something I'm working on for our 0.6 release. As soon as it's ready though, I'll be sure to write up some documentation.

**Comment by whichonespink44** [comment]
@Sunconure11 @IceDragon200 Quick update... the biome support portion of the API isn't going to be finished anytime soon, so... I'll be adding inherent support for GrowthCraft's Bamboo Forest in RTG 0.7.0, tentatively scheduled to be released on 21st Feb. If you want, I can post a snapshot build here before it's released so you guys can suggest tweaks.

**Comment by IceDragon200** [comment]
@whichonespink44 If its aesthetics, talk with @Sunconure11, @Ar97x or @PitchBright, I'm only fussy about code

**Comment by whichonespink44** [comment]
Yep, it's just aesthetics for now.

**Comment by Sunconure11** [comment]
I would say something similar to what is in now, but, maybe add bits of podzol and some rocks here and there.

**Comment by whichonespink44** [comment]
Does anyone have any screenshots of the Bamboo Forest? In the vanilla, non-RTG worlds I've tried generating using only GC 2.3.1/2.4.1, the Bamboo Forest looks exactly like a vanilla Forest and there's no bamboo:

![bambooforest](http://i.imgur.com/Xmynw6c.png)

**Comment by Sunconure11** [comment]
@IceDragon200 Possible bug, maybe see if you can fix this in a dev build

**Comment by IceDragon200** [comment]
@whichonespink44 @Sunconure11 It's not a bug, its a feature! 
Looks like the code was using some old method that was removed in 1.7 (don't forget this was ported from 1.6 previously), I've fixed it in the latest dev build :)

**Comment by whichonespink44** [comment]
Tricksy methodses!

That's awesome - looking forward to the next release :)

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/xap9bt3dpx6h0xy/kendosword.png?dl=0

Here is your kendo sword. I had to pretty much base it against katanas from balkon's weapons. Cheese blocks will come tomorrow.

**Comment by Sunconure11** [comment]
@whichonespink44 

https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/200

Use the latest dev build, growthcraft fixed the bamboo forests.

**Comment by whichonespink44** [comment]
Nice one! :+1:

**Comment by whichonespink44** [comment]
@Sunconure11 @IceDragon200 I know it's only a preview build, but... just an FYI... the latest preview build (95dc5fc) crashes on startup: http://pastebin.com/dA1u6T3h

Adding Forestry prevents the crash.

EDIT: Bamboo Forest is looking good! :+1:

**Comment by whichonespink44** [comment]
Added in 5f00d4b

**Comment by IceDragon200** [comment]
@whichonespink44 Fak I knew I missed something, thanks for pointing that out, glad it works.

Oh, do you have dev builds I could test with?

**Comment by whichonespink44** [comment]
Not anywhere accessible, but I'd like to start doing what you guys are doing with the preview builds. In the meantime, you can either compile our 'dev' branch or I can provide a link to a compiled snapshot in a couple hours.

**Comment by whichonespink44** [comment]
@IceDragon200 Latest development snapshots can be found here:

https://github.com/Team-RTG/Realistic-Terrain-Generation/wiki/Development-Snapshots

**Comment by IceDragon200** [comment]
@whichonespink44 Thanks :D
