### ISSUE TITLE
Crash while exploring on a new world .

### ISSUE THREAD

**Issue by crunkazcanbe** [Team-RTG/Realistic-Terrain-Generation#449]
Crash is here http://pastebin.com/W6bLe8jq I think its due to a biome the rockhounding mod adds If so could you add support ?

**Comment by whichonespink44** [comment]
The End is using biome ID 9, which would suggest an ID conflict. Could you do an NEI biome dump and post it here? I had a quick look at the source code but couldn't see any biomes that get registered by Rockhounding.

**Comment by Zeno410** [comment]
That's probably some kind of CC error. I thought I'd squished that bug but maybe not. Does the problem recur when you reopen the world.

**Comment by whichonespink44** [comment]
Any joy with this @crunkazcanbe? I tried to reproduce the crash with [CC Beta39](https://www.dropbox.com/s/q0vo7477x4vk7wf/ClimateControl-0.4.beta39.jar?dl=0) but couldn't, so it's possible this might've been fixed.

I'll close this for now, but feel free to comment here if it's still happening and I'll re-open it.

Also, just for clarification, Rockhounding definitely doesn't add any new biomes, so no extra support is necessary for this one. All of the Rockhounding world gen seemed to be generating just fine.

Let us know how you get on.
