### ISSUE TITLE
Possible crash between this mod, Natura, RTG, and Streams

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#454]
http://pastebin.com/W4xfG2c1

Started happening after updating to the RC builds, and it continues into 0.50. Is this indeed connected to RTG, or am I going to have the dev of Streams deal with this?

**Comment by whichonespink44** [comment]
It's possible that this is connected to RTG, but I'm struggling to see how.

RTG seems to 'get involved' at [line 603](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/ChunkProviderRTG.java#L603) in ChunkProviderRTG, but all it's doing there is posting a Forge event, which is then triggering stream generation, which is failing.

Do you happen to know what biome exists at these coords:

0,0,16 to 15,255,31

**Comment by Sunconure11** [comment]
Unfortunately, I cannot tell, as every time this error happens, that world crashes is basically corrupt. However, it has happened on worlds in the middle of generation without issue. I'll look into that.

**Comment by Zeno410** [comment]
Somebody has to ask the Streams developer what exactly Streams is requiring that it's not getting.

**Comment by whichonespink44** [comment]
@delvr Any chance you could take a look at the crash report in the OP and see if anything jumps out at you? I believe @Sunconure11 has opened an issue ([#9](https://github.com/delvr/Streams/issues/9)) on the Streams repo if you'd rather discuss there.

**Comment by delvr** [comment]
Sure, I'll take a look and get back to you.

**Comment by whichonespink44** [comment]
@Sunconure11 Do you know if this is still happening in RTG 0.6?

**Comment by delvr** [comment]
Just to let you know I'll be releasing a patch to the Farseek API (used by Streams) tomorrow that should fix this crash (I can't be 100% sure because it's difficult to reproduce, but we'll see how it goes).

**Comment by whichonespink44** [comment]
Awesome, thanks for the update.

I see you're also [releasing an update to Streams](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2346379-streams-real-flowing-rivers?comment=366) as well... can't wait to see what those tunnels look like! :)

**Comment by delvr** [comment]
I've released Farseek API 1.0.11 which should fix this issue; if someone here was able to reproduce it consistently, please let me know if it worked for you.

Also, the Streams update is live. :-)

**Comment by whichonespink44** [comment]
@Sunconure11 Is this still happening for you with the latest version of Farseek? I'm going to assume that it's not, but we can always re-open this issue if necessary.
