### ISSUE TITLE
Ticking block entity crash (RFTools + GenLayerRiverMix)

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#458]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1450

RTG + CC + RFTools - http://pastebin.com/1AbQzP8a

RTG + RFTools - http://pastebin.com/nP9AK9Tr

**Comment by Zeno410** [comment]
I have a guess on why this is happening; I'll test it once I get my fork updated
\

**Comment by Haggle1996** [comment]
Me sticking my nose in other peoples business: I see this crash all the time when trying to load old worlds into newer versions of RTG/CC. I've never encountered it on a map generated with the same version of RTG.

**Comment by whichonespink44** [comment]
That's definitely good to know, but I think particular instance was an actual glitch which Zeno's fixed in 966c072.

Keep sticking your nose in as much as you want mate - your feedback's always appreciated.
