### ISSUE TITLE
New crash with a new world while exploreing . Missing biome

### ISSUE THREAD

**Issue by crunkazcanbe** [Team-RTG/Realistic-Terrain-Generation#461]
As the title says I just created a new world and was flying around and after about 30 minutes or so I got a crash the log is here http://pastebin.com/71yzpzsS

**Comment by crunkazcanbe** [comment]
I logged back into this world it let me ,but after exploring again I have a different crash now here http://pastebin.com/iPsmc9Ez

**Comment by Zeno410** [comment]
That looks like a bug on EB's end. Your setup is apparently using the EB generator and it tried to place biome 255, which didn't exist. Now it's crashing trying to do something with it. You could try the same setup in a default world and see what happens there - I'll bet EB will generate the same biome layout.

**Comment by crunkazcanbe** [comment]
Actually I used the realistic world gen when making this world but I do have EB installed with it to have its biomes in the realistic world gen .

**Comment by crunkazcanbe** [comment]
Mind you as well that second crash happend a long while after logging back into that world . I traveled quit a ways since the spot with the last crash .

**Comment by Zeno410** [comment]
Oh, a little different. But I'd still like to know what EB does with the same seed if RTG is not involved (default or EB world). It should be generating the same biomes.

**Comment by srs-bsns** [comment]
Both of those crashes were caused when ticking pigs in the same general area. The first @ x:521,z:895, and the second at x:512,z:935. So a start might be to go to that location in the world and see what biome is there.

Also, providing a dump of biome IDs might be helpful as well. If you don't know how to do that:
1. Go into the NEI options by clicking the [options] button in the inventory screen (bottom left)
2. Tools -> Data Dumps
3. There should be 2 buttons beside Biomes. Click 'Used' until it says 'All' then click 'Dump'. This will create the file <minecraft dir>/dumps/biome.csv, which is just a text file. Paste this to pastebin.

**Comment by whichonespink44** [comment]
@crunkazcanbe Are you still having this issue in RTG 0.6?
