### ISSUE TITLE
Question regarding BiomeTweaker and this mod

### ISSUE THREAD

**Issue by Sunconure11** [Team-RTG/Realistic-Terrain-Generation#468]
BiomeTweaker has an option to create custom biomes. Is it possible for said biomes to spawn in your world type?

**Comment by whichonespink44** [comment]
I'm not sure (never tried it), but I'm almost certain it's not possible.

At the moment, RTG checks to see if there's a realistic version of each biome it places, and if it doesn't find one, it throws an exception.

**Comment by Zeno410** [comment]
A "realistic" biome will need a realistic terrain module and a realistic surface module, neither of which will be in a BiomeTweaker config. There could be other issues as well. Potentially, depending on how the config system comes out, it might be possible to have custom biomes in RTG but that's a ways off.

**Comment by srs-bsns** [comment]
Just to put this question to bed, No, a BT custom biome will crash RTG (Tested):
```
java.lang.RuntimeException: No realistic version of biome [ID]
```

**Comment by whichonespink44** [comment]
Thanks for testing that @srs-bsns - As Zeno mentioned, creating biomes with BiomeTweaker might eventually be possible once the API's biome support has been implemented, but I'd have to put in special functionality for it to work. Right now (or rather, when the first iteration of the API is complete), biome-adding mods will be able to add support for their own biomes.
