### ISSUE TITLE
No realistic version of biome 152 with Extra Planets

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#474]
http://pastebin.com/fxgKngww

mod list ^

in the extraplanets config

`   
    I:"Triton Biome ID"=161
    I:"Uranus Biome ID"=152
    I:"Venus Biome ID"=149
`

**Comment by srs-bsns** [comment]
From [RTG's MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes) under _**Known Issues**_:

```
No realistic version of biome X - A lot of people have been experiencing crashes that contain this
message: "java.lang.RuntimeException: No realistic version of biome X", where X is a biome ID.
This crash is usually caused by either a biome ID conflict of some sort, or by a mod that adds a
biome which RTG doesn't support. Here are some things you can do to help prevent this crash
from happening:

* When configuring biome IDs, try to avoid using IDs 128 through 167, as these are reserved for
vanilla's 'mutated' biomes and can cause strange behaviour even when mutated biomes are disabled.
(You should also avoid ID 255 if possible.)
```

**Comment by whichonespink44** [comment]
@Tsyklop Did you ever manage to get this working? If not, zip up your entire config folder and your fml-client-latest.log and post a Pastebin/DropBox link here and we'll re-open the issue and investigate further. If it's not the mutated biome ID issue, I suspect it might be related to BiomeTweaker configs. Either way, we're releasing a feature in 0.6.1 called 'biome patching' which will prevent these types of crashes from happening (unless you want them to).

**Comment by Sharkking** [comment]
I had a similar crash yesterday

http://pastebin.com/nteBKQzc

ExtraPlanets.cfg:    I:"Uranus Biome ID"=152
using biomes´o´plenty as well and no BiomeTweaker

Is there or can you add an option to blacklist biome-id´s in RTG ?

**Comment by Sharkking** [comment]
I have changed the Extraplanets biomes to

biomeid {
    I:"Callisto Biome ID"=168
    I:"Ceres Biome ID"=169
    I:"Deimos Biome ID"=170
    I:"Eris Biome ID"=171
    I:"Europa Biome ID"=172
    I:"Ganymede Biome ID"=173
    I:"Io Biome ID"=174
    I:"Jupiter Biome ID"=175
    I:"Mercury Biome ID"=176
    I:"Neptune Biome ID"=177
    I:"Phobos Biome ID"=178
    I:"Pluto Biome ID"=179
    I:"Rhea Biome ID"=180
    I:"Saturn Biome ID"=181
    I:"Titan Biome ID"=182
    I:"Triton Biome ID"=183
    I:"Uranus Biome ID"=184
    I:"Venus Biome ID"=185
}

and make a new test.

**Comment by Sharkking** [comment]
it seems to work so far. No crash when exploring the same region in DIM0 again.

**Comment by whichonespink44** [comment]
Thanks for confirming that changing the IDs worked.

RTG 0.6.1 will introduce something called 'biome patching' which will prevent these crashes from happening.

**Comment by Sharkking** [comment]
Thanks for your attention
