### ISSUE TITLE
Trees(except Palms) growing in the desert on biome borders

### ISSUE THREAD

**Issue by Lodugh** [Team-RTG/Realistic-Terrain-Generation#481]
Saw some acacia trees grow inside the desert. I dont think it is wanted like that, right?
Here is a screenshot:
![2016-02-07_01 13 51](https://cloud.githubusercontent.com/assets/13154183/12870207/3c7ff514-cd3a-11e5-8e4a-0e4e4af07859.png)

**Comment by whichonespink44** [comment]
This is part of the new decorative biome transition system, so it's intended behaviour, but I see what you're saying and kind of agree with you that it looks weird in this particular transition from Savanna to Desert.

When decorations like trees and other biota bleed from one biome into another, it usually looks pretty good. Maybe we can look into preventing decorations from bleeding into desert biomes, but if I remember correctly, it would be pretty tricky to implement, if it's even possible at all.

**Comment by Zeno410** [comment]
When RTG is placing the decorations, you can prevent some of these kinds of problems by placing restrictions on the surface block it's placed on. So you could just not place Acacia trees on sand. Birch forest has this neat trick where it places birch shrubs on sand - works pretty well.

**Comment by Zeno410** [comment]
http://makingtalmidim.blogspot.com/2013/11/trees-of-desert-acacia.html

**Comment by whichonespink44** [comment]
_"When RTG is placing the decorations, you can prevent some of these kinds of problems by placing restrictions on the surface block it's placed on."_

Might put something like that in the biome configs at some point, but now that I've seen that link about Acacias in the desert, this doesn't look weird to me at all anymore. :)

**Comment by Lodugh** [comment]
Yeah I was already thinking that it might be realistic, I just didnt like the looks. Would be nice to have something like that in the configs :). It would be enough if there'd be an option that trees only can grow on dirt or something like that.

**Comment by whichonespink44** [comment]
I'm just doing some work on the biome configs now, so I'll see if I can sneak something like that in there before tonight's release - if not, I'll definitely get something in there next time.

**Comment by Lodugh** [comment]
Great, thank you!

**Comment by whichonespink44** [comment]
Added a config option called "Allow Trees to Generate in Sand" in 164a9e1, but just realised that currently it prevents Palm Trees from generating on beaches. Hmmm. I'll fix that before I push it to `master`
