### ISSUE TITLE
Future of configs.

### ISSUE THREAD

**Issue by Claycorp** [Team-RTG/Realistic-Terrain-Generation#486]
Is there anything in the works or planned where configs will not need to be deleted constantly? Personally it doesn't affect me much but I feel that people who customise the crap out of stuff are going to get sick of the constant wipes. Even a backup of the configs would be a good idea if nothing else can be done.

Just thought I would point this out. (Yes I understand this is a Beta/Alpha mod.)

**Comment by whichonespink44** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1559

It's a fair point for sure, so I've updated the release notes for 0.6. To be honest, it's just something I write out of habit to ensure that everyone's using the same configs, but it's really not necessary to delete the RTG config folder unless the structure of the folder changes, and even then it's just to avoid confusion as to which files do what.

From now on, I'll only recommend deleting the RTG config folder when necessary.
