### ISSUE TITLE
Linear type snow cover on Extreme Hills

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#487]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1560

Mohawky noticed some linear snow cover during testing. I haven't seen this in the few words that I tested, but thought I'd mention it here. Maybe it's just a one-off?

http://i.imgur.com/PxU6pX9.jpg

**Comment by Zeno410** [comment]
I couldn't see exactly what was wrong there. I'm guessing it's some jumbled biomes, which would be a CC problem, but I've never seen anything like that.

**Comment by whichonespink44** [comment]
I'll close it for now, and we can always re-open if it starts happening more frequently.
