### ISSUE TITLE
Latitudinal Biome Placement

### ISSUE THREAD

**Issue by UndeadZeratul** [Team-RTG/Realistic-Terrain-Generation#493]
One of the things that drew me into ATG (and actually probably the only thing keeping me from jumping ship to RTG) is the ability to determine where to place what biomes based on a temperature and rainfall scale.  I'm pretty sure RTG and CC do this to some extent, but I couldn't find the Latitudinal form of determining temperature that ATG supports.

Basically, what I'm looking for is the ability to say that x=0 is the equator of my world (or maybe even a temperate climate, which is what ATG does), and that travelling a certain amount of blocks north or south means travelling to the poles, where the the temperature gets colder and colder.  Travelling east or west keeps the temperature roughly the same, as one would expect.  This way biomes are placed less randomly and more logically based on the distance from the north/south pole and the equator.

I could not find the ability to do this anywhere, but if this is possible then let me know, as I'd love to have the terrain generation of RTG combined with the biome placement of ATG.

**Comment by whichonespink44** [comment]
I believe @KdotJPG is working on a biome layout system that might make this possible, but I'm not sure about the specifics.

**Comment by Zeno410** [comment]
There's no latitudinal system in CC or in any of the other layout managers I'm aware of. It's on my mental list of possible enhancements, but it's not natural with the CC system.

**Comment by UndeadZeratul** [comment]
Oh, ok well then I guess at least I'm not asking something that already exists in RTG's scope.  I'd feel pretty silly if I was asking for something that was already doable.  I figured, considering all the steps to make the terrain generation as "realistic" as possible, why not extend that into the biome layout management as well?

**Comment by whichonespink44** [comment]
Closing as it's outside RTG's scope.

**Comment by UndeadZeratul** [comment]
Aww, that makes me sad.  If it can't be worked into RTG itself, would you know of any alternative methods to achieve the desired effect?  Would I need to ask CC's devs, maybe?

**Comment by whichonespink44** [comment]
One of the things we're going to do at some stage is contact the various biome-**layout**-adding mod authors to see if they'll add support for RTG. For example, Enhanced Biomes already allows RTG to use its biome layouts, so if you use RTG with only Enhanced Biomes (without CC or BiomeTweaker), you'll get EB biome layouts. RTG could use BOP biome layouts, but it would require the BOP devs to add a line of code.

Following on from that... maybe we could do the same thing with ATG? I'm not sure if ATG actually has its own biome layouts, but if it does, maybe we could approach the mod authors to see if they could allow RTG to use ATG biome layouts? That way, you could have the latitudinal biome layouts from ATG whilst using an RTG world type for the realistic terrain.

All depends on whether ATG does its own biome layouts, which I'm assuming it does but will need to look at the code to be certain.

**Comment by UndeadZeratul** [comment]
Hmm, It's hard to say because ATG doesn't have any visible source that I'm aware of (EDIT: looks like the source was recently added [here](https://github.com/TTFTCUTS/ATG)), but from what I know of how it works (in 1.7.10 at least), is that it manages it's own map of integers for rainfall, temperature, and height.  At any given X,Z coordinate, depending on the 3 dimensions provided by the maps, ATG determines what biome should be at that location.

How it determines those numbers is based on several factors, but they tie into terrain generation as well because as I said, one of the dimensions is height, which is the baseline terrain height used (he has terraingen modifiers that RTG COULD hook into, but I'm not sure how effective that route would be).  Temperature can either be randomly plotted, or laid out in horizontal waves (the latitudinal layout) based on some other nuanced factors.

Again, not entirely sure how easy it would be to intertwine ATG's biome layout system with RTG's terrain generation, but given what little I know, the immediate path would be to look into their TerrainGenMod classes and see what you could leverage there.

Otherwise, we'd have to ask @TTFTCUTS what he would suggest.

**Comment by Zeno410** [comment]
I don't think ATG could function as a layout manager. Unlike every other system I'm aware of, ATG generates terrain *first* and then generates the biome map from that, in conjunction with some other things like latitude. If generation isn't coupled to the chunk manager, then he could generate a fake world height map, produce a biome map, and send that to RTG. It would be slow, but possible. But RTG couldn't do that - the height map generation is all tangled up with chunk generation.
