### ISSUE TITLE
Village material config options

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#501]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/392#issuecomment-180260038

Not sure this falls within RTG's scope, but we'll already have the infrastructure in place when #392 is resolved, so I might consider it.

**Comment by Zeno410** [comment]
For wood, I assume? Good other than we'd probably have add a var for each biome for it. There is a default tree for many biomes you might be able to use.

**Comment by whichonespink44** [comment]
I'll be back-porting the village config system from 1.8 tonight/tomorrow, so hopefully this will make it into the 0.7 release on Sunday.

**Comment by whichonespink44** [comment]
Change of plans - the village config system is being pulled out of the 1.8.9 version of RTG and turned into a standalone mod. As such, we will not be backporting anything to the 1.7.10 version.

However, there's still the occasional glitch with the desert villages being part-desert, part-regular, so we might need to implement some of that code if we can't find another fix.

**Comment by topisani** [comment]
i might have a way to fix the well thing without using a custom StructureVillagePieces. If it works i put it in 1.8.9 and you can port it. basically it should be possible to skip the VillageBlockId event and just set isDesert in MapGenVillageRTG. This means it will use vanilla's block replacing.

**Comment by topisani** [comment]
The problem is vanilla is of cause checking biomes using instanceof and not biomeIDs. But we should be able to set that variable manually
