### ISSUE TITLE
thoughts about rivers

### ISSUE THREAD

**Issue by Xexanos** [Team-RTG/Realistic-Terrain-Generation#503]
Hey folks,
I was thinking about some config options regarding rivers.
1. would it be possible to add a percentage to decrease river generation similar to cc?
2. add min/max width option to rivers
3. set min/max width of beach (relatively flat area filled with block(s) depending on neighboring biomes)

Additionally it would be nice to have the rivers more curvy (maybe add a sin based modificatior with a period of 100 - 120 Blocks)
Another thing is, that rivers cutting through elevated terrain often course strange breaks in the landscape. Would it be possible to smooth them of? Or, if you don't like this or it isn't possible to implement, could you implement the generation shown in [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1304) (which would actually work realy good with config option #3 from my list^^)?

**Comment by lebanni** [comment]
May I suggest river flowing down mountains through lakes to ocean ? Unless Streams improve the way they are generated.

**Comment by Zeno410** [comment]
The way the are done, it would be possible to make rivers rarer, it would be possible to make rivers wider or narrower on average, and it would be possible to make them more or less curvy. I don't think it would be possible to put limits on river width - it's not like the GenLayer process where you have a line of "river" which gets wider, it's a noise algorithm which tends to put 0's in linear groups.

RTG isn't going to do flowing rivers. It would be a huge projects and would require completely changing how we do rivers. Besides, that's what Streams is doing and I see no reason to duplicate that work.

**Comment by whichonespink44** [comment]
I've added the doable config options as a separate issue (#516)
