### ISSUE TITLE
Too small biomes resulting in seemingly misplaced structures

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#528]
![2016-02-21_18 32 09](https://cloud.githubusercontent.com/assets/3133596/13204677/5e497dda-d8d6-11e5-9fb8-27f2dbc8eb15.png)
The yellow wool is a tiny desertbiome, and that is why the temple spawns.
Two aproaches could be taken:
1. Check how much of the structure would be in the correct biome before spawning it
2. Somehow make sure biomes this small wont happen
Id go for 2, as the small biomes also sometimes result in something like desert - tiny extremehills - ice mountains, which will look like desert - icemountains

Btw: this was in 1.8.9, i would be very surprised if it wouldnt have happened in 1.7 too though, thats why im posting it here

**Comment by Zeno410** [comment]
Changing structure generation is out of our scope. What's generating the biome layout? That's the primary problem.

**Comment by topisani** [comment]
Agreed, and I don't know the answer to that question myself

**Comment by whichonespink44** [comment]
Moving this to the 1.8 tracker.
