### ISSUE TITLE
Saplings for RTG trees.

### ISSUE THREAD

**Issue by Claycorp** [Team-RTG/Realistic-Terrain-Generation#533]
Please oh god please add some sort of saplings for the trees. You could just do some crafting recipes to make them attainable instead of relying on drops because you only use vanilla leaves/logs.

They are amazing and I guarantee people would love to grow them. I personally love the willows the most.

**Comment by whichonespink44** [comment]
This is an extremely popular request, but unfortunately it's outside the scope of this project.

However, we'd be more than happy to work with any mod developer who wanted to make this as an addon mod, including exposing RTG's tree classes to the API.

If I ever get some free time I might do it myself, but it's not going into RTG itself, sorry.

**Comment by Claycorp** [comment]
Awh. Tis a shame. At least you will be willing to work with someone if anyone wants to do it.

**Comment by whichonespink44** [comment]
Not only that, but I'd love to use it in my survival worlds too! :)  Like I said, if I ever get some free time, I'll try to do it myself if someone doesn't beat me to it first.

**Comment by ChilledDayz** [comment]
I have to say that would be an awesome additional. To an amazing mod.

**Comment by whichonespink44** [comment]
@Claycorp @ChilledDayz Just a quick one to let you know that vanilla saplings can grow RTG trees as of version 1.0-snapshot-2.

This post explains the functionality in more detail: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2933

**Comment by Claycorp** [comment]
Interesting way to implement it. Now you can at least grow them around your home area to keep it matching the rest of the biome. Still looking forward to the saplings though as I would like to move tree types around the world.

**Comment by whichonespink44** [comment]
Yeah, it's definitely not ideal, but it's the best we could do without making it an addon. The custom saplings will likely come in the form of an addon for the 1.9.4 version at some point.

**Comment by whichonespink44** [comment]
@Claycorp I would also like to move tree types around in my world, and I've just figured out how to do it... essentially you need a mod like [Biome Wand](http://spacechase0.com/mods/minecraft/biome-wand/) or [Biome Reactors](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2655049-biome-reactors-1-0-2-change-biomes-using-redstone) or something similar, and then it's just a case of changing the biome to match whatever tree you want (and then changing it back afterwards if you want).

Granted, that's a helluva lot of work just to grow a tree, but... it'll hold me over until the addon is a thing.
