### ISSUE TITLE
Change desertShadowBlock

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#540]
the current dessert shadow block is quite dark. I recomend we change it to the lighter white hardened clay.

Just some images:
first one is the current.
![2016-02-22_01 10 14](https://cloud.githubusercontent.com/assets/3133596/13372980/266ec59e-dd5b-11e5-9816-dc305b13aa72.png)
![2016-02-23_17 07 47](https://cloud.githubusercontent.com/assets/3133596/13372985/3ea202c0-dd5b-11e5-87b7-ba2a463e1984.png)

Yes it is slightly more to the pink side, but i still think it fits better.

**Comment by whichonespink44** [comment]
:+1:

**Comment by whichonespink44** [comment]
Fixed in 18e6360
