### ISSUE TITLE
Add support for Amberoguia

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#542]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293792-1-8-1-7-10-forge-ssp-smp-amberoguia-mod-v1-5-adds

**Comment by whichonespink44** [comment]
@Zeno410 If I wanted to add support for these last few biome-adding mods, would it be safe to 'borrow' some of the existing terrain templates you've created and apply them to the biomes from these mods? Or would you still need to get involved in order to make sure everything was 'flowing' together smoothly?

For example, if Amberoguia adds a Foresty type biome, could I just use the vanilla Forest terrain and add custom decorations as appropriate?

**Comment by Zeno410** [comment]
Sure, if you want "looks like x" you can copy the code, make a child, use the object, whatever. Only thing to be aware of is the noWaterFeatures and noLakes flags, which are in RBB, not TB, and a very occasional biome that overrides lake generation to change it (like Bayou).

**Comment by VelocityRa** [comment]
The Amberoguia biome is discontinued for the 1.7.10 version of the mod, therefore not RTG compatibility is needed.
[Source/Quote from the dev](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293792-1-8-1-7-10-forge-ssp-smp-amberoguia-mod-v1-5-adds?comment=112)
