### ISSUE TITLE
Add support for SushiCraft

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#545]
http://www.curse.com/mc-mods/minecraft/235736-sushicraft#t1:other-downloads

**Comment by VelocityRa** [comment]
SushiCraft's decoration system is quite unusual so it's not possible for RTG to be compatible with it, only way is to ask the dev to change the way they do things, which is not necessarily what we want to be focusing on right now.

If there is interest reply here and I'll reopen the issue, but form the time being it will remain closed.
