### ISSUE TITLE
1.8.9-Add Support for the Agricultural Revolution Mod

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#550]
http://minecraft.curseforge.com/projects/the-agricultural-revolution

**Comment by srs-bsns** [comment]
This is in the wrong place. You want to post in https://github.com/Team-RTG/1.8.9-Realistic-Terrain-Generation/issues for RTG 1.8.9.

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by whichonespink44** [comment]
Yep, this has already been added to the 1.8.9 tracker (https://github.com/Team-RTG/1.8.9-Realistic-Terrain-Generation/issues/24) and will likely be in the next alpha release of 1.8.9

**Comment by WenXin20** [comment]
Ok, cool
