### ISSUE TITLE
[EDIT:NO BUG]Highlands compatibility broken in 0.7.0?

### ISSUE THREAD

**Issue by Lodugh** [Team-RTG/Realistic-Terrain-Generation#552]
Im using RTG 0.7.0, Highlands 2.2.3 and BiomeTweaker 1.2.128 and I cant find any Highlands Biomes. I have some other mods runnig alongside those but I dont really think they would affect that part of the game. Or does it work for anyone else?

Greetings,
Lodugh

**Comment by Zeno410** [comment]
If you play a default world, do you get Highlands biomes? If you do, it's an RTG problem, if you don't your BiomeTweaker setup is not right.

**Comment by whichonespink44** [comment]
@Lodugh I don't think you have to include the Thaumcraft biomes in the BiomeTweaker tweaks, unless you want to control how often they generate (weight). I haven't actually confirmed that though, so I could be wrong.

**Comment by topisani** [comment]
at least in 1.8 you are not wrong
