### ISSUE TITLE
Automatically generate the relevant tweaks if BiomeTweaker is installed.

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#553]
Currently, if someone is using BiomeTweaker, they have to copy & paste the example tweaks from GitHub. Granted, this is much easier than having to do them from scratch, but it's still a cumbersome process and a sizable barrier-to-entry, especially for people who are new to RTG or BT or just terrain generators in general.

It would be nice if RTG could detect BT on startup and generate the RTG.cfg file if it doesn't exist. Then the only thing the user would have to do is modify BiomeTweaker.cfg to include the RTG.cfg file.

Ideally, this process should automatically detect all of the RTG-supported biomes that have been registered and include them in the RTG.cfg file.

**Comment by topisani** [comment]
Ideally I think we should be able to do without. But if that's not possible, this is definitely the next best option. I might take another look at the per world config and config guis and if those happen we could have a button in there to generate those files

**Comment by Zeno410** [comment]
I agree it's worth doing. We could probably include copies of the files in the mods resources and just copy them, if somebody could figure out how to access the mod resource directories.

**Comment by topisani** [comment]
in 1.9 this would be killed by removing the BiomeTweaker dependency [#15](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues/15)

**Comment by srs-bsns** [comment]
>We could probably include copies of the files in the mods resources and just copy them

Since biome IDs are not static (for mod added biomes, anyways), it would probably be best to generate them from the loaded game so that all biome IDs are set correctly. Or atleast generate the parts of the configs that we need to from a template. Because it seems that the biggest problem that people run into are biome IDs that don't line up with our current default configs, and the default configs are only designed for single mods anyways, and not combinations.

**Comment by topisani** [comment]
i think we can skip this, as it is obsolete for 1.9 anyway, and its probably too involved for a feature that will only be used for 1.0

**Comment by whichonespink44** [comment]
> as it is obsolete for 1.9 anyway

That's not a valid reason to skip it, imo.

Having said that, if no one wants to tackle this one, then I don't mind removing it from the 1.0 milestone. Climate Control, in many ways, serves the same purpose as BiomeTweaker, so it's not like people don't have an easier alternative.

**Comment by whichonespink44** [comment]
Incidentally, I just went to check the forums after removing the milestone for this, and this is what I see: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2392

**Comment by topisani** [comment]
yeah, i was just thinking, its a pretty big thing to do (i think). I think a better OP description, and maybe recomending CC out of the box is a better way to do this

**Comment by srs-bsns** [comment]
No point in attempting to implement this in 1.7.10 now.
