### ISSUE TITLE
Biome rewrites/cleanups

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#557]
Just thought we needed a central checklist for biomes that need to be cleaned up in some way, since you often see them, but then forget about it later.
Add them all here!

- [ ] Vanilla Mesa (mainly cleanup work, could maybe use some of the new savanna plateau code)
- [ ] Vanilla Desert M (ugh)
- [ ] BOP Sacred springs: large underwater areas
- [ ] BOP Moor: should be higher
- [ ] BOP Fungi Forest: A little low
- [ ] BOP Eucalyptus Forest: flooded areas?

**Comment by Zeno410** [comment]
Sacred springs: large underwater areas
Moor: should be higher
Fungi Forest: a little low
Eucalyptus Forest - flooded areas?

**Comment by topisani** [comment]
![](http://i.imgur.com/3agSTEq.jpg)
forrest hills? anywhere we could use something like this?

**Comment by whichonespink44** [comment]
That's actually what I was trying to achieve with my '[Rolling Hills](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/dev/src/main/java/rtg/world/gen/terrain/TerrainRollingHills.java)' template, but... my limited understanding of noise stopped me from taking it any further.

I originally thought the '[Grassland Hills](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/dev/src/main/java/rtg/world/gen/terrain/TerrainGrasslandHills.java#L17)' template could achieve this (and still might), but I wasn't able to plug in the right noise values

**Comment by Zeno410** [comment]
There probably aren't enough octaves in the current templates. The "rolling hills" has only three octaves, and there's a wide gap between the 200 wide hills noise and the 50 wide longer ground noise. That looks doable with our current tools. The other thing you'd want to do for that is a transform on some of the noises to make them "pointier" - take the 1.3 power of the noise or something like that.

**Comment by Zeno410** [comment]
That kind of stuff would like a full biome to operate in - xxx hills isn't good because of the smoothing issue. Loads of candidate biomes in the mod biomes. Vanilla is short if you're trying to keep the feel of the vanilla biomes - Taiga and Cold Taiga are the only "hilly" biomes I can think of (maybe MegaTaiga?)

**Comment by whichonespink44** [comment]
I think all of the biomes in the OP have been sorted (except Desert M, which I'll be getting to shortly), so I'm going to close this. If there are any specific biomes, that need a makeover, we can always create another issue.
