### ISSUE TITLE
AE2 biom

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Team-RTG/Realistic-Terrain-Generation#559]
http://hastebin.com/fasuvixezo.md
periodic crash the client when you run the world
146 this biome AppliedEnergistics2

I found a world conflict
AE2 in the world -11, and -11 in ThaumicTinkerer. I'm in a ThaumicTinkerer.cfg changed to -19
And it seems then, became generated biome of AE2 but it should not ...

**Comment by srs-bsns** [comment]
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/474
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/466
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/455#issuecomment-176828067

**Comment by whichonespink44** [comment]
@SvEgiiVEteR Please also see these two recent forum posts:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1869

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1870

There is most likely a biome ID conflict of some sort that you will need to resolve and/or BOP biome IDs were changed.

To help find the conflict, you could try using [Anti ID Conflict](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2387300-say-no-to-id-conflicts-install-anti-id-conflict) mod.

I'm going to close this issue, but please let us know if none of these solutions help and we'll re-open it.

**Comment by SvEgiiVEteR** [comment]
@whichonespink44 
the problem did not exist before.
Then I changed the ID of all biomes
BOP made the default.
others put one after the other

AE used to be 154 in past
dump
old, where there was no breakage
http://hastebin.com/gubixakoti.avrasm
new breakage
@srs-bsns 
thanks for the info
http://hastebin.com/kabuquvete.avrasm

It seems some ID 128-167
do not cause breakage the game
For this reason, before I did not have such a problem ...
Now I have changed AE2 200
I will continue to watch, maybe what that ID (128-167) break the world
