### ISSUE TITLE
RTG requireing a non-exsistant version of Growthcraft?

### ISSUE THREAD

**Issue by InkDragon** [Team-RTG/Realistic-Terrain-Generation#563]
every time I try to start up with growthcraft installed I get the following error:

[Client thread/ERROR]: The mod RTG (Realistic Terrain Generation) requires mod versions [Growthcraft|Bamboo@[1.7.10-2.5.0,)] to be available

only problem is that there is no 2.5.0 version... the latest version is 2.4.0

**Comment by Sunconure11** [comment]
Not non-existent, it is being built around the preview builds, which will get a full release at an unknown time. For now, turn off growthcraft biomes, unless you want to use the preview builds (note: clear all of your old configs for growthcraft, and set back any changes beforehand)

https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/200

**Comment by InkDragon** [comment]
thank you for pointing me at the new growthcraft build. I'll switch to that, as it seems less of a hassle in the long run
