### ISSUE TITLE
Crash on Server startup - java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by rckymtnrfc** [Team-RTG/Realistic-Terrain-Generation#564]
I'm seeing this with version 0.0.4.

http://pastebin.com/8hAZP9TG

Thanks!

**Comment by srs-bsns** [comment]
You are reporting to the wrong repo. You want to go here: [Team-RTG/1.8.9-Realistic-Terrain-Generation/issues](https://github.com/Team-RTG/1.8.9-Realistic-Terrain-Generation/issues)

**Comment by rckymtnrfc** [comment]
Sorry, I didn't realize you had these split.  I'll post it there, thanks!
