### ISSUE TITLE
RTG+Bop Lots of Mushroom Biomes

### ISSUE THREAD

**Issue by Aldjeron** [Team-RTG/Realistic-Terrain-Generation#566]
I've tried everything I can see I can change including turning off the actual MushoomIsland Biome generation to no avail. Regardless of what genWeight I set I still get tons of MushroomIsland Biomes all over the overworld not even as islands. Has anyone else had this issue? or better know how to fix it?
I'm using the available cfg files for the RTG+Bop files as a base. I've added other things for the pack such as the Thaumcraft, Ars 2 and Buildcraft with no issues. Except still have 75% mushroomisland.

PS I'm using BiomeTweaker

**Comment by Zeno410** [comment]
There's a mushroom island problem with BoP. MohawkyMagoo posted a fix for it in either the RTG or the CC threads a while back.

**Comment by whichonespink44** [comment]
Here's the post where MohawkyMagoo explains how to resolve the BOP/Mushroom Island issues:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1489

Good luck!

**Comment by Abalieno** [comment]
Not funny.

**Comment by srs-bsns** [comment]
AYFKM?! Necroposting in a 7 1/2 year old closed issue?
