### ISSUE TITLE
WAILA shows wrong wood type

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#575]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=1941

**Comment by whichonespink44** [comment]
Looks like this is something that will need to get sorted on WAILA's side.

@VelocityRa has submitted a ticket on the WAILA tracker: https://bitbucket.org/ProfMobius/waila/issues/254/wood-always-displaying-as-oak-when-rotated

**Comment by topisani** [comment]
if this is a waila bug, do we need to do anything?
Btw, i noticed there are no issues with this in 1.9

**Comment by whichonespink44** [comment]
Nope, this out of our hands.

**Comment by srs-bsns** [comment]
>Btw, i noticed there are no issues with this in 1.9

Probably due to the new system of using BlockStates, which lessens the chance of these kind of things from happening.

**Comment by topisani** [comment]
if this is out of our hands, cant we close this? there probably wont be any  waila updates for 1.7 anyway

**Comment by VelocityRa** [comment]
Yeah I was thinking that as well, this shouldn't be on *our* Issue traker, it's WAILA's bug.

**Comment by topisani** [comment]
this is delta 5 to supreme leader ( @whichonespink44 ). requesting permission to close issue

**Comment by VelocityRa** [comment]
This is Ground Control to Major Pink

**Comment by whichonespink44** [comment]
I think we should leave it open so people are aware that it's a known issue, but... it's not assigned to a milestone, so this one's effectively closed.

**Comment by topisani** [comment]
@VelocityRa im pretty sure pink IS ground control

**Comment by srs-bsns** [comment]
I think leaving this issue open has run it's course, and I don't think this is an issue is WAILA beyond 1.7.10
