### ISSUE TITLE
BoP Biomes don't generate

### ISSUE THREAD

**Issue by Charnuz** [Team-RTG/Realistic-Terrain-Generation#580]
BoP Biomes do not generate using the Realistic world generation type. Using non-edited configs for both BoP and RTG. Is this intended?

Used:
BiomesOPlenty-1.7.10-2.1.0.1889-universal
RTG-1.7.10-0.7.0
forge-10.13.4.1614

**Comment by whichonespink44** [comment]
If you want to generate biomes from Biomes O' Plenty, Highlands, or ATG, you will also need to install either [Climate Control](http://goo.gl/6c9Htb) or [BiomeTweaker](http://goo.gl/hy502C).

Please see the first post of the official forum thread for installation and configuration instructions:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes
