### ISSUE TITLE
Bug where Biomes meet

### ISSUE THREAD

**Issue by Gravenknob** [Team-RTG/Realistic-Terrain-Generation#586]
https://gyazo.com/736643959e42358e880e67d21ae8dc91
This has been happening a lot on my BoP mod since I installed this mod.
Other mods that may influence this are Tinker's construct, NeoTech, Buildcraft, and Thaumcraft.

**Comment by Gravenknob** [comment]
I also have BiomeTweaker*

**Comment by Zeno410** [comment]
That looks like a chunk wall from altered biome placement, which is not something RTG does. Isn't that vanilla terrain? One thing to be aware of is that almost any change to your biome set, no matter how small, will scramble biome placements and cause chunk walls all over the place (unless you're using Climate Control, which can stop that).
