### ISSUE TITLE
Mesa terrain

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#590]
I watched breaking bad, made me realize the current mesas look nothing like mesas. Plateaus need to be flatter, with a kinda hill going up the side
![](http://www.newstatesman.com/sites/default/files/images/40c0e441-6e31-127e-fa46-7dc6debc9685_BB_513_UC_0211_0048.jpg)
You can assign me and milestone this for 0.8.0

**Comment by whichonespink44** [comment]
Duplicate #594
