### ISSUE TITLE
Split rivers

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#591]
![2016-03-25_18 41 48](https://cloud.githubusercontent.com/assets/10927161/14057490/0d147c70-f2f9-11e5-9731-f34297529157.png)

![2016-03-25_18 44 00](https://cloud.githubusercontent.com/assets/10927161/14057492/14d594f8-f2f9-11e5-93ad-4521f7ca0de3.png)

I noticed this as I was taking the new screenshots - hadn't seen it before today.

As cool as I think it looks, I'm assuming it's not intended behaviour?

**Comment by Zeno410** [comment]
Very much not. I haven't seen it, strangely. This is in the 1.7.10 version? Can you give me a vanilla seed and location?

**Comment by whichonespink44** [comment]
Yep, 1.7.10 with RTG 0.8.0-snapshot-1 only.

Seed=753548930

It should spawn you right in the split river, but if you want to see where it starts, you can TP to -258 90 57. It starts there and then eventually dissipates into a swamp biome.

**Comment by Zeno410** [comment]
It's a problem from the hack I put in to cover up the bug in the simplexCellular code. I could try to hack the hack, but it would be better for Kdot to fix the point distribution. I don't know what algorithm he's using so I have no idea how to properly fix the problem.

**Comment by whichonespink44** [comment]
@KdotJPG Any ideas on this one?

**Comment by whichonespink44** [comment]
@Zeno410 @KdotJPG I haven't seen this in snapshot 2 - is it safe to close this one?

**Comment by Zeno410** [comment]
It's safe to close this particular one.
