### ISSUE TITLE
Coastal Cliffs

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#592]
![falaise-etretat-domaine-saint-clair-le-donjon_1200 600 crop-s photo e8b03](https://cloud.githubusercontent.com/assets/10927161/14060436/4fcc32f2-f35c-11e5-9b3d-efe68b831db6.jpg)

In early alpha, RTG had some [legacy 'coastal cliff' code](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/v0.0.1/src/main/java/rtg/biomes/realistic/coast) that got ported across from RWG, but it wasn't working. The framework for them appeared to be [only](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/v0.0.1/src/main/java/rtg/biomes/realistic/RealisticBiomeBase.java#L110-L152) [partially](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/v0.0.1/src/main/java/rtg/world/ChunkManagerRealistic.java#L269) [implemented](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/v0.0.1/src/main/java/rtg/world/ChunkManagerRealistic.java#L432), so I removed it (although the author of RWG did post some screenshots of them working on his Twitter account, but they must've been from his development environment).

I think this should be something we look at for v2.0 but just posting it here for reference.

**Comment by Zeno410** [comment]
This ties into the general issues of cliffs. Cliffs on the edges of biomes would be nice but the smoothing system is very hostile. The best way I can think of is to add information about the biome neighborhood to the terrain call and add in some fiddly special-case code in all the biomes concerned. Basically all the local biomes have to generate exactly the same terrain.

**Comment by topisani** [comment]
Still got Plans for this in 1.7? If so, I'm definitely up for taking a look at it

**Comment by whichonespink44** [comment]
I was thinking this was probably more of a v2 thing, as I believe it would require some pretty heavy modifications to the beach & biome repair systems.

**Comment by topisani** [comment]
Yep, good idea. Will you close this and make one in the v2 repo?

**Comment by whichonespink44** [comment]
https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues/75
