### ISSUE TITLE
RTG{1.9-0.0.1} crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [Team-RTG/Realistic-Terrain-Generation#593]
Issue: RTG{1.9-0.0.1} crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/e8e2f168da1a9bd655d0

fml server latest:
https://gist.github.com/2e88374acaa8218f2ee8

**Comment by srs-bsns** [comment]
We are aware of this. RTG-1.9-0.0.1 was built against Forge 1804, but the Forge team have commit a lot of changes in the last few updates that changes the way data is accessed. Things are going to be a bit shakey for a while.

**Comment by whichonespink44** [comment]
I could release v0.0.2 which would solve this issue for now, but... as srs-bsns mentioned, Forge is undergoing some intense refactoring, so it will likely crash again the next time you upgrade Forge.

I'll try to release v0.0.2 today or tomorrow, but in the meantime, you could try downloading the latest dev build and see if that works: http://travis.teamrtg.org/1.9-Realistic-Terrain-Generation

**Comment by kreezxil** [comment]
Excellent, the jenkins build #18 doesn't crash the server on startup.
Thanks much. :) for build 1811
