### ISSUE TITLE
Merge PR #14 from the 1.9 repo

### ISSUE THREAD

**Issue by topisani** [Team-RTG/Realistic-Terrain-Generation#594]
Everything from [this](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/pull/14) PR should be merged into this one. Whos up for that? (its the new mesas)

**Comment by whichonespink44** [comment]
I'll give it a go since I merged the other Mesa stuff, but... really we should be doing this the other way around - redesigning the biome in 1.7.10 and then forward-porting.

**Comment by srs-bsns** [comment]
Once all these access changes are made in Forge it's going to be a headache going either way, but yeah, we should probably do forward-porting. Especially since 1.7.10 is more familiar and should be a priority to finish. The we can focus heavily on 1.9 when Forge is stable.

**Comment by topisani** [comment]
yeah i know, i just like doing things in my own codebase. we should probably be lookin into an IBlockState implementation in 1.7... any thoughts on that?

**Comment by whichonespink44** [comment]
It would certainly help us keep both 1.8.9 and 1.9 more easily in sync, so +1 from me.

**Comment by topisani** [comment]
yep, if the constructors at least looked the same, evrything would be easier
