### ISSUE TITLE
EB Terrain updates

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#595]
Reviewing EB terrains and altering as necessary to reflect the source biomes and/or produce effects

**Comment by srs-bsns** [comment]
FYI: [MCF #2161](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2161)

This is happening in both EB Plateau and Snowy Plateau. Those biomes don't naturally have the mesa structure. Don't know if you are aware of this, but if not, you are now. :)

![](http://media-minecraftforum.cursecdn.com/attachments/193/115/635949533974506518.png)
![](http://media-minecraftforum.cursecdn.com/attachments/193/116/635949533977787819.png)

**Comment by Zeno410** [comment]
I replied to this in the thread, but these were probably just running default terrains I hadn't gotten to yet. I'm working on Plateau and I think the default was a terrainCanyon or terrainMesa, which would do that.

**Comment by whichonespink44** [comment]
Finished in d86bed6
