### ISSUE TITLE
BOP Crag tweaks

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#597]
As requested by Meerkatmanx:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2078

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2082

Not sure what we can/should do from his comments... maybe the occasional flat area with the occasional water pool?

**Comment by Zeno410** [comment]
Charm? Crag had charm? I thought it was one of the most absurd biomes ever. The current design is indeed to be looked at and not built in. I could make the spires come and go, with comparatively flat ground at about the height of the spires bases elsewhere.

**Comment by whichonespink44** [comment]
Crag was never my thing, but I can see why others have developed a soft spot for it.

I think he was actually requesting flattish areas at the *top* of the spires, which could maybe be achieved by making the spires significantly 'fatter'?

**Comment by whichonespink44** [comment]
Improved in 86cdae2
