### ISSUE TITLE
Biome-specific cave settings

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#601]
Request:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2132

Initial thoughts:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2134

**Comment by Zeno410** [comment]
More or less the same thing I'd say. The easiest thing to do would be to make the cave generator reluctant to breach the surface, by not removing, say, the top two solid blocks.

**Comment by whichonespink44** [comment]
I'm a bit reluctant to mess around too much with the cave generator, so I don't think we should worry about the Y value aspect of this request.

However, I think it should be easy enough to have biome-specific 'density' and 'frequency' settings.

Whoever this gets assigned to, let's leave the 'global' cave settings in rtg.cfg, but if the biome configs have been set, then RTG should use those instead.

Also, if this turns out to be more complicated than adding a few biome config options and tweaking MapGenCavesRTG to use the biome's values, then I'm happy to drop this one.

**Comment by whichonespink44** [comment]
Added in 1eb90d9 (caves) and aa81321 (ravines).
