### ISSUE TITLE
Generate Emeralds in DeepDark

### ISSUE THREAD

**Issue by Tsyklop** [Team-RTG/Realistic-Terrain-Generation#602]
Emeralds wiil generates in the DeepDark from ExtraUtilites.
Can you change this? or this bug ExtraUtilites?
![2016-03-29_15 49 44](https://cloud.githubusercontent.com/assets/6783568/14109067/fff74040-f5c8-11e5-92b5-056a1156ea8a.png)

**Comment by srs-bsns** [comment]
RTG Doesn't touch any dimension that isn't 0.
