### ISSUE TITLE
Half-cobble/half-sandstone villages

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#607]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2193

I suspect it'll have something to do with the way we're assigning the biome variable in EventManagerRTG:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/event/EventManagerRTG.java#L239

**Comment by topisani** [comment]
you would be 100% correct on that. but i dont know how to fix it

**Comment by whichonespink44** [comment]
Fixed in 0.8.0-snapshot-3

**Comment by whichonespink44** [comment]
Re-appeared in #705 :ghost:
