### ISSUE TITLE
Add biome config to prevent BOP ocean decorations

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#614]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2240

**Comment by topisani** [comment]
In v2, this will be acomplished by access to the BOP WorldConfig object, with a GUI screen

**Comment by whichonespink44** [comment]
Closing as the request was actually for an option to prevent BOP from decorating vanilla ocean, which is outside of RTG's scope.
