### ISSUE TITLE
Sever won't use RTG setting [RTG-1.7.10-0.8.0-snapshot-2]

### ISSUE THREAD

**Issue by parcel31u** [Team-RTG/Realistic-Terrain-Generation#615]
With level-type=RTG the server just used normal terrain generation. This is on a pre-existing world.

**Comment by topisani** [comment]
pre existing RTG world? or was it vanilla originally

**Comment by Zeno410** [comment]
I'm pretty sure the served world stores its level type somewhere and you have to change it there for an existing world. Level-type in the main directory is for new worlds.

**Comment by VelocityRa** [comment]
If you do decide to change the level type, you can do that easily with [NBTExplorer](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac).
If not, what I'd do is use MCEdit to copy my base or whatever else I care about and place them in a fresh RTG world.

**Comment by srs-bsns** [comment]
>I'm pretty sure the served world stores its level type somewhere and you have to change it there for an existing world. Level-type in the main directory is for new worlds.

This is correct, it's stored in **level.dat**. To change it you will need NBTExplorer (or another NBT editor) and you need to set **level.dat -> Data -> generatorName** to **'RTG'**.

But as Zeno said, this is highly ill-advised.

**Comment by whichonespink44** [comment]
@parcel31u I'm closing this, but feel free to comment on this issue if you need to.
