### ISSUE TITLE
Discussion: The possibility of adding realistic versions of Twilight Forest biomes

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#617]
@Team-RTG/everyone, This has been asked several times by several people.

**__Arguments for__:**

1. Although TF biomes don't normally generate outside of the TF dimension, there is still the possibility of using BiomeTweaker to generate them in the Overworld. Opinions vary on whether or not full functionality of those biomes would work outside of the TF dimension (such as TF mobs spawning, etc..), but in the case of RTG that stuff is a bit irrelevant, and besides, there are likely other means that people would be able to fix those other issues. (Custom Mod Spawner, etc..)

2. In the MCF thread, Robijnvogel brought up a good point that pertains to possible future RTG support of Mystcraft and RFTools. In that case, adding support for TF now means we wouldn't have to do it later, and later we probably would due to the popularity of TF. This doesn't, of course, solve the greater problem of all of the other non-supported biomes that RTG wouldn't be able to generate in custom dimensions, but that's a problem for another Issue#.

3. I thought of doing argument 1 myself on several occasions in the past, but the lack of RTG support always stopped me. Make it so!

**Arguments against:**

1. Since RTG is still locked in Dim 0, this is still outside of RTG's scope. (Weak argument if we want to expand RTG compatibility outside of Dim 0)

2. Too lazy to do it.

3. ...

What say you?

**Comment by whichonespink44** [comment]
If another mod adds a non-Overworld biome to the Overworld, then it's fair game for RTG and should be eligible for biome support.

**Comment by whichonespink44** [comment]
However... I'd rather not do this in 1.7.10 as it could inspire a flurry of requests for other non-Overworld biome support to be added, and to be honest, it just feels a bit outside of 1.7.10's scope.

Happy to make this part of 1.9's scope though.
