### ISSUE TITLE
Flat walls

### ISSUE THREAD

**Issue by Stabington** [Team-RTG/Realistic-Terrain-Generation#620]
I just generated a world and found this. Seed = ni
![2016-04-09_12 36 15](https://cloud.githubusercontent.com/assets/8779331/14403240/3703f29c-fe50-11e5-9b76-3d238425b7b7.png)

Forge 12.16.0.1859, 
RTG-1.9-0.0.5

**Comment by topisani** [comment]
please open issues in 1.9 at the 1.9 repo: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues
Other than that, that is extremely weird. It seems the chunks have been offset, but only for the river. Might be a forge bug, i dont think 0.0.5 was supposed to even run on forge 1859.

**Comment by srs-bsns** [comment]
0.0.5 was built with Forge 12.16.0.1830.. I don't think anything has changed since then with respect to world gen.

**Comment by Zeno410** [comment]
That looks like the result of my first round of patching the river system to deal with double points. It should have been fixed in the 1.7.10 version for a while.

**Comment by whichonespink44** [comment]
Moved to 1.9 issue tracker: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues/72

**Comment by Zeno410** [comment]
I just found an issue that can cause this kind of behavior. When a noise function gets called on x/wavelength and x is an integer there are sometimes rounding problems.
