### ISSUE TITLE
Fix HLBog surfacing

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#632]
Currently placing gravel at the waterline - should be dirt. May also affect some other biomes - many have gravel on lakeshore where dirt might be better

**Comment by whichonespink44** [comment]
From Zeno:

> It turned out the biome WAS placing the gravel. The source biome is tuned to not have much at the waterline so there's not a whole lot, while the terrainMarsh code we were using produces a LOT of waterline. I retuned ours and it's fine now.

Fixed in 04ec121
