### ISSUE TITLE
Mesa tweaks

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#635]
Mesas and Plateaus are 'leaking' far out of their biomes.

Also, the clay patterning looksa little odd on the mesa tops. Each layer has mixed colours but the colours change drastically from layer to layer. So a one block step up on the tops makes the colours change too abruptly. Maybe we could just use hardened clay or a mixed block effect with two specific colours that go well together?

**Comment by topisani** [comment]
id like to see some examples of the surfacing you are talking about. I dont think i follow you exactly...

**Comment by whichonespink44** [comment]
@Zeno410 reported this in Discord, so he might have some seeds/screens. I've also seen this, so I'll try to post some screenies later on.

**Comment by whichonespink44** [comment]
World Seed:
-5001027545084418649

This is a good seed to get an idea of what's happening with the 'leaking' - although, I would imagine that some leaking is unavoidable since RTG doesn't control the biome placement, right?

When you load up this seed, you spawn in a Mesa biome, and then as you fly around the perimeter, you encounter most of the Mesa variants, and you can see how they all transition into other biomes.

The only issue these screenshots don't illustrate is the 'clay mesa tops' although you can kinda see what's happening in the 2nd and 3rd screenshots. It's that same kind of effect, except on the tops of the plateaus (I think it's the Mesa Plateau FM biome?). In order to see that one, just load up Lonely Biome set to 166 (I think).

![2016-04-15_17 34 42](https://cloud.githubusercontent.com/assets/10927161/14568920/9c3fe2fa-0333-11e6-8a95-48909d55f011.png)

![2016-04-15_17 36 29](https://cloud.githubusercontent.com/assets/10927161/14568927/a09a4908-0333-11e6-9767-dedaca9e81da.png)

![2016-04-15_17 40 40](https://cloud.githubusercontent.com/assets/10927161/14568934/abb65304-0333-11e6-97f3-7acb5a08cf4c.png)

![2016-04-15_17 39 12](https://cloud.githubusercontent.com/assets/10927161/14568942/b312477a-0333-11e6-95b3-a900ea11e626.png)

**Comment by whichonespink44** [comment]
On a slightly related note, I thought this looked kinda weird, but again, not sure how much control we have over stuff like this:

![2016-04-15_17 39 12](https://cloud.githubusercontent.com/assets/10927161/14568942/b312477a-0333-11e6-95b3-a900ea11e626.png)

**Comment by whichonespink44** [comment]
Also thought I'd mention... for every one of these screenshots, I could've taken a dozen others where the Mesa variants are looking absolutely gorgeous. :)

**Comment by topisani** [comment]
- Issue 1 (terrain leakage): elementary to fix, i just gotta set a minimum border value. It has happened cause i am negating biome smoothing to get that nice cliff.
 - Issue 2 (Surface thingy): This is kinda intentional, as it is how vanilla is doing it too, and i like the different colours on the surface too, but the lines are maybe too smooth and mathmatical. Do you rather just want one colour on top? cause i essentially like the idea, but i can easily disable it

**Comment by whichonespink44** [comment]
Issue 2: As always with these sorts of things, it's difficult to say without seeing it. In theory, I think restricting it to just two mid-range colours (e.g. pink, red, orange, or regular hardened clay) would look better, but it might not.

**Comment by Zeno410** [comment]
That third pic was exactly what I was talking about. I was thinking to do the top with a different procedure than the in-ground layers. You get the noise in a float [] - I think if you set the colors of the top layer based on the float [] rather than the height it should work out better.

**Comment by topisani** [comment]
so what you are asking for is one colour per height for the top block?

**Comment by Zeno410** [comment]
Well, that's one option, but that's not what I'm asking for. I'm asking for the height coordinate passed to the color selection be changed from the int of the block height to the float of the noise height (so, basically, not rounded).

**Comment by whichonespink44** [comment]
Tweaked in e5787ca
