### ISSUE TITLE
Cave Control Issues

### ISSUE THREAD

**Issue by Shadows-of-Fire** [Team-RTG/Realistic-Terrain-Generation#638]
While I have noticed that you support Reika's Chromaticraft, using Reika's Cave Control in a realistic world setting seems to make the world loading take forever, and eventually just pause. There really isn't much in the way of information, since the log basically goes as normal, menu loading is fine, but once a world begins to generate, intervals of >1 between Generating Spawn Area, and loading times of between 3 hours and infinity (I gave up trying to generate after that time). Not sure if anything can be done about it, but its probably worth looking into.

**Comment by whichonespink44** [comment]
I thought this issue was resolved: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/350

Maybe try setting enableCaveModifications=false and/or enableRavineModifications=false in rtg.cfg and see if that helps.

Let us know if not.

**Comment by Shadows-of-Fire** [comment]
Even with both of those set to false the issue persists.

**Comment by whichonespink44** [comment]
With both of those options set to false, RTG doesn't interfere with cave gen or ravine gen, so I'm not sure what would be causing the infinite hanging.

The only thing we can think of that might be causing this is maybe Cave Control is trying to change ChunkProviderGenerate, but RTG doesn't have one in the normal place? Really not sure.

@ReikaKalseki Any ideas what might be causing this? There was a [similar issue](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/350) a few months ago, but it seemed to have been resolved with CaveControl V10b + DragonAPI V10d.

**Comment by ReikaKalseki** [comment]
Aside from from some loading processes, CaveControl has not changed at all since v10.

**Comment by whichonespink44** [comment]
@Shadows-of-Fire Can you confirm that this is happening with just RTG + Cave Control (no other mods installed)? If it's still happening, then we will look into it further. However, if it's not still happening, then it's probably some mod interaction bug and would be difficult to diagnose (essentially, you'd have to keep adding mods one-by-one until you find the mod that causes the lag).

In the meantime, it might be worth noting that RTG has config options that allow you to control many aspects of world gen that Cave Control allows you to control, so if all you want is the ability to increase cave/ravine frequency or the ability to enable/disable ravines/mineshafts/strongholds, then you can just use RTG's config options for that.

**Comment by Shadows-of-Fire** [comment]
Will check in a while, But what I personally want CC for is the lava fill below Y-10

**Comment by ReikaKalseki** [comment]
You mean disabling the lava fill? Because it is on in vanilla.

**Comment by whichonespink44** [comment]
We can add config options for lava fill, but I'd still like to get to the bottom of this. I'll do some testing when I get around to doing the config options.

**Comment by Shadows-of-Fire** [comment]
Theres probabaly a chance that it could be something else's fault. But i can't think 9f what. Maybe Climate Control or Streams. I doubt it could be BoP, and I wasnt using anything else that seems like it would mess with worldgen

**Comment by whichonespink44** [comment]
I've just been doing some testing with RTG 0.7.0, Cave Control V12a, and DragonAPI V12e, and aside from some initial startup stuttering in Extreme Hills biomes, RTG and Cave Control seem to work perfectly fine together.

I've also tested with and without Climate Control 0.5.beta50, and I didn't notice any problems whatsoever, so this is likely a different mod interaction bug.

I'm going to close this for now, but if you can confirm that RTG is involved in the issue by isolating it with just the mods involved, please feel free to open up another issue.

**Comment by Shadows-of-Fire** [comment]
I'll have to check and see what it could've been. It may be streams, since it generates underground streams.

**Comment by ReikaKalseki** [comment]
....It does?

**Comment by whichonespink44** [comment]
The latest version of Streams (0.2) digs into mountains rather than carving out a huge ravine like 0.1 used to, but I don't think it generates them below sea level. Could be wrong though.

**Comment by srs-bsns** [comment]
I didn't see anything below sea level the last time I tested with 0.2
