### ISSUE TITLE
ASM

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#640]
Right, so I've been thinking about using ASM to resolve #531 (Oceancraft bug).

What are everyone's thoughts on ASM in general?

My personal opinion (at least as far as RTG is concerned) is that it should be avoided at all costs. But it really bothers me that RTG isn't fully-compatible with Oceancraft, so I've been thinking of making an exception here.

My idea is to add a config option called "Allow full compatibility with Oceancraft" (disabled by default). If enabled, RTG would use ASM to modify the relevant OC file to ensure compatibility.

Would we be opening up a can of worms by doing something like that? Or am I making a mountain out of a molehill here?

**Comment by Shadows-of-Fire** [comment]
Since @thomassu is completely unresponsive to requests, and since a wide majority still relies heavily on MC 1.7.10, its probably the best solution. That said, if he decides to change his 1.7.10 version to decorate correctly, then it should probably reverted.

**Comment by VelocityRa** [comment]
I really don't think it's worth the hassle, especially for something disabled by default.
I don't know ASM (don't even know if anyone on our team does) but it seems pretty messy and difficult from some Forge code I checked. (in `cpw.mods.fml.common.asm.transformers`)

**Comment by topisani** [comment]
@VelocityRa :+1: wtf is asm?

**Comment by srs-bsns** [comment]
@topisani, https://en.wikipedia.org/wiki/Assembly_language
Have fun with that. :smile:

**Comment by VelocityRa** [comment]
More specifically: https://www.wikiwand.com/en/ObjectWeb_ASM

**Comment by whichonespink44** [comment]
Ok, unless @Zeno410 comes in and says "ASM, piece of cake!", then the general consensus seems to be that we shouldn't consider ASM for this.

Instead, I'm going to message @thomassu on MCF to see if he'll consider tweaking `WorldGeneratorOceancraft.java` to use biome ID checks instead of biome equality checks, and if he does, then great, and if not... well, at least we tried.

**Comment by srs-bsns** [comment]
@VelocityRa, I know it's ObjectWeb_ASM, I just wanted to see how Topi would react to seeing true low-level Assembly. :P

**Comment by whichonespink44** [comment]
_"Message sent."_
