### ISSUE TITLE
snapshot-4

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Team-RTG/Realistic-Terrain-Generation#646]
https://gist.github.com/bb707dea2c1a361e6cd9e36e0a42ccf3
snapshot-3 worked without crash and 0.7.0
log
https://gist.github.com/733a55260739fb296c937d2e94b74831

**Comment by whichonespink44** [comment]
I'm looking into this now.

Could you post you **rtg.cfg** file here please?

**Comment by SvEgiiVEteR** [comment]
https://gist.github.com/61d6db7f80ae58b029c5995f0f3667f8

**Comment by whichonespink44** [comment]
I think I've fixed the issue.

Could you try this version and let me know? https://goo.gl/dYciNL

**Comment by SvEgiiVEteR** [comment]
@whichonespink44 Thank you, it seems everything is working. :)
