### ISSUE TITLE
Config Options for Lava Fill below Y=10

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#648]
See #638 for background.

We should probably make sure RTG adheres to the way vanilla does it by default, though I haven't looked to see exactly how it's done.

And then the config options should try to mimic what Cave Control is doing for those who are having compatibility issues.

**Comment by topisani** [comment]
what do we do currently? dont we generate lava bellow y=10?

**Comment by whichonespink44** [comment]
Not sure - haven't looked into yet. But IIRC, I don't think we are.

**Comment by whichonespink44** [comment]
We were only considering this because it looked like Cave Control might be incompatible with RTG (see #638 for details).

It turns out that Cave Control and RTG work fine together, so I don't think this is something we need to worry about now.
