### ISSUE TITLE
mc 1.9 forge latest (1865) generating, loading, closing world takes so~ long

### ISSUE THREAD

**Issue by Jiraiyah** [Team-RTG/Realistic-Terrain-Generation#652]
basically that is the problem, when i generate a world, load it or want to close and go back to main menu, it takes ages.

**Comment by VelocityRa** [comment]
There's a 1.9 repo for RTG:
https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation
Please submit your issue there. Also provide more detail, how long does it take approximately? What are your PC specs? Would also be helpful to submit a Forge log.

**Comment by Jiraiyah** [comment]
hmm i am not sure what was the problem, but deleted the profile with forge and all, and recreated and installed forge, seems problem is gone, but there is something regarding rogue like dungeon when i want to create a world with your generator that causes NPE, will post the issue in your repo, not sure if this is on your side or not though.
thanks for help

**Comment by VelocityRa** [comment]
:+1:
