### ISSUE TITLE
RTG .8 snapshot 4 odd mesa gen

### ISSUE THREAD

**Issue by vagaprime** [Team-RTG/Realistic-Terrain-Generation#658]
just created a new world after updating to snapshot 4 and the mesa gen seems a little off, ALso some biome transitions seem bugged.

http://imgur.com/a/w3vWX

top picture is taken in game the bottom picture is a saved map from journey map

**Comment by whichonespink44** [comment]
@vagaprime Do you still have the world seed for this? Can you confirm if this is still happening in [snapshot 5](http://minecraft.curseforge.com/projects/realistic-terrain-generation/files/2296032)?

**Comment by Zeno410** [comment]
There are some XY inversions there. Topi, does any of your mesa code do XY flips?

**Comment by topisani** [comment]
Nope, this is extremely weird. No idea what's going on. Like pink said. Seed and coords please

**Comment by vagaprime** [comment]
the seed is -2599301795896205058 and the cords are X=-25 Y=-130. I have not had a chance to upgrade to snaphot 5 yet, next time I get the the free time to update mods will be this weekend.

**Comment by srs-bsns** [comment]
RTG-1.7.10-0.8.0-snapshot-5
I'm just not seeing it. This is a mixture of all 3 Mesa biomes, or their mutations (Bryce).

![](http://www.nihilism.ca/minecraft/misc/20160427-RTG-1.7.10-dots.png)

**Comment by topisani** [comment]
wow srs, that world looks too good

**Comment by vagaprime** [comment]
Not sure if this will help as well but here is a list of all the mods I have in my pack at this time.

https://docs.google.com/spreadsheets/d/13WVyKMBs3wSDexM8u18fbpin77VEwHLOjXdLmtoNsRU/edit#gid=577458583

**Comment by vagaprime** [comment]
ok I have just updated to snapshot 5 and recreated the world. with the same result. If you like I can link you to a copy of the dev build of my pack with the world save included.

**Comment by whichonespink44** [comment]
I've just tested the seed with RTG + CC + BOP, and I'm not seeing anything like the first screenshot.

@vagaprime I just had a look at your mod list and noticed that you're using BOP, but you haven't installed Climate Control or BiomeTweaker. Not sure if that's what's causing the problem, but if you want BOP biomes, you'll need either CC or BT as well as RTG.

I'm closing this for now, but let us know if it crops up again when the release candidate is published later tonight.
