### ISSUE TITLE
TODO: Rename the example BiomeTweaker configs

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#660]
I'm opening this here, but it applies to all the RTG repos.

I propose we rename all of the example configs that we have for BiomeTweaker so that there's less confusion over what config is what and where the configs go. Having two `rtg.cfg`'s is, I think, confusing a lot of people. All of the BiomeTweaker configs should be renamed something like BT-RTG.cfg, or RTG-BT.cfg, or whatever.

**Comment by whichonespink44** [comment]
Yeah, that's been bugging my OCD since I first named it.

When I'm finished re-decorating some of the Highlands biomes, I'm gonna make RTG auto-generate those files on startup if they don't exist (#553), but I'll be sure to change the filenames to something less ambiguous when I do.
