### ISSUE TITLE
Ground looks like it got sliced in some terrain

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#664]
Kinda like an earthquake, but is this intentional? I'm using RTG 0.8.0 snapshot-5 for 1.7.10, BOP, and BiomeTweaker loaded with RTG tweaks for BOP. The seed is: -5709895089551681541
![2016-04-24_22 54 32](https://cloud.githubusercontent.com/assets/11594018/14775646/8bd4ad80-0a75-11e6-9c30-7a697b3b4d0e.png)

**Comment by whichonespink44** [comment]
@Zeno410 Kinda looks like the branch of that river ran into a biome that doesn't have rivers enabled, but both Desert and Savanna have rivers enabled, so... not sure how that happened. Unless the branch of the river is actually the start of a lake?

**Comment by Zeno410** [comment]
This is probably one of those rarish bugs in the cell noise system. What are the coordinates?

**Comment by VelocityRa** [comment]
-108 and +114 (it's on the top right of the screenshot)

**Comment by chaNcharge** [comment]
Here's another screenshot in the same seed, but this time, the only mod that is installed is RTG 0.0.5 for 1.9. The same issue occurs in same seed, but at a MUCH larger scale. 
![2016-04-25_20 04 06](https://cloud.githubusercontent.com/assets/11594018/14805484/264eba44-0b21-11e6-9019-66ecd00c9c82.png)

**Comment by topisani** [comment]
It doesnt surprise me in the 1.9 version. That code is rather old, and from when we had that issue all over the place. 1.7 is a shame though, I thought we fixed that

**Comment by Zeno410** [comment]
The problem has something to do with a changeover in river basins. I did one fix for the double rivers and then later another fix for the giant river, and it's that second fix that mostly exposed the problem on top. As Topi says, those patches haven't made it to 1.9 yet. I'm not sure I can fix the latest issues because I don't understand what it's trying to do. It looks like it's changing to a completely different set of "poles" (points the rivers are placed as far as possible from) and the two different sets of poles are supposed to generate the same result in an area. But they don't, quite, and I don't understand how they're supposed to be the same.

The other two fixes were cases where the problem was pretty obvious (poles way too close together).

**Comment by chaNcharge** [comment]
I haven't seen this happen in 0.7.0 for 1.7.10, maybe you changed or added something that's causing this?

**Comment by srs-bsns** [comment]
Since RTG-1.7.10-0.7.0 there have been:
Commits: 486
Files: changed 1,044

So yeah, probably something that's changed. :)

**Comment by Zeno410** [comment]
Like I said, when I put in the second patch it exposed the most recent. Before it was at least sometimes hidden by a large area of flattening. It's rare too - I do a lot of test flying and I've only seen it once.

**Comment by srs-bsns** [comment]
Yeah, I just flew around in that world for quite a while, fallowing every river I saw, exposing a lot of chunks, and the only occurance was the one near spawn. I haven't seen it in any of my other test worlds, but I haven't really tested the last few snapshots very much.

Everything is looking awesome though, save a few quirks.

**Comment by chaNcharge** [comment]
I guess it is pretty rare and minor, wouldn't mind a fix though :)

Everything else seems to be ok other than minor performance issues and this bug.

**Comment by Zeno410** [comment]
Well, I finally looked at this area and it's absolutely horrific. Multiple long chunk walls, a long split river, and some oddly flat areas. Vastly worse than anything I'd ever seen resulting from the various problems with the SimplexCellularNoise. Even if it's rare, this is unacceptable and I'm going to try to roll back to the earlier Voronoi noise for rivers. I'll leave everything else (lakes and the occasional biome terrain) using simplex cellular until and unless I see similar problems there.

**Comment by chaNcharge** [comment]
So ever since 0.8.0 RC-1, this issue seems to be fixed so far! I haven't seen it at all in the same seed and coordinates as I posted earlier, so I'm gonna take a guess that this bug is probably fixed at this point.

**Comment by chaNcharge** [comment]
Aaand, I forgot about the 1.9 RTG. Whoops!

**Comment by Zeno410** [comment]
The changes haven't been ported to 1.9 yet. Don't worry, they will be.

**Comment by whichonespink44** [comment]
Fixed in 4eb6eb0
