### ISSUE TITLE
Highlands Cocoa Beans

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#666]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2465

**Comment by Zeno410** [comment]
When you redecorate Oasis and Tropical Island (and maybe Jungle Island), just make a RTGCocoanutPalm with the same structure as the Highlands palm but with Jungle wood and vanilla cocoa beans (nobody gets my jokes :-( ) and use it instead of the HL Palm. I was thinking about a config option but based on the comment that the HL cocoa beans spam the console as they grow, we need to just kill them.

**Comment by whichonespink44** [comment]
Death to all HL cocoa beans! It shall be done!! :fork_and_knife:

**Comment by VelocityRa** [comment]
Why should that be fixed by us? Would be incredibly easy for the HL author to fix it by removing the logging lines wouldn't it?

**Comment by Zeno410** [comment]
The maintainer for the 1.7.10 version hasn't logged on in 5 months.

**Comment by VelocityRa** [comment]
Ah, alright.

**Comment by whichonespink44** [comment]
So I've just been looking into this, and I've managed to create an RTG palm tree that extends the HL Palm tree and overrides its generate() method, replacing HL Cocoa with vanilla Cocoa. So it will look exactly like the HL Palm, except it will have vanilla cocoa beans.

That's the good news.

The bad news is that in order to 'replace' the HL Palm with the RTG version whilst keeping all of the other HL decorations, we'll need to manually decorate all of the biomes that contain the HL Palm:

* Desert Island
* Dunes
* Oasis
* Tropical Islands

Unless anyone knows if it's possible to prevent the HL Palm from generating another way?

**Comment by Zeno410** [comment]
I can't think of a not-seriously-hacky way to stop the HL Palms. All those have relatively simple decorations, though, and I don't think you have to do Dunes - I think it only gets Palms via Oases.

**Comment by topisani** [comment]
I know it would be nice, but why are we trying to solve a highlands bug?

**Comment by whichonespink44** [comment]
Fixed in 6da78b6

**Comment by Zeno410** [comment]
Partly because a lot of people want it, and partly because we're the Highlands team now. With great power comes great responsibility, blahblahblah...
