### ISSUE TITLE
Still seeing occasional random air pockets in oceans.

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#669]
###### RTG version is irrelevant, this has been happening for a long time. It's somewhat rare.
RTG-1.7.10-0.8.0-snapshot-5
BiomesOPlenty-1.7.10-2.1.0.1889-universal
BiomeTweaker-1.7.10-2.0.182
Default configs
Seed: -5709895089551681541

Originally I had only ever seen the pockets like in this first image, which always seem to appear in the same manner.. looking almost like how ore might spawn in the world. These are legit air blocks and requires an adjacent block update to cause minecrafts 'infinite water' to fill it in. I've only ever seen this with RTG, and considering how the world generates, something has to be replacing the water blocks with air blocks.

x = 3808, z = -2238
![](http://www.nihilism.ca/minecraft/20160427-RTG-Issue669/RTG-1.7.10-Issue669-1.png)

Lately I've also been seeing pockets appear that look like this second image. There is no real pocket, it's just a 'sheet' of air between 2 blockspaces. It's not on chunk borders, and doesn't seem to have any kind of pattern to it, except it's always that size and shape. It instantly disappears upon a block update that touches it.

x = -368, z = 537
![](http://www.nihilism.ca/minecraft/20160427-RTG-Issue669/RTG-1.7.10-Issue669-2.png)

**Comment by topisani** [comment]
ive seen this in vanilla some years ago when i used 1.7. Not sure its an RTG thing

**Comment by whichonespink44** [comment]
I'm pretty sure these are the air pockets that generate over Mineshafts or large caves (1.7.10 issue). Next time you find of those, dig straight down underneath it, and you'll almost certainly find either an underground cave (one of those big square dirt-filled ones) or a Mineshaft.

Either way, this is definitely a vanilla issue.
