### ISSUE TITLE
Mowzie's Mobs Ferrous Wroughtnaut chamber never generates?

### ISSUE THREAD

**Issue by chaNcharge** [Team-RTG/Realistic-Terrain-Generation#672]
I'm not entirely too sure about this, but do ferrous wroughtnaut chambers generate in RTG worlds? I'm using Mowzie's Mobs 1.2.7, LLibrary 0.3.4, and RTG 0.8.0 snapshot 5. I've been doing a bit of running around and I've yet to find even one chamber. If there's a seed with a chamber generated in older versions such as 0.7.0, post it below so we can take a look.

**Comment by srs-bsns** [comment]
See: https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/442

**Comment by whichonespink44** [comment]
@chaNcharge I don't have a seed, unfortunately, but you can try increasing the spawn rate of the Ferrous Wroughtnaut in the MM configs, and then use one of the many [1.7.10 x-ray glitches](https://www.youtube.com/watch?v=LGjMIYNul18) to have a look underground.

If you don't see any with the spawn rate increased, try using version 0.6.2 of LLibrary, as that one was definitely working in 0.7.0 and should still be working in the 0.8 snapshots.

Let us know if not.

**Comment by chaNcharge** [comment]
Guess I was just unlucky in finding one. I had to use VoxelFlight just to find even one chamber in like 500 blocks. I should probably increase the spawn rate of them...
