### ISSUE TITLE
yet to fine any underwater temples in 1.9 when using this mod

### ISSUE THREAD

**Issue by BlueSteelAUS** [Team-RTG/Realistic-Terrain-Generation#675]
no underwater temples , but the mob that are to protect it still spawn

**Comment by topisani** [comment]
this is/was a known bug. Where did the issue go? anyway, im milestoning this for the upcomming v2.0.0-alpha.1

**Comment by topisani** [comment]
oh wait, this is the wrong issue tracker. Issues for 1.9 should be reported at https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues
