### ISSUE TITLE
Strange chunks in RTG 0.8

### ISSUE THREAD

**Issue by Kehaan** [Team-RTG/Realistic-Terrain-Generation#681]
Promised to make a issue here. Using the newest 0.8 RC1 on 1.7.10, i am sometimes getting these strange chunks:

![2016-05-04_10 10 30](https://cloud.githubusercontent.com/assets/6755642/15011264/24a90cfe-11f1-11e6-8948-08707df97aa6.png)
![2016-05-04_10 10 36](https://cloud.githubusercontent.com/assets/6755642/15011265/24ae67ee-11f1-11e6-94be-d39a2e888148.png)
![2016-05-04_10 10 38](https://cloud.githubusercontent.com/assets/6755642/15011266/24aeec3c-11f1-11e6-9486-3da4041b759e.png)

Its not a big issue, but just something i noticed :)

Logs: https://www.dropbox.com/s/guhiy61n95hlsog/logs.zip?dl=0

**Comment by topisani** [comment]
@Zeno410 so you thought you could just let this pass? :P 
@Kehaan Thanks for reporting, we are aware of the issue

**Comment by Zeno410** [comment]
What are those carroty things and how do they get there?

**Comment by Kehaan** [comment]
Thats from ChocoCraft-4.1.5, its Gysahl Greens.

**Comment by Zeno410** [comment]
The reason I'm asking is that if the snow isn't placed, it *should* mean the populate didn't run, including any of the pre- and post- populate and decorate events. So unless Chococraft is using an exotic placement method, they should be there either. Is the biome Ice Plains?

**Comment by Kehaan** [comment]
In screenshot 2 i am inside the broken chunk. And its Ice Plains :)

**Comment by whichonespink44** [comment]
Fixed in 2a1870f

Hopefully, we'll be releasing RC-2 tonight so you can confirm this is working.

Let us know if not.

**Comment by Kehaan** [comment]
It seems like its fixed in RC-2 :)
