### ISSUE TITLE
0.8 RC-1 Cobwebs generating in rivers

### ISSUE THREAD

**Issue by Yazzeh** [Team-RTG/Realistic-Terrain-Generation#685]
I've only really noticed it nearby Sacred Springs and Roofed Forests so far.
![2016-05-04_18 13 58](https://cloud.githubusercontent.com/assets/2250087/15031755/28ddeed8-1229-11e6-872a-2d47c0f23e87.png)

**Comment by whichonespink44** [comment]
Cobwebs are supposed to generate in Roofed Forests, but not in the adjacent rivers.

We'll fix this in the next release - in the meantime, if you want, you can disable cobwebs from generating by setting **"RTG Decoration: Cobwebs"=false** in [config/RTG/biomes/vanilla.cfg](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/dev/etc/config/RTG/biomes/vanilla.cfg#L2111)

**Comment by whichonespink44** [comment]
Fixed in 41ff68c
