### ISSUE TITLE
Crash on Server Startup - Exception preparing structure feature  at teamrtg.rtg.world.gen.structure.StructureOceanMonumentRTG

### ISSUE THREAD

**Issue by rckymtnrfc** [Team-RTG/Realistic-Terrain-Generation#695]
I'm seeing the following crash during the server startup.  http://pastebin.com/DkxJKLQi

**Comment by rckymtnrfc** [comment]
Just realized I didn't have RTG as the level-type in the server.properties.  I changed that and it started up fine but it could have also just not generated an Ocean Monument this time around.

**Comment by srs-bsns** [comment]
Wrong repo. You're looking for: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues
Please open an issue there.
