### ISSUE TITLE
0.8 RC-2 server side 

### ISSUE THREAD

**Issue by SvEgiiVEteR** [Team-RTG/Realistic-Terrain-Generation#696]
https://gist.github.com/664ffeea60a53c9317247ab5041cb59d
any ideas?

**Comment by Zeno410** [comment]
That is a tripwire I set to find out if something happens that I didn't think should happen, and it should be gone in the next candidate.

**Comment by whichonespink44** [comment]
Fixed in 248ddf7

**Comment by SvEgiiVEteR** [comment]
@whichonespink44 soon a new version to test?
now testing rc2 and almost always crashes

**Comment by whichonespink44** [comment]
We're planning to release RC-3 on Sunday (or maybe even jump to 0.8 if it's ready).

**Comment by SvEgiiVEteR** [comment]
I'll just wait for Saturday.. thought to try if there is a test version.

**Comment by Zeno410** [comment]
Try my current test build: https://www.dropbox.com/s/ftyb1cjdryla118/RTG0.8.jar?dl=0
