### ISSUE TITLE
Alpha Performance Issues

### ISSUE THREAD

**Issue by whitestarx0312** [Team-RTG/Realistic-Terrain-Generation#699]
RTG: RTG-1.9-2.0.0-alpha.1.jar
Forge: forge-12.16.1.1887

Upon updating to the new alpha I noticed that the time to generate and start a new world increased significantly by at least 20 seconds, and made me think that the game was going to crash although it eventually did load. 

Furthermore, I have encountered an issue when generating new chunks. The TPS of the single player world skyrockets and chunks stop loading, leaving the area full of empty spaces. This does not happen when tested with RTG 0.0.5.

**Comment by srs-bsns** [comment]
Wrong Repo. You are looking for: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues
Pleaase open up this issue there.
