### ISSUE TITLE
Dimensional Control Incompatiability

### ISSUE THREAD

**Issue by Myrdden** [Team-RTG/Realistic-Terrain-Generation#706]
Hiya, so I've been using BnB's Dimensional Control (http://mods.curse.com/mc-mods/minecraft/229588-dimensional-control) to generate multiple worlds, and I figured that since RTG simply changes how biomes look, rather than how they're generated, it would be compatible. I was very wrong.

Here's what happened immediately upon creating a new world:
[crash-2016-05-15_18.12.04-server.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/265357/crash-2016-05-15_18.12.04-server.txt)

Using RTG 0.8 RC-2

**Comment by Myrdden** [comment]
Come to think of it, I should probably be asking them about this, shouldn't I.

**Comment by whichonespink44** [comment]
Yeah, even though RTG is all over that crash log, it's probably something for the DC devs to look at. If there's anything that RTG can do to help make the two mods compatible with each other, we'd be more than happy to work with them to see what's possible.
