### ISSUE TITLE
SGCraft doesn't generate Stargates in Desert Temples

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#714]
Report:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2709

Mod (including source):
http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/SGCraft/#mozTocId598776

**Comment by VelocityRa** [comment]
Well this is harder than I expected.

**Comment by whichonespink44** [comment]
Yeah, hard to see exactly what's going on with most of the code being at the same package level.

Does it print/log any messages when you get to a temple?

**Comment by VelocityRa** [comment]
Nope, it doesn't get to that point. I've set up a debugger with the mod (by having it as a library) and I sort of understand what it's trying to do:
`onInitMapGen` in `FeatureGeneration` happens normally (no error gets printed), but the SGStructureMap is never actually used (the code makes `structureMap` a "SGStructureMap" instead of HashMap and overrides some stuff to make sure the Component (FeatureUnderDesertPyramid) gets loaded.
I suspect `MapGenScatteredFeatureRTG` has probably something to do with it. I tried loading it up in different ways [here](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/master/src/main/java/rtg/world/gen/structure/MapGenScatteredFeatureRTG.java#L190) with no success.

**Comment by VelocityRa** [comment]
Tried to change what should be changed in our own `MapGenScatteredFeatureRTG`.
It prints the messages it should print, but no structure....
![image](https://cloud.githubusercontent.com/assets/6632271/15369136/fe0e3a3e-1d39-11e6-9674-a6e4fcf9245c.png)
I can't do this anymore, I've spen a fair few hours today on this thing alone.
If someone wants to tackle it just import the SGCraft jar as a library in IntellJ and link the source code provided in the website above to it. If it works wihout the jar in your mods folder, you have debugging.

**Comment by whichonespink44** [comment]
I spent some time on this last night but didn't make much progress. Probably worth getting the author of SGCraft involved as he might be able to spot something in MGSFRTG that we're just not seeing.

Worst-case scenario, if we can't get the Stargates to generate using MGSFRTG, we could always add a config option called **enableScatteredFeatureModifications**, similar to the others we have, and if set to false, RTG would use the vanilla MapGenScatteredFeature instead of MGSFRTG.

**Comment by whichonespink44** [comment]
It would mean players would have to choose between Stargates in desert temple or vanilla structures in mod biomes, but at least it would be something.

**Comment by VelocityRa** [comment]
Sounds fine to me, if we can't find another solution.

**Comment by Zeno410** [comment]
Yeah, most likely there's some trick going on and he'll know it but we won't without a lot of code review.

**Comment by VelocityRa** [comment]
The frustrating thing is I *did* spend a few hours doing just that - I'm pretty sure I understand what it's trying to do - but while it *should* work, it doesn't...
Pink's hack is the only solution it seems.

**Comment by Ezoteric** [comment]
wasnt this not working in vanilla also ? i dunno but i think i looked that up once as it didnt work for me either (before i even knew about rwg :P )

**Comment by VelocityRa** [comment]
@Ezoteric Yeah you have to enable a config option for it to work. Which makes this less worth to fix.

**Comment by whichonespink44** [comment]
I posted a message on the SGCraft thread regarding this issue: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287806-gregs-sg-craft-for-minecraft-1-7-10-and-1-8-9?comment=1032

**Comment by Ezoteric** [comment]
@VelocityRa I figured but it stil didnt do much back then :P

**Comment by Dreadp1r4te** [comment]
Hey guys, original poster of the issue here. @Ezoteric, I'm not sure if the config option (in SGCraft) used to do nothing, but it certainly does now; we've found around 5-6 Stargates in temples in previous worlds. Anyways, thanks a ton for looking into this for us!

**Comment by VelocityRa** [comment]
@Ezoteric It does, I tested them. You have to go to one of the 2 "towers" on the sides of the temple. There's a ladder near the door leading down to the room with the Stargate.

**Comment by Ezoteric** [comment]
I knew that all, but i think it was an older version as back then i read something about it that it didnt worked orso :P

But its nice to know if it works in RTG :) as my modpack also has it :P

**Comment by whichonespink44** [comment]
![](http://i.imgur.com/KBj5e1i.png)

![](http://i.imgur.com/QYbtGIQ.png)

Progress!

I've managed to get it so that it either spawns the SGCraft portion of the temple or the vanilla temple, but not both. Not sure why it's only one or the other, but it's getting there.

Hopefully I'll make more progress tonight.

**Comment by VelocityRa** [comment]
Nice! Did you do the "hack" you were talking about or is it a proper solution?

**Comment by whichonespink44** [comment]
No, it's a different hack :)

Since SGC won't generate the temples, I'm making RTG handle it by creating the FeatureUnderDesertPyramid component and adding it to the list of components in MGSFRTG. If I add both the vanilla and stargate components, it only generates the vanilla pyramid, so I tried adding just the stargate component on its own, and that's the first screenshot above.

Just need to figure out why it's not generating both.

**Comment by topisani** [comment]
have you tried adding them in different orders? one of them may fail if the other is already there

**Comment by whichonespink44** [comment]
Nope, but that's a good idea :+1:

**Comment by topisani** [comment]
soo... did that do the trick? or how did you fix it

**Comment by whichonespink44** [comment]
![](http://i.imgur.com/xFm3ZTu.gif)

Fixed in 01b33d3

The reason it would only generate one or the other is because of the way MPSFRTG was choosing which scattered feature to generate. For some reason, it was choosing a random structure from the ones that had been added, and since previously there was ever only one structure getting added to the list, it basically had no effect. But when I added the stargate to the list, it was choosing between the stargate and the temple itself, but never both.

So I just refactored MGSFRTG a bit and voila! :smile: 

I'm not entirely happy with the approach that I used in order to get this to work, but... I just couldn't for the life of me figure out why SGCraft wasn't generating the stargate. If the author of SGCraft ever sheds some light on this, I'll go back in and do it properly, but for now...

¯\\\_(ツ)_/¯

**Comment by Hiddenisme** [comment]
Are these changes only for the 1.8.9 version and if so will see the changes in the 1.7.10 version? Cause yes we are experiencing the same issue in our 1.7.10 modpack.

**Comment by whichonespink44** [comment]
This is issue was only reported in (and fixed for) the 1.7.10 version, so it will be working in the next 1.7.10 release.

**Comment by Ezoteric** [comment]
did you check into the swamp hut genning on top a desert temple in the swamps ? @whichonespink44

**Comment by Ezoteric** [comment]
![2016-05-29_15 15 13](https://cloud.githubusercontent.com/assets/14137626/15659604/8e72e146-26cd-11e6-98d0-dbdd6a5be866.png)

**Comment by whichonespink44** [comment]
Doh! Accidentally left some debugging code in... removed it in 8371e53 and everything seems to be working fine again. Let me know if not.

**Comment by Ezoteric** [comment]
Ok testing it now :)

**Comment by srs-bsns** [comment]
Closing this for now as this feature is currently broken and disabled by default in SGCraft.
