### ISSUE TITLE
Peony Top on Fallen Log = Crash

### ISSUE THREAD

**Issue by cattrfly** [Team-RTG/Realistic-Terrain-Generation#716]
I was harvesting a fallen spruce log and noticed as I reached the end that the top half of a double peony, which I'd thought was behind the log, was actually protruding from the log's last block. As I looked up at it, I briefly thought "oh, another nice touch of realism, vegetation growing from a rotting log"... and then my game froze and crashed. >_<  The crash report doesn't specifically mention RTG, but I thought since the fallen logs are generated by the mod it might be something you'd want to look into. Crash report attached below. Let me know if you need any other info. :)

[crash-2016-05-18_04.21.32-client.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/271017/crash-2016-05-18_04.21.32-client.txt)

**Comment by whichonespink44** [comment]
Moved this to the 1.9 repo:

https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues/116
