### ISSUE TITLE
EB overrides biome layout sometimes

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#720]

**Comment by whichonespink44** [comment]
@Zeno410 If this isn't causing major problems, I'm happy to leave this until after 1.0 is released.

**Comment by Zeno410** [comment]
I did not have any problems with this in several days of play in a survival test world. (other problems, but not this)

**Comment by srs-bsns** [comment]
It's certain this is an EB issue, and it will never be resolved.
