### ISSUE TITLE
Best way to deal with updates?

### ISSUE THREAD

**Issue by Xireka** [Team-RTG/Realistic-Terrain-Generation#723]
Hi RTG team!

I really love your mod, it gave me awesome terrain, sometimes I was just wondering at the beauty of some things.

Now to my actual question: you update rather frequently (which is awesome) but how to best deal with the updates? 

Create a new world every time? 
Retrogen?
Some other way I don't know of? 
Simply keep playing the current world and the updates will seamlessly add themselves to my world?

It's just, depending on the time between updates I am more or less advanced or maybe found a nice spot for a base but I'd like to enjoy the new fixed and updated stuff and until now I always recreated a new world but actually I was wondering what the best course of action would be? :)

Thank you in advance for the help, and keep being awesome :3

**Comment by srs-bsns** [comment]
It is clearly stated in the release notes for each release when RTG has changes that are not backwards compatible and requires a new world, or a deletion of the config files. In the coming weeks when 1.0.0 is released it should remain backwards compatible for a long time.

**Comment by Xireka** [comment]
Oh okay, I missed that then sorry :(

Thank you for the quick and precise answer and I noted it to myself then

Backwards compatible: no new world
Not backwards compatible: new world

Thanks and thanks for your dedication to generate even better worlds :)

**Comment by whichonespink44** [comment]
@Xireka Thanks for the kind words! :)

As @srs-bsns mentioned, when version 1.0 is released in the next couple of weeks, you'll be able to update RTG and the updates will seamlessly add themselves to your world. In the meantime, it's probably best to create a new world for new versions.

Have fun! :smile:

**Comment by Xireka** [comment]
@whichonespink44 Oh okay thanks for that info, I guess I'll stick with my current version since the newest one is not backwards compatible I believe. Then I'll update on my existing world when 1.0 is released.


One last question, the release says "delete the config folder" so does it mean it's compatible with an existing world as long as I delete the configs or is it simply not backwards compatible and 1.0 will be completely?

I got confused :$

**Comment by Zeno410** [comment]
If you have a world on RTG 0.7, I would not recommend ever updating it. 1.0 will probably be mostly or entirely backward compatible with 0.8, but it won't be with 0.7. A 0.7 world should stay on 0.7 forever, unless you're OK with chunk walls everywhere. 

The one exception is that if you're playing an oceanic world with Climate Control, you can explore until the edges of your exploration are all ocean and (very important!) the interior is COMPLETELY explored. Then you can update to a newer version. The biomes won't change, just the heights and decor of the biomes, so the chunk walls will all be under the ocean where you won't see them.

**Comment by Xireka** [comment]
Oh perfect then, my current version is RTG-1.7.10-0.8.0-RC-2

So I can update to 1.0 yay! :dancer: 

Thanks for the info tho, but luckily I did update to 0.8.0 on the update before this one :)
