### ISSUE TITLE
Strange generation of villages.

### ISSUE THREAD

**Issue by OneEyeMaker** [Team-RTG/Realistic-Terrain-Generation#726]
Hello.
I found strange bug with generation: RTG generated wrong type of villages (cobblestone villages in sandy biomes, for example) and RTG generates only ... parts of villages.
See here: http://imgur.com/a/968y5

I thought, that there's problem with chunk generation, but lines of these "fractures" don't match borders of chunks.

MC 1.7.10, RTG 0.8.
It's maybe related with #705 

P. S. Sorry for my English, I'm from Russia.

**Comment by srs-bsns** [comment]
More than likely related to #686, which was closed but not confirmed fixed.

**Comment by chaNcharge** [comment]
The dev version that @whichonespink gave me was a dev version, it might be fixed as I haven't seen it occur as of the dev version

**Comment by OneEyeMaker** [comment]
I found all these villages in final version (0.8.0), not in dev/RC. And I *didn't find* villages without this problem. (However, I didn't change config at all. I think default configuration a-priory should work properly.)
