### ISSUE TITLE
Unable To Disable Biomes In Config

### ISSUE THREAD

**Issue by HyperionNexus** [Team-RTG/Realistic-Terrain-Generation#730]
As the title says, I cannot remove particular biomes (Mainly BOP) from generating unlike old versions.

A friend did say I might need ClimateControl or Biometweaker to disable them and if I do, how to do it will be appreciated.

Version: RTG-1.7.10-0.8.0.

**Comment by whichonespink44** [comment]
Yep, you're gonna need either Climate Control or BiomeTweaker.

If you choose Climate Control, disable biomes via the CC configs.

If you choose BiomeTweaker, you can use these [example tweaks](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/master/etc/biometweaker/BiomesOPlenty) to get you started. Disable biomes by setting their 'genWeight' to zero.

Good luck!
