### ISSUE TITLE
Terrain Overrides Cave Generation

### ISSUE THREAD

**Issue by Quizer9O8** [Team-RTG/Realistic-Terrain-Generation#735]
Caves do not propely generate in BOP Canyon.
I haven't looked further in any other biome that uses hardened clay in its terrain.
![2016-05-21_19 13 18](https://cloud.githubusercontent.com/assets/19509275/15634784/3bb31b70-25cd-11e6-8fe8-f3bcc976a817.png)
![2016-05-21_20 01 55](https://cloud.githubusercontent.com/assets/19509275/15634981/4d3fa426-25d2-11e6-8c0c-7e8aa22d1c78.png)

**Comment by whichonespink44** [comment]
I don't think this is a bug, just a cave that started to generate but didn't make it very far (happens all the time).

Using the default cave settings, this happens more frequently than it does in vanilla.

If you want to confirm this is what's happening, just modify the cave settings such that caves are more frequent and more dense, and then load up a new world with the same seed to see if the cave generates differently.
