### ISSUE TITLE
Chunky Biome Borders

### ISSUE THREAD

**Issue by Quizer9O8** [Team-RTG/Realistic-Terrain-Generation#736]
Well... these do still exist but not so frequently anymore.
![2016-05-21_19 14 09](https://cloud.githubusercontent.com/assets/19509275/15634833/6b628f26-25ce-11e6-81a0-3d487b4d7e04.png)
![2016-05-21_19 37 36](https://cloud.githubusercontent.com/assets/19509275/15634835/729faa30-25ce-11e6-98d6-fca1964915da.png)
![2016-05-21_19 40 38](https://cloud.githubusercontent.com/assets/19509275/15634837/751aed06-25ce-11e6-8f29-909ee6a37648.png)
![2016-05-21_19 18 09](https://cloud.githubusercontent.com/assets/19509275/15634848/9410af3e-25ce-11e6-8710-2e1db0ee409d.png)

**Comment by whichonespink44** [comment]
Is there anything we can do here? I'm assuming this is biome repair stuff? I rarely see this myself.

**Comment by Zeno410** [comment]
You rarely see it because it's rare. There are two things I'm thinking about: adding some noise to the repair process and making adjustments for lakes (they mostly happen around the scenic lakes).

**Comment by RufusStark** [comment]
When I do see these kinds of borders (maybe 1 in 20), its nearly always near an ocean coastline.

**Comment by Zeno410** [comment]
It's always near an ocean, because otherwise the biome repair won't do anything (it looks for beaches). But, you also need beach level land at the limit of the repair, and that usually happens only near the scenic lakes. Rivers do it too, but the repair process is aware of them.

**Comment by Ezoteric** [comment]
i think its not that bad, i mean you only really notice when your staring at it close by :P

And why cant there be a few straight lines in the world ? :P

**Comment by RufusStark** [comment]
Oh, I see. My point was more that I don't necessarily see lakes nearby when I find those borders. I probably just didn't notice because I didn't know to look for that. Ezoteric makes a good point that you don't really notice it unless you're right on top of it. It's also fairly noticeable on maps.

**Comment by Zeno410** [comment]
A lot of times the lake gets biome-repaired to ocean so you have no idea it was even a lake.

**Comment by Quizer9O8** [comment]
Those straight lines arent that bad but in my opinion they are too long like the wasteland one. Isnt there a way to turn thos straight lines into wave like borders

**Comment by Zeno410** [comment]
There is a "waving" system but either the waves are too small or there's some kind of edge error. I do see them sometimes.

**Comment by whichonespink44** [comment]
@Zeno410  I think this is rare enough that we can leave it until after 1.0 has been released, but if you want to try and improve it for 1.0, go for it.

**Comment by Zeno410** [comment]
Let's have a look at what the schedule for 1.0 release looks like. It is likely to be a lot of work for a small benefit.

**Comment by srs-bsns** [comment]
Is this still an issue? I haven't really observed it anywhere in my 1.0 tests.
Or is it just so rare that I haven't run into it?

**Comment by Zeno410** [comment]
It does exist. I find I don't see it often unless I'm looking for it. Also, it only happens near coasts so if you're looking at all-land areas you won't see it.

**Comment by whichonespink44** [comment]
As Zeno mentioned above, this would require a lot of work for not much improvement as it's about as good as it gets already.
