### ISSUE TITLE
Cobblestone boulders aren't converted to their UBC equivalent

### ISSUE THREAD

**Issue by Yazzeh** [Team-RTG/Realistic-Terrain-Generation#737]
I can see that decorative cobblestone accents, like in Highlands, are converted to their UBC equivalent cobblestone in that area, however the boulders on the surface are still the vanilla stone type.

I'd really like this to work properly, so boulders could help you find a specific stone type you're looking for.

**Comment by whichonespink44** [comment]
Fixed in 2eeb82d
