### ISSUE TITLE
WorldGenPond crash

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#739]
Original report:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2804

Crash log:
http://pastebin.com/09gqrsZB

The user has stated that this is still happening when using RTG 0.8.0:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2809

**Comment by Zeno410** [comment]
Fixed in aab4456ea45ad8b9dc69343e525f9d4f64b89446
