### ISSUE TITLE
ConcurrentModificationException when generating structure

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#740]
Original report:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2811

Crash report:
http://pastebin.com/4jsjknpT

**Comment by VelocityRa** [comment]
Here's an extra report with some more info: http://pastebin.com/ecmeiTt2

**Comment by Zeno410** [comment]
I'd say 90% chance the problem is:
Reika.ChromatiCraft.Auxiliary.ChromaAux.interceptChunkPopulation(ChromaAux.java:88)

**Comment by RufusStark** [comment]
I've been getting the same exception with much the same stack trace, and don't have ChromatiCraft installed. Thinking it was something related to (village) structure generation, I tried setting "Village Crash fix" to true to no avail. In fact, that seems to make it worse, though it's really hard to say with concurrency errors. Let me know if you'd like another crash report with the same error but different mods installed.

**Comment by Zeno410** [comment]
Yes, I'd definitely like another stack trace.

**Comment by RufusStark** [comment]
Here's a crash I got today: http://pastebin.com/5EA7sxqj

You'll see I'm using ChunkGen, but I've crashed with the same exception while exploring manually and not running ChunkGen. In any case, I don't think ChunkGen is parallelized.

Also, I set "Village Crash fix" back to false, and I'm more convinced that setting it to true made things worse.

**Comment by whichonespink44** [comment]
I experienced this the other day, and it was almost certainly caused by the Placemod mod, as I don't have any other structure-adding mod in my pack. I'll try to reproduce it with just Placemod and RTG so we can get an environment to debug.

**Comment by whichonespink44** [comment]
Also, @Zeno410 mentioned something in #686 that might help with this.

**Comment by whichonespink44** [comment]
Potentially fixed in df5df01

Closing for now, but we can re-open if necessary.
