### ISSUE TITLE
Volcanos make "shelves" over ocean

### ISSUE THREAD

**Issue by Zeno410** [Team-RTG/Realistic-Terrain-Generation#742]
Similar to the "shelves over lakes" but more distressing because they're much bigger and make it difficult to even get onto the volcano
![2016-05-30_19 49 23](https://cloud.githubusercontent.com/assets/5322776/15663421/cf80f696-26af-11e6-9b80-768c85c6d3ca.png)
I have no idea why it's being surfaced in stone (converted to UB stone later) but this is definitely an RTG volcano.

And you really want people to be able to get on these islands because
![2016-05-30_21 43 57](https://cloud.githubusercontent.com/assets/5322776/15663454/21fac7a8-26b0-11e6-97a0-a0c7c36725a2.png)

I'm thinking maybe the volcano can get passed the ChunkLandscape and alter it as necessary. Volcano generation will have to go farther out to deal with volcanos reaching the ocean, however we do it.

**Comment by Ezoteric** [comment]
yeah, i nothiced this the moment the code changes were made from RWG.

It seems its a structure get at y64, dunno if RWG also had this, but it never floated in RWG like this :P it always had blocks under it.

**Comment by Quizer9O8** [comment]
I found something like this in a lake some weeks ago and posted it on mc forums. I dont think its that bad but that the shelf stops at water aint good. It needs to go all the way to the bottom like a slope

**Comment by Zeno410** [comment]
RWG restricted the biome it appeared in, so it wouldn't be over the ocean (there was a chunk wall at the biome border, essentially, if it would have been) and it didn't have the scenic lakes. I'll bet it had problems with rivers but that would be pretty rare.

**Comment by whichonespink44** [comment]
@Team-RTG/rtg-1-7-10-writers Any ideas on how we can fix this?

**Comment by Zeno410** [comment]
My thought is the volcano generator should go out to the point where the volcano would be below y30 at least and fill down to the noise level.

**Comment by Zeno410** [comment]
Fixed in #750. The routine already did all the hard stuff, it just wasn't replacing water.
