### ISSUE TITLE
End Portal Frame not spawning

### ISSUE THREAD

**Issue by TataTawa** [Team-RTG/Realistic-Terrain-Generation#744]
I tried a lot of times. But I can't get any end portal frame. I'm using ender eyes to find it but there is nothing. The stronghold is there.

**Comment by TataTawa** [comment]
there is a chance that the game freeze when come near to the end portal.

**Comment by whichonespink44** [comment]
What version are you using? It's spawning fine for me in 0.8.0.

**Comment by TataTawa** [comment]
using 0.8.0. mods with IC2, TiC ,COG and NEI
I also find that the freeze of the game means I'm kicked by my own internal server.

**Comment by whichonespink44** [comment]
Please provide your fml-client-latest.log file and a crash report if possible.

**Comment by TataTawa** [comment]
Oh, I found that it is the compatibility issue with oceancraft. when the game freezes, it is near ocean. Also, when end portal is not near ocean, the spawn is OK. the log file also shows something error at oceancraft.

**Comment by whichonespink44** [comment]
Glad you found the end portal. :)

**Comment by topisani** [comment]
yeah, that really was the end of this issue
