### ISSUE TITLE
highlands tundra too high dunes

### ISSUE THREAD

**Issue by Ezoteric** [Team-RTG/Realistic-Terrain-Generation#747]
Tundra used the polar/desert terrain but the dune is way too high. better set it just like desert height :)

**Comment by Ezoteric** [comment]
![2016-06-10_23 09 40](https://cloud.githubusercontent.com/assets/14137626/15978765/79d12946-2f60-11e6-8244-01f43defe8bf.png)

**Comment by srs-bsns** [comment]
I've never really liked these dunes very much. It's not so much the height as it is how sharp they are.

Snow, and especially sand, don't form like this naturally. Dunes are waveforms created by the friction of air moving across a surface and even a slight breeze would prevent such a steep structure, or in the very rare case that one might develop, would erode it before you'd even know it existed.

**Comment by Zeno410** [comment]
Dunes actually can have sharp peaks; it's the steepness that's excessive. I really like them for the HL Dunes biome (which I have in stone and sandstone) but otherwise, yeah, it's sometimes too much. I looked at altering them but I couldn't figure out why that code would produce dunes. I guess it's an interference effect. Changing at this point seems like it would go against the backward compatibility commitment.

RTG Highlands Tundra per se is not at all faithful to the Highlands Tundra biome, which is mostly flat and bland, with a few shrubs to make it playable. But the crazy dunes seemed to be popular in other biomes so I left the biome as it had been.

**Comment by srs-bsns** [comment]
A fix for the ocean surface bug will also be backwards-incompatible and will be made for the 1.0.0 release (@whichonespink44 said he wanted to wait until then), so the dunes can be altered and the changes commited then as well.

The code can always be altered now and either commented out until then, or just not committed until then. :)

**Comment by Zeno410** [comment]
Bugs are more of an issue than aesthetic preferences. Speaking of which - did somebody fix the ocean floors? I just started to take a look a try to fix it and they're fine - nice and even at 30, as the code should do.

**Comment by Ezoteric** [comment]
@Zeno410 
Well tbh if the dunes are like 4 it would be fairly flat again :)

**Comment by Zeno410** [comment]
Then all we would need to do is change the config default, which doesn't create much backwards incompatibility (users just need to conserve previously default configs). Do we have the world-specific configs going?

**Comment by Ezoteric** [comment]
vanilladeser has the dunes added where tundra file is quite empty.

I could change it all to the same as desert including the config files ;)

**Comment by Ezoteric** [comment]
I think 
return terrainPolar(x, y, simplex, river);

should be
return terrainPolar(x, y, simplex, river, 140f, (minDuneHeight + (float)ConfigRTG.duneHeight), 60, 70, base) +
                groundNoise(x, y, 2f, simplex)*river;

**Comment by whichonespink44** [comment]
@Zeno410 I don't think anyone's fixed the ocean floors, but I haven't come across any floors that need to be fixed yet. As for the dunes, we could lower the config default a bit, but I'd rather not mess with the terrains at this stage unless absolutely necessary.

**Comment by Zeno410** [comment]
The reason I'm asking is that I *did* see the ocean floor problem earlier, and then when srs-bsns mentioned it I remembered I'd never fixed it. So I popped up a test world and it wasn't there. I hadn't been able to figure out how it had been happening in the first place - the floor code is very straightforward.

**Comment by whichonespink44** [comment]
Ocean floor bug fixed in 7fd26f2
