### ISSUE TITLE
World stuck in result infinity recursion at chunk decoration

### ISSUE THREAD

**Issue by VladimirMangos** [Team-RTG/Realistic-Terrain-Generation#755]
I have problem with infinity (not sure, but at least long time period) in chunk decoration calls at world chunks loading. After wait I terminate minecraft. World finish load and place player to world and show self. But no progress save and no world interaction world with preserved result after world reload.

Hmm, crash report have stack overlow remark but minecraft not crash for me and terminated manually.

Crash file http://pastebin.com/E8qkTxsG
Lastest log http://paste2.org/K402YBvN (in past2.ca because pastebin.com not alow so large pastes)
fml-client-latest.log http://wikisend.com/download/639544/fml-client-latest.zip (too large for paste, compressed to zip)

Mayb need some list already active decoration/some stage processing chunks for prevent cyclic reenter to its...

-------

**Comment by srs-bsns** [comment]
This is the wrong repo for reporting issues for RTG-1.9.4, you are looking for: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/issues

However, this issue is already known and is being addressed.

**Comment by VladimirMangos** [comment]
Oh, sorry and thank you)
