### ISSUE TITLE
Add biome support for Highlands UT

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#774]
_From @whichonespink44 on March 29, 2016 13:42_

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2494877-highlands-uncharted-territory-finally-for-1-8-9

_Copied from original issue: Team-RTG/1.8.9-Realistic-Terrain-Generation#63_

**Comment by Zeno410** [comment]
This is an interesting one because the plan for UT was to use Topi's generation system welding to fix it. So, do we want to do the UT terrains in RTG or import the welding?

**Comment by whichonespink44** [comment]
I guess it depends on how easy/difficult it is to import the welding vs how easy/difficult it is to upgrade the terrain system to use the latest 1.7.10 stuff.

Unless we're planning to bring the entire 1.8.9 version of RTG inline with the latest and greatest from the other two versions, then it might be best to just add support for UT using the existing 1.8.9 terrains.

**Comment by whichonespink44** [comment]
Something else to consider... if you we _do_ import the welding system, that means we could also close #777, #778, #780, #781, and #775, whilst also ensuring that any other biome-adding mods for 1.8.9 are automatically supported.

**Comment by whichonespink44** [comment]
Added in 7bfcc1a
