### ISSUE TITLE
Add Support for Beautiful Vanilla Mod-1.8.9

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#777]
_From @WenXin20 on March 7, 2016 15:31_

V0.5 adds 2 new biomes.
http://minecraft.curseforge.com/projects/beautiful-vanilla-alpha-0-45-for-minecraft-1-8/files/2285873

_Copied from original issue: Team-RTG/1.8.9-Realistic-Terrain-Generation#44_

**Comment by srs-bsns** [comment]
This mod is now defunct, and it doesn't seem that there's any more interest in it. Also, 1.8.9
