### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#779]
_From @topisani on February 28, 2016 19:21_

Quite a few things need some refactoring for performance reasons. This is going to be a central list of all of them.
- [ ] Use MutableBlockPos instead of BlockPos in loops

_Copied from original issue: Team-RTG/1.8.9-Realistic-Terrain-Generation#26_

**Comment by whichonespink44** [comment]
@topisani I'm gonna be giving 1.8.9 some love this weekend... is this as simple as replacing all instances of `BlockPos` with `MutableBlockPos`? Or is the idea to use MutableBlockPos and its set() method to avoid creating millions of BlockPos objects?

**Comment by topisani** [comment]
this is really stupid microoptimization in most cases, but ye, the point is to use MutableBlockPos in tight loops, but only in those

**Comment by whichonespink44** [comment]
Cool... in that case, I think I'll close this issue, but... moving forward, maybe we can all start using MBP instead of BP, replacing occurrences as we come across them.
