### ISSUE TITLE
Add support for Agricultural Revolution

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#780]
_From @whichonespink44 on February 28, 2016 14:6_

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2501618-the-agricultural-revolution-ver-0-7-2-reinventing

_Copied from original issue: Team-RTG/1.8.9-Realistic-Terrain-Generation#24_

**Comment by whichonespink44** [comment]
_From @topisani on February 28, 2016 15:0_

Whats included in this? im guessing it doesnt need biometweaker voodoo, so its just adding the biomes? ima need a bit of guidance for this

**Comment by whichonespink44** [comment]
Cool, yeah I can give you a crash course in biome support... can also put something in the GitBook for reference.

It's basically just creating a biome config, realistic biome, terrain, and surface for all of the overworld biomes in the mod. I usually do an NEI dump to get the biome names and class names if they don't have an API. From there, it's basically choosing an existing biome that most closely resembles the one you're adding support for and then tweaking as necessary. The tweaking is a little complicated, but we can go through it at some point.

**Comment by WenXin20** [comment]
Just so you know, this mod is for 1.10.2 and 1.9.4 now.

**Comment by whichonespink44** [comment]
I've added support for this in the 1.10.2 version (PR #942), but I haven't merged it into dev yet because there's a problem with AR's oceanic biomes. Essentially, they're crashing when trying to generate, and I don't know why:

http://pastebin.com/qquQtyrB

I'll post this in the AR thread on Minecraft Forums and see if @mrmoeman can shed some light on what might be happening.

**Comment by whichonespink44** [comment]
I've asked for some help from the author of AR:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2501618-the-agricultural-revolution-ver-0-8-7-reinventing?comment=291

Hopefully between us both, we can figure out why those oceanic biomes are crashing.

**Comment by whichonespink44** [comment]
Added in 90e4817

**Comment by WenXin20** [comment]
Not sure if this affects anything, but this mod recently changed its mod id from cookingplus to agriculturalrevolution

**Comment by whichonespink44** [comment]
@WenXin20 Are you sure? I just downloaded the latest version for 1.10.2 and the mod ID is still 'CookingPlus'

**Comment by srs-bsns** [comment]
The mod ID in the `mcmod.info` file hasn't been updated and it still `CookingPlus`, but if you look at the bytecode in the main class, the mod ID has indeed changed:

```
CookingPlusMain.java #Lnet/minecraftforge/fml/common/Mod; modid agriculturalrevolution
```

**Comment by whichonespink44** [comment]
This is what I'm seeing in the 1.10.2 version:

```
@Mod(modid="CookingPlus", name="The Agricultural Revolution", version="0.8.1", acceptedMinecraftVersions="[1.10.2]")
public class CookingPlusMain
{
  public static final String MODID = "CookingPlus";
  public static final String MODNAME = "The Agricultural Revolution";
  public static final String VERSION = "0.8.1";
```

**Comment by srs-bsns** [comment]
I was looking at the bytecode for: [v0.9.0](https://minecraft.curseforge.com/projects/the-agricultural-revolution/files/2352098)

**Comment by whichonespink44** [comment]
Bleh, my bad... I could've sworn that's the one I downloaded!

So I guess we should update our reference to the new ID when we release 4.1.19... it will mean that 4.1.1.9 worlds won't be backwards-compatible with worlds that have AR pre 0.9, but that's already the case with AR on its own, so that should be fine, right?

**Comment by srs-bsns** [comment]
I'm making a fix right now. Worlds should be backwards compatible just fine, unless they changed something in the mod which requires us to change something other than just the mod ID.

**Comment by whichonespink44** [comment]
Well, it says this on the mod page:

> WARNING: if you are planning on updating the mod from 0.8.9 or before to 0.9 it will not work on old worlds

**Comment by srs-bsns** [comment]
Oh, sorry, didn't realise what I even typed. What I meant was
- any version of AR can still be used with RTG.
- any backwards incompatibility is with AR, not RTG.

So, we don't need to put up a warning that RTG won't be backwards compatible, just that worlds created with the older version of AR won't be. (they should have reflected this in their version number by bumping the major! :smirk: )

**Comment by srs-bsns** [comment]
Updated in 37f80f5cc647a6576b78881954a9b244e9d14a12
