### ISSUE TITLE
[1.10.2] Alpha.6 Performance Issues and Crashing (CMEs)

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#789]
_From @Lanse505 on June 16, 2016 19:52_
##### Affected Mod Versions
- Forge: 12.17.0.1964
- RTG: RTG-1.9.4-2.0.0-alpha.5
- Pam's HarvestCraft: 1.9.4a
##### Issue Description:

Issue 1:
There are currently some rather hefty performance issues with Base RTG for 1.9.4 however it seems that with Pam's Harvestcraft this issue gets ALOT worse. 

Issue 2:
Also there seems to be a wierd bug with Chunks genning rather slowly (most likely due to chunk population) however it does cause some rather strange Visual bugs when you go into "unloaded" chunks. For example like this http://i.imgur.com/lykaoAm.png
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Install the Above mods + JEI + WAILA (those are the only other 2 mods in this instance)
2. Load up and Create a New World
3. Use Jprofiler to check the issue or just wait 10 mins while it generates a world.
##### Extra Information:

Funnily enough this doesn't cause a crash however it drains ALOT of memory during world generation and takes about 10 minutes on my pc (which not really the best it is pretty decent)

Call Tree Information:
http://i.imgur.com/H2mRfMM.png

It continues about 70-99+ calls in and doesn't really stop, it seems to be a very very deep rabbit hole of generation calls and other wierd things.

From Discord:
Vel0cityX - Today at 9:41 PM
@zeno410 Could this be decorations requiring nearby chunks -> calling provideChunk -> decoration for these chunks happens and then it continues on like that?
The callstack suggests that this is kind of what happens right?

WhichOnesPink - Today at 9:43 PM
Zeno's delayed decoration stuff fixed that in 1.7.10... looks like we might need to port that to 1.9.4

Vel0cityX - Today at 9:43 PM
Yup, func_186025_d is provideChunk
Yeah

I'll continue digging deeper into potensial issues!

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#131_

**Comment by whichonespink44** [comment]
_From @Lanse505 on June 16, 2016 19:53_

Also the chunk generation seems to be abit wonkey once it acctually generates the chunks:
http://i.imgur.com/JPePCeG.png
http://i.imgur.com/Ru3ZFf2.png

**Comment by whichonespink44** [comment]
_From @Lanse505 on June 16, 2016 19:55_

During Chunkgen it boils down to this call tree:
http://i.imgur.com/V1SAwqN.png

**Comment by whichonespink44** [comment]
_From @Lanse505 on June 16, 2016 20:2_

The first issue (aka massive initial generation lag) Gets even worse with BoP added :P
http://i.imgur.com/AgNclnh.png
http://i.imgur.com/LIA40pD.png

**Comment by whichonespink44** [comment]
_From @Lanse505 on June 16, 2016 20:29_

Also adding BoP caused a crash:
https://gist.github.com/Lanse505/f0a0c4611da74d0bbdbf14229958d2fb

This happened after about 13 minutes of Spawn Generation time when it loaded you into the world.

**Comment by whichonespink44** [comment]
_From @Lanse505 on June 16, 2016 20:30_

[22:01:42] [Server thread/INFO]: Preparing start region for level 0
[22:01:43] [Server thread/INFO]: Preparing spawn area: 0%
[22:13:09] [Server thread/INFO]: Preparing spawn area: 98%
[22:13:10] [Server thread/INFO]: Preparing spawn area: 98%

**Comment by whichonespink44** [comment]
_From @xtraspecialj on June 17, 2016 16:13_

Any news on improving the 1.9.4 performance of this mod?  I really want to use this mod on my next playthrough but the missing pieces of chunks as mentioned in the op make it impossible.  I found a command block command to pre-generate the chunks but it takes forever just to get a decent sized radius, it isn't perfect, and I often go well outside of the radius anyways...

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 17, 2016 16:56_

@xtraspecialj, RTG is being rewritten for 1.9.4 and it is still in the early stages, hence why it is Alpha. It will be a while before it is usable for normal play.

**Comment by whichonespink44** [comment]
_From @xtraspecialj on June 27, 2016 0:18_

@srs-bsns:. Thanks for the update sir, great mod!. I appreciate the devs hard (and beautiful) work on it. And sure, I'm aware it's in Alpha and not officially cleared to be a recommended mod for a playthrough, but you and I both know that there are many times Alpha versions are good enough to use as a "daily driver" so to speak.  Given that this is the issues thread and I hadn't seen any news other than the Discord discussion in the OP, I was just inquiring to see if the root cause had been verified and how it was going. If the update was "nope, nothing yet". Then that's cool. Or, if the update was "yep, figured it out and hopefully this problem will be solved soon" then that's even cooler.  But, the only way to know is to ask.  So I did.

**Comment by whichonespink44** [comment]
_From @topisani on June 27, 2016 1:41_

we have been busy with the 1.7.10 release lately, but during the following weeks we should get back into 1.9.4, this time with the entire team focused on it. So nope, we havent fleshed out the specific issues, but we will start work on it pretty soon.

**Comment by topisani** [comment]
fixed by #835! @Lanse505, you will probably be happy to hear that ;)

**Comment by Lanse505** [comment]
Sweeeet~

**Comment by srs-bsns** [comment]
@Lanse505, FYI: The performance issues aren't resolved yet. The attempted solution was a bit hasty.

**Comment by topisani** [comment]
to be fair most of them are, but some locations still set off some recursive decoration loop and slow down everything. Mostly its very playable though

**Comment by srs-bsns** [comment]
Please move all discussion about this issue to #866.
