### ISSUE TITLE
Semi-Random crash for new world with farseek & streams

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#790]
_From @elix-x on June 15, 2016 8:39_

For a few days, i'm experiencing this crash when creating a world. It happens 2 times out of 3 (For every 3 worlds created only 1 is playable). Relogging into world after crash doesn't help, wll, because world isn't generated.
I could as weel report it [here](https://github.com/delvr/Farseek/issues), but NPE happens in your code.
[Crash report](https://gist.github.com/elix-x/5212b9cc370bce7ac5e384f04fa68ed3) and affected [method](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dev/src/main/java/teamrtg/rtg/core/world/ChunkProviderRTG.java#L619) and [line](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dev/src/main/java/teamrtg/rtg/core/world/ChunkProviderRTG.java#L689).
Forge-1959
Rtg-A5

Note: theoretically it can happen with any world while generation of any chunk, but i did not test it.

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#129_

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 15, 2016 13:8_

Probably a dupe of #126

**Comment by whichonespink44** [comment]
_From @elix-x on June 15, 2016 13:24_

"Highly probalby"_tm_, but i have it only when farseek & streams are installed. And the stack trace also contains them.

**Comment by topisani** [comment]
this will need to be reconfirmed since #835. That PR changes the code that is referenced here A LOT

**Comment by Elix-x** [comment]
It was already fixed...

**Comment by topisani** [comment]
Oh, well that's great then :)
