### ISSUE TITLE
Floating Water Source Block in 1.9

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#794]
_From @PrinceZorg on May 9, 2016 20:58_
- Forge: 1.9-12.16.1.1887
- RTG: RTG-1.9-2.0.0-alpha.1

(sorry for my bad english)
World generates floating water source blocks in rivers and oceans when ravins or caves comes out.
It's like rivers and oceans are generated and then caves and ravins are made but water source blocks are not updated. 

This exemple is made with defaut cfg file. 
![2016-05-09_22 32 50](https://cloud.githubusercontent.com/assets/19273721/15127775/74aeefb6-1638-11e6-9dfb-6dec577c1f90.png)

seed : -3592711992285616835
xyz : -192 55 306

Problem is easier to find with more caves and ravins in cfg file.
This second exemple is on the same seed but with this cfg file (just more caves)
[http://pastebin.com/FDVzYgVb](url)

![2016-05-09_22 06 35](https://cloud.githubusercontent.com/assets/19273721/15127922/3a0c3ca0-1639-11e6-9d45-434b75f88664.png)
![2016-05-09_22 07 14](https://cloud.githubusercontent.com/assets/19273721/15127961/7007a13c-1639-11e6-8b04-22436cb3bc38.png)

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#101_

**Comment by whichonespink44** [comment]
Thanks for the report.

I wonder if this has anything to do with the water blocks being Blocks.water instead of Blocks.flowing_water

When I was working on volcanoes, I noticed that if the lava was Blocks.lava, it wouldn't trickle down the side of the volcano if there was a crack in the caldera - it would just sit there. But if I changed it to Blocks.flowing_lava, it would flow down the crack in the caldera every time.

**Comment by whichonespink44** [comment]
_From @PrinceZorg on June 10, 2016 18:25_

Hi,
Tested last alpha 5 with 1.9.4, problem is still there.

**Comment by whichonespink44** [comment]
_From @topisani on June 20, 2016 0:24_

im not exactly sure how this should be fixed. how i see it, there are two options:
1. Check for water in cave/ravine gen code, and make sure they dont break into rivers/ponds
2. Somehow make sure the water flows down and fills the cave  

The issue here is pretty simple. The first one is gonna be slightly weird to do, and im not sure its the right way to go. But for the second one, imo the the whole cave should fill up with source blocks - flooded caves would be awesome anyway. but if we had to do that, id think the way to do it would be splitting the cave code in 2. first part gets all the positions that will be replaced with air, second one replaces them with air, unless it has hit water, in which case it fills the entire cave with water. This might lead to some weird issues with underwater lakes and such on chunk borders. whats everyones opinion?

**Comment by srs-bsns** [comment]
I'm almost certain that this was vanilla mechanics at play, just like suspended sand in deserts in vanilla worlds that would remain suspended until a block update. This was fixed in 1.10.2. Pretty certain there nothing to for us to do here anymore.
