### ISSUE TITLE
Crash with BOP [1.9.4]

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#796]
_From @MCEventHorizon on June 10, 2016 19:59_
##### Affected Mod Versions
- Forge:1957
- RTG:1.9.4-2.0.0-alpha.5

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)

-Biomes O' Plenty: 1.9.4-4.1.0.2025

srs_edit: http://pastebin.com/J9sFXRMU

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#128_

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 10, 2016 22:13_

This might be related: [MCF #2892](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2892)

> Got a crash trying to generate a new world with the 1.9.4 version: [http://pastebin.com/hbfT1FDD](http://pastebin.com/hbfT1FDD)

Both stacktraces appear to show some kind of endless looping during decoration.

**Comment by topisani** [comment]
duplicate, closing
