### ISSUE TITLE
Biome repair issues after porting

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#798]
_From @topisani on April 29, 2016 15:57_

I ported some 0.8 changes, which included some changes to the BiomeAnalyzer. This has created a weird problem:
![2016-04-29_17 42 35](https://cloud.githubusercontent.com/assets/3133596/14921627/6d54f862-0e33-11e6-8c9a-36bcb7d1c17c.png)
The small bright spot in the middle is a river biome. They also occur around/in/as beaches ocacionally, and they are sometimes ocean biomes instead.
I have no idea whats going on here, so im assigning you @Zeno410 to this. If you dont find the time for it ill try looking at it again, but this is very much voodoo to me.

Also id like this to be fixed this weekend if possible, then we could release v2.0.0-alpha.1 on sunday or so.

PS. This will only happen after #89 

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#90_

**Comment by whichonespink44** [comment]
_From @Zeno410 on April 29, 2016 16:49_

I don't think I can get to this soon - I have to finish filling in the decoration rabbit hole, and convert the rivers back to Voronoi noise, and I don't even have a 1.9 dev environment set up yet.

But you could try altering the constant 
float beachTop = 64.5f;
to 64f

Not sure about the ocean but there's a similar oceanTop that's set to a half-step

**Comment by whichonespink44** [comment]
_From @topisani on May 4, 2016 13:43_

That small spot is extreme hills (no EH inside a 50 block radius)
![2016-05-04_15 39 21](https://cloud.githubusercontent.com/assets/3133596/15015864/81f05620-120e-11e6-9d6c-cab0580a579e.png)
This aparently goes deeper than i thought. Still fairly certain its BiomeRepair related, since thats what i updated that introduced this behaviour, and it only seems to happen around water or when otherwise close to sea level.

**Comment by whichonespink44** [comment]
_From @Zeno410 on May 4, 2016 17:59_

Biome repair can go a little farther that 50 - 64, I think, and it can go 64 x and z at once. Two things I can think of: the search might be running in the wrong sequence and sometimes a biome doesn't get set so it uses another biome.

A last possibility is that it's really there. You could try turning biome repair off and seeing what's there for it to work with.

**Comment by whichonespink44** [comment]
It wouldn't surprise me if it's actually there - lately I've been using seeds where most biomes can be found within a 2,000-block radius of spawn, and the vanilla generator is definitely capable of placing minuscule patches of biome like that.

**Comment by whichonespink44** [comment]
_From @topisani on May 4, 2016 20:11_

They definitely aren't there (tested same seed pre porting), and repair is the only thing that changes the biome array

**Comment by whichonespink44** [comment]
_From @topisani on May 7, 2016 13:9_

half of this was rivers not being removed, however it still seems like there are a few issues with biome repair (like the exHills one)

**Comment by topisani** [comment]
i have not seen this for a long time, and i am considering it fixed for now. Might be reopened later
