### ISSUE TITLE
WorldFeatures

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#804]
_From @topisani on April 6, 2016 7:25_

These will be mainly used for valcanoes for now, but the point is to have add something that is placed like a feature, with access to the distance from the center and such, but instead of directly placing blocks, it will be able to act like a biome, manipulating the terrain and surfacing.

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#63_

**Comment by whichonespink44** [comment]
_From @topisani on April 24, 2016 11:9_

this might be the solution to quite a few things, lakes and posibly rivers should be terrainFeatures as well.

**Comment by topisani** [comment]
These are theoretically implemented, but still need some work
