### ISSUE TITLE
[1.9.4] Crash with BoP

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#805]
_From @JCMais on June 9, 2016 0:58_
##### Affected Mod Versions
- Forge: 12.17.0.1954
- RTG: RTG-1.9.4-2.0.0-alpha.5
- BoP: BiomesOPlenty-1.9.4-4.1.0.2025-universal
##### Issue Description:

Crash during initial world loading.
Crash-log: https://gist.github.com/JCMais/ede876013bb190dfbc15f500a29abb60
##### Steps to reproduce the issue: (If it's easily reproducible.)

Enable `B:"Use BOP biome layout if avaliable"=true` in the configuration file and try to generate a new world.

![debug view](http://image.prntscr.com/image/d8a174742f3f4a53bdd25bb46b7b9c3d.png)

biome is null here: https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dev/src/main/java/teamrtg/rtg/core/world/ChunkProviderRTG.java#L662

Edit: After more investigation, the whole `biomes` array is null, also, the `biomeGenerators` array from the `RealisticBiomeGenerator` class is missing all BoP biomes, see below:
![screenshot_5](https://cloud.githubusercontent.com/assets/1041647/15965695/e07143e0-2ef5-11e6-8d06-04e7e7e71d04.png)

This is an issue, because the biomes array is populated with calls to  [RealisticBiomeGenerator.getRealistic](https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dev/src/main/java/teamrtg/rtg/api/world/gen/RealisticBiomeGenerator.java#L54)

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#126_

**Comment by whichonespink44** [comment]
_From @Zeno410 on June 10, 2016 13:41_

I think this can happen if a biome is assigned to 255.

**Comment by whichonespink44** [comment]
_From @Ezoteric on June 10, 2016 14:49_

yeah, bugger we cant enter the world for a dump... which we cant do without nei ? :P

**Comment by whichonespink44** [comment]
_From @JCMais on June 10, 2016 14:59_

@Ezoteric there is the [TellMe](http://minecraft.curseforge.com/projects/tellme) mod.

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 10, 2016 17:44_

> yeah, bugger we cant enter the world for a dump... which we cant do without nei ? :P

There is an alpha version of Mantle released for 1.9.4 which can be used to dump biome IDs with the config setting `B:"Dump BIOME ID's in log"=true`

**Comment by whichonespink44** [comment]
_From @Ezoteric on June 10, 2016 21:0_

i do have mantle but i dont see a config :p 

i may check tell me :)

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 10, 2016 21:8_

Hrm.. you mean there's no settings in `/config/SlimeKnights/Mantle.cfg`?

**Comment by whichonespink44** [comment]
_From @Ezoteric on June 10, 2016 21:10_

i dont have a slimeknight config .... weird maybe older version

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 10, 2016 21:34_

Yeah, after looking at the source, it appears they removed the dump features, all the way back in 1.8.9. Oh well.

**Comment by whichonespink44** [comment]
_From @Ezoteric on June 10, 2016 21:38_

np :) we still got tellme ;)

**Comment by whichonespink44** [comment]
_From @JCMais on June 11, 2016 3:31_

Here is the biome dump: https://gist.github.com/JCMais/7385b1ac1763c49c1a833e6834d5d2f5

No biome with id 255.

**Comment by whichonespink44** [comment]
_From @topisani on June 20, 2016 0:15_

the biomeGenerators array looks normal to me on that screenshot. What should be wrong with it?

**Comment by whichonespink44** [comment]
_From @JCMais on June 20, 2016 5:34_

@topisani I don't recall exactly where, but it tries to get the biome generator for a BOP biome from that array, but as it's not in there, Null is returned, which causes the original issue.

To be more exact:

https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dd61c955083ec06a70f8d08cf57a6162fccea476/src/main/java/teamrtg/rtg/core/world/ChunkProviderRTG.java#L598

here is where the biomes array (passed to the getNewerNoise) is populated, with calls to https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dd61c955083ec06a70f8d08cf57a6162fccea476/src/main/java/teamrtg/rtg/api/world/biome/RTGBiome.java#L149 which in turns calls https://github.com/Team-RTG/1.9-Realistic-Terrain-Generation/blob/dd61c955083ec06a70f8d08cf57a6162fccea476/src/main/java/teamrtg/rtg/api/world/gen/RealisticBiomeGenerator.java#L49

**Comment by whichonespink44** [comment]
_From @srs-bsns on June 22, 2016 17:33_

Probably related: [MCF #2968](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=2968)

**Comment by topisani** [comment]
this apears to be due to the BOP biomes not being added to `RealisticBiomeGenerator.biomeGenerators` for one reason or another, if one (@whichonespink44) were to take a look at it, they should probably follow the trail that starts [here](https://github.com/topisani/Realistic-Terrain-Generation/blob/c3ddeed3f6a8eda2c61c00fd50a48d523c3daf8a/src/main/java/teamrtg/rtg/core/RTG.java#L62-L62)

**Comment by topisani** [comment]
fixed in #839
