### ISSUE TITLE
Crash with Rogulike Dungeons

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#808]
_From @MCEventHorizon on May 9, 2016 22:57_

It doesn't happen without RTG so I think it has something to do with this mod.
Crashlog: http://pastebin.com/fCJCgndH

_Copied from original issue: Team-RTG/1.9-Realistic-Terrain-Generation#102_

**Comment by whichonespink44** [comment]
_From @topisani on May 11, 2016 9:28_

This is the known biome dictionary bug. No idea whats causing it, but i will investigate.

The duplicate reffers to #78

**Comment by topisani** [comment]
this one was killed with the whole RBB != BGB thing. Thats ages ago.
