### ISSUE TITLE
Cactus generates on yellow sand, not on red sand.

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#822]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3097

**Comment by topisani** [comment]
i remember looking at this some months ago, its all very weird, cause i think we are sending the correct flag to the WorldGenCactus.

It should be noted cactus can grow on coarse dirt too

**Comment by whichonespink44** [comment]
Fixed in 9d22243
