### ISSUE TITLE
RTG doesn't always remove rivers?

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#823]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3097

**Comment by Zeno410** [comment]
No way. That doesn't even look remotely like a leftover river (which creates a strip of inappropriate surfacing). There's just some water where the river would have been, which happens sometimes, duh.

**Comment by srs-bsns** [comment]
> No way. That doesn't even look remotely like a leftover river

Yes, it would look like the image below. The only time I ever saw vanilla rivers not getting removed is when I broke the event that removed them. ;)

![2016-07-06_04 40 48](https://cloud.githubusercontent.com/assets/8453133/16776585/0f0ab55e-4834-11e6-93f1-670bd1c697b8.png)
