### ISSUE TITLE
Caves leaving dirt & not removing clay in Mesa

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#824]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3097

**Comment by srs-bsns** [comment]
I think any thing here is either:
 - Already fixed, or was never broken to begin with.
 - too much work to fix trivial issues that likely won't ever get used as there isn't a high demand of users starting new worlds in 1.7.10.
 - the changes would be breaking, and therefore not going to happen in 1.7.10.
