### ISSUE TITLE
Server crash with apparently no reason #832

### ISSUE THREAD

**Issue by lightning02** [Team-RTG/Realistic-Terrain-Generation#833]
I've tryed to use forge server, but beside what I was thinking the results are worst, it crashed more fast.

I've so also tryed to use the snapshot that srs-bsns suggested, but the error seems to be the same and still occur, maybe more frequently?
This is the forge-server crash report: http://pastebin.com/7VX9hWy9
These are latest and fml-latest: 
https://www.dropbox.com/s/dvwefkrqs1tu7v0/fml-server-latest.log?dl=1
https://www.dropbox.com/s/6i1dkb6muz8wudf/latest.log?dl=1 

Also, I noticed this weird thing happening, it could be related with the crash, I removed those blocks once, but they still occurr to re-appear..

http://i.imgur.com/GHcqH8n.jpg?1

By the way, I don't get why you would not support thermos, most of the errors that occurr on thermos occurr in the same way on forge servers ....

**Comment by srs-bsns** [comment]
1. That crash report clearly states that the crash has occured with Climate Control, NOT RTG.
2. You are still using an unsupported plugin manager. Though it may not be the plugin manager itself that is causing an issue, it is most likely one of the plugins that you are using. Any plugin that manipulates how chunks are loaded can cause serious issues with the proper operation of Forge mods that alter world generation.
3. You are using >350 mods. There is no way to rule out a mod interaction bug, and the time it would take to determine that for this kind of bug is ridiculous...

![angtft](https://cloud.githubusercontent.com/assets/8453133/16885122/0c6db36e-4a9b-11e6-86b1-952880334269.jpg)

**Comment by lightning02** [comment]
what do you mean with unsupported plugin manager?
I had no plugin installed on the forge server o.o

**Comment by srs-bsns** [comment]
From the crash report:

> Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'

With the exception of FML and Forge, those platforms are not supported for the reason I stated in my previous post. And, if you aren't using any plugins for those platforms, then why do you even have them installed?

**Comment by lightning02** [comment]
I don't know why it say that, this is what I have in the folder;
http://i.imgur.com/u028Swf.png
I used forge to start the server o_o
could it be because the world was originally created on thermos?

**Comment by srs-bsns** [comment]
> could it be because the world was originally created on thermos?

Yes. It is likely that the minecraft_server.1.7.10.jar has been altered by Thermos, so Forge is using that altered .jar
I suggest you start from scratch with a plain vanilla server .jar and then use Forge. This should ensure that Thermos is not getting loaded.
