### ISSUE TITLE
saplingGrowTreeRTG() crashes when WorldChunkManager != RTG

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#834]
https://www.dropbox.com/s/wr40a5sdrv8vfly/crash-2016-07-15_22.09.42-server.txt?dl=0

We'll likely need to add in an additional check for that event @ [EventManagerRTG.java#L189](https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.7.10-dev/src/main/java/rtg/event/EventManagerRTG.java#L189) where we also...
1. `return` when (WorldChunkManager instanceof WorldChunkManagerRTG) is `false`, or
2. `return` if the dimension the event occurs in is not dim-0.

The former is the best choice for the future, maybe not with RTG-1.7.10, but with RTG-1.9.4 and beyond, as it won't be dimensionally restrictive.

**Comment by whichonespink44** [comment]
Fixed in 1026ee4
