### ISSUE TITLE
RTG splash screen when creating new world

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#843]
So it's come to my attention that a lot of people are installing RTG, choosing the Default world type, and thinking that **that's** the realistic terrain. Some sort of placebo effect or something? ¯\_(ツ)_/¯

I know this is a problem because of the number of PMs I've gotten about it and the number of mod showcases where the person making the video fails to choose the 'Realistic' world type. The most recent video (https://www.youtube.com/watch?v=SLFLbkIu_H4) only has 40+ views as of this writing, but it's on a channel that has 19,000+ subscribers, so the views are going to increase over time, and this is just the latest example. I've also seen other videos (even some mildy-popular Let's Plays) where they advertise RTG as being an installed mod, but the Default world type is used.

So...

I know there's no way RTG can work in the Default world type, but what about having a screen similar to the BOP screen when creating a new world that prompts the user to choose the Realistic world type if they want RTG terrain?

I know there are other priorities at the moment, but if anyone feels like doing something different, this could make a huge difference to a lot of folks.

**Comment by topisani** [comment]
i fully support this. Might find some time for it during the next week. Great idea!

**Comment by whichonespink44** [comment]
Yet another mod showcase where they use the Default world type:

https://www.youtube.com/watch?v=ZEFsXKcZa2s&t=459

(skip to [7:40](https://www.youtube.com/watch?v=ZEFsXKcZa2s&t=459) for the facepalmz)

![](http://i.imgur.com/iWKad22.jpg)

**Comment by topisani** [comment]
HAH! we really need this!

**Comment by whichonespink44** [comment]
If we wanted to do this quickly, maybe we could make the 'Realistic' world type selected by default when MC loads with RTG installed.

[Edit: Maybe something similar to this? https://github.com/FireBall1725/DefaultWorldGenerator ]

**Comment by whichonespink44** [comment]
Added for 1.7.10 in 9e01287

**Comment by whichonespink44** [comment]
Added for 1.10.2 in 9ed1eb0

**Comment by whichonespink44** [comment]
I'll be doing this for the 1.8.9 version this weekend.

**Comment by whichonespink44** [comment]
Added for 1.8.9 in 8ff4d07
