### ISSUE TITLE
RTG errors in log when creating new world with other mods presents

### ISSUE THREAD

**Issue by MrAmericanMike** [Team-RTG/Realistic-Terrain-Generation#844]
##### Affected Mod Versions:

RTG-1.9.4-2.0.0-alpha.5
Pam's HarvestCraft 1.9.4c
Chisel-MC1.9.4-0.0.6.33
- Forge version: 12.18.0.2010
- RTG version: 1.9.4-2.0.0-alpha.5
##### Issue Description:

The log goes crazy when trying to create a world. So bad that MultiMC gives up.

> MultiMC stopped watching the game log because the log length surpassed 100000 lines.
> You may have to fix your mods because the game is still loggging to files and likely wasting harddrive space at an alarming rate!

http://pastebin.com/fLUy0d4a

Same pack, not using RTG as Worldgen, the pack launchs correctly.

**Comment by srs-bsns** [comment]
1.9.4-2.0.0-alpha.5 is old. This issue is already known and is being worked on.

**Comment by MrAmericanMike** [comment]
Thanks.
"Was old" Ii was the newest 1.10.2 I found yesterday when I put the pack together. I just saw there is an Alpha 6 :D
