### ISSUE TITLE
Crash and hang on world gen: Alpha 6 1.10.2

### ISSUE THREAD

**Issue by MokahTGS** [Team-RTG/Realistic-Terrain-Generation#846]
##### Affected Mod Versions:

BoP
##### Issue Description:

World hangs on creation:

http://pastebin.com/dVjii23E

**Comment by topisani** [comment]
Yeah seems we havent gotten completely rid of performance issues, this is technically the same issue. We are on it!

Could you provide us with a seed for testing?

**Comment by Amperthorpe** [comment]
Hey, I am having the same issue in my 1.10.2 modpack. 
Seed: 5830979473997003837
Crashlog: https://www.phit.link/files/share/crash-2016-07-24_21.41.18-server.txt
Modpack: http://www.technicpack.net/modpack/principium.876229
