### ISSUE TITLE
Not generating the NEW WORLD (1.10.2)

### ISSUE THREAD

**Issue by Sasikaa** [Team-RTG/Realistic-Terrain-Generation#847]
##### Affected Mod Versions:

Mods:
ActuallyAdditions-1.10.2-r51.jar
AgriculturalExpansion[1.9.4][1.10.2]r-1.2.0.jar
AppleCore-mc1.10.2-1.3.5.jar
ArmorPlus1.9.4-4.0.4.0.jar
Aroma1997Core-1.9.4-1.0.7.0.jar
AromaBackup-1.9.4-1.0.1.1.jar
autopackager-1.6.3.jar
Bagginses-1.10-3.0.2a.jar
Baubles-1.9.4-1.2.1.0.jar
BBG-1.9.4-5.0.0.jar
bdlib-1.12.1.4-mc1.10.2.jar
BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar
BetterFps-1.3.2.jar
BloodMagic-1.9.4-2.0.3-51.jar
Bookshelf-1.9.4-1.2.3.279.jar
Botania-unofficial.r1.8-312.jar
Bullseye-1.9.4-1.0.3.jar
Calculator-1.9.4-3.0.7.jar
Chameleon-1.9.4-2.1.6.jar
Charset-0.3.0-pre12.jar
ChestTransporter-1.10-2.5.0.jar
Chisel-MC1.9.4-0.0.6.33.jar
chiselsandbits-11.5.jar
combathelp-1.9.4-1.0.3.jar
CommonCapabilities-1.9.4-1.1.1.jar
CookingForBlockheads-mc1.9.4-3.1.26.jar
CorrelatedPotentialistics-1.1.2.jar
covers-0.3.0.3-mc1.10.2.jar
CraftableHorseArmor-1.3.0-1.10.jar
craftingtweaks-mc1.9.4-5.0.6.jar
CraftTweaker-1.10.2-3.0.10.jar
CustomMainMenu-MC1.9.4-2.0.1.jar
CyclopsCore-1.9.4-0.7.2.jar
deepresonance-1.9.4-1.2.0beta35.jar
ElecCore-1.9.4-1.5.292.jar
Enchiridion-1.9.4-3.1.6.jar
EnderBags-1.9.4-2.0.0.jar
EnderCore-1.10.2-0.4.1.40-beta.jar.disabled
EnderCore-1.10.2-0.4.1.41-beta.jar
EnderIO-1.10.2-3.0.1.71_beta.jar.disabled
EnderIO-1.10.2-3.0.1.73_beta.jar
endertanks-1.10.0-1.4.1.jar
enderthing-1.10.2-0.6.10.jar
enderutilities-1.10.2-0.6.5-beta.1.jar
EnderZoo-1.10-1.2.3.43.jar
EndMetals_1.9-1.0.4.jar
environmentaltech-1.10-0.10.1a.jar
EvilCraft-1.9.4-0.10.6.jar
extrautils2-1.10.2-alpha-1.0.1.jar
ezstorage-2.1.6.jar
FastLeafDecay-v10.jar
flatcoloredblocks-mc1.10-v4.1.jar
forestry_1.10.2-5.1.12.200.jar
gendustry-1.6.4.10-mc1.10.2.jar
generators-0.9.20.6-mc1.10.2.jar
GiacomosFishingNet1.9.4-1.4.jar
GrappleHooks-1.10-1.0.8.jar
Harvest-1.9.4-1.0.1-8.jar
IntegratedDynamics-1.9.4-0.4.1.jar
InventoryTweaks-1.61-58.jar
ironchest-1.10.2-7.0.7.795.jar
itemscroller-1.10.2-0.5.2.jar
jei_1.10.2-3.7.8.234.jar
journeymap-1.10.2-5.2.4-unlimited.jar
JustEnoughResources-1.10.2-0.4.6.41.jar
LunatriusCore-1.10.2-1.1.2.36-universal.jar
Mantle-1.10-0.10.3.jar
mcjtylib-1.10-1.9.8.jar
MCMultiPart-1.2.0-universal.jar
MekanismAll-1.10.2-9.1.0.homebaked-01.jar
MmmMmmMmmMmm-1.11.jar
mobtotems-1.10.2-0.1.2.jar
moreoverlays-1.6-mc1.9.4.jar
Morpheus-1.10-3.1.6.jar
Morph-o-Tool-1.0-5.jar
NashornLib-1.9.4-1.8.77-1.3.1.8.jar
NetherMetals_1.9-1.1.2.jar
netherportalfix-mc1.9.4-4.0.1.jar
NoMobSpawningOnTrees-1.1.5-mc1.10.jar
NoMoreRecipeConflict-0.4(1.9).jar
notenoughwands-1.9.4-1.3.5.jar
OpenComputers-MC1.10-1.6.0.2-beta.4.jar
OptiFine_1.10.2_HD_U_C2.jar
OreDictionaryConverter-1.9.0.jar
OreSpawn_1.9.4-1.0.3.jar
PackingTape-1.9.4-0.5.2.jar
Pam's HarvestCraft 1.9.4c.jar
PersistentBits-1.10.2-0.5_exp.jar
Pillar-1.0-3.jar
platforms-1.10.0-1.2.0.jar
pressure-1.3.1.6-mc1.10.2.jar
ProgressiveAutomation-1.10.2-1.6.48.jar
quantumflux-1.9.4-2.0.7.jar
Quark-beta-46.jar
RandomThings-MC1.10-3.7.4.jar
redstonepaste-mc1.9.4-1.7.4.jar
refinedstorage-0.8.10.jar.disabled
refinedstorage-0.8.12.jar
Reliquary-1.10.2-1.3.2.423.jar.disabled
Reliquary-1.10.2-1.3.2.427.jar
ResourceLoader-MC1.9.4-1.5.1.jar
rftools-1.10-5.06.jar
rftoolsdim-1.10-4.30beta46.jar
RoguelikeDungeons-1.10.2-1.5.4.jar
roots-1.10.2-0.109.0.jar
**RTG-1.9.4-2.0.0-alpha.6.jar**
Schematica-1.10.2-1.7.8.150-universal.jar
ShadowMC-1.10.2-3.4.4.jar
shetiphiancore-1.10.0-3.3.0.jar
ShieldHider-1.0.1_1.9.4.jar
SimpleDimensions-MC1.10-1.3.jar
simplegenerators-1.10-0.7.1a(1).jar
simpleretrogen-1.10-4.0.1+8.jar
SleepingBag-1.9.4-1.2.1.jar
SolarVillage-1.10-1.1.0.14.jar
SonarCore-1.9.4-3.0.5.jar
SoulShards-TOW-1.10.2-2.5.4-38.jar
SpiceOfLife-mc1.9.4-1.3.3.jar
StorageDrawers-1.9.4-3.2.1.jar
StorageNetwork-1.9.4-1.12.4.jar
Substratum-1.10.2-1.6.0.1.jar
supercraftingframe-1.10.2-1.2.0.85.jar
TConstruct-1.10-2.3.3a.jar
teleporters-1.1.3.jar
terraqueous-1.10.0-1.2.0.jar
Tesla-1.9.4-1.1.0.24.jar
theoneprobe-1.10-1.0.13.jar
tinker_io-1.10-release 2.3.1c.jar
TombManyGraves-1.9.4-2.1.6.jar
UniDict-1.10.2-1.3b.jar
valkyrielib-1.10-0.10.1.jar
ViesCraft-0.2.9b-mc1.10.2.jar
Waila-1.7.0-B3_1.9.4.jar
WailaHarvestability-mc1.10-1.1.7.jar
WaterStrainer-1.9.4-1.1.0.jar
WeaponsPlus1.9.4-3.0.0.0.jar
WIT-1.9.4-1.0.19-36.jar
xprings-1.1.0.jar
- Forge version: forge-1.10.2-12.18.1.2014
- RTG version: RTG-1.9.4-2.0.0-alpha.6
##### Issue Description:

My log file copy-paste:

[2016/7/20 15:07:05 PM] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[2016/7/20 15:07:05 PM] [Server thread/INFO] [mcjty.lib.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[2016/7/20 15:07:05 PM] [Server thread/INFO] [mcjty.lib.varia.Logging]: Cleaning up RFTools dimensions
[2016/7/20 15:07:05 PM] [Server thread/INFO] [FML]: [RTG-INFO] Unregistering RTG's Terrain Event Handlers...
[2016/7/20 15:07:05 PM] [Server thread/INFO] [FML]: [RTG-INFO] RTG's Terrain Event Handlers have been unregistered successfully.
[2016/7/20 15:07:05 PM] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by topisani** [comment]
we are gonna need a full log file for that. put it in a [gist](https://gist.github.com)
