### ISSUE TITLE
Crash on 1.10.2 alpha.6 when creating RTG World

### ISSUE THREAD

**Issue by t3f** [Team-RTG/Realistic-Terrain-Generation#850]
##### Affected Mod Versions:
- Forge version: 1.10.2 - 12.18.1.2014
- RTG version:  RTG-1.9.4-2.0.0-alpha.6
##### Issue Description:

Crash right during world generation.

https://gist.github.com/t3f/e3a5479db4348062ed9db8518168a729

**Comment by srs-bsns** [comment]
This is a known issue that is being worked on.
