### ISSUE TITLE
Raw clay? mc1.10.2

### ISSUE THREAD

**Issue by StrangeThistle** [Team-RTG/Realistic-Terrain-Generation#852]
##### Affected Mod Versions:
- Forge version: forge-12.18.1.2018 for Minecraft 1.10.2
- RTG version: RTG-1.9.4-2.0.0-alpha.6
##### Issue Description:

With RTG, bodies of water (rivers, oceans, swamps, etc.) are consistently generating lined almost entirely with stone types with only small amounts of sand (beach biomes have more sand extending under the water) , dirt, and grass (underwater) and extremely little raw clay where with vanilla generation using the same seed they are lined predominantly with sand, dirt, and clay with some stone types in the mix. This observation is based on a limited exploration of the area around spawn in a handful of random seeds, with only the last one checked against vanilla generation. If I can't find clay in the swamplands, I can't use RTG, as much as I would like to.
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. set world type to realistic 
2. create new world
   3.

**Comment by srs-bsns** [comment]
@StrangeThistle Are you using any other mods that alter world gen? I haven't noticed any problems with clay generation, nor any of the other problems with stone types in bodies of water.

**Comment by topisani** [comment]
i cant see why clay should be generating. I am not asking it to anywhere in the v2 code. Its definately an issue, and it would be great to do a small fix for it for the next release. Im thinking this could be a way to test worldfeature surfacing, by adding patches of clay to the waterfeatures

**Comment by StrangeThistle** [comment]
![2016-07-22_18 27 48](https://cloud.githubusercontent.com/assets/8715948/17073543/b94850b8-503f-11e6-9138-97154981b0d8.png)
Here is a screenshot of what I’m seeing (with the 3 newer vanilla stone types disabled in the RTG config) and the mod list for the custom profile I put together in the Curse launcher (for the Mac, if it might matter, Java version 1.8.0.91). I just went in for a screenshot with chisel disabled, so that isn’t it. I just don't know enough to know what else to check without going down the list, which would take a while as it may also be slowing down the world gen process on my already inadequate MacBook. I've messed with several of the RTG config settings, but not the biome wall shading block settings.

mod list:

Better With Mods-0.8.2-1.9.4-hotfix2
BetterFps-1.3.2
BlockDrops-1.10.2-1.0.6
Boilerplate-1.9.4-8.2.3-universal
ChanceCubes-1.10-2.1.3.115
Charset-0.3.0-pre12
Chisel-MC1.9.4-0.0.6.33.jar.disabled
chiselsandbits-11.5
ClayWorldGen-1.1.0-1.10.2
craftingtweaks-mc1.9.4-5.0.6
EnderCore-1.10.2-0.4.1.41-beta
EnderIO-1.10.2-3.0.1.74_beta
extrautils2-1.10.2-alpha-1.0.1
FastLeafDecay-v10
FusionLord's Patrons-1.10.2-b2
Graves-1.10.2-b27-universal
InventoryTweaks-1.61-58.jar.disabled
ironchest-1.10.2-7.0.7.795
jei_1.10.2-3.7.8.234
journeymap-1.10.2-5.2.4-unlimited
JustEnoughResources-1.10.2-0.4.6.42
JustJetpacks-1.10-1.0.0
KleeSlabs-mc1.10-3.3.1
Mantle-1.10-0.10.3
MCMultiPart-1.2.0-universal
MmmMmmMmmMmm-1.11
modnametooltip_1.10.2-1.6.0
ModularUtilities-1.9.4-0.2.2
moreoverlays-1.6-mc1.9.4
nethercore-1.10.2-2.0.2
obsidianbuster-1.0
PackingTape-1.9.4-0.5.2
portablecraftbench-1.10.2-1.5.0
rangedpumps-0.2
recycler-1.3.1-1.9.4
RFTL 1.0
RTG-1.9.4-2.0.0-alpha.6
SilentLib-1.9.4-1.0.12-20
SuperMultiDrills-1.9.4-1.4.0-27
TConstruct-1.10-2.3.3a
tellme-1.10.2-0.3.0-pre.3
theoneprobe-1.10-1.0.13
Tinkers' Addons-1.10.x-1.0.3
topaddons-1.10.2-0.2.0
Totemic-1.9.4-0.7.7
VisibleArmorSlots[1.10.2]-2.0
WaterStrainer-1.9.4-1.1.0

**Comment by StrangeThistle** [comment]
If we should be expecting the surface under air and the surface under water to generate exactly the same in this version, then this may just be a major departure from the vanilla Minecraft mechanics and not a mod conflict. It still looks unusual to me in a bad way. Vanilla world gen and chunk loading seems significantly faster compared to RTG. Could all the underwater grass be causing a problem, or could that be a conflict with FastCraft?

~Richard P.

**Comment by topisani** [comment]
RTG 2.0 performance is still an issue, but remember it is still in alpha, and its in alpha for a reason. the surfacing going underwater is a "bug" in the sense that we havent gotten to it yet, RTG 2.0 is a complete rewrite.
Yep, we need clay and sand underwater, not grass and dirt. were workingonit
