### ISSUE TITLE
Hangs on "Loading World Building Terrain"

### ISSUE THREAD

**Issue by viper2g1** [Team-RTG/Realistic-Terrain-Generation#853]
##### Affected Mod Versions:
- Forge version: 12.18.1.2014
- RTG version: Alpha 6
##### Issue Description:

Looks like this is a repost but I figured I'd give you my log in case you needed more data.
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Select RTG generation in options
2. Generate new world
##### Extra Information:
- Minecraft Crash Report: https://gist.github.com/viper2g1/efa72a96464b366e92425f9ff6480b07
- Client Log: https://gist.github.com/viper2g1/07860bc5d79acb77309b69c9c610e4cf

**Comment by srs-bsns** [comment]
Yes, this is a known issue that is being worked on. See: #789.
The logs aren't much help at this point, but thanks for taking the time to post them anyways.
