### ISSUE TITLE
[1.10.2] Random exceptions while generating

### ISSUE THREAD

**Issue by MapperTV** [Team-RTG/Realistic-Terrain-Generation#858]
##### Affected Mod Versions:
- Forge version: 12.18.1.2011
- RTG version: 2.0.0-alpha6
- BoP: 4.1.0.2052
##### Issue Description:

When generating chunks, randomly throws some errors and close the server (in single player, closes the game itself).
Restarting the server will not necessary crash it again. The map will start generating again until it runs into another crash with the same error. This means the chunk where the error appeared first can still be generated after restarting.

http://pastebin.com/Y33yyRzJ
##### Steps to reproduce the issue: (If it's easily reproducible.)

Just run the game with the mods and make a new world. Generate chunks until it crashes.

Seed world: 631243383654813945 using RTG as terrain type.

Just ask me if you want more information.

**Comment by srs-bsns** [comment]
Dupe. Related to #789
