### ISSUE TITLE
Add biome support for the Hot Water mod

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#861]
1.9.4- http://minecraft.curseforge.com/projects/hot-water-mod

**Comment by whichonespink44** [comment]
The Hot Spring biome doesn't generate in 1.10.2, so keeping this a 1.9.4 feature request.

**Comment by whichonespink44** [comment]
The Hot Water biome still isn't being registered in 1.10.2 as version 3.0.2 so closing this for now. Will re-open if a 1.10.2 version is ever released.
