### ISSUE TITLE
Terrain Walls

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#863]
So I was testing the latest 1.1.0 build ahead of its release when I spawned in a Forest biome next to a river, with some really high banks. I followed it for a bit, and it deviated from the river and went inland, forming a 'terrain wall' for about a hundred blocks.

I thought it was something specific to 1.1.0, but I tried the same seed in 1.0.1, and it's the same result.

This video shows the terrain walls in more detail:

https://www.youtube.com/watch?v=rNl9Q0ecQC4

@Zeno410 This is the first time I've seen anything like this since... well, probably since 0.7.0 (maybe even further back than that), and no one else has reported anything like this, so I'm assuming it's a very rare edge case of a particular set of biomes coming together where a river gets placed, so I'm not too worried about it, but just thought I'd open an issue here in case it was a sign of something deeper going on.

It's super easy to reproduce... just use the following seed, and it should spawn you right on the river bank:

Seed = **-3128872699819320671**

**Comment by srs-bsns** [comment]
> This is the first time I've seen anything like this since... well, probably since 0.7.0

Yeah, I haven't seen anything like that since atleast 0.7.0 either.

**Comment by Zeno410** [comment]
Looks like a discontinuity in river smoothing. What's the hilly biome?

**Comment by whichonespink44** [comment]
It's actually a weird mixture of Plains, Forest, and Forest Hills... even some of the hilly areas are Plains.

**Comment by srs-bsns** [comment]
Is this even an issue still? And if it is, is it enough of an issue, or common enough, to be of concern?

**Comment by whichonespink44** [comment]
It's pretty rare... if we ever tweak the terrains in 1.7.10 again, this will likely get resolved then.

**Comment by srs-bsns** [comment]
No more breaking changes for 1.7.10.
