### ISSUE TITLE
RTG + AntiqueAtlas preventing further decorations

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#865]
From a recent PM:

"Recently I became aware of a cross-mod problem between RTG and AntiqueAtlas while working on a modpack. After you activate an atlas,the generation of most trees, flora and rock formations stops. mountains and the first part of the biome that get loaded in still generate, but further leave a blank space like this:"

![](https://s31.postimg.org/jn21k3o5n/2016_07_25_12_22_18.png)

"Forge 1.7.10 - [10.13.4.1614], RTG and Antique Atlas."

**Comment by srs-bsns** [comment]
I don't see there being enough interest in sleuthing this, which is unlikely to be RTG's fault.
