### ISSUE TITLE
[1.7.10] The new event handling system from 1.1.0 might be a bit CPU-heavy

### ISSUE THREAD

**Issue by Revemohl** [Team-RTG/Realistic-Terrain-Generation#868]
After updating to 1.1.0 and getting even worse FPS than the usual on my poor computer (as well as rather frequent lag spikes), I decided to pull VisualVM up and run a CPU sampling. I can't read it too well, but according to what I saw, all the entries that mentioned events went up quite a bit in CPU usage. Going back to 1.0.1 seems to have made things go back to how I'm used to see them (and made VisualVM report values I'm more familiar with as well), so I've decided to open up an issue in here in order to ask someone who has more knowledge in this area to further investigate this topic.

**Comment by whichonespink44** [comment]
@Revemohl Thanks for reporting this... do you know how to export the report that you were looking at? It would be incredibly helpful if we could see what you were seeing.

**Comment by srs-bsns** [comment]
@Revemohl
A VisualVM snapshot, and a fml-client-latest.log would be appreciated.

**Comment by whichonespink44** [comment]
Going to assume this has been resolved in the 1.1.1 release. We can re-open if that's not the case.
