### ISSUE TITLE
client side crash

### ISSUE THREAD

**Issue by lightning02** [Team-RTG/Realistic-Terrain-Generation#869]
http://pastebin.com/X8bCtSWT
This is all the info I have, the crash report :/ from the user that crashed, I guess he was looking around in a village, but not sure, this is the first time it happens btw.
We're using RTG-1.7.10-1.0.1 snapshot actually :o

**Comment by srs-bsns** [comment]
This issue was fixed. Please update to [RTG-1.7.10-1.1.0](https://github.com/Team-RTG/Realistic-Terrain-Generation/releases/tag/v1.7.10-1.1.0).
