### ISSUE TITLE
Village generating in the middle of the ocean

### ISSUE THREAD

**Issue by Crazy-KSK** [Team-RTG/Realistic-Terrain-Generation#874]
- Minecraft version 1.10.2
- Forge version: 12.18.1.2027
- RTG version: 1.9.4-2.0.0-alpha.6
- Biomes O' Plenty version: 1.9.4-4.1.0.2052

http://i.imgur.com/5Mq28CT.jpg
Seed: -1135270400

**Comment by srs-bsns** [comment]
I'm assuming something else is modifying worldgen on your end.

This is with only RTG-1.9.4-2.0.0-alpha.6 and BiomesOPlenty-1.9.4-4.1.0.2052 and default configs:
![2016-07-28_15 33 01](https://cloud.githubusercontent.com/assets/8453133/17226716/ba0545cc-54d8-11e6-9687-07f88ce50ab0.png)

You can clearly see (under crosshairs) that the village well is on land and that, AFAIK, is all that is checked for village placement. In a vanilla world the same kind of placement will occur.

We've decided that we aren't going to do anything in RTG that alters villages (custom placement, etc) other than frequency and size, and even those options may get removed at a later date, as it falls outside of RTG's scope (terrain only).

Thanks for reporting this anyways.
