### ISSUE TITLE
Heavy Biome fragmentation with BOP

### ISSUE THREAD

**Issue by Crazy-KSK** [Team-RTG/Realistic-Terrain-Generation#876]
I hope you don't mind me reporting issues involving BOP even thought RTG is still alpha.
- Minecraft version 1.10.2
- Forge version: 12.18.1.2027
- RTG version: 1.9.4-2.0.0-alpha.6
- Biomes O' Plenty version: 1.9.4-4.1.0.2052
- (no other mods)
- Seed: 1

http://i.imgur.com/hNhUCoH.jpg
there are like 50 little unconnected biome blotches within that village also it seems to have spawned two villages on top of each other (I know that used to happen in vanilla not sure about now)
this only happens with RTG+BOP

**Comment by srs-bsns** [comment]
> this only happens with RTG+BOP

No, I've seen this sort of thing happen with RTG by itself. Double villages, double mineshafts, etc..
This is related to #866.

I'll leave this open for now until it's properly confirmed about the biome mish-mash.

**Comment by topisani** [comment]
the villages happened when we updated to 1.10, however, since we have stopped doing anything related to structure gen, it has been fixed. The biomes i dont know about, have you tried it with bop only and the same seed?
