### ISSUE TITLE
Spruce and birch trees in Jungle

### ISSUE THREAD

**Issue by Crazy-KSK** [Team-RTG/Realistic-Terrain-Generation#877]
-  Minecraft version 1.10.2
- Forge version: 12.18.1.2027
- RTG version: 1.9.4-2.0.0-alpha.6
- (no other mods)
- Seed: 1

http://i.imgur.com/SuO3Itz.jpg
Its all jungle or jungle hills
There is also podzol  all over the place

**Comment by srs-bsns** [comment]
This may also be related #866.
This likely won't be able to be confirmed until we nail down all of the decoration issues causing the performance problems.

**Comment by whichonespink44** [comment]
The podzol is intentional for Jungle biomes, and the trees could be decoration bleeding but haven't tested yet to confirm.

**Comment by Zeno410** [comment]
_Really_ looks like decoration bleeding. If you look "down" it's almost all jungle trees. So the pic is showing temperate forest trees _next_ to a jungle.

**Comment by whichonespink44** [comment]
Yep, definitely decoration bleeding.

@Crazy-KSK Both of the things you observed are intended behaviour. When the biome config system is working again, you will be able to replace the podzol with grass and reduce the amount of decoration bleeding.
