### ISSUE TITLE
Jungle M missing its dirt layer 

### ISSUE THREAD

**Issue by Crazy-KSK** [Team-RTG/Realistic-Terrain-Generation#878]
-  Minecraft version 1.10.2
- Forge version: 12.18.1.2027
- RTG version: 1.9.4-2.0.0-alpha.6
- (no other mods)
- Seed: 1

http://i.imgur.com/lwkSCBO.jpg

**Comment by whichonespink44** [comment]
Probably some minor surfacing bug. I'll look into it this weekend.
