### ISSUE TITLE
Add realistic versions of Tech Reborn biomes

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#886]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3217

**Comment by srs-bsns** [comment]
I don't think there's anything we need to do here. TechReborn should be able to decorate biomes with their trees without us doing anything, and we probably shouldn't be customising mod added stuff (and possibly crreating balace issues, etc..).

**Comment by whichonespink44** [comment]
Good point - I've updated the title to clarify.

RTG has inherent biome support in v2, so this would just involve doing realistic versions of the biomes from TR.

**Comment by whichonespink44** [comment]
TechReborn doesn't add biomes, and I can confirm that rubber trees are growing in the biomes they're allowed to (Swamp, Forest, Jungle). Nothing to do here. :)
