### ISSUE TITLE
Add biome support for Oh, the Places You'll Go

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#889]
[Oh, the Places You'll Go Mod](https://minecraft.curseforge.com/projects/oh-the-biomes-youll-2)

**Comment by srs-bsns** [comment]
RTG is currently be rewritten in a way so that we won't have to add specific support for mod added biomes, it will be more-or-less automatic. However, the rewrite is only in the early stages and progress is currently slow.

**Comment by srs-bsns** [comment]
RTG is currently be rewritten in a way so that we won't have to add specific support for mod added biomes, it will be more-or-less automatic. However, the rewrite is only in the early stages and progress is currently slow.

**Comment by whichonespink44** [comment]
Whilst the re-write will support mod-adding biomes by default, the terrain won't be realistic by default.

**Comment by WenXin20** [comment]
Ok, cool, and thanks

**Comment by whichonespink44** [comment]
Mod: https://mods.curse.com/mc-mods/minecraft/247560-oh-the-biomes-youll-go-3

Biomes: http://biomesyougo.weebly.com/biomes.html

**Comment by whichonespink44** [comment]
Added in 07703a6

**Comment by WenXin20** [comment]
This mod recently had a  update that added the Athura Forest Biome.

**Comment by whichonespink44** [comment]
https://mods.curse.com/mc-mods/minecraft/247560-oh-the-biomes-youll-go-3

> Athura Forest: A bright and very pretty forest, with very high terrian!

**Comment by whichonespink44** [comment]
Added in 5adf040 - also added support for the new Shrubs biome, as well as the Mushroom Mountains biome, which isn't actually listed anywhere on the wiki and might not even be added to the Overworld, but I added it just in case.
