### ISSUE TITLE
Crystal Cave openings from the Advanced Lightsabers mod not generating

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#892]
Original post:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3246

Mod:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2306721-advanced-lightsabers-over-3-5-trillion-unique

Screenshots of what they should look like (Plains and Desert biomes only, I think):

![](http://i.imgur.com/1vIezFC.png)

![](http://i.imgur.com/kcTnWwd.png)

**Comment by srs-bsns** [comment]
1.7.10
No releases, nor has the repo been touched, since May.
Most people using this mod are likely using it in specialised modpack which probably doesn't include RTG.
This type of world gen is not RTG's responsability.
