### ISSUE TITLE
Stronghold config options

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#893]
Add config options for distance, count, and spread:

http://minecraft.gamepedia.com/Superflat#Structure_generation_options

**Comment by topisani** [comment]
didnt velo include it in the world configs thingy?

**Comment by whichonespink44** [comment]
This issue is just for the 1.7.10 & 1.8.9 versions.

**Comment by whichonespink44** [comment]
Added for 1.8.9 in dfdeaa2
