### ISSUE TITLE
Add config option for Mesa / Savanna Plateau clay block

### ISSUE THREAD

**Issue by DracoScythem** [Team-RTG/Realistic-Terrain-Generation#895]
The idea behind this is the following: For quite every block RTG uses for its terrain there is a config option (shadowing, decoration, even bedrock) - the Hardened / Stained Clay for the Mesa and Savanna Plateau is the only one missing that option (and it should be very simple to implement).
It would probably only benefit a handful of modpacks as most don't have reasonable substitutes, but for those such an option would be great.

What I'm imagining would look somewhat like this

<pre>
# The block to use for the Mesa and Savanna Plateau Biomes (metas/colours 0-15  from above)
# Warning: This might require adjustment of the color configurations above
    #  [default: minecraft:stained_hardened_clay]
    S:"Stained Clay Substitute"=minecraft:stained_hardened_clay

# The secondary block to use for the Mesa and Savanna Plateau Biomes (meta/color -1 from above)
    #  [default: minecraft:hardened_clay]
    S:"Hardened Clay Substitute"=minecraft:hardened_clay
    I:"Hardened Clay Substitute Meta"=0
</pre>

at the end of the plateaus{ } section.

**Comment by whichonespink44** [comment]
This already exists in the 1.7.10 & 1.8.9 versions:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.7.10-master/etc/config/RTG/rtg.cfg#L175-L201

It will also soon exist in the 1.9.4/1.10.2 version.

Or, do you mean that there should also be an option to use a different block altogether, other than clay?

**Comment by DracoScythem** [comment]
What I mean is the block type (currently one is limited to the meta values) - so replacing the clay with another block (so, yes different block altogether) wich would have the condition that all variants of it (representing the vanilla stained clay colors) are only differentiated by their meta value.

**Comment by whichonespink44** [comment]
Should be easy enough to do - I'll try to get it in for the next release.

**Comment by DracoScythem** [comment]
Thanks :grinning:

**Comment by whichonespink44** [comment]
Added for 1.8.9 in 2464a3d

Here's what the new config options look like: https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.8.9-dev/etc/config/RTG/rtg.cfg#L216-L257

**Comment by DracoScythem** [comment]
Looks perfect, thanks again :smile:

**Comment by srs-bsns** [comment]
Nothing left to do here.

**Comment by DracoScythem** [comment]
As 1.7 is still missing this I assume you stopped actively supporting it?
(Nothing wrong with it, just curious as I couldn't find any 'official statement')

**Comment by srs-bsns** [comment]
We're in the process of putting together a final release for 1.7.10, so issues that will no longer be addressed for 1.7.10 are being closed, while others that won't cause any breaking changes will be fixed. I though that this was already resolved, but it appears not.

**Comment by whichonespink44** [comment]
Added for 1.7.10 in 8ea9b3c
