### ISSUE TITLE
PopulateChunkEvent.Populate.EventType.ICE throws exception if event result is denied

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#906]
Original post: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3272

Crash report: http://pastebin.com/C4j345Rw

When populating the chunk, if the ICE event is cancelled, RTG throws an exception instead of just carrying on:

https://github.com/Team-RTG/Realistic-Terrain-Generation/blob/1.10.2-dev/src/main/java/rtg/world/gen/ChunkProviderRTG.java#L872-L893

@Zeno410 We can probably just remove the `else` statement here, unless it was put there for a specific reason?

**Comment by dexman545** [comment]
I have also experienced this crash.

CR: http://pastebin.com/9sFFsx9h

**Comment by whichonespink44** [comment]
Fixed in f3f85e1
