### ISSUE TITLE
"square" terrain

### ISSUE THREAD

**Issue by incognietis** [Team-RTG/Realistic-Terrain-Generation#909]
OK so I loaded up the snapshot release of 1.10.2 WITH Biomes o Plenty and found a very ugly square terrain. I did not test without BOP so I am not sure if it's related to BOP biomes or not, but what I can tell you is that the forest biome that I am floating over in the screenshot appears to be the BOP version of the forest biome. Good Luck!

![2016-08-20_10 52 35](https://cloud.githubusercontent.com/assets/21144424/17832291/c84678e2-66c4-11e6-9d50-8969c19e89e4.png)

[fml-client-latest.txt](https://github.com/Team-RTG/Realistic-Terrain-Generation/files/428395/fml-client-latest.txt)

**Comment by incognietis** [comment]
What I am talking about is the stone patches along the river, but I actually just noticed there is a very obvious straight line biome border where the savanna biome meets the forest biome near the hotbar's leftmost box. You can see how the podzol cuts off while the grass bleeds over a bit into the forest. I'm assuming that once biome bleeding is incorporated that this would probably be fixed, but I thought I would mention it.

**Comment by srs-bsns** [comment]
This is already known and is currently being addressed. A fix was unavailable for the first snapshot.

**Comment by whichonespink44** [comment]
Multiple assignees?!? When did _that_ become a thing?!? :dancer:

**Comment by whichonespink44** [comment]
These are all related to #920 so closing this as dupe.
