### ISSUE TITLE
1.10.2 appears to no longer do Biomes O Plenty biomes

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#912]
1.10.2 appears to no longer do Biomes O Plenty biomes - now only has vanilla biomes.  And there's no option in the config anymore to switch them on.

**Comment by whichonespink44** [comment]
To generate BOP biomes in the new snapshots, you will need to install either Climate Control or BiomeTweaker. If you install CC, it should work out of the box. If you install BiomeTweaker, you can use these example scripts to get you up and running quickly:

https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.10.2-dev/etc/biometweaker/BiomesOPlenty
