### ISSUE TITLE
Incorrect Spawning of Ocean Monuments

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#913]
Have found Ocean Monuments with guardians and all spawned in all kinds of biomes - it just hacks a square area out and places the temple in.  This happens even with the config option:
B:"Enable Ocean Monument Modifications"=false

**Comment by whichonespink44** [comment]
What version of RTG?

**Comment by whichonespink44** [comment]
Also, could you provide your fml-client-latest.log file so we can look into this further?

**Comment by Zygus42** [comment]
Nps - done direct

Also, could you provide your fml-client-latest.log file so we can look into this further?

**Comment by Zygus42** [comment]
1.10.2 - RTG-1.10.2-4.1.1.2-snapshot-1.

**Comment by whichonespink44** [comment]
Fixed in a2b70b6

**Comment by srs-bsns** [comment]
The current `@Override` for `BiomeProviderRTG#areBiomesViable` needs to either be removed (revert to using the vanilla method of the superclass), or match vanilla functionality. This `@Override` has existed since the early days of RWG.

**Comment by srs-bsns** [comment]
Fixed in https://github.com/Team-RTG/Realistic-Terrain-Generation/commit/035000faec44a674a17b214c5cfe8f27f416bcd5
