### ISSUE TITLE
Deeper rivers

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#923]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3297

Not sure what kind of side effects this would have, but someone requested this in the forums, so just posting it here.

**Comment by Zygus42** [comment]
That would be me :)

See below:
Any chance for config settings to make Deep Oceans, Oceans and maybe even rivers deeper ?

Deep Oceans are currently only around 15 to 20 squares deep, which I know is somewhere around the same as vanilla Minecraft, but they could go another 40 deeper and still not hit bedrock, which would allow the construction of some decent underwater bases and such.  _After further testing I notice that at 30 the land under the Ocean/Deep Ocean goes completely flat, so figure this must be some kind of hard limit you've added / are using.  35 blocks max is not a lot when you're wanting to do decent ocean builds_.

When the River width settings is increased, the river depth should be increased also, as you end up with very shallow, very wide rivers - maybe realistic sometimes, but you do get wide, deep rivers also.

**Comment by Ezoteric** [comment]
The deeper ocean will screw up the oil source of railcraft was it ?
Atleast thats what i remember why we had it made less deeper in the past.

Deeper river shouldnt be a problem if you make it like max 15/20 blocks deep i guess

**Comment by Zygus42** [comment]
Railcraft is not on 1.10, and not sure it will be.

Make it a config setting, then if you need it to be deeper, you can set it that way.

For Rivers I wasn't really thinking more than 5 to 8 or so deep, but again, could be a setting and people can play with it to get the results they like.

**Comment by Ezoteric** [comment]
oceans should be doable like the dune height option :)

dunno about rivers

**Comment by Ezoteric** [comment]
found this setting (  protected final float minOceanFloor; // The lowest Y coord an ocean floor is allowed to be. )
isnt this a config setting already ?

**Comment by Zygus42** [comment]
Not that I can find - unless it's called something obscure ?  Wanted a setting in EvilCraft for years and just recently found out it's been there the whole time :)  I just didn't know that the weather controllers were called evil temples.  I don't see any settings for anything to do with Oceans though.

**Comment by JetstormLP** [comment]
Zygus, CovertJaguar is working on updating Railcraft to 1.10.2 right now. his Patreons have access to the alpha releases right now. So it is being updated but we probably won't see an available version to the public for another month or so at least.

**Comment by whichonespink44** [comment]
There's no config setting to make the oceans deeper, and there probably won't be for the reasons mentioned on the forums. However, I think river depth could probably be a thing so I'll take a look at getting it into this weekend's snapshot.

**Comment by jonqrandom** [comment]
pretty please could we have a config option to loosen RTG's safety/sanity checks (like 'minOceanFloor'), so RTG only refuses to do things that will definitely crash? something like "IPromiseNotToBugTeamRTGAboutMyWorldBeingTrashedPleaseRespectMyBiomeTweakerConfigs="
that's either false by default, or even not automatically generated in the config file at all, and has to be added manually?
please? o.o';

**Comment by Zygus42** [comment]
And as to the Railcraft argument for capping ocean depths, we're now using Railcraft again in 1.10, but it doesn't have oil wells, but even if it did, I would think that this would be better left as a problem for the Railcraft developers.  In my opinion anyways :)

**Comment by Sandriell** [comment]
Railcraft never had oil generation... that is Buildcraft. Buildcraft will not be developed for 1.10.2 and is instead targetting 1.11.2

**Comment by srs-bsns** [comment]
There's no reason to keep this issue open as this would be a breaking change. It's already a part of the [1.11 TODO list](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1116) and it will likely be backported to 1.10 if we decided to do anymore breaking changes there, but nothing like this will be backported to 1.7.10.

**Comment by whichonespink44** [comment]
This can wait until after we release for 1.12

**Comment by srs-bsns** [comment]
No, it can't wait. It either gets done now, or not at all, because this is a breaking change to world gen.

I'll look into this next week, because I still want to find the cause of that irritating river noise bug causing weird generation near the world origin, and I will do it at the same time that I explore actualising rivers from the biome provider so that processes that look for rivers from biome lookups can do so with RTG rivers and lakes.

**Comment by whichonespink44** [comment]
We can release world-breaking updates after the initial release for 1.12 as long as we make it clear to everyone that it's a world-breaking update. Not ideal obviously, but I'm not holding up the release any longer just so we can implement a feature request.

But sure, if you think you can finish it off in the next week or two, then great.

**Comment by srs-bsns** [comment]
Lets be real. This will never happen.
