### ISSUE TITLE
Config option for Flowing Liquids not working in 1.10.2

### ISSUE THREAD

**Issue by Zygus42** [Team-RTG/Realistic-Terrain-Generation#925]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version:  forge-1.10.2-12.18.1.2071
- RTG version: RTG-1.10.2-4.1.1.2-snapshot-2
##### Issue Description:

I've tried a variety of setting on this, slowly dropping I:"Flowing Water Chance" from 200 down to 20 and I've seen no difference at all in the number of water sources on hills or mountains.

**Comment by whichonespink44** [comment]
Fixed in 3b5ea94 and will be in the next snapshot, scheduled for release tonight.
