### ISSUE TITLE
Add support to Afraid of the dark (1.8.9)

### ISSUE THREAD

**Issue by Doom-Walker** [Team-RTG/Realistic-Terrain-Generation#931]
##### Affected Mod Versions: Afraid of the Dark 1.8.9-1.1.4

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: forge-1.8.9-11.15.1.1902-1.8.9-universal
- RTG version: RTG-1.8.9-1.0.0-snapshot-2
##### Issue Description: when on world type realism Afraid of the Dark Biomes do not generate.  I recenty made a 1.8.9 modpack with progression stlye game play that requires you to go through this mod to advance into the modpack. I really enjoy your mod and would love it if it had compatibility with the afraid of the dark biomes so i can play on world type realism

(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)
##### Steps to reproduce the issue: (If it's easily reproducible.)

1.
2.
3.
##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

**Comment by whichonespink44** [comment]
The next time we work on 1.8.9, we'll definitely add support for Afraid of the Dark.

**Comment by Doom-Walker** [comment]
thank you i appreciate that! keep up the goodwork! :+1:

**Comment by whichonespink44** [comment]
Added in e6f028a
