### ISSUE TITLE
[1.10.2] Crash while exploring, possibly due to Recurrent Complex?

### ISSUE THREAD

**Issue by SeriousCreeper** [Team-RTG/Realistic-Terrain-Generation#932]
##### Affected Mod Versions:
- Forge version: 12.18.1.2076
- RTG version: 4.1.1.2-snapshot-4
##### Issue Description:

Flying around, generating new chunks, eventually causes a crash.
##### Extra Information:

Crashlog: http://pastebin.com/6iwvfzgx
Little bit of my fml-client-latest before the crash, seems like it's trying to gen recurrent complex structure? 
http://pastebin.com/QUvDanBp

Let me know if there is anything else i could provide that could help!

**Comment by srs-bsns** [comment]
> seems like it's trying to gen recurrent complex structure?

No, the crash report shows that RTG is trying to generate a desert temple but is getting a null return on the biome at the event coordinates. We've seen this before, but the cause isn't yet known.

**Comment by whichonespink44** [comment]
Fixed(ish) in 441c6b0. Whilst the root cause of this issue is still unknown, RTG will no longer crash if MapGenScatteredFeatureRTG receives a null biome.
