### ISSUE TITLE
Ravines don't cut through stained clay

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#933]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3348

I think this is more of an issue with the way the surfacing is done in Mesa biomes, but worth a look either way.

**Comment by srs-bsns** [comment]
I was going to try to reproduce it before opening an issue here, but oh well. :P

**Comment by srs-bsns** [comment]
After examination of the the chunks, it appears that this is the x/z flipping issue (#920), so closing this.

Proof:
![2016-09-01_05 47 17](https://cloud.githubusercontent.com/assets/8453133/18163693/40f49c9e-700a-11e6-963b-a70a95f2d563.png)
![2016-09-01_06 00 36](https://cloud.githubusercontent.com/assets/8453133/18163694/43088798-700a-11e6-8459-16ee74ae690d.png)
