### ISSUE TITLE
[1.10.2] - Really weird terrain generation

### ISSUE THREAD

**Issue by Tencao** [Team-RTG/Realistic-Terrain-Generation#936]
- Forge version: - 1.10.2-12.18.1.2073
- RTG version :1.10.2-4.1.1.2-snapshot-4

https://cdn.discordapp.com/attachments/132421212835020801/221416406992945153/unknown.png

This was caused by a new, freshly generated world. Other oddities include some really plain terrain generation that feels like it should have something there, but isn't (As you can also see in the background of the picture). Not all parts of the world are like this, and some seem to generate normally, however this makes the mod pretty much unusable

**Comment by srs-bsns** [comment]
#920
