### ISSUE TITLE
Biome Smoothness

### ISSUE THREAD

**Issue by incognietis** [Team-RTG/Realistic-Terrain-Generation#946]
So I remember loading up a beta version of RTG, I think it was for Minecraft 1.9... Anyways, that version had a new feature called Biome Bleeding which made this already awesome mod about 10x as awesome. I'm wondering if that feature is coming back in future releases? The extremely ugly biome transitions that we get in the newer versions of minecraft may be ok when tied with the rest of the vanilla world, but when paired with RTG's world gen it really sticks out a lot.

**Comment by srs-bsns** [comment]
This issue tracker is for bug reports only. Please use our [MFC forum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes) for discussions, or join us on our [Discord channel](https://discord.gg/0wIG7mz3g6Qynq4E).

The feature you are refering to is a part of the RTG rewrite (RTG2) which has been put on hold for now. Currently the 1.7.10 version of RTG has been ported to newer Minecraft versions, however, it doesn't have this feature.
