### ISSUE TITLE
Mineshafts not generating correctly in Mesa (Branch: 1.10.2/flippage)

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#948]
This may be due to some flipping still happening that needs to get ironed out, or may be related to a previous flipping fixes that now need to be reversed.

![2016-09-15_11 17 12](https://cloud.githubusercontent.com/assets/8453133/18558617/ce25ea04-7b41-11e6-852f-951be5091fce.png)
![2016-09-15_11 19 01](https://cloud.githubusercontent.com/assets/8453133/18558621/cf6c56f0-7b41-11e6-9212-2d519e3058bf.png)
![2016-09-15_11 20 06](https://cloud.githubusercontent.com/assets/8453133/18558624/d07fa966-7b41-11e6-8ea6-6352c3892929.png)

**Comment by whichonespink44** [comment]
Mineshafts can generate on the surface in Mesa biomes now:

http://minecraft.gamepedia.com/Abandoned_mineshaft#Generation

I haven't actually seen one in vanilla, but... something tells me they shouldn't look like the ones in those screenshots, so it's probably some flipping causing the weirdness... in fact, it's probably the same flipping that's causing the villages to gen all over the place.

**Comment by srs-bsns** [comment]
> Mineshafts can generate on the surface in Mesa biomes now:

I did not know this. Neat.

> in fact, it's probably the same flipping that's causing the villages to gen all over the place.

This is what I assumed. I assigned you since you were working on that and know where to look and fix it. ;)
To add more info, what you see on the surface in those screenshots is all that exists of the mineshafts; It does not continue underground.

**Comment by whichonespink44** [comment]
So I used Lonely Biome set to Mesa to try and find one of these in a default world, and here's what it looks like:

![2016-09-18_08 27 45](https://cloud.githubusercontent.com/assets/10927161/18613823/15602e90-7d7a-11e6-9270-868ffc0f388a.png)

I thought RTG's use of clay might be causing them generate a bit weirdly in RTG worlds, but... looking at the way they generate in default worlds, I don't think there are any issues. They just look a bit janky overall.

But the loot in the minecart chests more than makes up for it!!! :D

**Comment by srs-bsns** [comment]
Uhhh... yeah... ![](https://media.giphy.com/media/jeXiz1RAvzX44/giphy.gif)

If that's what surface Mineshafts are supposed to look like in vanilla, then I'm calling out Mojang on this tomfoolery. Minecart tracks should NEVER be built on sand and should have some kind of solid support underneath.

Furthermore, the design and layout of the structure on the surface shouldn't just match what a mineshaft looks like below the surface, with a bunch of parallel tracks that seem to serve no logical purpose for a mine. They could have added a surface layout where tracks go into derelict buildings (ore processing?) or something to atleast make it look plausible.

This just looks dumb and completely unrealistic, and in a RTG world I'd almost be inclined to just denying the creation of a surface mineshaft as to not add a blemish to a nice looking surface.

GG Mojang.

**Comment by whichonespink44** [comment]
Yeah, I was actually considering a config option to disable them because... yeah... talk about an eyesore!!

The only cool things about them aesthetically are the exposed entrances... everything else is just a disaster. Shame really - such a cool idea in theory.

I'll probably add a config option before we release 1.10.2-4.1.1.2
