### ISSUE TITLE
WTF's Expedition Mod Support

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#956]
##### Issue Description:

I believe the cave biomes mod in the update beta 12 added new sub-biomes.
##### Extra Information:

[-Mod Link](https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks)

**Comment by whichonespink44** [comment]
If I'm not mistaken, I think Expedition's sub-biomes already generate in RTG worlds. However, I just tried loading the latest RTG snapshot with the latest Expedition, and I think we may have broken compatibility when we refactored some of our stuff in the latest RTG snapshot.

@WhiskyTangoFox Hope our refactoring doesn't cause you too much grief! :( If there's anything you need in the form of an API, we might be able to come up with something to prevent this from happening in the future?

**Comment by whichonespink44** [comment]
@WenXin20 WTF just posted an update that fixes this issue:

https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks/files/2331065

I'm closing this, but let us know if you're still experiencing the problem after updating.

**Comment by WenXin20** [comment]
Ok
