### ISSUE TITLE
Problems with Tree generation 1.8.9.

### ISSUE THREAD

**Issue by Corcustos** [Team-RTG/Realistic-Terrain-Generation#959]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: forge-1.8.9-11.15.1.1902-1.8.9-universal (Needed for pixelmon beta 9)
- RTG version: RTG-1.8.9-1.0.0-snapshot-2
##### Issue Description:

(Please provide screenshots if neccessary/possible. Images can be dragged & dropped into this window.)

RTG isn't generating any custom trees. The biomes and mountains generate nicely, but I can't find a single RTG tree that generated. My level type is RTG as well. I'm not quite sure what's going on. Biomes also look rather large. I also want to note that I haven't touched the config either. Do I have to change something to enable the spawning of said trees? I'm also using a clean installation of of forge, spongeforge, pixelmon, and RTG. (I'm also seeing no volcanoes.)
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Install forge-1.8.9-11.15.1.1902-1.8.9-universal
2. Start server & Stop server.
3. Install spongeforge-1.8.9-1890-4.2.0-BETA-1744
4. Install Pixelmon-1.8.9-4.3.0-beta9-universal
5. Start server & Stop server.
6. Install RTG-1.8.9-1.0.0-snapshot-2
7. Start server.
##### Extra Information:
- If you have a crashlog, please provide it by using http://pastebin.com/ or https://gist.github.com/
- You can also provide your client log file: /.minecraft/logs/fml-client-latest.log
- If your client log file is too big for pastebin you can use https://gist.github.com/

I have no crash logs or any errors in the console.

![image](https://cloud.githubusercontent.com/assets/15864775/18653604/fdcc201a-7ea8-11e6-8ca0-3b8813b44bde.png)
![image](https://cloud.githubusercontent.com/assets/15864775/18653629/2270a0da-7ea9-11e6-9d06-c954be76e326.png)

**Comment by srs-bsns** [comment]
This is an incompatibility with SpongeForge. When SpongeForge is loaded, RTG's biome decoration routines do not run. It is unlikely there is anything we can do about it on our side, and the Sponge team is no longer developing for 1.8.9.
