### ISSUE TITLE
NPE w/ Expedition Mod

### ISSUE THREAD

**Issue by WenXin20** [Team-RTG/Realistic-Terrain-Generation#962]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version: 2085
- RTG version: 4.1.1.2 Snapshot 6
- [Expedition Mod](https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks): Beta 12.4
##### Issue Description:

When creating a world, I get a npe without a crash with the Expedition mod.
##### Steps to reproduce the issue: (If it's easily reproducible.)
1. Create a world with the expedition mod loaded.
##### Extra Information:
- [Log](http://pastebin.com/aKDsuJNn)

**Comment by srs-bsns** [comment]
Duplicate of #961

We're going to need the full log and the crash report. Please provide that in the other [issue thread](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/961)
