### ISSUE TITLE
Unable to disable BoP gem ores

### ISSUE THREAD

**Issue by ShneekeyTheLost** [Team-RTG/Realistic-Terrain-Generation#964]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version:
- RTG version: 4.1.1.2 - snapshot 7
##### Issue Description:

Biomes O Plenty, starting 1.8 and later, no longer has a config file to disable oregen. Instead it is done through a menu when you create a new world under More Options, and select Biomes O Plenty for World Type, and clicking on Configuration button on that screen. However, this means it is now impossible to prevent the spawning of the completely worthless biome-dependent gem ores that it spawns in. 

Since you already have config options to prevent the spawning of vanilla worldgen, can you include an option to prevent BoP ores from generating?

**Comment by srs-bsns** [comment]
BoP's ore generation is done during BoP's biome decoration process. It is outside of the scope of RTG to interfere in the workings of other mods, and I'm not sure there's a non-intrusive way we can do it on our end. This would be best addressed with [BoP](https://github.com/Glitchfiend/BiomesOPlenty/issues)
