### ISSUE TITLE
Stone Beach issues

### ISSUE THREAD

**Issue by aurumvorax** [Team-RTG/Realistic-Terrain-Generation#969]
##### Affected Mod Versions:

(Please list other mods and their versions if you feel they are relevant to this issue. i.e. Biomes O' Plenty)
- Forge version:1566
- RTG version:1.7.10-1.01
##### Issue Description:

Stone beaches are covered in snow, and spawn frequently at the edges of warm and hot biomes.  The stone beach biome sometimes also creates a 1-2  block thick layer of ice, this is dependant on shore slope.  Basically, a snowy edge biome keeps getting used with warm/hot biomes.  Can we prevent this, or have the option to disable stone beaches?
##### Steps to reproduce the issue: (If it's easily reproducible.)
1.  Generate a world, normal creative settings
2. Fly around, looking for coastlines
3. Repeat until found

**Comment by aurumvorax** [comment]
Additional/Possible fix:  both stone beach and extreme hills generate covered in snow, regardless of height.  I suspect this is the root of the problem, as they have the same temperature rating.

**Comment by whichonespink44** [comment]
Is this happening with just RTG installed and no other mods?

If you have other mods installed, please Pastebin/Dropbox your fml-client-latest.log file so we can take a closer look. A screenshot would also be helpful if you have one on-hand - no worries if not, the log file should have most of the info we need.

**Comment by aurumvorax** [comment]
This bug isn't showing up with only RTG installed, as far as I can tell.  Extreme hills get snowy at around y = 85, like normal, stone beaches aren't covered in snow.

I'm beginning to think this is a mod interaction with ClimateControl.  I have used biometweaker to set the stone beach and extreme hills temperature higher(0.4) with no effect.

I'm apparently not generating a logfile, which is new, but I'm running an unmodified version of Revolution 3, which has climate control in it.

**Comment by whichonespink44** [comment]
@Haggle1996 @Zeno410 

Any ideas why aurumvorax is getting these frozen stone beaches? I checked the REVOLUTION|3 issue tracker and didn't see anything related to stone beaches.

**Comment by Zeno410** [comment]
It's another mod, and it's a bug in that mod as snowy stone beaches are wrong everywhere. They should at least be snow-free to the same height Extreme Hills are. Stone beaches snowy _that_ way would be something to avoid sometimes, but would almost never be a problem in RTG.

**Comment by whichonespink44** [comment]
@aurumvorax Since this isn't a bug with RTG on its own, I'm gonna close this. Best advice we could give would be to remove mods from the pack one-by-one (or in batches) until the problem stops. If it turns out to be an interaction bug with RTG and another mod, let us know the details and we'll investigate further.

**Comment by Haggle1996** [comment]
Sorry, just getting to this.

What you're probably seeing is Haggle1996/RevolutionPack#513, which also has a workaround, but no fix. It shouldn't be related to RTG, just very noticeably on these types of biomes.
