### ISSUE TITLE
NULL biome (8) found ...

### ISSUE THREAD

**Issue by ghost** [Team-RTG/Realistic-Terrain-Generation#970]
##### Affected Mod Versions:
- Forge version: forge-1.10.2-12.18.1.2094-universal
- RTG version: 4.1.1.2-snapshot-8
- BOP version: 5.0.0.2085-universal
##### Issue Description:

Server crashes with error message given below, when Patch Biome ID is set to -1, and starts fine when it's set to 1.

Expected behavior: Server should not crash when Patch Biome ID is set to -1.
##### Steps to reproduce the issue:
1. Set I:"Patch Biome ID"=-1
2. Start the server.
##### Extra Information:

> Description: Exception in server tick loop
> 
> java.lang.RuntimeException: NULL biome (8) found when setting up beaches for biomes.
>         at rtg.world.biome.realistic.RealisticBiomePatcher.getPatchedRealisticBiome(RealisticBiomePatcher.java:38)
>         at rtg.world.biome.BiomeAnalyzer.setupBeachesForBiomes(BiomeAnalyzer.java:286)
>         at rtg.world.biome.BiomeAnalyzer.<init>(BiomeAnalyzer.java:40)
>         at rtg.world.gen.ChunkProviderRTG.<init>(ChunkProviderRTG.java:66)
>         at rtg.world.WorldTypeRTG.getChunkGenerator(WorldTypeRTG.java:50)
>         at net.minecraft.world.WorldProvider.func_186060_c(WorldProvider.java:61)
>         at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:854)
>         at net.minecraft.world.WorldServer.<init>(WorldServer.java:115)
>         at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:252)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
>         at java.lang.Thread.run(Thread.java:745)

Full Crashlog:
[https://gist.github.com/mankra/cf41b247c1ee0245db28d60e2b3742a4](https://gist.github.com/mankra/cf41b247c1ee0245db28d60e2b3742a4)

**Comment by whichonespink44** [comment]
Fixed in 3d77960

@mankra Here's the fixed version if you want to carry on testing: [RTG-1.10.2-4.1.1.2-prerelease-1.jar](https://goo.gl/Hb5tSr)
