### ISSUE TITLE
EBXL Leaf Decay Lag

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#972]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3529

**Comment by srs-bsns** [comment]
While thinking about this issue and reminiscing about the old old days using EBXL, on it's own, or with RWG, I can remember strange leaf decay issues and finding piles of fresh saplings lying around while traveling through the world.

I'd chalk this one up to an EBXL issue, so closing this for now. If someone brings this up again, we can revisit it then.
