### ISSUE TITLE
Fresh water vs Salt water surfacing

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#981]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3610

**Comment by srs-bsns** [comment]
I thought I had posed this question here, but I guess it must have been on Discord or MCF, so I will pose it here now for posterity:

Since when does Minecraft water have a salinity property that would allow for any kind of differentiation in generation?
