### ISSUE TITLE
Can you add support for MoreChineseMinecraft MOD's?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Team-RTG/Realistic-Terrain-Generation#982]
MoreChineseMinecraft is one add biome Mod by chinese player.
MOD post posted:http://www.mcbbs.net/forum.php?mod=viewthread&tid=638080&extra=page%3D1

PS：Non-I works

**Comment by mgdgfbhevdyeh** [comment]
My English is no good.

**Comment by shp241** [comment]
so,I am the author of MoreChineseMinecraft ,if you agree to add my biomes ,Please reply me and I will give you the source.

**Comment by whichonespink44** [comment]
@shp241 Please can you provide a link to the mod's JAR file and source code?

Also, is MoreChineseMinecraft only for 1.10.2?

**Comment by shp241** [comment]
@whichonespink44 Yes,it is only for 1.10.2(at least now is) and the link to the JAR is  https://minecraft.curseforge.com/projects/morechineseminrcraft/files
and I don't want my mod is open-source(at least now),so can you give me an e-mail address and I will send you the source JAR.

**Comment by whichonespink44** [comment]
My email address is whichonespink44@gmail.com

**Comment by shp241** [comment]
I have send the letter,use mediafire.

**Comment by whichonespink44** [comment]
Added in c5a8977
