### ISSUE TITLE
Strucutres generating in trees

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#986]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3618

Biome Tweaker's config files from here: https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.10.2-dev/etc/biometweaker/BiomesOPlenty , untouched.
All used mods:
BiomesOPlenty-1.10.2-5.0.0.2086
BiomeTweaker-1.10.2-2.1.225
OptiFine_1.10.2_HD_U_C4_pre
RTG-1.10.2-4.1.1.2
Xaeros_Minimap_1.10.8.1

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3632

**Comment by whichonespink44** [comment]
I haven't seen this in any of my testing before the release of 4.1.1.2, so not sure what's happening here.

**Comment by whichonespink44** [comment]
![](https://cdn.discordapp.com/attachments/168326116761665536/231911704303239168/2016-10-01_15.51.13_2.png)

Looks like village pieces are also getting up there.

**Comment by lightningo7** [comment]
Issue of the well is either not in 1.10 or in a snapshot version. Also user had FTB Infinity installed meaning lots of mods that effect generation.

**Comment by srs-bsns** [comment]
Uhh.. since when is FTB Infinity for MC 1.10? In the FTB launcher it's still listed as 1.7.10 only. Is it a Alpha/Beta version he's using?

In any case, he's likely using other mods. In his screenshots, the tree that the dungeon is in doesn't look like any tree that I know of, and I've not seen anything like this before in RTG. You should query him for a full mod list.

**Comment by whichonespink44** [comment]
This has been more or less confirmed to be an issue with Optifine's multithreading and/or chunk generation settings.

The question now is... what do we do about it? Personally, I'd kinda like to take the rigid stance that 'RTG does not support Optifine. Use at your own risk.' and be done with it, but... that's not really keeping in the spirit of RTG's ethos of mod compatibility.

Is it worth looking for a workaround? Or maybe trying to isolate the specific setting in Optifine that's causing the problem?
