### ISSUE TITLE
RTG + Chunkgen?

### ISSUE THREAD

**Issue by Corcustos** [Team-RTG/Realistic-Terrain-Generation#989]
I'm trying to generate a new world using the chunkgen and RTG mod. It successfully adds data for the chunks that were already generated, but when It gets to new chunks, I get a crash. I was wondering if there was anything that could be done on this end, or if it was a problem with chunkgen itself. I've already contacted the author of chunkgen, and decided it was a good idea to get the input of the authors of RTG as well.

Versions:
chunkgen-1.8.9-1.3.0.jar
RTG-1.8.9-1.0.0-snapshot-2.jar
BiomeTweaker-1.8.9-2.1.206.jar
forge-1.8.9-11.15.1.1902-1.8.9-universal.jar

Crash Message:
net.minecraft.util.ReportedException: Exception generating new chunk at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:163) ~[ld.class:?] at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114) ~[ld.class:?] at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) ~[ld.class:?] at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181) ~[ld.class:?] at net.minecraft.world.World.func_72964_e(World.java:287) ~[adm.class:?] at net.minecraft.world.World.func_175726_f(World.java:282) ~[adm.class:?] at net.minecraft.world.World.func_180495_p(World.java:822) ~[adm.class:?] at net.minecraft.world.gen.feature.WorldGenMinable.func_180709_b(WorldGenMinable.java:76) ~[apj.class:?] at com.pixelmonmod.pixelmon.pixelutilities.worldgen.GenericOreGenerator.generate(GenericOreGenerator.java:42) ~[GenericOreGenerator.class:?] at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?] at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262) ~[ld.class:?] at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1082) ~[amy.class:?] at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172) ~[ld.class:?] at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114) ~[ld.class:?] at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84) ~[ld.class:?] at com.gecgooden.chunkgen.util.Utilities.generateChunk(Utilities.java:49) ~[Utilities.class:?] at com.gecgooden.chunkgen.handlers.TickHandler.onServerTick(TickHandler.java:31) ~[TickHandler.class:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_TickHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?] at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:253) ~[FMLCommonHandler.class:?] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:649) ~[MinecraftServer.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92] Caused by: java.lang.ExceptionInInitializerError at rtg.world.biome.realistic.RealisticBiomeBase.rMapVolcanoes(RealisticBiomeBase.java:399) ~[RealisticBiomeBase.class:?] at rtg.world.biome.realistic.RealisticBiomeBase.generateMapGen(RealisticBiomeBase.java:425) ~[RealisticBiomeBase.class:?] at rtg.world.gen.ChunkProviderRTG.func_73154_d(ChunkProviderRTG.java:278) ~[ChunkProviderRTG.class:?] at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154) ~[ld.class:?] ... 23 more Caused by: java.lang.NullPointerException at rtg.world.gen.feature.WorldGenVolcano.(WorldGenVolcano.java:26) ~[WorldGenVolcano.class:?] at rtg.world.biome.realistic.RealisticBiomeBase.rMapVolcanoes(RealisticBiomeBase.java:399) ~[RealisticBiomeBase.class:?] at rtg.world.biome.realistic.RealisticBiomeBase.generateMapGen(RealisticBiomeBase.java:425) ~[RealisticBiomeBase.class:?] at rtg.world.gen.ChunkProviderRTG.func_73154_d(ChunkProviderRTG.java:278) ~[ChunkProviderRTG.class:?] at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:154) ~[ld.class:?]

All help is appreciated. Thanks.

**Comment by whichonespink44** [comment]
@Corcustos would you be able to Pastebin the entire crash report if you still have it? Also, does the crash still happen if you remove ChunkGen?

**Comment by Corcustos** [comment]
This only happens if I add RTG or Chunkgen and try to generate a new chunk using them. Both mods work fine individually. Together, they do not.

Full crash log:
[http://pastebin.com/GJ4z0X5m](http://pastebin.com/GJ4z0X5m)

**Comment by whichonespink44** [comment]
@Trevanant Is that the crash-report.txt file that got created in your crash-reports folder? It seems to be missing some key pieces of information.

Also, if it's not too much trouble, could you also post your fml-client-latest.log file via Pastebin/Gist/Dropbox/etc?

(This is likely the same biome patching issue we resolved in 7bcdc59 for 1.10.2)

**Comment by Corcustos** [comment]
That's the entire latest crash-report.txt from the crash report folder. All I did was copy and paste the contents into pastebin.

Here's my latest fml-server-latest.log as the client log doesn't exist in my folders: [http://pastebin.com/467xwbEc](http://pastebin.com/467xwbEc)

Edit: will there be a fix for 1.8.9?

**Comment by lightningo7** [comment]
There will eventually be a fix once we figure out what's doing it and once we're working on this version again.

**Comment by lightningo7** [comment]
Issue should be fixed from the commit mentioned above. Wait for a release on that. Having said that you will have to lower the chunk generation speed in the chunkgen.cfg to 0.5 as going at the normal speed it causes Mojang's watchdog to kick in and time the server out.

**Comment by whichonespink44** [comment]
@Corcustos Just a heads-up... it's probably going to be a week or two before we drop a new 1.8.9 release.
