### ISSUE TITLE
Possibility of a NoSuchMethodError in ChunkProviderRTG

### ISSUE THREAD

**Issue by srs-bsns** [Team-RTG/Realistic-Terrain-Generation#991]
Upon investigating #988, It appears that between MC 1.7 and 1.10 the interface `net.minecraft.world.chunk.IChunkProvider` has been gutted. Most importantly `IChunkProvider#chunkExists` was removed. The implementation class in vanilla Minecraft (net.minecraft.world.gen.ChunkProviderServer), however, still has this method and it can still be called by the server (by requesting the world's chunk provider).

RTG's implementation class `rtg.world.gen.ChunkProviderRTG` does not have a `chunkExists` method with this same signature (`(int, int)`) and I feel that there is the possibility that if a mod checks to see if a chunk exists by way of the world's chunk provider, it will result in a `NoSuchMethodError`.

**Comment by whichonespink44** [comment]
Closing this for 1.8.9 as there's already a chunkExists(int, int)

**Comment by srs-bsns** [comment]
I'm not sure why I added the 1.8.9 tag. The interface was changed in 1.9.4.
