### ISSUE TITLE
Flat bedrock not working

### ISSUE THREAD

**Issue by whichonespink44** [Team-RTG/Realistic-Terrain-Generation#992]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3653

**Comment by srs-bsns** [comment]
I noticed this before, some time ago, (I believe in 1.7.10,) that flat bedrock wasn't working in mod-added biomes. @Zeno410 said something about it that explained why it wasn't working, but I can't recall the details of that conversation. I thought that it had been resolved, but maybe it wasn't.

This was before porting 1.7.10 to newer versions of Minecraft.

**Comment by whichonespink44** [comment]
I've just tested this with RTG on its own, and with BOP, and everything seems to be working fine in both vanilla and modded biomes. I suspect that the user had another mod installed that also affected bedrock generation.
