### ISSUE TITLE
Custom BOP trees in RTG world

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Team-RTG/Realistic-Terrain-Generation#999]
(My English is no good)
If RTG is similar to RWG,BOP tree can be customized In RTG own world, not very good?
（1.10.2)

https://imgur.com/a/8URHH
![bsma08p](https://cloud.githubusercontent.com/assets/20567492/19310069/dc7b02fe-90ba-11e6-8b3b-a51ac10eddde.jpg)
![jjq0hkw](https://cloud.githubusercontent.com/assets/20567492/19310088/f3e1aefc-90ba-11e6-8b17-cad7c0805a63.jpg)

**Comment by whichonespink44** [comment]
@mgdgfbhevdyeh Are you asking if RTG can add different versions of BOP's trees? Or are you asking if RTG can generate RTG trees that use BOP blocks?

**Comment by mgdgfbhevdyeh** [comment]
@whichonespink44 I asking if RTG can generate RTG trees that use BOP blocks?
（Sorry my English is bad, but I really like RTG）

**Comment by mgdgfbhevdyeh** [comment]
@whichonespink44  RTG can add different versions of BOP's trees Also OK

**Comment by whichonespink44** [comment]
We might consider this when we re-design BOP biomes in the future. Closing for now.
